"""Extra fields for the 9-step talk track, keyed by problem title, merged onto data_problems.PROBLEMS."""

SUPPLEMENT = {
    "Two Sum": dict(
        clarify="Exactly one solution guaranteed? Can't reuse the same element twice?",
        bottleneck="Checking every pair re-scans the array for a partner I could just remember instead.",
        test="nums=[2,7,11,15], target=9 -> map builds {2:0}, then 7's complement 2 is already in the map -> [0,1]. Edge: nums=[3,3], target=6 -> works since we check the map before inserting.",
        other_edges="no valid pair exists; negative numbers; target achieved by first two elements.",
    ),
    "Contains Duplicate": dict(
        clarify="Can the array be empty or have one element? Any bound on value range?",
        bottleneck="Comparing every pair re-checks values I could just remember in a set as I go.",
        test="nums=[1,2,3,1] -> seen builds {1,2,3}, hits 1 again -> True. Edge: empty array -> loop never runs, False.",
        other_edges="all unique; all identical; single element.",
    ),
    "Group Anagrams": dict(
        clarify="Case-sensitive? Only lowercase letters guaranteed, or could there be other characters?",
        bottleneck="Sorting each string to compare it against every other string is repeated, wasted work.",
        test="['eat','tea','tan'] -> 'eat'/'tea' share a count key, 'tan' gets its own. Edge: empty string -> its own group.",
        other_edges="single string in the list; all strings anagrams of each other; duplicate identical strings.",
    ),
    "Product of Array Except Self": dict(
        clarify="Can the array contain zero(s)? Division truly disallowed?",
        bottleneck="Re-multiplying the whole array minus one element, for every element, redoes overlapping work.",
        test="[1,2,3,4] -> prefix pass gives [1,1,2,6], suffix pass folds in to [24,12,8,6]. Edge: one zero, e.g. [1,2,0,4] -> [0,0,8,0].",
        other_edges="two or more zeros (all outputs 0); negative numbers; array of length 2.",
    ),
    "Subarray Sum Equals K": dict(
        clarify="Can values be negative? Does an empty subarray count (no, subarrays are non-empty contiguous runs)?",
        bottleneck="Recomputing each subarray's sum from scratch re-adds numbers I've already summed before.",
        test="[1,1,1], k=2 -> prefix sums 1,2,3; seen[0]=1 upfront; count becomes 2. Edge: k=0 with a zero in the array needs seen[0]=1 handled correctly.",
        other_edges="all negative numbers; k not achievable at all; single-element array equal to k.",
    ),
    "Valid Palindrome": dict(
        clarify="Only alphanumeric characters count, case-insensitive? Can the string be empty?",
        bottleneck="Building a whole cleaned copy of the string uses O(n) extra space I don't need.",
        test="\"A man, a plan, a canal: Panama\" -> pointers skip punctuation/case, converge to True. Edge: string of only punctuation -> pointers cross immediately, True.",
        other_edges="single character; numbers mixed with letters; already-lowercase palindrome.",
    ),
    "Container With Most Water": dict(
        clarify="Can heights be zero? At least two lines guaranteed?",
        bottleneck="Checking every pair of lines recomputes areas for pairs that can't possibly beat the current best.",
        test="[1,8,6,2,5,4,8,3,7] -> pointers start at ends (area 7*1=7), move shorter side inward, converge to best=49. Edge: all equal heights -> widest pair (the ends) is optimal immediately.",
        other_edges="two lines only; one very tall line surrounded by short ones; strictly increasing heights.",
    ),
    "Longest Substring Without Repeating Characters": dict(
        clarify="Empty string possible? Only ASCII, or could there be unicode?",
        bottleneck="Restarting a fresh scan from every index re-examines characters already confirmed unique.",
        test="\"abcabcbb\" -> window grows to \"abc\" (len 3), hits repeat 'a', shrinks left, best stays 3. Edge: \"\" -> loop never runs, best=0.",
        other_edges="all identical characters (\"aaaa\"); string with no repeats at all; single character.",
    ),
    "Minimum Window Substring": dict(
        clarify="Multiplicity of characters in t matters (need at least that many of each)? What if t is empty or longer than s?",
        bottleneck="Checking every substring directly recomputes its character counts from scratch each time.",
        test="s=\"ADOBECODEBANC\", t=\"ABC\" -> window expands/shrinks to \"BANC\". Edge: t empty -> return \"\" immediately.",
        other_edges="t longer than s (no answer, return \"\"); t's characters not present in s at all; s equals t exactly.",
    ),
    "Valid Parentheses": dict(
        clarify="Only the six bracket characters appear, no other text mixed in?",
        bottleneck="Repeatedly scanning and removing matched pairs re-scans the whole string over and over.",
        test="\"()[]{}\" -> every open matches the most recent close, stack empties, True. Edge: \")(\" -> first char is a close with an empty stack, False.",
        other_edges="single unmatched bracket; only opening brackets; only closing brackets; empty string (trivially valid).",
    ),
    "Design Min Stack": dict(
        clarify="Do push/pop/top/getMin ALL need true O(1), not just amortized? Duplicate values possible?",
        bottleneck="Scanning the whole stack on every getMin call redoes a search I could track incrementally instead.",
        test="push(-2),push(0),push(-3),getMin()->-3,pop(),top()->0,getMin()->-2. Edge: push same min twice then pop once -> getMin still correct via <= comparison.",
        other_edges="popping down to empty; strictly increasing pushes; strictly decreasing pushes.",
    ),
    "Daily Temperatures": dict(
        clarify="Return 0 when no warmer day exists? Temperatures guaranteed positive integers?",
        bottleneck="Scanning forward from every day re-examines days already ruled out as 'not warmer' for a previous day.",
        test="[73,74,75,71,69,72,76,73] -> stack resolves each day as a warmer one appears; day 0 waits 1 day. Edge: strictly decreasing temps -> nothing ever resolves, all zeros.",
        other_edges="all identical temperatures (never strictly warmer, all zeros); single day; strictly increasing temps.",
    ),
    "Evaluate Reverse Polish Notation": dict(
        clarify="Division truncates toward zero, not floor? Expression always guaranteed valid?",
        bottleneck="N/A for this one -- postfix is meant to be evaluated with a stack directly; there's no meaningfully slower correct alternative.",
        test="[\"2\",\"1\",\"+\",\"3\",\"*\"] -> push 2,1; '+' -> 3; push 3; '*' -> 9. Edge: negative division like -7/2 needs int(a/b), not a//b.",
        other_edges="single-number expression, no operators; division resulting in an exact integer; deeply nested operator chains.",
    ),
    "Implement Queue using Stacks": dict(
        clarify="Are push/pop/peek/empty all that's required? Any constraint on amortized vs. worst-case time?",
        bottleneck="Reversing the whole stack on every single pop/peek call redoes the same shuffling repeatedly.",
        test="push(1),push(2),peek()->1,pop()->1,empty()->False. Edge: interleaved push/pop -- out_stack only refills once fully drained, preserving order.",
        other_edges="popping until truly empty; a single element; many pushes with no pops in between.",
    ),
    "Implement Stack using Queues": dict(
        clarify="Are push/pop/top/empty all required? Push allowed to be O(n) if pop/top stay O(1)?",
        bottleneck="Using two full queues and swapping them every push does more bookkeeping than necessary.",
        test="push(1),push(2),top()->2,pop()->2. Edge: single-element stack -- rotation loop runs zero times, element stays at front.",
        other_edges="popping to empty; pushing then immediately popping repeatedly; large sequential pushes.",
    ),
    "Maximum Depth of Binary Tree": dict(
        clarify="Depth counted in nodes (not edges)? Empty tree has depth 0?",
        bottleneck="N/A here -- the recursive definition IS the efficient solution; only alternative is iterative BFS, not a slower one.",
        test="root=3,left=9,right=20(15,7) -> left depth 1, right depth 2, total 1+max(1,2)=3. Edge: empty tree (root=None) -> 0.",
        other_edges="single-node tree (depth 1); completely skewed tree (depth = node count); perfectly balanced tree.",
    ),
    "Binary Tree Level Order Traversal": dict(
        clarify="Return values grouped by level, left to right within each level? Empty tree returns []?",
        bottleneck="DFS with explicit depth tracking works but is more error-prone than BFS's natural level grouping.",
        test="root=3,left=9,right=20(15,7) -> [[3],[9,20],[15,7]]. Edge: empty tree -> [] immediately.",
        other_edges="single-node tree; only left children (skewed); only right children (skewed).",
    ),
    "Binary Tree Vertical Order Traversal": dict(
        clarify="Ties at the same column AND same depth ordered left to right? Column indices can be negative?",
        bottleneck="A DFS-then-sort-everything approach does more sorting than needed when BFS already visits top-to-bottom, left-to-right.",
        test="root=3,left=9,right=8(left=4) -> columns -1:[9,4], 0:[3,8]? trace carefully per structure. Edge: two nodes same column+level from different parents -- BFS order still resolves left-to-right correctly.",
        other_edges="empty tree (return []); single node (one column); all nodes in one column (a straight line).",
    ),
    "Clone Graph": dict(
        clarify="Graph is connected and undirected? Guaranteed no self-loops beyond what's explicit in neighbors lists?",
        bottleneck="Recursing without tracking visited nodes infinite-loops on any cycle, which this graph type has.",
        test="node 1 with neighbors [2,4] -> clone recurses, map prevents re-cloning shared neighbors. Edge: single node with itself as a neighbor -- map entry created before recursing avoids infinite loop.",
        other_edges="single node with no neighbors; a simple cycle of 3 nodes; disconnected part (not expected, but worth asking).",
    ),
    "Course Schedule": dict(
        clarify="Prerequisites given as [a,b] meaning b before a? Can there be duplicate prerequisite pairs?",
        bottleneck="Trying every possible course ordering directly is combinatorially expensive (factorial).",
        test="numCourses=2, prereqs=[[1,0]] -> course 0 has no deps, course 1 depends on 0, no cycle, True. Edge: [[0,0]] -- course depends on itself, DFS revisits itself mid-path, cycle detected, False.",
        other_edges="no prerequisites at all (always True); a long chain with no cycle; disconnected groups of courses.",
    ),
    "Binary Search": dict(
        clarify="Array guaranteed sorted ascending? Duplicate values possible (does it matter which index is returned)?",
        bottleneck="Scanning left to right ignores the sorted order that lets me eliminate half the array per comparison.",
        test="[-1,0,3,5,9,12], target=9 -> mid narrows down, found at index 4. Edge: target not present, e.g. target=2 -> left crosses right, return -1.",
        other_edges="single-element array; target is the first or last element; empty array.",
    ),
    "Find Minimum in Rotated Sorted Array": dict(
        clarify="All values unique guaranteed? Could the array be not rotated at all (already sorted)?",
        bottleneck="Scanning every element to find the min ignores the sorted-then-rotated structure that binary search can exploit.",
        test="[3,4,5,1,2] -> mid=5>right(2) so search right half; converges to index 3, value 1. Edge: not rotated, e.g. [1,2,3,4,5] -> nums[mid] never exceeds nums[right], converges to index 0.",
        other_edges="rotation point at the very start (no rotation); rotation point at the very end; two-element array.",
    ),
    "LRU Cache": dict(
        clarify="Capacity guaranteed at least 1? Does 'use' include both get AND put (both refresh recency)?",
        bottleneck="Using a plain list to track recency order means removing/reordering an item costs O(n) (shifting).",
        test="capacity=2: put(1,1),put(2,2),get(1)->1,put(3,3) evicts key 2,get(2)->-1. Edge: updating an existing key's value must move it to most-recent, not just overwrite in place.",
        other_edges="capacity of 1 (every put evicts the previous key); getting a key right after inserting it; repeated puts to the same key.",
    ),
    "Random Pick with Weight": dict(
        clarify="Weights guaranteed positive integers? Does pick_index get called many times (yes, so precompute once)?",
        bottleneck="Building a bucket array of size sum(weights) wastes huge memory when weights are large.",
        test="w=[1,3] -> prefix=[1,4], total=4; random in [1,4]: 1->index 0, 2..4->index 1 (3x more likely, matching weight). Edge: single weight of 1 -> always index 0.",
        other_edges="all weights equal (uniform pick); one very large weight dominating; two weights only.",
    ),
    "Rotting Oranges": dict(
        clarify="4-directional spread only, not diagonal? Return 0 if no fresh oranges exist at the start?",
        bottleneck="Rescanning the entire grid every single minute to find newly-infected oranges redoes work already known.",
        test="[[2,1,1],[1,1,0],[0,1,1]] -> rot spreads outward minute by minute, takes 4 minutes total. Edge: a fresh orange sealed off by walls with no path to any rotten orange -> fresh never hits 0, return -1.",
        other_edges="no fresh oranges at all (return 0); no rotten oranges but fresh ones exist (return -1); grid that's entirely empty cells.",
    ),
    "Maximum Subarray": dict(
        clarify="Array guaranteed non-empty? Must return a real subarray sum (can't return 0 for an empty selection)?",
        bottleneck="Recomputing every subarray's sum from scratch redoes overlapping additions across nearby subarrays.",
        test="[-2,1,-3,4,-1,2,1,-5,4] -> running sum resets after negatives, builds up to best=6 via [4,-1,2,1]. Edge: all-negative array, e.g. [-3,-1,-2] -- starting at nums[0] (not 0) correctly gives -1.",
        other_edges="single-element array; entire array is the answer (all positive); array with a single large positive surrounded by negatives.",
    ),
    "Top K Frequent Elements": dict(
        clarify="Order of the output doesn't matter? k guaranteed <= number of distinct elements?",
        bottleneck="Fully sorting all distinct values by frequency does more ordering work than needed when I only want the top k.",
        test="[1,1,1,2,2,3], k=2 -> counts {1:3,2:2,3:1}; buckets collect from freq=3 down, stop once 2 collected -> [1,2]. Edge: k equals number of distinct elements -> loop collects everything before returning.",
        other_edges="all elements with the same frequency; k=1 (single most frequent); many low-frequency singletons.",
    ),
}
