PROBLEMS = []

PROBLEMS.append(dict(
    title="Walls and Gates", lc_num="286", difficulty="MEDIUM", pattern="Multi-Source BFS",
    relevance="Common interview pattern",
    restate="We're given a 2D grid representing a building, where each cell is either a wall (-1), a gate (0), or an empty room (a large sentinel value like 2147483647), and we need to fill every empty room with the distance to its nearest gate, leaving walls unchanged.",
    clarify_questions=[
        "Can I move in all four directions (up, down, left, right), not diagonally?",
        "Should unreachable rooms (surrounded entirely by walls, no path to any gate) stay at the sentinel value?",
        "Can there be multiple gates in the grid?",
        "Should I modify the grid in place, or return a new grid?",
    ],
    restate_say=["Just to confirm, I move in four directions only, there can be multiple gates, and I need to fill each empty room in place with its distance to the NEAREST gate, correct?"],
    brute_idea="For every empty room, run a separate BFS (or DFS) outward to find the nearest gate, recording the shortest distance found.",
    brute_say=["The straightforward approach is, for every single empty room, run its own BFS out to find the nearest gate and record that distance."],
    brute_time="Each BFS from a room can take O(rows * cols) in the worst case, and there can be O(rows * cols) rooms, giving O((rows*cols)²) overall.",
    brute_space="O(rows * cols) per BFS for the visited tracking.",
    brute_complexity_say="This is O((rows times cols) squared) time in the worst case, since we potentially do a full grid-sized BFS separately for every single room, which is very wasteful.",
    bottleneck="I'm redoing a full search from every single room, when actually multiple gates and rooms share overlapping search space; if I start the search from ALL gates simultaneously instead, each cell only needs to be visited once.",
    bottleneck_say="The bottleneck is running a separate search from every room, when I could instead run one combined search starting from all gates at once, since BFS naturally finds shortest distances outward from its starting points.",
    optimization_explain="I use Multi-Source BFS. Instead of searching FROM each room TO the nearest gate, I search FROM all the gates simultaneously OUTWARD to every reachable room. I initialize a queue with every gate's position (distance 0). Then I do a standard BFS: for each cell dequeued, I look at its four neighbors; if a neighbor is an empty room (still holding the sentinel value), I set its distance to current distance + 1 and enqueue it. Because BFS explores in increasing distance order, the first time any room is reached is guaranteed to be via the shortest path from SOME gate.",
    key_insight="Starting BFS simultaneously from every gate (rather than from each room individually) means every cell is visited at most once total, since BFS naturally expands in order of increasing distance, guaranteeing the first visit to any room is via its true nearest gate.",
    optimization_say=[
        "Instead of searching from each room to find its nearest gate, I'll flip the direction: start a BFS from ALL the gates at the same time.",
        "I'll put every gate into a queue first, then expand outward level by level, filling in each newly reached room with its distance.",
        "Since BFS expands in order of distance, the first time a room is reached is guaranteed to be its shortest distance to any gate.",
    ],
    code_blocks=[
        dict(code="from collections import deque\n\ndef walls_and_gates(rooms):\n    if not rooms:\n        return\n    rows, cols = len(rooms), len(rooms[0])\n    queue = deque()\n    for r in range(rows):\n        for c in range(cols):\n            if rooms[r][c] == 0:\n                queue.append((r, c))",
             say="I handle the empty grid case, then find every gate (a cell with value 0) and add all of them to the queue upfront, before starting the BFS.",
             why="Seeding the queue with ALL gates at once (rather than one at a time) is exactly what makes this 'multi-source' — the BFS naturally explores from every gate simultaneously, in lockstep by distance."),
        dict(code="    directions = [(-1,0),(1,0),(0,-1),(0,1)]\n    while queue:\n        row, col = queue.popleft()\n        for dr, dc in directions:\n            new_row, new_col = row + dr, col + dc\n            if (0 <= new_row < rows and 0 <= new_col < cols\n                    and rooms[new_row][new_col] == 2147483647):\n                rooms[new_row][new_col] = rooms[row][col] + 1\n                queue.append((new_row, new_col))",
             say="I process the queue level by level, checking all four neighbors of the current cell. If a neighbor is within bounds and still holds the sentinel value (meaning it's an unvisited empty room), I set its distance to one more than the current cell's distance and add it to the queue.",
             why="Checking for the sentinel value doubles as our 'visited' check, so a room is only ever processed once total, which is what gives this its efficient linear-time guarantee across the whole grid."),
    ],
    dry_run="Small grid: [[INF, -1, 0, INF], [INF, INF, INF, -1], [INF, -1, INF, -1], [0, -1, INF, INF]] (INF=2147483647). Queue starts with both gates: (0,2) and (3,0). Process (0,2): neighbors (0,1)=-1 skip, (0,3)=INF -> set to 1, enqueue. (1,2)=INF -> set to 1, enqueue. Process (3,0): neighbors (2,0)=INF -> set to 1, enqueue. Continue expanding level by level, filling every reachable room with increasing distances, until the queue is empty, leaving unreachable rooms (if fully walled off) still at INF.",
    dry_run_say="Starting the BFS from both gates at once, the search expands outward layer by layer, correctly assigning each empty room the distance to whichever gate reaches it first — which is guaranteed to be its true nearest gate.",
    edge_case="A room completely walled off from every gate, with no possible path. It's never dequeued or reached by the BFS from any gate, so it correctly remains at the sentinel value 2147483647, signaling it's unreachable, exactly as the problem expects.",
    edge_case_say="Let me check a room that's completely sealed off by walls with no path to any gate — since the BFS never reaches it, it correctly stays at the sentinel value, signaling it's unreachable.",
    other_edge_cases=[
        "A grid with only one gate",
        "A grid with no gates at all (every room stays at the sentinel value)",
        "A grid that's entirely walls except a single gate",
        "A grid where a room is equidistant from two different gates",
    ],
    final_complexity_rows=[["Optimized", "O(rows * cols)", "O(rows * cols)"]],
    final_complexity_say="This is O(rows times cols) time since every cell is enqueued and processed at most once, and O(rows times cols) space for the queue in the worst case, a big improvement over the naive per-room BFS approach.",
    pushback=[
        ("Why is multi-source BFS correct here, not just faster?", "Because BFS explores cells in strictly increasing order of distance from its starting points, and since ALL gates start simultaneously at distance 0, the very first time any room is reached is guaranteed to be via whichever gate is genuinely closest, so correctness and efficiency come together in one pass."),
        ("Can you solve this with DFS instead?", "DFS could work but would require additional bookkeeping to track and compare distances via different paths, since DFS doesn't naturally explore in order of increasing distance the way BFS does, making it less natural and potentially requiring revisiting cells multiple times to guarantee correctness."),
        ("What if walls could change dynamically?", "This solution assumes a static grid for a single query; if walls or gates could be updated frequently, a different approach (like maintaining a more dynamic shortest-path structure, or recomputing BFS whenever the grid changes significantly) would be needed."),
        ("Can you optimize this further?", "No, O(rows times cols) is already optimal since we must visit every reachable room at least once to determine its distance."),
    ],
    mistakes=[
        "Running BFS from each room individually instead of seeding the queue with all gates at once.",
        "Forgetting to check grid boundaries before accessing a neighbor, causing an index error.",
        "Using a separate visited set instead of relying on the sentinel value check, adding unnecessary complexity.",
        "Not skipping walls (-1) when considering neighbors, potentially overwriting them incorrectly.",
    ],
    recovery=[
        "If stuck: 'Running BFS from every room separately seems slow because of overlapping work. What if I flip the direction and search outward from all the gates instead?'",
        "If I only start BFS from one gate: recognize that with multiple gates, I need to seed the queue with ALL of them at the start, not just search from a single one.",
        "If the interviewer hints 'think about starting from multiple points at once': confirm and describe multi-source BFS explicitly.",
        "If I get an index error: double-check the boundary conditions on the neighbor check before accessing rooms[new_row][new_col].",
    ],
    pattern_recognition=dict(
        triggers="'nearest gate/source', 'distance to closest of multiple targets', 'fill grid with distances'",
        pattern="Multi-Source BFS",
        first_thought="Instead of searching FROM each target TO the nearest source, flip it: search FROM all sources simultaneously OUTWARD.",
        trap="Running BFS separately from each room instead of seeding the queue with every gate up front.",
    ),
    memory_hook="Walls and Gates → \"Start BFS from every gate at once — first arrival is always the nearest.\"",
    recap_key_idea="Seed the BFS queue with all gates simultaneously; expand outward, and the first visit to any room is guaranteed to be its shortest distance.",
    recap_data_structure="A queue (deque) for BFS.",
    recap_algorithm="Multi-Source BFS.",
    recap_time="O(rows * cols)", recap_space="O(rows * cols)", recap_edge_case="A room with no path to any gate (stays at the sentinel value).",
    talk_track=[
        ("Interviewer", "Fill each empty room in this grid with its distance to the nearest gate."),
        ("Me", "Got it — I move in four directions, there can be multiple gates, and I modify the grid in place, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force: run a separate BFS from every room to find its nearest gate — that's O((rows times cols) squared) since there's a lot of overlapping search work."),
        ("Interviewer", "How would you avoid that overlap?"),
        ("Me", "I'd flip the direction of the search: instead of searching from each room outward to find a gate, I start a BFS from ALL the gates simultaneously, expanding outward. Since BFS explores in order of increasing distance, the first time any room is reached is guaranteed to be from its true nearest gate."),
        ("Me", "Let me code that — seed the queue with every gate's position first, then expand level by level, filling in distances as I go."),
        ("Me", "Tracing a small grid with two gates, the search correctly fills every reachable room with increasing distances outward from whichever gate reaches it first."),
        ("Me", "Edge case: a room completely sealed off by walls never gets reached, and correctly stays at the sentinel value signaling it's unreachable."),
        ("Me", "Final complexity: O(rows times cols) time and space, since every cell is processed at most once."),
    ],
))

PROBLEMS.append(dict(
    title="Rotting Oranges", lc_num="994", difficulty="MEDIUM", pattern="Multi-Source BFS",
    relevance="Common interview pattern",
    restate="We're given a grid where each cell is either empty (0), a fresh orange (1), or a rotten orange (2), and every minute any fresh orange adjacent to a rotten orange also becomes rotten; we need to find the minimum number of minutes until no fresh orange remains, or -1 if that's impossible.",
    clarify_questions=[
        "Can rotting spread in all four directions, not diagonally?",
        "Should I return 0 if there are no fresh oranges at all to begin with?",
        "Are there guaranteed to be some rotten oranges initially, or could there be none?",
        "Should I return -1 if some fresh oranges can never be reached?",
    ],
    restate_say=["Just to confirm, rotting spreads in four directions each minute, and I need the minimum minutes until every orange is rotten, or -1 if some fresh orange can never be reached, correct?"],
    brute_idea="Simulate minute by minute: scan the entire grid each minute, find all currently fresh oranges adjacent to a rotten one, mark them to rot at the end of that minute, and repeat until no more changes happen.",
    brute_say=["A direct simulation approach scans the whole grid every minute, finds newly infected oranges, and repeats until nothing changes, counting the minutes elapsed."],
    brute_time="Each minute's scan is O(rows*cols), and in the worst case we might need O(rows*cols) minutes (a long snake-like spread), giving O((rows*cols)²).",
    brute_space="O(rows*cols) to track which cells rot in a given minute.",
    brute_complexity_say="This simulate-every-minute-with-a-full-scan approach is O((rows times cols) squared) in the worst case, since scanning the whole grid repeatedly for each minute of spread adds up.",
    bottleneck="I'm rescanning the entire grid every single minute just to find the 'frontier' of newly rotten oranges, when I could directly track exactly which cells are on that frontier and only ever process each orange once.",
    bottleneck_say="The bottleneck is repeatedly scanning cells that already rotted or are still far from any rot, when I really just need to track the current 'frontier' of oranges about to spread.",
    optimization_explain="I use Multi-Source BFS, starting from every initially rotten orange simultaneously. I seed a queue with all rotten oranges' positions, and also count the total number of fresh oranges upfront. Then I process the queue level by level (each level represents one minute): for every rotten orange dequeued, I check its four neighbors, and any fresh orange found gets marked rotten, has the fresh count decremented, and gets enqueued for the next level. I track how many 'minutes' (BFS levels) it takes. At the end, if any fresh oranges remain uninfected, I return -1; otherwise I return the number of minutes elapsed.",
    key_insight="BFS naturally processes nodes in order of distance from the starting points, and here 'distance' directly corresponds to 'minutes elapsed', so a standard level-by-level BFS from all initial rotten oranges simultaneously directly simulates the minute-by-minute spread without redundant rescanning.",
    optimization_say=[
        "I'll seed a BFS queue with every initially rotten orange, and also count how many fresh oranges exist at the start.",
        "I'll process the queue level by level, where each level corresponds to exactly one minute passing, spreading rot to fresh neighbors and decrementing my fresh-orange counter as I go.",
        "At the end, if the fresh-orange counter isn't zero, some oranges were unreachable, so I return -1; otherwise I return the number of minutes (levels) it took.",
    ],
    code_blocks=[
        dict(code="from collections import deque\n\ndef oranges_rotting(grid):\n    rows, cols = len(grid), len(grid[0])\n    queue = deque()\n    fresh_count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 2:\n                queue.append((r, c))\n            elif grid[r][c] == 1:\n                fresh_count += 1",
             say="I scan the grid once to find all initially rotten oranges (adding them to the queue) and count all initially fresh oranges.",
             why="Seeding the queue with every rotten orange at once (multi-source) is what lets a single BFS simulate all the spreading happening simultaneously, exactly matching how rot spreads in real minutes."),
        dict(code="    minutes = 0\n    directions = [(-1,0),(1,0),(0,-1),(0,1)]\n    while queue and fresh_count > 0:\n        minutes += 1\n        for _ in range(len(queue)):\n            row, col = queue.popleft()\n            for dr, dc in directions:\n                new_row, new_col = row + dr, col + dc\n                if (0 <= new_row < rows and 0 <= new_col < cols\n                        and grid[new_row][new_col] == 1):\n                    grid[new_row][new_col] = 2\n                    fresh_count -= 1\n                    queue.append((new_row, new_col))",
             say="I process the queue in full 'levels': the inner for loop handles exactly the oranges that were rotten at the start of this minute, so anything newly rotted gets added for the NEXT minute, not this one. I increment minutes once per level, and only continue while there's still both something in the queue and fresh oranges left to infect.",
             why="Using 'for _ in range(len(queue))' to process a fixed snapshot of the queue's current size is the standard trick for level-by-level BFS, ensuring minutes increments exactly once per real minute of spread, not once per individual orange."),
        dict(code="    return minutes if fresh_count == 0 else -1",
             say="At the end, if every fresh orange got infected (fresh_count reached 0), I return the number of minutes it took; otherwise, some oranges were unreachable, so I return -1.",
             why="This final check distinguishes 'everything successfully rotted' from 'some oranges were permanently isolated and could never rot', which is exactly what the problem is asking us to detect."),
    ],
    dry_run="grid = [[2,1,1],[1,1,0],[0,1,1]]. Initial queue: [(0,0)]. fresh_count=6. Minute 1: process (0,0): neighbors (1,0)=1->rot, fresh_count=5, enqueue; (0,1)=1->rot, fresh_count=4, enqueue. minutes=1. Minute 2: process (1,0): neighbors (2,0)=0 skip, (1,1)=1->rot,fresh_count=3,enqueue. process (0,1): neighbors (0,2)=1->rot,fresh_count=2,enqueue; (1,1) already 2, skip. minutes=2. Minute 3: process (1,1): neighbors (2,1)=1->rot,fresh_count=1,enqueue. process (0,2): no new fresh neighbors. minutes=3. Minute 4: process (2,1): neighbor (2,2)=1->rot,fresh_count=0,enqueue. minutes=4. Loop ends since fresh_count=0. Return 4.",
    dry_run_say="Tracing a 3x3 grid with one initially rotten orange in the corner: the rot spreads outward minute by minute, and it takes exactly 4 minutes for every fresh orange to become rotten.",
    edge_case="A fresh orange that's completely isolated from any rotten orange, e.g. surrounded by empty cells with no rotten orange ever reaching it. The BFS never reaches that cell, so fresh_count never drops to 0, and the function correctly returns -1.",
    edge_case_say="Let me check a fresh orange that's isolated and can never be reached by any rotten orange — the fresh count never reaches zero, so we correctly return -1.",
    other_edge_cases=[
        "No fresh oranges at all initially (should return 0 immediately)",
        "No rotten oranges at all, but some fresh oranges exist (should return -1, since nothing can ever start spreading)",
        "A grid that's entirely empty cells",
        "All oranges already rotten from the start (should return 0)",
    ],
    final_complexity_rows=[["Optimized", "O(rows * cols)", "O(rows * cols)"]],
    final_complexity_say="This is O(rows times cols) time since every cell is enqueued and processed at most once, and O(rows times cols) space for the queue in the worst case, a significant improvement over the naive repeated-full-scan simulation.",
    pushback=[
        ("Why process the queue in 'levels' using its snapshot size?", "Because each level of the BFS corresponds exactly to one minute of real time, and using len(queue) at the START of each minute's processing ensures I only handle the oranges that were rotten BEFORE this minute, correctly separating this minute's spread from the next minute's."),
        ("What if there are no rotten oranges at the start but some fresh ones exist?", "The queue starts empty, so the while loop never executes, minutes stays 0, but fresh_count is still greater than 0, so the function correctly returns -1, since nothing can ever start rotting."),
        ("Can you solve this without modifying the input grid?", "Yes, I could use a separate visited/rotten-tracking structure instead of mutating grid values directly, at the cost of a bit more space, if modifying the input isn't allowed."),
        ("Can you optimize this further?", "No, O(rows times cols) is optimal since we must at least examine every orange once to determine the final outcome."),
    ],
    mistakes=[
        "Processing the queue without snapshotting its size per level, causing minutes to be miscounted (processing multiple 'minutes' of spread in a single increment, or vice versa).",
        "Forgetting to decrement fresh_count when a fresh orange becomes rotten, breaking the final check for whether all oranges were infected.",
        "Not handling the initial edge case where there are no fresh oranges at all (should immediately return 0).",
        "Confusing 'minutes' with 'number of oranges processed', rather than 'number of BFS levels'.",
    ],
    recovery=[
        "If stuck: 'Simulating minute by minute with a full grid rescan each time seems wasteful. Since rot spreads outward like a wave, this feels like a multi-source BFS problem, where distance corresponds directly to minutes.'",
        "If minutes come out wrong: check whether I'm using the queue-snapshot trick (for _ in range(len(queue))) to correctly separate one minute's processing from the next.",
        "If the interviewer hints 'think about all the rotten oranges spreading at once': confirm and describe seeding the BFS queue with all of them simultaneously.",
        "If fresh_count logic seems off: trace through a small example by hand to confirm it decrements exactly once per orange that turns rotten.",
    ],
    pattern_recognition=dict(
        triggers="'spreads over time', 'minutes until all infected/reached', 'simultaneous spreading from multiple sources'",
        pattern="Multi-Source BFS (level-by-level = time steps)",
        first_thought="Time steps in the problem map directly to BFS levels/distance — seed the queue with all starting 'infected' cells and expand level by level.",
        trap="Not using the level-snapshot trick, causing minutes to be counted incorrectly.",
    ),
    memory_hook="Rotting Oranges → \"BFS levels ARE the minutes — seed with every rotten orange at once.\"",
    recap_key_idea="Multi-source BFS from all initially rotten oranges; each BFS level equals one minute; track fresh count to detect unreachable oranges.",
    recap_data_structure="A queue (deque) for level-by-level BFS.",
    recap_algorithm="Multi-Source BFS with level counting.",
    recap_time="O(rows * cols)", recap_space="O(rows * cols)", recap_edge_case="A fresh orange that can never be reached (return -1).",
    talk_track=[
        ("Interviewer", "Find the minimum minutes until no fresh orange remains, or -1 if impossible."),
        ("Me", "Got it — rot spreads in four directions each minute, and I return -1 if some fresh orange can never be reached, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A direct simulation would rescan the whole grid every minute to find newly infected oranges, which is O((rows times cols) squared) in the worst case."),
        ("Me", "Since every rotten orange spreads simultaneously, I can treat this as multi-source BFS: seed the queue with all initially rotten oranges, and process it level by level, where each level equals one minute."),
        ("Me", "Let me code that, using the queue-snapshot trick to make sure I count minutes correctly, and tracking a fresh-orange counter to know when everything's infected."),
        ("Me", "Tracing a 3x3 grid with one rotten orange in the corner: the rot spreads outward, and it takes exactly 4 minutes for everything to turn rotten."),
        ("Me", "Edge case: if a fresh orange is completely isolated and can never be reached, the fresh count never reaches zero, and we correctly return -1."),
        ("Me", "Final complexity: O(rows times cols) time and space, since every cell is processed at most once."),
    ],
))
