PROBLEMS = []

PROBLEMS.append(dict(
    title="Kth Largest Element in a Stream", lc_num="703", difficulty="EASY", pattern="Heap (Min-Heap of size k)",
    relevance="Design-heavy problem",
    restate="We need to design a class that, given an integer k and an initial stream of numbers, supports adding new numbers to the stream one at a time and always returning the kth largest element in the stream so far.",
    clarify_questions=[
        "Does 'kth largest' mean the kth largest counting duplicates (so [5,5] with k=2 gives 5, not the 2nd distinct value)?",
        "Is k guaranteed to be less than or equal to the number of elements added so far after initialization?",
        "How many times will 'add' be called \u2014 does that affect whether we optimize for frequent calls?",
        "Can the numbers include duplicates or negative values?",
    ],
    restate_say=["Just to confirm, kth largest counts duplicates, k stays fixed for the object's lifetime, and 'add' will likely be called many times, so I should optimize for repeated calls, not just one query, correct?"],
    brute_idea="Keep a plain list of all numbers seen so far, and every time 'add' is called, insert the new number, sort the whole list, and return the kth element from the end.",
    brute_say=["The simplest approach is to store every number in a list, and each time a new number is added, re-sort the entire list and pick out the kth largest."],
    brute_time="Each call to 'add' costs O(n log n) for the sort, where n is the number of elements seen so far.",
    brute_space="O(n) to store all the numbers.",
    brute_complexity_say="This is O(n log n) time per add call, which adds up badly if 'add' is called many times, since we're re-sorting everything from scratch every single time.",
    bottleneck="I'm re-sorting the entire history of numbers on every single call, when I really only ever need to know the k largest values \u2014 everything smaller than that is irrelevant and doesn't need to be tracked precisely at all.",
    bottleneck_say="The bottleneck is treating every number as equally important and re-sorting everything, when I only actually care about the k largest values at any given time.",
    optimization_explain="I maintain a Min-Heap that never holds more than k elements \u2014 specifically, the heap always holds exactly the k largest numbers seen so far, with the SMALLEST of those k sitting at the top of the heap. When a new number arrives: if the heap has fewer than k elements, I just add it. Otherwise, I compare the new number to the heap's smallest (top) element; if the new number is bigger, it deserves to be in the top k, so I pop the current smallest and push the new number in its place. In either case, the kth largest element is always exactly the top of this size-k min-heap.",
    key_insight="If I only ever keep the k largest elements seen so far, then the smallest one AMONG those k is, by definition, the kth largest element overall \u2014 and a min-heap gives me O(1) access to that smallest-of-the-k value at all times.",
    optimization_say=[
        "I'll maintain a min-heap capped at size k, holding exactly the k largest numbers seen so far.",
        "When a new number comes in, if the heap isn't full yet, I just add it; if it's full, I only replace the heap's smallest element if the new number is bigger.",
        "The top of this heap is always the smallest of the current top-k, which is exactly the kth largest value overall.",
    ],
    code_blocks=[
        dict(code="import heapq\n\nclass KthLargest:\n    def __init__(self, k, nums):\n        self.k = k\n        self.heap = []\n        for num in nums:\n            self.add(num)",
             say="In the constructor, I store k and start with an empty heap, then add every number from the initial stream one at a time using the same 'add' method I'll use later.",
             why="Reusing 'add' for the initial numbers avoids duplicating logic \u2014 the constructor is really just a sequence of the same operation that happens later for each new number."),
        dict(code="    def add(self, val):\n        if len(self.heap) < self.k:\n            heapq.heappush(self.heap, val)\n        elif val > self.heap[0]:\n            heapq.heapreplace(self.heap, val)\n\n        return self.heap[0]",
             say="If the heap hasn't reached size k yet, I just push the new value in. Once it's at size k, I only push a new value in (replacing the current smallest) if it's bigger than the heap's current smallest element. Either way, I return the heap's top, which is the current kth largest value.",
             why="heapq.heapreplace does an efficient pop-then-push in one operation, and only doing the replace when val is bigger than the current minimum avoids unnecessary heap operations when the new value wouldn't even make it into the top k anyway."),
    ],
    dry_run="k=3, initial nums=[4,5,8,2]. add(4): heap size 0<3, push -> [4]. add(5): size 1<3, push -> [4,5] (heap keeps 4 on top). add(8): size 2<3, push -> [4,5,8] (heap keeps 4 on top). add(2): size 3, not <3. 2 > heap[0]=4? No. So heap unchanged, still [4,5,8], top is 4. Return 4 (the 3rd largest among 4,5,8,2 is indeed 4). Now call add(3): size 3, 3>4? No, heap unchanged, return 4. Call add(10): size 3, 10>4? Yes, heapreplace pops 4 and pushes 10 -> heap becomes [5,8,10] (top now 5). Return 5, which is the 3rd largest among {4,5,8,2,3,10}: sorted desc is 10,8,5,4,3,2, and the 3rd largest is indeed 5.",
    dry_run_say="With k=3 and numbers 4,5,8,2 added initially, the heap settles on holding {4,5,8} with 4 on top, meaning 4 is the 3rd largest so far. Adding 3 doesn't change anything since it's smaller than the current minimum of the top 3. Adding 10 replaces 4 with 10, and the new 3rd largest becomes 5.",
    edge_case="Adding a value smaller than everything currently in the heap once the heap is already at size k, e.g. continuing the example above and adding 1. Since 1 is not greater than heap[0]=5, the heap remains unchanged, and the kth largest stays 5, correctly ignoring numbers that don't even make it into the current top k.",
    edge_case_say="Let me check adding a very small number once the heap is already full, like adding 1 to a heap holding {5,8,10} \u2014 since 1 isn't bigger than the current minimum of 5, the heap correctly stays unchanged, and the answer remains 5.",
    other_edge_cases=[
        "k equals 1 (just track the single largest value seen)",
        "Duplicate values being added multiple times",
        "The initial nums array being empty",
        "k equal to the total count of numbers added so far, right at the boundary",
    ],
    final_complexity_rows=[["add()", "O(log k)", "O(k)"]],
    final_complexity_say="Each call to 'add' runs in O(log k) time, since heap push/replace operations on a heap of size k cost O(log k), and the heap uses O(k) space total, regardless of how many numbers have been added overall, which is a big improvement over the brute force's O(n log n) per call.",
    pushback=[
        ("Why use a min-heap and not a max-heap?", "Because I specifically need fast access to the SMALLEST of the current top-k elements (to decide whether a new number should replace it, and to answer the 'kth largest' query directly), and a min-heap gives O(1) access to its minimum at the top, which is exactly the value I need."),
        ("What if k could change after the object is created?", "The problem specifies k is fixed for the object's lifetime; if it needed to change dynamically, I'd need additional logic to resize the heap, potentially rebuilding it from a larger stored history, which would add complexity."),
        ("Can you avoid heapq.heapreplace and just use separate pop and push?", "Yes, that would work too, but heapreplace does it as a single optimized operation (pop then push) rather than two separate calls, which is slightly more efficient in practice."),
        ("Can you optimize this further?", "O(log k) per add is already quite efficient; the only way to do better would be O(1) amortized, which isn't generally achievable for this kind of 'maintain the kth order statistic under insertions' problem with a comparison-based structure."),
    ],
    mistakes=[
        "Re-sorting the entire history on every add call instead of maintaining a bounded-size heap.",
        "Using a max-heap of ALL elements instead of a min-heap capped at size k, which wastes both time and space.",
        "Forgetting the 'val > heap[0]' check before replacing, and always replacing regardless of whether the new value actually belongs in the top k.",
        "Not reusing the 'add' method for processing the initial nums list in the constructor, leading to duplicated logic.",
    ],
    recovery=[
        "If stuck: 'Re-sorting on every call is wasteful since I only ever care about the top k values. Let me think about a structure that only remembers the k largest values efficiently.'",
        "If I use the wrong heap type: reason aloud, 'I need quick access to the smallest of my current best k, so that's a min-heap, not a max-heap.'",
        "If the interviewer hints 'you don't need the full history': confirm and describe capping the heap at size k.",
        "If unsure about heapreplace: it's equivalent to a pop followed by a push, just combined into one call for efficiency \u2014 explain it that way if the exact function name is forgotten.",
    ],
    pattern_recognition=dict(
        triggers="'kth largest in a stream', 'design a class that supports adding and querying kth largest'",
        pattern="Heap (Min-Heap bounded to size k)",
        first_thought="I only need to track the top k values at any time \u2014 a size-k min-heap gives me instant access to the smallest of those top k, which is the kth largest overall.",
        trap="Rebuilding/re-sorting the whole history on every call instead of maintaining a small bounded heap incrementally.",
    ),
    memory_hook="Kth Largest in a Stream \u2192 \"Min-heap of size k; the top of the heap IS the kth largest.\"",
    recap_key_idea="Maintain a min-heap capped at size k; a new value only gets added if it beats the current minimum of the top k.",
    recap_data_structure="A min-heap (Python's heapq) of size at most k.",
    recap_algorithm="Bounded heap maintenance across repeated 'add' calls.",
    recap_time="O(log k) per add", recap_space="O(k)", recap_edge_case="Adding a value smaller than everything already in a full heap (should be ignored).",
    talk_track=[
        ("Interviewer", "Design a class that returns the kth largest element in a stream after each new number is added."),
        ("Me", "Got it \u2014 kth largest counts duplicates, k stays fixed, and I should expect 'add' to be called many times, so I should optimize for that, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "The simplest approach would re-sort the entire history on every add call, which is O(n log n) per call \u2014 that gets expensive fast."),
        ("Me", "Since I only ever care about the k largest values, I'll maintain a min-heap capped at size k. If it's not full yet, I just add the new number. Once it's full, I only replace the heap's smallest element if the new number beats it."),
        ("Me", "The heap's top is always the smallest of the current top-k, which is exactly the kth largest value, so I can return it directly after every add."),
        ("Me", "Let me code that, reusing the add method itself to process the initial numbers in the constructor."),
        ("Me", "Tracing k=3 with initial numbers 4,5,8,2: the heap settles on {4,5,8}, so the 3rd largest is 4. Adding 10 replaces 4, giving a new 3rd largest of 5."),
        ("Me", "Edge case: adding a small number once the heap is full and it doesn't beat the current minimum \u2014 the heap correctly stays unchanged."),
        ("Me", "Final complexity: O(log k) per add call, O(k) space, much better than re-sorting the whole stream every time."),
    ],
))
