PROBLEMS = []

PROBLEMS.append(dict(
    title="Jump Game", lc_num="55", difficulty="MEDIUM", pattern="Greedy",
    relevance="Common interview pattern",
    restate="We're given an array where each element represents the maximum jump length from that position, starting at index 0, and we need to determine if we can reach the last index.",
    clarify_questions=[
        "Can jump lengths be 0, potentially trapping us at a position?",
        "Are all values guaranteed non-negative?",
        "Is the array guaranteed non-empty, and does a single-element array trivially return true?",
        "Do we need the actual path, or just whether it's reachable?",
    ],
    restate_say=["Just to confirm, from any index I can jump up to (but not exceeding) that index's value forward, and I just need a yes/no on whether index 0 can reach the last index, correct?"],
    brute_idea="Use recursion or DFS: from the current index, try every possible jump length, and recursively check if any of them can eventually reach the end.",
    brute_say=["A direct approach is recursive: from any position, try every possible jump size and recursively check if any of those choices eventually reaches the last index."],
    brute_time="In the worst case, this branches into many choices at every step, giving exponential O(2^n) time without memoization.",
    brute_space="O(n) for the recursion stack.",
    brute_complexity_say="This is exponential time in the worst case, since at every index we might branch into many different jump choices, and those branches multiply quickly.",
    bottleneck="I'm exploring many different specific jump choices, when actually all I really need to know is the single furthest index reachable so far — the exact path taken doesn't matter, only how far it lets me go.",
    bottleneck_say="The bottleneck is treating this like a full path-search problem, when actually I only need to track the single furthest reachable index as I scan through, not every possible route to get there.",
    optimization_explain="I use a Greedy approach, scanning left to right while tracking the furthest index reachable so far. At each index i, if i is beyond the furthest reachable point, I can never even get here, so it's impossible to continue; otherwise, I update furthest = max(furthest, i + nums[i]). If at any point furthest reaches or exceeds the last index, I know I can get there.",
    key_insight="I don't need to know exactly which sequence of jumps gets me somewhere — I only need to know the single furthest index that's reachable using any combination of jumps up to the current point, and that value can be tracked and updated in one simple linear scan.",
    optimization_say=[
        "I'll scan left to right, keeping track of the furthest index reachable so far using any jumps up to this point.",
        "At each index, if it's beyond what I could ever reach, I'm stuck, so I return False immediately.",
        "Otherwise, I update the furthest reachable index using the current position's jump length, and if that ever covers the last index, I return True.",
    ],
    code_blocks=[
        dict(code="def can_jump(nums):\n    furthest = 0",
             say="I initialize furthest, the farthest index reachable so far, to 0, since we start at index 0.",
             why="This single variable is all the state I need to track — it summarizes every possible combination of jumps taken so far into one number."),
        dict(code="    for i in range(len(nums)):\n        if i > furthest:\n            return False\n        furthest = max(furthest, i + nums[i])",
             say="For each index, if it's beyond the furthest point I could have reached, I could never have gotten here in the first place, so I return False. Otherwise, I update furthest using how far I could jump from here.",
             why="Checking 'i > furthest' before updating catches the case where we've hit a dead index that was never actually reachable, which would otherwise silently produce a wrong (too optimistic) answer."),
        dict(code="    return True",
             say="If the loop finishes without ever returning False, that means every index along the way was reachable, so I return True.",
             why="Reaching the end of the loop means the furthest reachable point never fell short of any index we needed to pass through, which is exactly the condition for successfully reaching the last index."),
    ],
    dry_run="nums = [2,3,1,1,4]. i=0: 0<=furthest(0). furthest=max(0,0+2)=2. i=1: 1<=2. furthest=max(2,1+3)=4. i=2: 2<=4. furthest=max(4,2+1)=4. i=3: 3<=4. furthest=max(4,3+1)=4. i=4: 4<=4. furthest=max(4,4+4)=8. Loop ends (i only goes to len-1=4). Return True — index 4 (the last index) was reachable.",
    dry_run_say="Tracing [2,3,1,1,4]: the furthest reachable index quickly grows to 4, covering the last index, so we correctly return true.",
    edge_case="A 0 that traps us, e.g. nums=[3,2,1,0,4]. i=0: furthest=max(0,3)=3. i=1: 1<=3, furthest=max(3,1+2)=3. i=2: 2<=3, furthest=max(3,2+1)=3. i=3: 3<=3, furthest=max(3,3+0)=3. i=4: 4>furthest(3), return False immediately — correctly detecting we can never reach index 4 because the 0 at index 3 traps us there.",
    edge_case_say="Let me check a case with a 0 that traps us, like [3,2,1,0,4] — the furthest reachable index gets stuck at 3, and when we reach index 4, it's beyond what's reachable, so we correctly return false.",
    other_edge_cases=[
        "Single-element array (trivially true, we're already at the last index)",
        "Array starting with a 0 (only true if the array has length 1)",
        "Array where every element is the same large jump value",
        "Array with a very long stretch of zeros",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time since it's a single pass through the array, and O(1) space since only one running variable, furthest, is tracked.",
    pushback=[
        ("Why does the greedy approach work here?", "Because reachability is monotonic — if I can reach some index, tracking the single furthest point reachable using ALL jumps available so far always dominates any other bookkeeping; there's no advantage to remembering a specific path, since only the furthest extent matters for future reachability."),
        ("Can you solve this with Dynamic Programming instead?", "Yes, a DP approach would define dp[i] as whether index i is reachable, checking all previous reachable indices that could jump to i, but that's O(n²) in the naive form, strictly worse than the O(n) greedy approach."),
        ("What if you needed to find the actual sequence of jumps, not just whether it's possible?", "I'd need to track more information, like a 'came from' pointer at each step, and greedy would need to be adjusted to a proper shortest-path or backtracking approach to reconstruct one valid path."),
        ("Can you optimize further?", "No, O(n) is optimal since we must examine every index at least once to determine overall reachability."),
    ],
    mistakes=[
        "Forgetting the check 'if i > furthest' and blindly updating furthest even at an unreachable index, giving an incorrect true result.",
        "Confusing this with the related 'Jump Game II' (minimum number of jumps), which requires additional bookkeeping.",
        "Assuming jump values are always positive, missing that a 0 can create a trap.",
        "Trying to solve this recursively without memoization, leading to exponential blowup.",
    ],
    recovery=[
        "If stuck: 'Instead of tracking every possible jump path, let me just track the single furthest index reachable overall — that should be enough information.'",
        "If I forget to check 'i > furthest': notice the bug during a dry run involving a trapping zero, where the algorithm would otherwise wrongly continue past an unreachable index.",
        "If the interviewer hints 'you don't need the actual path': confirm and describe the greedy furthest-reachable-index tracking.",
        "If confused with Jump Game II: clarify out loud that this version only asks yes/no reachability, not minimum jumps.",
    ],
    pattern_recognition=dict(
        triggers="'can you reach the last index', 'maximum jump length from each position'",
        pattern="Greedy (track the furthest reachable index)",
        first_thought="I don't need the actual jump sequence, just the single furthest point reachable so far, updated as I scan.",
        trap="Forgetting to check if the current index itself is still reachable before updating the furthest-reach variable.",
    ),
    memory_hook="Jump Game → \"Track the furthest you could ever reach — forget the actual path.\"",
    recap_key_idea="Scan left to right, tracking the furthest reachable index; fail immediately if the current index is beyond that.",
    recap_data_structure="One scalar variable, furthest.",
    recap_algorithm="Greedy single pass.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="A 0 value that traps progress before reaching the end.",
    talk_track=[
        ("Interviewer", "Can you reach the last index of this array, jumping at most nums[i] steps from index i?"),
        ("Me", "Got it — just a yes/no answer, and jump values could include 0, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A recursive approach trying every jump choice would be exponential in the worst case."),
        ("Me", "Instead, I only need to track the furthest index reachable so far as I scan left to right. If I ever reach an index beyond that furthest point, I'm stuck and return false; otherwise, I keep updating the furthest reach."),
        ("Me", "Let me code that — a single pass with one running variable."),
        ("Me", "Tracing [2,3,1,1,4]: the furthest reachable index quickly covers the last index, so it's true."),
        ("Me", "Edge case: a trapping zero, like [3,2,1,0,4] — the furthest reach gets stuck at index 3, and index 4 becomes unreachable, correctly returning false."),
        ("Me", "Final complexity: O(n) time, one pass, O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Task Scheduler", lc_num="621", difficulty="MEDIUM", pattern="Greedy + Math (or Heap simulation)",
    relevance="Common interview pattern",
    restate="We're given a list of tasks (each represented by a letter) and a cooldown period n, meaning the same task must be separated by at least n other tasks or idle slots, and we need to find the minimum total time (including idle time) needed to complete all tasks.",
    clarify_questions=[
        "Can different task types be scheduled back-to-back with no restriction, only the SAME task type needs the cooldown?",
        "Is n guaranteed to be non-negative?",
        "If there's idle time needed, does it count toward the total time returned?",
        "Can the order of different task types be chosen freely to minimize idle time?",
    ],
    restate_say=["Just to confirm, only repeating the SAME task requires waiting n slots (other tasks or idle time) in between, and I want to minimize total time including any necessary idle slots, correct?"],
    brute_idea="Simulate scheduling minute by minute: at each time slot, greedily pick any available task (not on cooldown) with the highest remaining count, or idle if none are available, and track the total time elapsed using a priority queue.",
    brute_say=["A direct simulation approach processes one time unit at a time, using a priority queue (or similar structure) to always pick the most frequent available task, adding idle time when nothing's available."],
    brute_time="This simulation runs in roughly O(total_time * log(unique_tasks)) since each time step involves a heap operation.",
    brute_space="O(unique_tasks) for the counts and heap.",
    brute_complexity_say="This simulation approach is efficient, roughly O(total time times log of the number of distinct tasks), and is actually a fully valid solution — but there's also a neat closed-form math formula that avoids simulating minute by minute at all.",
    bottleneck="Simulating every single time unit works but is more computation than necessary; since the structure of the optimal schedule is very predictable (it's dominated by however many times the MOST frequent task appears), there's a direct formula that skips the simulation entirely.",
    bottleneck_say="Simulating minute by minute isn't wrong, but it's more work than needed, since the answer's shape is actually determined by simple counting: how many times does the most frequent task appear, and how many DIFFERENT tasks tie for that maximum frequency.",
    optimization_explain="I use a Greedy + Math formula approach. I count each task's frequency. Let max_freq be the highest frequency among all tasks, and max_count be how many distinct tasks share that highest frequency. Picture the schedule as (max_freq - 1) complete 'chunks', each chunk being (n+1) slots wide (the most frequent task, plus n cooldown slots to fill with other tasks or idle time), plus one final chunk containing just the max_count tasks that tied for the highest frequency. This gives a formula: (max_freq - 1) * (n + 1) + max_count. However, if there are enough OTHER tasks to fill in all the idle gaps, idle time is never actually needed, so the true answer is the maximum of that formula and simply the total number of tasks.",
    key_insight="The tightest constraint on the schedule always comes from the single most frequent task (or tasks, if there's a tie), since scheduling it optimally with the mandatory cooldown gaps determines a minimum schedule length; if there are enough other distinct tasks to fill every gap, the schedule can be fully packed with no idle time, in which case the answer is just simply the total number of tasks.",
    optimization_say=[
        "I'll count the frequency of every task, then find the maximum frequency and how many tasks share that maximum.",
        "I'll use those two numbers directly in a formula: (max_freq minus 1) times (n plus 1), plus however many tasks tie for the max frequency.",
        "Since idle time is only actually needed if there aren't enough other tasks to fill the gaps, I'll take the maximum of that formula and the total task count, which naturally handles both cases.",
    ],
    code_blocks=[
        dict(code="from collections import Counter\n\ndef least_interval(tasks, n):\n    counts = Counter(tasks)\n    max_freq = max(counts.values())",
             say="I count how many times each task appears, then find the highest frequency among all of them.",
             why="The most frequent task is what dictates the minimum spacing structure of the entire schedule, so it's the key number I need first."),
        dict(code="    max_count = sum(1 for count in counts.values() if count == max_freq)",
             say="I count how many distinct tasks share that maximum frequency.",
             why="If multiple tasks tie for the most frequent, they all need to occupy the final 'leftover' chunk together, which adds directly to the schedule length rather than needing extra cooldown-driven idle time."),
        dict(code="    formula = (max_freq - 1) * (n + 1) + max_count\n    return max(formula, len(tasks))",
             say="I compute the theoretical minimum length using the chunk-based formula, then return the larger of that and the total number of tasks.",
             why="Taking the max with len(tasks) correctly handles the case where there are so many different tasks that every cooldown gap gets filled naturally, meaning no idle time is ever needed and the answer is simply the total task count."),
    ],
    dry_run="tasks = ['A','A','A','B','B','B'], n=2. counts={'A':3,'B':3}. max_freq=3. max_count=2 (both A and B have frequency 3). formula = (3-1)*(2+1)+2 = 2*3+2 = 8. len(tasks)=6. max(8,6)=8. A valid schedule: A B idle A B idle A B, which is 8 slots — matches!",
    dry_run_say="With tasks A,A,A,B,B,B and n=2: both A and B tie for the max frequency of 3, so the formula gives (3-1)*(2+1)+2 = 8, and indeed a valid schedule like A-B-idle-A-B-idle-A-B takes exactly 8 time units.",
    edge_case="n=0, meaning no cooldown is needed at all. formula = (max_freq-1)*(0+1)+max_count = max_freq - 1 + max_count. Taking the max with len(tasks) will typically just resolve to len(tasks) directly, since with no cooldown restriction, tasks can just be run back-to-back in any order, needing exactly as many slots as there are tasks.",
    edge_case_say="Let me check n=0, meaning there's no cooldown restriction at all — the formula still computes correctly, but the max with len(tasks) naturally resolves to just the total number of tasks, since we can run everything back-to-back with no idle time needed.",
    other_edge_cases=[
        "Only one type of task with a large n (lots of forced idle time)",
        "Many different task types, each appearing only once (no idle time ever needed)",
        "All tasks identical (worst-case spacing scenario)",
        "n larger than the number of distinct other tasks available to fill gaps",
    ],
    final_complexity_rows=[["Optimized (formula)", "O(t)", "O(1)"]],
    final_complexity_say="This is O(t) time, where t is the number of tasks, just to count frequencies, and O(1) extra space (a fixed 26-letter alphabet at most for typical constraints), which is much faster than simulating minute by minute.",
    pushback=[
        ("Why does taking the max with len(tasks) work?", "Because the chunk-based formula assumes the worst case where idle time is genuinely necessary to satisfy cooldowns; but if there are enough distinct OTHER tasks to naturally fill every gap without ever needing to idle, the true minimum schedule length is simply the total number of tasks, which is what the max() correctly captures."),
        ("Can you solve this with a heap-based simulation instead?", "Yes, that's a fully valid alternative: repeatedly pick the most frequent available task each round (using a max-heap) and track a cooldown period per task type; it directly simulates the schedule and naturally handles all edge cases, at the cost of being a bit more code and slightly higher complexity than the closed-form formula."),
        ("Why does the most frequent task determine the chunk structure?", "Because that task needs the most total spacing overall; scheduling it as evenly as possible (its instances forming the 'skeleton' of the schedule, each followed by n cooldown slots) creates the minimum possible structure, and other tasks simply get slotted into those gaps."),
        ("Can you optimize this further?", "O(t) is already optimal since we must at least look at every task once to count frequencies."),
    ],
    mistakes=[
        "Forgetting to take the max with len(tasks), which would undercount when there's no idle time actually needed.",
        "Miscounting max_count (forgetting to count ALL tasks tied for the maximum frequency, not just one).",
        "Off-by-one in the formula (forgetting the '-1' on max_freq, since the last occurrence of the max-frequency task doesn't need a trailing cooldown).",
        "Trying to simulate this manually without recognizing the direct formula, leading to unnecessarily complex code.",
    ],
    recovery=[
        "If stuck: 'Let me think about which single task type is the hardest to schedule — probably whichever one appears most often, since it dictates the spacing needed throughout.'",
        "If the formula gives a wrong answer: double check I'm taking the max with len(tasks), and that max_count correctly counts ALL tied tasks, not just one.",
        "If the interviewer asks for a simulation instead: pivot to a heap-based approach that greedily always schedules the currently most frequent available task.",
        "If unsure why '-1' appears in the formula: reason it through with a tiny example, like a single task type with frequency 3 and n=2, which needs exactly 2 gaps (not 3) after its first, second, but not third occurrence.",
    ],
    pattern_recognition=dict(
        triggers="'cooldown between repeated tasks', 'minimum time to complete all tasks with spacing constraint'",
        pattern="Greedy + Math (chunk-based formula), or Heap-based simulation",
        first_thought="The most frequent task(s) determine the schedule's minimum structure; a formula based on max frequency and its count often beats simulating minute by minute.",
        trap="Forgetting to compare the formula's result against the plain total task count, missing the 'no idle time needed' case.",
    ),
    memory_hook="Task Scheduler → \"The busiest task sets the pace — formula beats simulating minute by minute.\"",
    recap_key_idea="Compute (max_freq - 1) * (n + 1) + max_count, then take the max with the total task count.",
    recap_data_structure="A frequency counter (hash map).",
    recap_algorithm="Greedy + closed-form counting formula.",
    recap_time="O(t)", recap_space="O(1)", recap_edge_case="Enough distinct tasks to eliminate all idle time (formula < total task count).",
    talk_track=[
        ("Interviewer", "Find the minimum time to schedule all these tasks, with a cooldown of n between repeats of the same task."),
        ("Me", "Got it — only the SAME task needs the cooldown, other tasks can fill those gaps freely, and I return the total time including any idle slots, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "One valid approach is simulating minute by minute with a max-heap, always picking the most frequent available task — that works, but there's actually a direct formula that avoids simulation."),
        ("Me", "I'll count each task's frequency, find the maximum frequency, and how many tasks tie for it. The schedule structure is dominated by the most frequent task, which needs (max_freq - 1) complete cycles of (n+1) slots each, plus a final chunk holding however many tasks tied for that max frequency."),
        ("Me", "But if there are enough other distinct tasks to fill every gap, no idle time is actually needed, so I take the max of that formula and just the total number of tasks."),
        ("Me", "Let me code that — counting frequencies, then applying the formula."),
        ("Me", "Tracing tasks A,A,A,B,B,B with n=2: both A and B tie for max frequency 3, giving a formula result of 8, matching a valid schedule like A-B-idle-A-B-idle-A-B."),
        ("Me", "Edge case: n=0 means no cooldown at all, and the max with the total task count correctly resolves to just running everything back-to-back."),
        ("Me", "Final complexity: O(t) time to count frequencies, O(1) extra space."),
    ],
))

PROBLEMS.append(dict(
    title="Car Pooling", lc_num="1094", difficulty="MEDIUM", pattern="Difference Array / Line Sweep (Greedy)",
    relevance="Common interview pattern",
    restate="We're given a list of trips, each with a number of passengers and a start/end location, and a car capacity, and we need to determine if it's possible to pick up and drop off all passengers for all trips without ever exceeding the car's capacity.",
    clarify_questions=[
        "Does a passenger getting dropped off at location x free up capacity immediately at that same location, before new passengers boarding at x are counted?",
        "Are start and end locations guaranteed to be non-negative, with start always less than end?",
        "Can multiple trips overlap at the same locations simultaneously?",
        "Is capacity a fixed constant for the whole scenario?",
    ],
    restate_say=["Just to confirm, at any given location, passengers dropping off free up capacity before new passengers at that same location board, and I need to check that total passengers never exceed capacity at any point along the route, correct?"],
    brute_idea="For every unit of distance along the route, sum up all passengers from trips that are currently 'active' (started but not yet ended) at that point, and check if it ever exceeds capacity.",
    brute_say=["A direct approach is to check, at every possible location along the route, how many passengers are currently in the car from all overlapping trips, and see if that ever exceeds capacity."],
    brute_time="If checking each location requires scanning all trips, and there are many possible locations, this could be O(trips * max_location), which can be quite slow.",
    brute_space="O(1) beyond tracking the trips themselves.",
    brute_complexity_say="This naive approach can be O(trips times max_location) if I check every location against every trip, which is inefficient, especially over a large range of locations.",
    bottleneck="I'm recomputing the total passenger count from scratch at every location, when passenger count only actually CHANGES at the specific start and end points of trips — I should only need to look at those change points, not every possible location in between.",
    bottleneck_say="The bottleneck is checking every single location individually, when the passenger count only changes at a handful of specific points (trip starts and ends), so I should focus only on those.",
    optimization_explain="I use a Difference Array (also called a Line Sweep) technique. I create an array representing the change in passenger count at each location: at a trip's start location, I ADD its passenger count (people getting on); at its end location, I SUBTRACT that same count (people getting off). Then I do a single pass across all locations in order, maintaining a running total (a prefix sum of these changes), and check at every point whether that running total ever exceeds capacity.",
    key_insight="Instead of tracking 'how many passengers are on the car at each location' directly, I only need to track WHERE passenger count changes (a trip's start and end), and a running sum across those change points reconstructs the exact passenger count at every location efficiently.",
    optimization_say=[
        "I'll create a difference array where each trip adds its passenger count at its start location and subtracts it at its end location.",
        "I'll then do a single pass across all locations, keeping a running sum of these changes.",
        "If that running sum ever exceeds capacity at any point, I know it's not possible to fulfill all the trips.",
    ],
    code_blocks=[
        dict(code="def car_pooling(trips, capacity):\n    changes = [0] * 1001\n    for passengers, start, end in trips:\n        changes[start] += passengers\n        changes[end] -= passengers",
             say="I set up a changes array large enough to cover the maximum possible location (the constraints typically cap locations at 1000). For every trip, I add its passenger count at the start location, and subtract it at the end location.",
             why="Subtracting at the END location (not end-1) correctly reflects that those passengers are no longer in the car starting exactly at that point, which matches the convention that drop-offs free capacity immediately at that same location."),
        dict(code="    current_passengers = 0\n    for change in changes:\n        current_passengers += change\n        if current_passengers > capacity:\n            return False\n\n    return True",
             say="I sweep across the changes array left to right, maintaining a running total of passengers, and checking after each step whether it exceeds capacity.",
             why="This running sum (essentially a prefix sum over the difference array) reconstructs the exact number of passengers in the car at every single location, letting me catch a capacity violation the moment it would occur."),
    ],
    dry_run="trips = [[2,1,5],[3,3,7]], capacity=4. changes array (showing relevant indices): changes[1]+=2 -> changes[1]=2. changes[5]-=2 -> changes[5]=-2. changes[3]+=3 -> changes[3]=3. changes[7]-=3 -> changes[7]=-3. Sweep: index0:0,current=0. index1: current=0+2=2, <=4 ok. index2: current=2 (no change), ok. index3: current=2+3=5, 5>4! Return False — correctly identifying that at location 3, both trips overlap (2+3=5 passengers), exceeding capacity 4.",
    dry_run_say="Tracing trips [[2,1,5],[3,3,7]] with capacity 4: at location 3, both trips are active simultaneously, putting 5 passengers in the car, which exceeds the capacity of 4, so we correctly return false.",
    edge_case="A drop-off and a pick-up happening at the exact same location, e.g. one trip ending at location 5 and another starting at location 5. Since the end location's subtraction and the start location's addition both apply exactly AT index 5, the running sum correctly reflects that the departing passengers' capacity is freed up before or simultaneously with the new passengers boarding, matching the standard convention for this problem.",
    edge_case_say="Let me check a case where one trip ends exactly where another begins — since both the subtraction (for the ending trip) and the addition (for the new trip) apply at that same location in the difference array, the running sum correctly reflects that departing passengers free up room right at that point.",
    other_edge_cases=[
        "A single trip that exactly fills the capacity (should be fine, not exceeding it)",
        "Trips that don't overlap at all (should always be fine regardless of capacity, as long as each individual trip fits)",
        "Many small trips that individually fit but collectively overlap and exceed capacity",
        "A trip with 0 passengers (a no-op, shouldn't affect anything)",
    ],
    final_complexity_rows=[["Optimized", "O(trips + max_location)", "O(max_location)"]],
    final_complexity_say="This is O(trips + max_location) time, since building the difference array is proportional to the number of trips, and sweeping across it is proportional to the location range, and O(max_location) space for the difference array itself.",
    pushback=[
        ("Why subtract exactly at the end location, not end - 1?", "Because the problem's convention is that a passenger occupies the car from their start location up to but not including their end location, so subtracting at the end index correctly removes them from the running count starting exactly there, matching real-world 'drop off, then possibly pick someone else up at the same stop' semantics."),
        ("What if location values could be very large or sparse?", "Instead of a fixed-size array, I could use a hash map or sort all the distinct start/end points and use a compressed range, doing coordinate compression to keep the sweep proportional to the number of DISTINCT points rather than the absolute value range."),
        ("Can you solve this without an array, using sorting instead?", "Yes, an alternative is to create a list of (location, change) events, sort them by location (with drop-offs processed before pick-ups at the same location), and do the same running-sum sweep over that sorted list, which is O(trips log trips) time instead of O(max_location) space."),
        ("Can you optimize this further?", "The array-based sweep is already quite efficient given the bounded location range; if that range were much larger, the sorting/event-based approach would be preferable to avoid excessive space usage."),
    ],
    mistakes=[
        "Subtracting at end - 1 instead of end, misrepresenting when passengers actually leave the car.",
        "Forgetting to check capacity DURING the sweep, only checking the final total (which would miss violations that resolve themselves later).",
        "Assuming trips are given in any particular order; the difference array technique doesn't require sorting since additions/subtractions are order-independent as long as they're applied at the correct absolute location.",
        "Using an array sized incorrectly, either too small (missing high locations) or unnecessarily large (wasting space).",
    ],
    recovery=[
        "If stuck: 'Checking every single location directly against all trips is repetitive. Passenger count only really changes at specific start/end points — let me track just those changes and sum across them.'",
        "If capacity checks come out wrong: verify whether I'm checking after each running sum update, not just at the very end.",
        "If the interviewer hints 'think about where the count actually changes': confirm and describe the difference array / line sweep approach.",
        "If the location range seems too large for a fixed array: pivot to a sorted-events approach with coordinate compression.",
    ],
    pattern_recognition=dict(
        triggers="'overlapping intervals with capacity limit', 'passengers picked up and dropped off along a route'",
        pattern="Difference Array / Line Sweep",
        first_thought="The total at any point only changes where an interval starts or ends — track just those change points instead of every possible position.",
        trap="Subtracting at the wrong index (end-1 instead of end), or only checking the final total instead of checking during the sweep.",
    ),
    memory_hook="Car Pooling → \"Add at pickup, subtract at drop-off, sweep and watch the running total.\"",
    recap_key_idea="Build a difference array marking +passengers at start and -passengers at end; sweep with a running sum, checking against capacity at every step.",
    recap_data_structure="A difference array indexed by location.",
    recap_algorithm="Difference Array / Line Sweep.",
    recap_time="O(trips + max_location)", recap_space="O(max_location)", recap_edge_case="A drop-off and pick-up occurring at the exact same location.",
    talk_track=[
        ("Interviewer", "Determine if this car can complete all the given trips without exceeding capacity."),
        ("Me", "Got it — drop-offs free up capacity right at that same location, before new pick-ups at that spot count, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "Checking every single location against every trip directly would be inefficient if the location range is large."),
        ("Me", "Instead, passenger count only actually changes at trip start and end points, so I'll use a difference array: add the passenger count at the start location, subtract it at the end location."),
        ("Me", "Then I sweep across all locations once, keeping a running sum, and check if it ever exceeds capacity."),
        ("Me", "Let me code that — building the difference array from the trips, then the sweep with the capacity check."),
        ("Me", "Tracing trips [[2,1,5],[3,3,7]] with capacity 4: at location 3, both trips overlap, putting 5 passengers in the car, which exceeds capacity, so the answer is false."),
        ("Me", "Edge case: a drop-off and pick-up at the exact same location — the difference array correctly applies both changes right at that index, reflecting that capacity frees up immediately."),
        ("Me", "Final complexity: O(trips plus max location) time and space for the sweep."),
    ],
))
