PROBLEMS = []

PROBLEMS.append(dict(
    title="Add Two Numbers", lc_num="2", difficulty="MEDIUM", pattern="Linked List Traversal",
    relevance="Common interview pattern",
    restate="We're given two linked lists representing non-negative integers, where each node holds a single digit stored in reverse order (least significant digit first), and we need to add the two numbers and return the sum as a linked list in the same format.",
    clarify_questions=[
        "Are the digits stored least-significant-digit first, so I add from the heads directly?",
        "Can the two lists be different lengths?",
        "Are the numbers guaranteed non-negative, with no leading zero issues (except the number 0 itself)?",
        "Should I create a new list, or can I reuse existing nodes?",
    ],
    restate_say=["Just to confirm, each list stores a number's digits in reverse order, so I can add corresponding digits directly from the front, carrying over as needed, and the lists might not be the same length, right?"],
    brute_idea="Convert both linked lists into actual integers, add them normally, then convert the sum back into a linked list of digits in reverse order.",
    brute_say=["A simple approach is to convert each linked list into an integer, add the two integers together, and then convert that sum back into a new linked list."],
    brute_time="Converting each list takes O(n) or O(m), the addition itself is effectively O(max(n,m)) for big-integer arithmetic, and converting back is O(max(n,m)+1), so overall O(n+m).",
    brute_space="O(n+m) for the intermediate integers and the result list.",
    brute_complexity_say="This is O(n+m) time and space, but it depends on the language supporting arbitrary-precision integers, and it feels like an indirect way to solve what's fundamentally a digit-by-digit addition problem.",
    bottleneck="Converting to and from integers works, but it sidesteps the actual structure of the problem and may not be robust for extremely large numbers in languages with fixed integer sizes; the real task is just simulating grade-school addition directly on the digits.",
    bottleneck_say="Converting to integers works in Python, but it doesn't really solve the intended problem, which is about simulating digit-by-digit addition directly, especially since the lists might have different lengths and I need to handle carries.",
    optimization_explain="I simulate elementary-school addition directly on the two linked lists at the same time. I walk both lists simultaneously, adding corresponding digits plus any carry from the previous step, creating a new node for the digit (sum modulo 10) and carrying forward the tens digit (sum divided by 10). I continue until both lists are exhausted and there's no carry left.",
    key_insight="Because digits are stored least-significant-first, I can add left to right node by node exactly like manual addition, propagating a single carry value forward one step at a time, without ever needing to know the full numeric value of either list.",
    optimization_say=[
        "I'll walk both lists at the same time, node by node.",
        "At each step, I sum the two current digits (treating a missing node as 0) plus any carry from before, then create a new node holding that sum modulo 10, and update the carry to sum divided by 10.",
        "I keep going as long as either list still has nodes, or there's a leftover carry.",
    ],
    code_blocks=[
        dict(code="class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val = val\n        self.next = next\n\ndef add_two_numbers(l1, l2):\n    dummy = ListNode()\n    current = dummy\n    carry = 0",
             say="I use a dummy head node to simplify building the result list, a 'current' pointer to track where I'm building, and a carry variable starting at 0.",
             why="A dummy head avoids special-casing 'the first node' when building a new linked list, since I can always just attach after dummy and return dummy.next at the end."),
        dict(code="    while l1 or l2 or carry:\n        val1 = l1.val if l1 else 0\n        val2 = l2.val if l2 else 0\n        total = val1 + val2 + carry",
             say="I loop as long as there's a node left in either list, or a carry still to apply. I treat a missing node's value as 0, so shorter lists are handled naturally, and sum both digits plus the carry.",
             why="Continuing while carry is truthy handles the important edge case where adding the final digits produces an extra new digit, like 5+5=10 needing one more node for that leading 1."),
        dict(code="        carry = total // 10\n        current.next = ListNode(total % 10)\n        current = current.next\n        l1 = l1.next if l1 else None\n        l2 = l2.next if l2 else None\n\n    return dummy.next",
             say="I compute the new carry and the digit to store (total mod 10), attach a new node with that digit, advance my current pointer, and move both list pointers forward if they still have nodes.",
             why="Advancing l1 and l2 only if they exist (using the conditional) prevents crashing on the shorter list once it runs out of nodes, while the longer list keeps contributing digits."),
    ],
    dry_run="l1 = 2->4->3 (represents 342), l2 = 5->6->4 (represents 465). Step1: val1=2,val2=5,carry=0,total=7. carry=0, new node 7. Step2: val1=4,val2=6,carry=0,total=10. carry=1, new node 0. Step3: val1=3,val2=4,carry=1,total=8. carry=0, new node 8. l1,l2 both now None, carry=0, loop ends. Result list: 7->0->8, representing 807, which is 342+465=807. Correct!",
    dry_run_say="Tracing l1=2->4->3 and l2=5->6->4 (representing 342 and 465): adding digit by digit with carries gives the result list 7->0->8, representing 807, which matches 342 plus 465.",
    edge_case="Lists of different lengths with a trailing carry, e.g. l1=9->9 (99) and l2=1 (1). Step1: val1=9,val2=1,carry=0,total=10, carry=1, node 0. Step2: val1=9,val2=0 (l2 exhausted),carry=1,total=10,carry=1,node 0. Now both lists exhausted but carry=1, loop continues: val1=0,val2=0,carry=1,total=1,carry=0,node 1. Result: 0->0->1, representing 100, which is 99+1=100. Correct, and shows why looping on 'carry' truthy (not just list existence) matters.",
    edge_case_say="Let me check a case with a leftover carry after both lists end, like 99 plus 1 \u2014 the loop correctly continues one more step because of the carry, producing 100, which shows why I check 'or carry' in the while condition, not just the lists themselves.",
    other_edge_cases=[
        "Both lists represent 0 (single node with value 0 each)",
        "One list is much longer than the other",
        "Sum requires an entirely new leading digit beyond both lists' lengths",
        "Both lists have only a single node each with no carry needed",
    ],
    final_complexity_rows=[["Optimized", "O(max(n, m))", "O(max(n, m))"]],
    final_complexity_say="This is O(max(n, m)) time since we walk through both lists at most once, where n and m are their lengths, and O(max(n, m)) space for the newly created result list (not counting the input lists themselves).",
    pushback=[
        ("Why not just convert to integers directly?", "In Python that works because integers are arbitrary precision, but in many other languages fixed-size integers could overflow for very long lists, and the problem is fundamentally about digit-level list manipulation, so the direct simulation approach is more broadly correct and demonstrates the intended technique."),
        ("What if the digits were stored most-significant-first instead?", "Then I couldn't add directly from the heads; I'd need to either reverse both lists first (or use a stack to process from the end), add with carries, and build the result list in reverse (or reverse it again at the end)."),
        ("Can you avoid creating a new list and modify one of the inputs instead?", "Yes, I could reuse l1's nodes by updating their values in place and extending with l2's or new nodes as needed, saving some allocation, though it does mutate the input, which I'd clarify is acceptable first."),
        ("How do you handle a carry after both lists are exhausted?", "The while loop condition explicitly includes 'or carry', so even after both list pointers become None, if there's still a leftover carry, one more node gets created for it, which handles cases like 99 + 1."),
    ],
    mistakes=[
        "Forgetting to continue the loop when both lists are exhausted but there's still a carry left over.",
        "Not using a dummy head node, leading to awkward special-casing for the first node.",
        "Forgetting to advance l1/l2 conditionally (crashing when trying to access .next on None).",
        "Mixing up total // 10 (carry) and total % 10 (digit to store).",
    ],
    recovery=[
        "If stuck: 'This is just elementary school addition, but with digits stored in a linked list instead of an array \u2014 let me simulate that directly, adding node by node with a carry.'",
        "If I forget the dummy-head trick: reason aloud, 'building a new list is easier if I have a placeholder starting node I can always attach to, then return dummy.next at the end.'",
        "If the interviewer hints 'what happens after both lists end': double check the loop condition includes the carry, not just the list pointers.",
        "If I get carry/digit reversed: recheck against a concrete example like 9+9=18, where digit=8 and carry=1, aligning that with mod 10 and integer division by 10.",
    ],
    pattern_recognition=dict(
        triggers="'linked list representing a number', 'digits in reverse order', 'add two numbers'",
        pattern="Linked List Traversal with Carry Propagation (simulated arithmetic)",
        first_thought="Simulate manual addition directly on the lists, one digit position at a time, carrying forward exactly like on paper.",
        trap="Forgetting the loop must continue if a carry remains even after both lists are exhausted.",
    ),
    memory_hook="Add Two Numbers \u2192 \"Add node by node, carry the tens digit forward, just like paper addition.\"",
    recap_key_idea="Walk both lists simultaneously, summing digits plus carry, building a new list of (sum mod 10) with carry = sum // 10.",
    recap_data_structure="A dummy head node for the result linked list.",
    recap_algorithm="Simultaneous linked list traversal with carry propagation.",
    recap_time="O(max(n,m))", recap_space="O(max(n,m))", recap_edge_case="Leftover carry after both lists are exhausted (e.g., 99+1).",
    talk_track=[
        ("Interviewer", "Add these two numbers represented as linked lists, digits in reverse order."),
        ("Me", "Got it \u2014 so I can add corresponding digits directly from the heads, carrying as needed, and the lists could be different lengths, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "One approach in Python would be converting each list to an actual integer, adding them, and converting back \u2014 that works here since Python integers don't overflow, but it doesn't demonstrate the intended digit-by-digit simulation, and wouldn't be safe in other languages."),
        ("Me", "I'll instead simulate the addition directly: walk both lists together, sum the current digits plus carry, create a node for the result digit, and carry forward the rest."),
        ("Me", "Let me code that with a dummy head node to simplify building the result list."),
        ("Me", "Tracing 342 (2->4->3) plus 465 (5->6->4): digit by digit with carries gives 7->0->8, representing 807, which checks out."),
        ("Me", "Edge case: what if there's a leftover carry after both lists end, like 99 plus 1? My loop condition includes the carry, so it correctly adds one more node, giving 100."),
        ("Me", "Final complexity: O(max(n,m)) time and space, since I walk both lists once and build a result list of similar length."),
    ],
))

PROBLEMS.append(dict(
    title="Linked List Cycle", lc_num="141", difficulty="EASY", pattern="Fast & Slow Pointers",
    relevance="Common interview pattern",
    restate="We're given the head of a linked list, and we need to determine whether the list contains a cycle, meaning some node's next pointer eventually points back to a previously visited node.",
    clarify_questions=[
        "Should I return a boolean, or do I need to return the node where the cycle begins?",
        "Can the list be empty, or have just one node?",
        "Is there a constraint against using extra memory, like a hash set of visited nodes?",
        "Can a single node point to itself, forming a one-node cycle?",
    ],
    restate_say=["Just to confirm, I need to return true or false for whether a cycle exists, and ideally I should do it in O(1) space rather than tracking visited nodes in a set, correct?"],
    brute_idea="Use a hash set to track every node visited; if I ever revisit a node already in the set, there's a cycle.",
    brute_say=["The straightforward way is to keep a hash set of every node I've visited, and if I ever see a node that's already in the set, that means there's a cycle."],
    brute_time="O(n), since in the worst case (no cycle) we visit every node once.",
    brute_space="O(n) for the hash set of visited nodes.",
    brute_complexity_say="This is O(n) time, but also O(n) space for storing every visited node, which is more memory than should be necessary.",
    bottleneck="I'm using a whole hash set just to detect 'have I been here before', when two pointers moving at different speeds can detect a cycle without remembering any nodes at all.",
    bottleneck_say="The bottleneck is that remembering every visited node isn't actually necessary \u2014 there's a way to detect a loop using just two pointers and no extra memory.",
    optimization_explain="I use Floyd's Fast & Slow Pointers (Tortoise and Hare). I set two pointers at the head: slow moves one step at a time, fast moves two steps at a time. If there's no cycle, fast will reach the end (None) first. If there IS a cycle, fast will eventually 'lap' slow and they'll point to the same node, confirming a cycle exists.",
    key_insight="If two runners go around a circular track at different speeds, the faster one always eventually catches up to and passes the slower one from behind \u2014 that's exactly what guarantees slow and fast will meet if and only if a cycle exists.",
    optimization_say=[
        "I'll use two pointers starting at the head: slow moves one node at a time, fast moves two nodes at a time.",
        "If fast ever reaches the end of the list (hits None), there's no cycle.",
        "If slow and fast ever point to the exact same node, that means fast has lapped slow inside a loop, confirming a cycle.",
    ],
    code_blocks=[
        dict(code="def has_cycle(head):\n    slow = head\n    fast = head",
             say="I start both slow and fast pointers at the head of the list.",
             why="Both must start from the same point for the lapping logic to correctly detect a cycle rather than falsely triggering."),
        dict(code="    while fast and fast.next:\n        slow = slow.next\n        fast = fast.next.next\n        if slow == fast:\n            return True\n\n    return False",
             say="As long as fast (and the node right after it) exists, I move slow one step and fast two steps, and check if they've become equal. If the loop ends because fast ran off the end, there's no cycle.",
             why="Checking 'fast and fast.next' before advancing prevents a crash from trying to access .next on None, which would happen if fast reached the true end of a non-cyclic list."),
    ],
    dry_run="List: 3 -> 2 -> 0 -> -4 -> (back to 2, forming a cycle). slow=3,fast=3. Step1: slow=2, fast=0. Not equal. Step2: slow=0, fast=2 (fast wrapped: 0->-4->2). Not equal. Step3: slow=-4, fast=-4 (fast: 2->0->-4). Equal! Return True \u2014 a cycle exists.",
    dry_run_say="Tracing a list where the tail loops back into the middle: after a few steps, the fast pointer laps around and meets the slow pointer at the same node, confirming there's a cycle.",
    edge_case="A list with no cycle at all, e.g. 1->2->3->None. slow and fast start at 1. Step1: slow=2,fast=3. Not equal. Step2: fast.next is None so the while condition fails (fast=3, fast.next=None is falsy... actually need one more check): the loop simply exits once fast or fast.next becomes None, and we return False, correctly identifying no cycle.",
    edge_case_say="Let me check a plain list with no cycle, like 1->2->3->None \u2014 the fast pointer eventually runs off the end, the loop condition catches that, and we correctly return False.",
    other_edge_cases=[
        "Empty list (head is None)",
        "Single node with no self-loop",
        "Single node pointing to itself (a one-node cycle)",
        "Cycle that starts at the very head of the list",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time because in the worst case fast catches up to slow within one full loop around the cycle (bounded by the list's length), and O(1) space since only two pointers are used, no extra data structure.",
    pushback=[
        ("Why does the fast pointer always catch the slow pointer if there's a cycle?", "Because once both pointers are inside the cycle, the gap between them shrinks by exactly one node every step (since fast gains one extra step on slow each iteration), so the gap must eventually reach zero, meaning they meet, as long as the cycle has finite length."),
        ("Can you find WHERE the cycle begins, not just whether one exists?", "Yes \u2014 once slow and fast meet, reset one pointer to the head, keep the other at the meeting point, then move both one step at a time; they'll meet again exactly at the cycle's starting node, using the same math as the 'Find the Duplicate Number' problem."),
        ("Can you solve this with recursion?", "Not efficiently or safely \u2014 recursion would need to detect repeated nodes some other way (like passing a visited set), which brings back the O(n) space cost we were trying to avoid."),
        ("What if the list is extremely long with no cycle?", "The algorithm still terminates cleanly in O(n) time once fast reaches the true end (None), since there's no cycle to loop around."),
    ],
    mistakes=[
        "Checking only 'while fast' without also checking 'fast.next', causing a crash when advancing fast two steps.",
        "Starting slow and fast at different nodes instead of both at head.",
        "Comparing node values instead of node identity/reference (should be 'slow == fast' as node objects, or more precisely 'slow is fast' in Python for clarity, though == on ListNode by default falls back to identity unless overridden).",
        "Assuming a hash-set approach is necessary when O(1) space is explicitly asked for.",
    ],
    recovery=[
        "If stuck: 'A hash set works but uses O(n) space. Let me think about whether two pointers moving at different speeds could detect a loop without remembering anything.'",
        "If I forget the loop guard: reason aloud, 'fast moves two steps, so I need both fast and fast.next to exist before advancing, otherwise I'd crash on a null pointer.'",
        "If the interviewer hints 'think about runners on a circular track': confirm that's exactly the tortoise-and-hare intuition being used.",
        "If asked to find the cycle start and I forget the exact reset trick: reason through it as 'the distance from head to cycle start equals the distance from the meeting point to cycle start,' which is the underlying math.",
    ],
    pattern_recognition=dict(
        triggers="'linked list cycle', 'does the list loop back on itself', O(1) space",
        pattern="Fast & Slow Pointers (Floyd's Cycle Detection)",
        first_thought="Can two pointers moving at different speeds detect a loop without remembering visited nodes?",
        trap="Forgetting to guard fast.next before advancing fast two steps at a time.",
    ),
    memory_hook="Linked List Cycle \u2192 \"Two runners on a track \u2014 if there's a loop, the fast one always laps the slow one.\"",
    recap_key_idea="Move slow one step and fast two steps; if they ever meet, there's a cycle; if fast hits None, there isn't.",
    recap_data_structure="Two pointer variables \u2014 no extra structure.",
    recap_algorithm="Floyd's Tortoise and Hare.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Single node pointing to itself (smallest possible cycle).",
    talk_track=[
        ("Interviewer", "Determine if this linked list has a cycle."),
        ("Me", "Got it \u2014 just a true/false answer, and ideally in O(1) space rather than tracking visited nodes, right?"),
        ("Interviewer", "Yes."),
        ("Me", "A hash set of visited nodes would solve it in O(n) time and space, but since O(1) space is preferred, I'd use two pointers instead."),
        ("Me", "Slow moves one step at a time, fast moves two. If there's a cycle, fast eventually laps slow and they meet at the same node; if there's no cycle, fast reaches the end first."),
        ("Me", "Let me code that, being careful to check both fast and fast.next exist before advancing fast."),
        ("Me", "Tracing a list that loops back into itself: after a few steps, slow and fast do meet at the same node, confirming a cycle."),
        ("Me", "Edge case: a plain list with no cycle just has fast run off the end, and we correctly return false."),
        ("Me", "Final complexity: O(n) time, since the pointers converge within one loop around the cycle at most, and O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Intersection of Two Linked Lists", lc_num="160", difficulty="EASY", pattern="Two Pointers",
    relevance="Common interview pattern",
    restate="We're given the heads of two singly linked lists, and we need to find the node at which the two lists intersect (share the same tail), or return None if they don't intersect.",
    clarify_questions=[
        "Does 'intersect' mean the same node object, not just the same value?",
        "Can the two lists have different lengths before merging?",
        "Should I avoid modifying either list?",
        "Is there a memory constraint that would rule out a hash set of nodes?",
    ],
    restate_say=["Just to confirm, intersection means they share the exact same node onward (by reference, not just equal values), and the two lists can have different lengths leading up to that point, correct?"],
    brute_idea="For every node in list A, scan through all of list B checking for a matching node (by reference).",
    brute_say=["The brute-force way is, for every node in list A, scan through all of list B to see if any node matches it by reference."],
    brute_time="O(n * m) since for each of the n nodes in A, we scan up to m nodes in B.",
    brute_space="O(1) extra space.",
    brute_complexity_say="This is O(n times m) time because of the nested scan, and O(1) space since nothing extra is stored.",
    bottleneck="I'm redundantly rescanning list B for every single node in list A, when there's a smarter way to align both lists so I only need one synchronized pass.",
    bottleneck_say="The bottleneck is that I'm not aligning the two lists first; if I could make sure both pointers have the same distance left to the end, I could compare node by node in a single pass.",
    optimization_explain="I use Two Pointers with a clever trick: start one pointer at head A and another at head B. Each pointer walks its own list, and when it reaches the end, it jumps to the head of the OTHER list. Because both pointers collectively travel the same total distance (lengthA + lengthB) before potentially meeting, they either meet exactly at the intersection node, or both become None at the same time if there's no intersection.",
    key_insight="Switching each pointer to the other list once it runs out effectively equalizes the total distance each pointer travels, canceling out the length difference between the two lists without ever needing to explicitly compute or compare lengths.",
    optimization_say=[
        "I'll use two pointers, one starting at each list's head.",
        "Each one walks forward normally, and when it hits the end of its list, it switches to the head of the other list.",
        "Because this equalizes total distance traveled, the two pointers are guaranteed to meet exactly at the intersection node, or both reach None together if there's no intersection.",
    ],
    code_blocks=[
        dict(code="def get_intersection_node(head_a, head_b):\n    pointer_a = head_a\n    pointer_b = head_b",
             say="I start one pointer at the head of each list.",
             why="These will each traverse their own list first, then switch, which is the mechanism that equalizes total distance traveled."),
        dict(code="    while pointer_a != pointer_b:\n        pointer_a = pointer_a.next if pointer_a else head_b\n        pointer_b = pointer_b.next if pointer_b else head_a\n\n    return pointer_a",
             say="I keep moving both pointers forward. Whenever one runs out (becomes None), I redirect it to the other list's head instead. I stop once they're equal, whether that's at the real intersection node or both being None.",
             why="If there's an intersection, both pointers will have traveled lengthA + lengthB total steps by the time they reach it, guaranteeing they arrive there simultaneously; if there's no intersection, both simply become None at the same step, and the loop correctly exits with 'pointer_a == pointer_b == None'."),
    ],
    dry_run="A: 4->1->8->4->5, B: 5->6->1->8->4->5, intersecting at node with value 8 (shared tail: 8->4->5). pointer_a starts at 4(A), pointer_b at 5(B). They walk their own lists; pointer_a reaches None after 5 steps and switches to head_b; pointer_b reaches None after 6 steps and switches to head_a. Since pointer_a's path length (5 + up to intersection in B) equals pointer_b's path length (6 + up to intersection in A) by construction, they land on the shared node with value 8 at the same step. Return that node.",
    dry_run_say="With list A having length 5 and list B having length 6, both sharing a tail starting at the node with value 8: after each pointer finishes its own list and switches to the other, they arrive at the node with value 8 at exactly the same step, correctly identifying the intersection.",
    edge_case="No intersection at all, e.g. two completely separate lists. Both pointers will traverse lengthA + lengthB steps total, switching once each, and both become None simultaneously right after their second pass finishes, satisfying 'pointer_a != pointer_b' becoming false (None == None), correctly returning None.",
    edge_case_say="Let me check two lists that never intersect at all \u2014 both pointers switch once, and eventually both become None on the same step, so the loop correctly exits and returns None.",
    other_edge_cases=[
        "One list is empty (None) from the start",
        "The intersection point is the very first node of both lists (identical lists)",
        "The intersection point is the very last node (only the tail node is shared)",
        "Lists of equal length before intersecting",
    ],
    final_complexity_rows=[["Optimized", "O(n + m)", "O(1)"]],
    final_complexity_say="This is O(n + m) time since each pointer traverses at most the combined length of both lists once, and O(1) space since only two pointer variables are used, with no extra data structure.",
    pushback=[
        ("Why does switching pointers guarantee they meet at the intersection?", "Because by the time both pointers have switched once, each has traveled a total distance of lengthA + lengthB, meaning they're now the same distance from the end of the combined path, so from the intersection point onward they're perfectly synchronized."),
        ("Can you solve this with a hash set instead?", "Yes \u2014 walk list A, storing every node in a hash set, then walk list B checking if any node is already in that set; that's O(n+m) time but O(n) space, so the two-pointer approach is preferred when O(1) space matters."),
        ("What if the lists have cycles?", "This problem assumes acyclic (non-circular) singly linked lists; if cycles were possible, this approach could loop indefinitely, and I'd need cycle-detection logic layered on top first."),
        ("Can you compute the lengths first and align that way instead?", "Yes, that's an equivalent alternative: compute both lengths, advance the pointer on the longer list by the difference, then walk both pointers together until they match; it's also O(n+m) time and O(1) space, just a bit more code than the switching trick."),
    ],
    mistakes=[
        "Comparing node values instead of node references/identity, which could give false positives if values coincidentally match.",
        "Forgetting to redirect a pointer to the OTHER list's head (not its own head) when it runs out.",
        "Assuming both lists must be the same length before intersecting.",
        "Not handling the case where one or both lists are empty from the start.",
    ],
    recovery=[
        "If stuck: 'A hash set of visited nodes from one list would let me check the other list in O(n+m) time and O(n) space. Since I'd prefer O(1) space, let me think about how to align the two lists without extra memory.'",
        "If I redirect a pointer to the wrong head: verify with a dry run comparing total distances traveled by each pointer, which reveals the mistake immediately.",
        "If the interviewer hints 'think about equalizing the paths': confirm and describe the switch-to-the-other-list trick.",
        "If unsure this terminates for non-intersecting lists: reason through it \u2014 both pointers become None at the same step after their second pass, so the loop does terminate.",
    ],
    pattern_recognition=dict(
        triggers="'find the intersection of two linked lists', 'shared tail node'",
        pattern="Two Pointers with a length-equalizing switch trick",
        first_thought="Can I align both pointers so they've traveled equal total distances by the time they might meet?",
        trap="Comparing values instead of node identity, or redirecting a pointer to its own head instead of the other list's head.",
    ),
    memory_hook="Intersection of Linked Lists \u2192 \"When you hit your own end, switch to the other list \u2014 you'll meet at the join.\"",
    recap_key_idea="Two pointers switch to the other list's head when they run out, equalizing total distance traveled so they meet exactly at the intersection (or both hit None together).",
    recap_data_structure="Two pointer variables \u2014 no extra structure.",
    recap_algorithm="Two Pointers with a list-switching trick.",
    recap_time="O(n + m)", recap_space="O(1)", recap_edge_case="Lists that never intersect at all.",
    talk_track=[
        ("Interviewer", "Find the node where these two linked lists intersect, or return null."),
        ("Me", "Got it \u2014 intersection means the exact same node onward, not just equal values, and the lists could have different lengths before that point, right?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force: for every node in A, scan all of B for a match \u2014 O(n times m) time."),
        ("Interviewer", "How would you speed that up?"),
        ("Me", "I'd use two pointers, one starting at each head. Each walks its own list, and when it reaches the end, it switches to the other list's head instead of stopping. That equalizes the total distance both pointers travel, so they're guaranteed to meet exactly at the intersection, or both hit null at the same time if there isn't one."),
        ("Me", "Let me code that \u2014 the loop just keeps advancing both pointers, redirecting on null, until they're equal."),
        ("Me", "Tracing lists of length 5 and 6 sharing a tail starting at a node with value 8: after each pointer switches once, they land on that shared node at the same step."),
        ("Me", "Edge case: two lists that never intersect \u2014 both pointers become null at the same step after switching once each, correctly returning null."),
        ("Me", "Final complexity: O(n+m) time since each pointer travels at most the combined length once, O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Copy List with Random Pointer", lc_num="138", difficulty="MEDIUM", pattern="Hash Map (Linked List Cloning)",
    relevance="Advanced pattern",
    restate="We're given a linked list where each node has a 'next' pointer and also a 'random' pointer that can point to any node in the list (or None), and we need to create a deep copy of the entire list, including correctly wired random pointers.",
    clarify_questions=[
        "Can the random pointer point to any node in the list, including itself, or to None?",
        "Should the copy be entirely independent of the original (a true deep copy)?",
        "Is there a preferred space complexity, like O(1) extra beyond the output?",
        "Can the list be empty?",
    ],
    restate_say=["Just to confirm, each node has a next pointer and a random pointer that can point anywhere in the list or be null, and I need a fully independent deep copy with all pointers correctly re-wired, correct?"],
    brute_idea="First pass: create a copy of each node (values only, no pointers set). Second pass: use a hash map from original node to copied node to correctly wire up both next and random pointers on the copies.",
    brute_say=["A clean approach is a two-pass method: first create all the copied nodes and remember the mapping from original to copy in a hash map, then do a second pass to wire up next and random pointers using that map."],
    brute_time="O(n) for each of the two passes, so O(n) overall.",
    brute_space="O(n) for the hash map storing original-to-copy mappings.",
    brute_complexity_say="This is O(n) time for the two passes, and O(n) space for the hash map that lets me look up the copy corresponding to any original node.",
    bottleneck="This hash map approach is already quite good, but the interviewer may ask for an O(1) extra space solution, which requires a cleverer way to look up 'the copy of this node' without a separate map.",
    bottleneck_say="The main hash map solution is solid at O(n) time and space; the follow-up challenge is finding a way to avoid the extra O(n) space for the map, if the interviewer wants that.",
    optimization_explain="The Hash Map method: create a copy for every original node first, storing pairs in a map keyed by the original node. Then do a second pass over the original list, and for each original node, set copy.next = map[original.next] and copy.random = map[original.random] (handling None correctly). For the O(1)-space follow-up, an alternative technique interleaves each copied node directly after its original in the same list (original1 -> copy1 -> original2 -> copy2 -> ...), which lets you set random pointers using original.random.next (the copy right after the original's random target), then finally splits the interleaved list back into two separate lists.",
    key_insight="The hash map gives O(1) average lookup from any original node to its corresponding copy, which is exactly what's needed to correctly wire up random pointers that can point anywhere in the list, since without such a lookup you'd have no efficient way to find 'the copy of that specific node'.",
    optimization_say=[
        "First pass: walk the original list and create a copy of each node's value only, storing a mapping from original node to its copy in a hash map.",
        "Second pass: walk the original list again, and for each original node, use the map to set the copy's next and random pointers to the copies of the corresponding original targets.",
        "This correctly handles random pointers pointing anywhere in the list, including forward, backward, to itself, or to None.",
    ],
    code_blocks=[
        dict(code="class Node:\n    def __init__(self, val, next=None, random=None):\n        self.val = val\n        self.next = next\n        self.random = random\n\ndef copy_random_list(head):\n    if not head:\n        return None\n    old_to_new = {}",
             say="I handle the empty list case immediately, then set up a hash map to track the mapping from each original node to its new copy.",
             why="Handling None up front avoids unnecessary special-casing later, and the map is the core structure that lets me resolve random pointers correctly regardless of where they point."),
        dict(code="    current = head\n    while current:\n        old_to_new[current] = Node(current.val)\n        current = current.next",
             say="In the first pass, I walk the original list and create a brand-new node for each original node, storing just its value for now, and record the mapping in the hash map.",
             why="I deliberately don't wire up next or random pointers yet, since at this point I might not have created the copy of a node that a random pointer needs to point to."),
        dict(code="    current = head\n    while current:\n        copy = old_to_new[current]\n        copy.next = old_to_new.get(current.next)\n        copy.random = old_to_new.get(current.random)\n        current = current.next\n\n    return old_to_new[head]",
             say="In the second pass, I walk the original list again, and for each original node, I look up its copy and set the copy's next and random pointers using the map, translating from original nodes to their corresponding copies. Using .get() naturally returns None when there's no mapping, i.e. when the original pointer was None.",
             why="By this point every original node already has a corresponding copy in the map, so translating any pointer (next or random) via the map is guaranteed to succeed and correctly handles None targets too."),
    ],
    dry_run="List: A(random->C) -> B(random->A) -> C(random->C). First pass creates copies A', B', C' and map = {A:A', B:B', C:C'}. Second pass: A'.next = map[B] = B'; A'.random = map[C] = C'. B'.next = map[C] = C'; B'.random = map[A] = A'. C'.next = map[None] = None; C'.random = map[C] = C'. Result: fully independent copy A'->B'->C' with A'.random=C', B'.random=A', C'.random=C', exactly mirroring the original structure but with all-new nodes.",
    dry_run_say="Tracing a 3-node list with various random pointers: after the first pass creates all the copies, the second pass correctly rewires every next and random pointer using the map, producing a fully independent structural clone.",
    edge_case="A node whose random pointer points to itself, e.g. node C with C.random = C. In the map, map[C] = C', and when wiring C's copy, copy.random = map[C] = C', so the copy's random pointer also points to itself \u2014 correctly preserved.",
    edge_case_say="Let me check a node whose random pointer points to itself \u2014 the map correctly resolves that to the node's own copy, so the cloned node's random pointer also points to itself, preserving that structure.",
    other_edge_cases=[
        "Empty list (head is None)",
        "Single node with random pointing to itself or to None",
        "Every node's random pointer set to None",
        "Random pointers all pointing to the very first node",
    ],
    final_complexity_rows=[["Hash map approach", "O(n)", "O(n)"], ["Interleaving approach", "O(n)", "O(1) extra"]],
    final_complexity_say="The hash map solution is O(n) time for the two passes and O(n) space for the map; the interleaving follow-up technique achieves the same O(n) time but only O(1) extra space, at the cost of more intricate pointer manipulation.",
    pushback=[
        ("Can you do this in O(1) extra space?", "Yes, using the interleaving technique: insert each copy directly after its original node in the same list, so original.next is always the copy; then set each copy's random as original.random.next (the copy right after wherever the original's random points), and finally unweave the interleaved list back into two separate lists."),
        ("Why do you need two passes with the hash map approach?", "Because a node's random pointer might point to a node that hasn't been copied yet if I tried to wire everything in a single pass, so I first create all copies (pass one), and only then safely wire up pointers using the completed map (pass two)."),
        ("What if two different original nodes had the same value?", "That's fine \u2014 the hash map keys are the actual node objects (references), not values, so distinguishing between nodes with identical values is never an issue."),
        ("Can you avoid a hash map with a different data structure?", "The interleaving approach effectively replaces the hash map with the list structure itself (copy is always 'next' of original), which is the main alternative; otherwise, some structure that maps original-to-copy is fundamentally necessary for resolving arbitrary random pointers."),
    ],
    mistakes=[
        "Trying to wire up random pointers during the very first pass, before all nodes have been copied, causing missing map entries.",
        "Using .get() incorrectly or forgetting it (using indexing directly) which would raise an error when a pointer is None.",
        "Forgetting that map keys should be the original node objects, not values (since values might not be unique).",
        "For the O(1)-space version, forgetting to fully unweave the interleaved list at the end, leaving the original list corrupted.",
    ],
    recovery=[
        "If stuck: 'Random pointers can point anywhere, including nodes I haven't processed yet, so I need some way to look up 'the copy of any given original node' \u2014 a hash map does exactly that.'",
        "If I try to do it in one pass and get stuck: recognize the issue out loud \u2014 'I don't yet have the copy of a node my random pointer needs, so I should split this into two passes: create all copies first, then wire pointers.'",
        "If the interviewer asks for O(1) space and I don't remember the interleaving trick: describe the goal (avoid a separate map) and reason toward interleaving originals and copies as a way to 'store' the mapping implicitly in the list structure itself.",
        "If confused about get() vs indexing: remember dict.get(key) returns None by default for a missing key, which is exactly the behavior needed when an original pointer is None.",
    ],
    pattern_recognition=dict(
        triggers="'deep copy a linked list', 'random pointer', 'clone a graph/list with arbitrary pointers'",
        pattern="Hash Map for original-to-copy lookup (interleaving as an O(1)-space alternative)",
        first_thought="Arbitrary pointers mean I need a fast way to translate 'this original node' into 'its corresponding copy' \u2014 a hash map, or an implicit structural trick.",
        trap="Trying to wire pointers in the same pass as creating copies, before every node has been cloned.",
    ),
    memory_hook="Copy List with Random Pointer \u2192 \"Map every original to its copy first, then rewire using the map.\"",
    recap_key_idea="Two passes: first create all copies and record original-to-copy mappings, then rewire next/random pointers using that mapping.",
    recap_data_structure="Hash map from original node to copied node.",
    recap_algorithm="Two-pass clone-then-wire (or interleaving for O(1) space).",
    recap_time="O(n)", recap_space="O(n) [O(1) extra with interleaving]", recap_edge_case="A node whose random pointer points to itself.",
    talk_track=[
        ("Interviewer", "Deep copy this linked list, where each node also has a random pointer that can point anywhere in the list."),
        ("Me", "Got it \u2014 the copy needs to be a fully independent structure with correctly wired next and random pointers, and random can point to any node or null, right?"),
        ("Interviewer", "Yes."),
        ("Me", "I'll do this in two passes. First, I walk the list and create a copy of every node's value, storing a mapping from each original node to its copy in a hash map."),
        ("Me", "Then, in a second pass, I walk the original list again and use the map to wire up each copy's next and random pointers, translating original references into copy references."),
        ("Me", "Let me code that... using dict.get() so a null pointer in the original correctly maps to null in the copy."),
        ("Me", "Tracing a small 3-node example with various random pointers, the second pass correctly reproduces the exact same structure, but entirely with new nodes."),
        ("Me", "Edge case: a node whose random pointer points to itself \u2014 the map correctly resolves that to the node's own copy."),
        ("Me", "Final complexity: O(n) time for the two passes, O(n) space for the map."),
        ("Interviewer", "Can you do it in O(1) extra space?"),
        ("Me", "Yes \u2014 by interleaving each copy directly after its original in the same list, I can use original.random.next to find the copy of the random target without a separate map, then unweave the two lists at the end."),
    ],
))
