PROBLEMS = []

PROBLEMS.append(dict(
    title="Find K Closest Elements", lc_num="658", difficulty="MEDIUM", pattern="Binary Search",
    relevance="Common interview pattern",
    restate="We're given a sorted array, a target value x, and an integer k, and we need to return the k closest values to x from the array, sorted in ascending order.",
    clarify_questions=[
        "If there's a tie in distance between two candidates, which one wins \u2014 the smaller value?",
        "Is the array guaranteed to be sorted ascending?",
        "Can k equal the length of the array?",
        "Should the output remain sorted ascending?",
    ],
    restate_say=["Just to confirm, the array is sorted, and I need the k values closest to x, with ties broken in favor of the smaller value, returned in ascending order, correct?"],
    brute_idea="Compute the distance from every element to x, sort all elements by that distance (breaking ties by value), and take the first k, then re-sort those k by value.",
    brute_say=["The brute-force way is to compute each element's distance from x, sort everything by that distance, take the top k, and then sort those k back into ascending order."],
    brute_time="Sorting by distance is O(n log n), and the final sort of the k results is O(k log k), so overall O(n log n).",
    brute_space="O(n) to store distances alongside values.",
    brute_complexity_say="This is O(n log n) time because of the sort by distance, and O(n) space to hold that extra information.",
    bottleneck="I'm sorting the entire array by distance, but since the input is already sorted by value, the k closest elements must form a single contiguous window \u2014 I don't need to reorder anything if I can just find where that window starts.",
    bottleneck_say="The bottleneck is throwing away the fact that the array is already sorted; the answer is always some contiguous window of size k, so I just need to locate its starting position.",
    optimization_explain="I use Binary Search on the answer's starting index. I search for the left boundary of a window of size k within the range [0, n-k]. For a candidate left boundary 'mid', I compare x - nums[mid] (distance to the window's left edge) against nums[mid + k] - x (distance to the element just past the window's right edge). If the right-edge candidate is closer or equal, the window should shift right (mid+1 is a better start); otherwise, the current window (or something to its left) is at least as good, so I move the search left.",
    key_insight="Because the array is sorted, the k closest elements are always contiguous, so instead of searching over 'which elements', I can binary search over 'where does the window start', comparing just the two elements at the window's boundaries to decide which direction to shift.",
    optimization_say=[
        "Since the answer is always a contiguous window in a sorted array, I'll binary search directly for the window's starting index instead of comparing every element.",
        "For a candidate window starting at mid, I compare how close the element just before the window is to x, versus the element just after the window.",
        "Whichever comparison tells me the window should shift, I adjust my search bounds accordingly, narrowing down to the correct start in log(n) steps.",
    ],
    code_blocks=[
        dict(code="def find_closest_elements(arr, k, x):\n    left = 0\n    right = len(arr) - k",
             say="I set up a search range for the window's starting index: it can start anywhere from 0 up to len(arr) - k, since the window must fully fit inside the array.",
             why="Any starting index beyond len(arr) - k would make the window run off the end of the array, so those are never valid candidates."),
        dict(code="    while left < right:\n        mid = (left + right) // 2\n        if x - arr[mid] > arr[mid + k] - x:\n            left = mid + 1\n        else:\n            right = mid",
             say="I compare the distance from x to the window's left-edge element against the distance from x to the element just past the window's right edge. If the right side is strictly closer, the window should start further right, so I move left up; otherwise, I keep the search on the current side by setting right to mid.",
             why="This comparison directly encodes 'is shifting the window right an improvement', and using right = mid (not mid - 1) with left < right ensures the search converges correctly to the unique best starting index."),
        dict(code="    return arr[left:left + k]",
             say="Once left and right converge, left is the correct starting index of the window, so I return that slice of size k.",
             why="Because binary search narrows the range to a single point, left at the end of the loop is guaranteed to be the optimal window start."),
    ],
    dry_run="arr = [1,2,3,4,5], k=4, x=3. left=0, right=5-4=1. mid=0: compare x-arr[0]=3-1=2 vs arr[4]-x=5-3=2. Not strictly greater (2>2 is false), so right=mid=0. Now left=0,right=0, loop ends. Return arr[0:4] = [1,2,3,4].",
    dry_run_say="With arr=[1,2,3,4,5], k=4, x=3: there's only one possible starting index to check (0 or 1), and the comparison shows starting at 0 is at least as good, giving [1,2,3,4] as the closest 4 elements to 3.",
    edge_case="k equals the array length. Then left=0 and right=len(arr)-k=0, so the loop never executes, and the entire array is returned directly \u2014 correct, since there's only one possible window.",
    edge_case_say="Let me check when k equals the whole array's length \u2014 the search range collapses to a single point immediately, and I correctly just return the entire array.",
    other_edge_cases=[
        "x is smaller than every element in the array",
        "x is larger than every element in the array",
        "x exactly matches an element in the array",
        "k = 1 (just the single closest element)",
    ],
    final_complexity_rows=[["Optimized", "O(log(n-k) + k)", "O(k) for output"]],
    final_complexity_say="This is O(log(n-k)) time for the binary search over possible window starts, plus O(k) to build the output slice, and O(k) space for the returned result, which is essentially optimal since we must produce k elements.",
    pushback=[
        ("Why compare x - arr[mid] vs arr[mid+k] - x instead of absolute value comparisons directly on elements?", "Because those two specific elements are exactly the ones that would change if the window shifted by one position \u2014 comparing them tells us definitively whether shifting right improves the window, which is the core decision binary search needs at each step."),
        ("Can you solve this with two pointers rather than binary search?", "Yes, that's also a valid O(n) approach: start with the full array as the window and shrink from whichever end is farther from x until only k elements remain; it's simpler to reason about but doesn't get the logarithmic speed-up."),
        ("What if there's a tie in distance at the window boundary?", "The comparison uses strict greater-than, so a tie favors keeping the window where it is (shifting left, i.e., preferring the smaller value), which matches the typical tie-breaking rule of preferring smaller values."),
        ("Can you optimize further?", "We must output k elements, so O(k) is unavoidable for the output itself; the O(log(n-k)) search for the window start is already about as fast as this kind of search can get on a sorted array."),
    ],
    mistakes=[
        "Using right = mid - 1 instead of right = mid, which can skip over the correct boundary in this style of binary search.",
        "Comparing absolute values with abs() instead of directly comparing the two boundary differences, which can subtly mishandle tie-breaking.",
        "Forgetting the search range should be [0, len(arr)-k], not [0, len(arr)-1].",
        "Assuming a two-pointer shrinking approach is 'wrong' just because binary search is faster \u2014 both are valid, just different complexities.",
    ],
    recovery=[
        "If stuck: 'Since the array's sorted, the k closest values must be contiguous, so instead of thinking about individual elements, let me binary search for where that window starts.'",
        "If I'm unsure about the comparison direction: reason concretely with a small example, checking which side is closer to x and confirming the window should shift toward it.",
        "If the interviewer hints 'the answer is always a contiguous range': confirm and pivot straight to searching for the window's start index.",
        "If my binary search doesn't converge correctly: double check I'm using left < right (not <=) and right = mid (not mid-1), since that combination is what guarantees convergence here.",
    ],
    pattern_recognition=dict(
        triggers="'k closest elements', 'sorted array', 'nearest values to x'",
        pattern="Binary Search on the answer's position (not on a single value)",
        first_thought="In a sorted array, is the answer always a contiguous window? If so, binary search for the window's start instead of comparing every element.",
        trap="Comparing the wrong pair of boundary elements, or using off-by-one bounds in the search range.",
    ),
    memory_hook="K Closest Elements \u2192 \"Sorted array means the answer is one window \u2014 binary search for where it starts.\"",
    recap_key_idea="The k closest elements form a contiguous window; binary search for its optimal starting index by comparing boundary distances.",
    recap_data_structure="No extra structure \u2014 just index arithmetic on the sorted array.",
    recap_algorithm="Binary Search over window-start positions.",
    recap_time="O(log(n-k) + k)", recap_space="O(k)", recap_edge_case="k equal to the entire array length.",
    talk_track=[
        ("Interviewer", "Find the k values in this sorted array closest to x."),
        ("Me", "Got it \u2014 ties broken toward the smaller value, and the output should stay in ascending order, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force: compute distances for every element, sort by distance, take the top k, then re-sort by value \u2014 O(n log n)."),
        ("Interviewer", "Can you use the fact that the array is sorted?"),
        ("Me", "Yes \u2014 since it's sorted, the k closest elements always form one contiguous window. So instead of comparing individual elements, I can binary search for where that window should start."),
        ("Me", "At each candidate start, I compare the distance from x to the element just before the window versus just after it, and shift the window toward whichever side is closer."),
        ("Me", "Let me code that... searching over indices 0 to len(arr)-k."),
        ("Me", "Tracing arr=[1,2,3,4,5], k=4, x=3: the search quickly settles on starting at index 0, giving [1,2,3,4]."),
        ("Me", "Edge case: if k equals the whole array's length, the search range is a single point, so I just return everything."),
        ("Me", "Final complexity: O(log(n-k)) for the search plus O(k) to build the output, O(k) space."),
    ],
))

PROBLEMS.append(dict(
    title="Split Array Largest Sum", lc_num="410", difficulty="HARD", pattern="Binary Search on the Answer",
    relevance="Advanced pattern",
    restate="We're given an array of integers and an integer m, and we need to split the array into m contiguous non-empty subarrays such that the largest sum among those subarrays is as small as possible, and return that minimized largest sum.",
    clarify_questions=[
        "Must the subarrays be contiguous, in their original order?",
        "Are all numbers guaranteed to be non-negative?",
        "Is m always at least 1 and at most the length of the array?",
        "Do we need to return the actual split, or just the minimized value?",
    ],
    restate_say=["Just to confirm, I'm splitting the array into m contiguous pieces, and I want to minimize the largest sum among those pieces, returning just that minimized value, correct?"],
    brute_idea="Try every possible way to place m-1 dividers among the array to create m subarrays, compute the max subarray sum for each split, and take the split with the smallest such maximum.",
    brute_say=["A brute-force approach would try every possible placement of the m-1 split points and evaluate the resulting maximum subarray sum for each configuration."],
    brute_time="The number of ways to place dividers grows combinatorially, roughly C(n-1, m-1), which is exponential in the worst case.",
    brute_space="O(m) to track a given split configuration.",
    brute_complexity_say="This is exponential time in the worst case since we're essentially trying every combination of split points, which is completely impractical for larger arrays.",
    bottleneck="I'm exploring every possible way to split the array directly, when really I should be asking a simpler yes/no question: 'can we split the array into m or fewer pieces such that no piece exceeds some target sum?' \u2014 and that question is much easier to answer and to binary search over.",
    bottleneck_say="The bottleneck is searching over split configurations directly; instead I should search over candidate answer values and check feasibility, which is a much smaller and easier space to search.",
    optimization_explain="I use Binary Search on the Answer. The answer (minimized largest sum) must lie between max(nums) (can't split any smaller than the single largest element) and sum(nums) (the case of one single subarray, m=1). For any candidate 'mid' value, I greedily check: can I split the array into at most m subarrays where each subarray's sum is \u2264 mid? I do this by accumulating a running sum and starting a new subarray whenever adding the next element would exceed mid. If the number of subarrays needed is \u2264 m, mid is a feasible (achievable) largest sum, so I try smaller; otherwise mid is too small, so I need to allow a bigger largest sum.",
    key_insight="As the allowed maximum sum per subarray increases, the number of subarrays needed to satisfy that constraint monotonically decreases \u2014 that monotonic relationship is exactly what makes binary search on the answer valid here.",
    optimization_say=[
        "Instead of searching over ways to split the array, I'll binary search over possible values of the answer itself, between the largest single element and the total sum.",
        "For each candidate value, I'll greedily check how many subarrays are needed if no subarray's sum can exceed that candidate.",
        "If that count is within the allowed m, the candidate is achievable, so I try to shrink it further; otherwise I need to allow a larger candidate.",
    ],
    code_blocks=[
        dict(code="def split_array(nums, m):\n    def subarrays_needed(max_sum):\n        count = 1\n        current_sum = 0\n        for num in nums:\n            if current_sum + num > max_sum:\n                count += 1\n                current_sum = num\n            else:\n                current_sum += num\n        return count",
             say="I write a helper that, given a candidate max_sum, greedily counts how many subarrays are needed: I keep adding to the current subarray's sum until adding the next number would exceed max_sum, at which point I start a new subarray.",
             why="This greedy counting is always optimal for a fixed max_sum, since packing as much as possible into each subarray before exceeding the limit minimizes the total number of subarrays needed."),
        dict(code="    left = max(nums)\n    right = sum(nums)",
             say="I set the binary search bounds: the smallest possible answer is the largest single element (since that element alone can't be split further), and the largest possible answer is the sum of the whole array (using just one subarray).",
             why="These bounds are provably the true minimum and maximum feasible values for the answer, guaranteeing the true answer lies somewhere within this range."),
        dict(code="    while left < right:\n        mid = (left + right) // 2\n        if subarrays_needed(mid) <= m:\n            right = mid\n        else:\n            left = mid + 1\n\n    return left",
             say="I binary search: if the candidate mid allows splitting into at most m subarrays, it's achievable, so I try to shrink further by moving right down to mid. Otherwise, mid is too restrictive, so I need a bigger candidate and move left up.",
             why="Because feasibility is monotonic in mid (bigger mid always needs fewer or equal subarrays), binary search correctly converges to the smallest feasible mid, which is the answer."),
    ],
    dry_run="nums = [7,2,5,10,8], m=2. left=max=10, right=sum=32. mid=21: subarrays_needed(21): current=7,+2=9,+5=14,+10=24>21 so new subarray count=2, current=10,+8=18. Final count=2. 2<=2, feasible, right=21. mid=(10+21)//2=15: current=7,+2=9,+5=14,+10=24>15 new subarray count=2,current=10,+8=18>15 new subarray count=3,current=8. Final count=3. 3>2, not feasible, left=16. mid=(16+21)//2=18: current=7,+2=9,+5=14,+10=24>18 count=2,current=10,+8=18<=18 current=18. Final count=2. Feasible, right=18. mid=(16+18)//2=17: similar check gives count=3 (since 10+8=18>17). Not feasible, left=18. Now left=18=right, loop ends. Return 18.",
    dry_run_say="Tracing nums=[7,2,5,10,8], m=2: binary search narrows the candidate largest sum down step by step, checking feasibility with the greedy counter each time, and converges on 18, which is indeed the minimized largest sum (splitting as [7,2,5] and [10,8], sums 14 and 18).",
    edge_case="m equals the length of the array, meaning every element must be its own subarray. Then the answer is simply the largest single element, since each subarray is forced to be one number; the binary search correctly converges to max(nums) since subarrays_needed(max(nums)) always equals the array length in that scenario or fewer, and any smaller candidate would fail some element.",
    edge_case_say="Let me check when m equals the array's length, meaning each element must be alone \u2014 the answer should just be the largest single element, and the greedy feasibility check confirms that's exactly what the binary search converges to.",
    other_edge_cases=[
        "m = 1 (no splitting allowed, answer is the total sum)",
        "All elements identical",
        "Array with only one element",
        "One very large element dominating the rest of the array",
    ],
    final_complexity_rows=[["Optimized", "O(n log(sum - max))", "O(1)"]],
    final_complexity_say="This is O(n log(S)) time, where S is the range between the sum and the max element, since each binary search step costs O(n) for the feasibility check and there are O(log S) steps, and O(1) extra space beyond a few counters.",
    pushback=[
        ("Why is binary search on the answer valid here?", "Because the feasibility function \u2014 'can this array be split into \u2264 m subarrays each with sum \u2264 mid' \u2014 is monotonic: as mid increases, the number of subarrays needed can only decrease or stay the same, which is exactly the property binary search relies on."),
        ("Is the greedy subarray-counting always correct for a fixed max_sum?", "Yes \u2014 for any fixed cap, greedily packing as much as possible into the current subarray before starting a new one always uses the fewest subarrays possible, since delaying a split can never help and could only force an earlier, more restrictive split later."),
        ("Can you solve this with Dynamic Programming instead?", "Yes, there's a DP formulation where dp[i][j] represents the minimized largest sum using j subarrays for the first i elements, but that's O(n\u00b2 m) time, which is typically worse than the O(n log S) binary search approach for larger inputs."),
        ("What if numbers could be negative?", "This specific greedy/binary-search approach assumes non-negative numbers, since it relies on subarray sums only growing as you add more elements; negative numbers would break both the monotonicity of the feasibility check and the lower/upper bound reasoning."),
    ],
    mistakes=[
        "Setting the initial 'left' bound to 0 instead of max(nums), which can make the feasibility check incorrectly reject a value smaller than the largest single element.",
        "Off-by-one in the binary search (using <= for the loop condition instead of <, which can cause infinite loops in this style).",
        "Forgetting the greedy subarray counter must start with count=1 (the first subarray always exists) rather than 0.",
        "Assuming this generalizes directly to arrays containing negative numbers.",
    ],
    recovery=[
        "If stuck: 'Trying every way to split the array is exponential. Let me instead think about binary searching over possible answer VALUES and checking feasibility for each, which is a much smaller search space.'",
        "If unsure why the bounds are max(nums) and sum(nums): reason through both extremes \u2014 you can never do better than the largest single element, and you never need to do worse than putting everything in one subarray.",
        "If the interviewer hints 'think about binary searching on the answer, not the split': confirm and describe the feasibility-check helper function.",
        "If my binary search doesn't converge: double check I'm using left < right with right = mid (not mid - 1), matching the same convergence pattern as other 'search on the answer' problems.",
    ],
    pattern_recognition=dict(
        triggers="'minimize the maximum', 'split into m parts', 'largest sum as small as possible'",
        pattern="Binary Search on the Answer (paired with a greedy feasibility check)",
        first_thought="Can I binary search over possible answer VALUES instead of over configurations, using a greedy or counting check to test feasibility for each candidate?",
        trap="Trying to enumerate split configurations directly instead of recognizing the monotonic feasibility structure.",
    ),
    memory_hook="Split Array Largest Sum \u2192 \"Binary search the answer; greedily count subarrays to test feasibility.\"",
    recap_key_idea="Binary search over candidate 'largest sum' values, using a greedy pass to check if that candidate allows splitting into \u2264 m subarrays.",
    recap_data_structure="No extra structure \u2014 running sums and counters.",
    recap_algorithm="Binary Search on the Answer + Greedy feasibility check.",
    recap_time="O(n log(sum-max))", recap_space="O(1)", recap_edge_case="m equal to the array length (every element its own subarray).",
    talk_track=[
        ("Interviewer", "Split this array into m contiguous parts, minimizing the largest part's sum."),
        ("Me", "Got it \u2014 and I just need to return the minimized largest sum, not the actual split, right? Are all numbers non-negative?"),
        ("Interviewer", "Yes to both."),
        ("Me", "Brute force would try every possible placement of m-1 split points, which is exponential \u2014 not scalable."),
        ("Interviewer", "How would you approach it differently?"),
        ("Me", "I'd binary search on the answer itself. The answer is somewhere between the largest single element and the total sum. For a candidate value, I can greedily check how many subarrays are needed if no subarray exceeds that value \u2014 pack elements in until adding one more would exceed it, then start fresh."),
        ("Me", "If that count is within m, the candidate works and I try smaller; if not, I need a bigger candidate. That's a clean monotonic binary search."),
        ("Me", "Let me code the feasibility helper first, then the binary search around it."),
        ("Me", "Tracing [7,2,5,10,8] with m=2, the search converges to 18, splitting as [7,2,5] and [10,8]."),
        ("Me", "Edge case: if m equals the array length, every element must stand alone, and the answer correctly becomes the largest single element."),
        ("Me", "Final complexity: O(n log(sum - max)) time, since each of the O(log) binary search steps does an O(n) feasibility check, O(1) extra space."),
    ],
))

PROBLEMS.append(dict(
    title="Pow(x, n)", lc_num="50", difficulty="MEDIUM", pattern="Binary Search / Divide and Conquer (Fast Exponentiation)",
    relevance="Common interview pattern",
    restate="We need to implement a function that computes x raised to the integer power n, handling both positive and negative exponents, efficiently.",
    clarify_questions=[
        "Can n be negative, meaning I need to return 1 divided by x to the power of |n|?",
        "Can n be 0, in which case the answer is always 1?",
        "Can x be 0 or negative?",
        "Is there a concern about integer overflow or floating point precision given the language?",
    ],
    restate_say=["Just to confirm, n can be negative (meaning I return the reciprocal) or zero (returning 1), and x can be any real number, correct?"],
    brute_idea="Multiply x by itself n times in a simple loop.",
    brute_say=["The most direct approach is to multiply x by itself n times in a loop, accumulating the result."],
    brute_time="O(n) since we do n multiplications.",
    brute_space="O(1) extra space.",
    brute_complexity_say="This is O(n) time because we loop once per unit of the exponent, and O(1) space since we just keep a running product.",
    bottleneck="I'm doing far more multiplications than necessary \u2014 if I already know x squared, I've effectively computed two multiplications' worth of exponent in one step, and I can keep doubling that way instead of counting up one at a time.",
    bottleneck_say="The bottleneck is treating the exponent as something I must count through one unit at a time, when I can jump exponentially by repeatedly squaring the base.",
    optimization_explain="I use Fast Exponentiation (also called Binary Exponentiation), a Divide and Conquer technique. To compute x^n, I recursively compute half = x^(n//2), and combine: if n is even, the answer is half * half; if n is odd, it's half * half * x (to account for the leftover single factor). Negative n is handled by computing the positive-power result and taking its reciprocal.",
    key_insight="x^n can be built from x^(n/2) by squaring, cutting the exponent in half at each step, so the total number of multiplications needed grows logarithmically with n instead of linearly.",
    optimization_say=[
        "I'll handle the negative exponent case by converting it to a positive exponent and taking the reciprocal at the end.",
        "Then I'll recursively compute x to the half power, and square that result.",
        "If the exponent is odd, I multiply in one extra factor of x to account for the leftover.",
    ],
    code_blocks=[
        dict(code="def my_pow(x, n):\n    if n < 0:\n        x = 1 / x\n        n = -n",
             say="If n is negative, I flip the problem: invert x and make the exponent positive, since x^(-n) is the same as (1/x)^n.",
             why="Handling the sign once up front lets the rest of the function assume a non-negative exponent, simplifying the recursive logic."),
        dict(code="    def fast_pow(base, exp):\n        if exp == 0:\n            return 1\n        half = fast_pow(base, exp // 2)\n        if exp % 2 == 0:\n            return half * half\n        else:\n            return half * half * base",
             say="I define a helper that recursively computes base to the exp power. The base case is exponent 0, which is always 1. Otherwise, I compute half the work recursively and square it, adding one more factor of base if the exponent was odd.",
             why="Recursing on exp // 2 halves the problem size at every step, which is exactly what gives this its logarithmic time complexity instead of linear."),
        dict(code="    return fast_pow(x, n)",
             say="Finally, I call the helper with the (possibly adjusted) base and exponent and return its result.",
             why="By this point, any sign handling has already been resolved, so fast_pow only ever needs to deal with a non-negative exponent."),
    ],
    dry_run="x=2, n=10. fast_pow(2,10): half=fast_pow(2,5). fast_pow(2,5): half=fast_pow(2,2). fast_pow(2,2): half=fast_pow(2,1). fast_pow(2,1): half=fast_pow(2,0)=1; exp=1 is odd, return 1*1*2=2. Back in fast_pow(2,2): half=2, exp=2 even, return 2*2=4. Back in fast_pow(2,5): half=4, exp=5 odd, return 4*4*2=32. Back in fast_pow(2,10): half=32, exp=10 even, return 32*32=1024. Final answer: 1024, matching 2^10.",
    dry_run_say="Tracing 2 to the 10th power: the recursion halves the exponent each time \u2014 10, 5, 2, 1, 0 \u2014 and builds back up by squaring (and multiplying in an extra factor when odd), correctly landing on 1024.",
    edge_case="Negative exponent, e.g. x=2, n=-2. We flip: x becomes 1/2, n becomes 2. fast_pow(0.5, 2): half=fast_pow(0.5,1)=0.5*0.5*0.5=0.125? Let's recompute: fast_pow(0.5,1): half=fast_pow(0.5,0)=1; exp=1 odd, return 1*1*0.5=0.5. Back in fast_pow(0.5,2): half=0.5, exp even, return 0.5*0.5=0.25. Final answer 0.25, matching 2^-2 = 1/4.",
    edge_case_say="Let me check a negative exponent, like 2 to the power -2 \u2014 flipping x to 0.5 and n to 2, the recursion correctly gives 0.25, which is 1/4, exactly what 2^-2 should be.",
    other_edge_cases=[
        "n = 0 (always returns 1, regardless of x)",
        "x = 0 with a positive exponent (returns 0)",
        "x = 1 or x = -1 (result depends only on the parity of n for -1)",
        "Very large n (verifies the O(log n) speed advantage over the naive loop)",
    ],
    final_complexity_rows=[["Optimized", "O(log n)", "O(log n) recursion stack"]],
    final_complexity_say="This is O(log n) time since the exponent halves at every recursive call, and O(log n) space for the recursion call stack, which could be reduced to O(1) with an iterative version.",
    pushback=[
        ("Can you do this iteratively instead of recursively, to save stack space?", "Yes \u2014 I can iterate, repeatedly squaring the base and halving the exponent, and whenever the exponent is odd, multiply the current base into a running result before halving; that achieves the same O(log n) time with O(1) space instead of O(log n) recursion depth."),
        ("What about x=0 and n=0 together?", "Mathematically 0^0 is often defined as 1 by convention in these problems, so I'd clarify with the interviewer, but the recursive base case (exp==0 returns 1) naturally follows that convention here."),
        ("Could there be overflow or precision issues?", "Yes, for very large exponents or very small/large x, floating point precision could become an issue; in a language with fixed-size integers, overflow could also matter, so I'd mention that as a real-world caveat depending on the language and constraints."),
        ("Can you optimize further?", "O(log n) is already optimal for exponentiation by squaring \u2014 there's no known way to compute a general power in fewer than O(log n) multiplications for arbitrary bases."),
    ],
    mistakes=[
        "Forgetting to flip x to 1/x when n is negative, causing wrong (or crashing) results for negative exponents.",
        "Off-by-one in handling odd vs. even exponents (forgetting the extra factor of base when exp is odd).",
        "Using recursion without a proper base case, causing infinite recursion or stack overflow.",
        "Assuming the naive O(n) loop is 'good enough' without recognizing the interviewer likely wants the log(n) solution.",
    ],
    recovery=[
        "If stuck: 'The naive loop is O(n), multiplying one factor of x at a time. Let me think about whether I can 'double up' progress instead of only adding one factor per step \u2014 that suggests squaring.'",
        "If I forget to handle negative n: catch it in a dry run with a negative exponent and notice the result is wrong, then add the sign-flip logic.",
        "If the interviewer hints 'can you avoid n multiplications': pivot to recursively halving the exponent and squaring.",
        "If recursion depth worries the interviewer: offer the iterative version as a stack-space optimization.",
    ],
    pattern_recognition=dict(
        triggers="'x to the power of n', 'compute pow', 'exponentiation'",
        pattern="Fast (Binary) Exponentiation \u2014 Divide and Conquer",
        first_thought="Can I halve the exponent each step and square the result, instead of counting up one multiplication at a time?",
        trap="Forgetting the extra multiplication needed when the exponent is odd, or mishandling negative exponents.",
    ),
    memory_hook="Pow(x, n) \u2192 \"Halve the exponent, square the result \u2014 add one extra factor if odd.\"",
    recap_key_idea="Recursively compute half the exponent's result and square it; add one extra factor of x if the exponent is odd; invert for negative exponents.",
    recap_data_structure="No extra data structure \u2014 recursion.",
    recap_algorithm="Fast Exponentiation via Divide and Conquer.",
    recap_time="O(log n)", recap_space="O(log n) recursion (O(1) iterative)", recap_edge_case="Negative exponent, requiring reciprocal handling.",
    talk_track=[
        ("Interviewer", "Implement pow(x, n) for integer n, which can be negative."),
        ("Me", "Got it \u2014 negative n means I return the reciprocal of the positive-power result, and n=0 always gives 1, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "The direct way is a loop multiplying x by itself n times, which is O(n) time."),
        ("Interviewer", "Can you do better?"),
        ("Me", "Yes \u2014 instead of adding one factor of x at a time, I can recursively compute x to the half-exponent and square that result, cutting the exponent in half every step. If the exponent's odd, I multiply in one extra factor of x."),
        ("Me", "For negative n, I'll flip x to 1/x and make n positive before running that recursive logic."),
        ("Me", "Let me code that up... base case is exponent 0, returning 1."),
        ("Me", "Tracing 2 to the 10th power: the exponent halves through 10, 5, 2, 1, 0, and squaring back up gives 1024, correct."),
        ("Me", "Let me also check a negative exponent, like 2 to the -2 \u2014 flipping to 0.5 squared gives 0.25, which is right."),
        ("Me", "Final complexity: O(log n) time since the exponent halves each recursive call, O(log n) recursion stack space, though I could make it iterative for O(1) space."),
    ],
))
