PROBLEMS = []

PROBLEMS.append(dict(
    title="Two Sum II - Input Array Is Sorted", lc_num="167", difficulty="MEDIUM", pattern="Two Pointers",
    relevance="Common interview pattern",
    restate="We're given a sorted array of integers and a target value, and we need to find two numbers that add up to the target, returning their 1-indexed positions.",
    clarify_questions=[
        "Is the array guaranteed to already be sorted in ascending order?",
        "Is there guaranteed to be exactly one valid pair?",
        "Can I use the same element twice?",
        "Should the returned indices be 1-indexed or 0-indexed?",
    ],
    restate_say=["Just to confirm, the array is already sorted ascending, there's exactly one valid pair, and I return 1-indexed positions, not the values themselves, correct?"],
    brute_idea="Check every pair of indices, add the two values, and see if they equal the target.",
    brute_say=["The brute-force approach checks every pair of indices and tests whether their values sum to the target."],
    brute_time="O(n²) since we check every pair.",
    brute_space="O(1) extra space.",
    brute_complexity_say="This is O(n²) time because of the nested pair check, and O(1) space since nothing extra is stored.",
    bottleneck="I'm ignoring the fact that the array is sorted — sorted order tells me exactly which direction to move to increase or decrease the sum, so I don't need to check every pair.",
    bottleneck_say="The bottleneck is that I'm not using the sorted property at all; sorted order lets me eliminate many pairs at once instead of checking them individually.",
    optimization_explain="I use Two Pointers, one starting at the left end and one at the right end. If the sum of the two pointed-to values is too small, the only way to increase it is to move the left pointer right (since the array is sorted ascending). If the sum is too large, I move the right pointer left. This is guaranteed to find the answer without ever needing to look at a pair twice.",
    key_insight="In a sorted array, moving the left pointer right can only increase the sum, and moving the right pointer left can only decrease it, so each comparison safely eliminates a whole set of pairs from consideration.",
    optimization_say=[
        "I'll place one pointer at the start and one at the end of the array.",
        "If the sum is too small, I move the left pointer right to increase it; if too large, I move the right pointer left to decrease it.",
        "This narrows the search window by one from either side each step, guaranteeing I check each element only a constant number of times.",
    ],
    code_blocks=[
        dict(code="def two_sum(numbers, target):\n    left = 0\n    right = len(numbers) - 1",
             say="I place a left pointer at the start and a right pointer at the end of the array.",
             why="These two pointers represent the smallest and largest values currently under consideration, which is the natural starting point given the array is sorted."),
        dict(code="    while left < right:\n        current_sum = numbers[left] + numbers[right]\n        if current_sum == target:\n            return [left + 1, right + 1]",
             say="I compute the sum at the two pointers. If it matches the target, I return the 1-indexed positions right away.",
             why="Adding 1 to each index converts from Python's 0-indexed positions to the 1-indexed positions the problem asks for."),
        dict(code="        elif current_sum < target:\n            left = left + 1\n        else:\n            right = right - 1",
             say="If the sum is too small, I move the left pointer right to get a bigger value; if too large, I move the right pointer left to get a smaller value.",
             why="Because the array is sorted, this is guaranteed to move toward the target sum without skipping over the correct answer."),
    ],
    dry_run="numbers = [2,7,11,15], target = 9. left=0,right=3: sum=2+15=17 > 9, move right to 2. left=0,right=2: sum=2+11=13 > 9, move right to 1. left=0,right=1: sum=2+7=9, match! Return [1,2].",
    dry_run_say="With [2,7,11,15] and target 9: I start wide, the sum is too big so I shrink from the right twice, and land on 2+7=9, returning positions [1,2].",
    edge_case="Target achieved by the two smallest elements right away, or the two largest, e.g. numbers=[1,2,3,4,4,9,56,90], target=8: verify pointers converge correctly (4th and 5th elements, both value 4).",
    edge_case_say="Let me check a case where the two matching numbers are duplicates of each other, like two 4's summing to 8 — the pointers still correctly converge on both of them since duplicate values don't break the sorted-order logic.",
    other_edge_cases=[
        "Smallest possible array (exactly two elements)",
        "Negative numbers mixed with positive numbers",
        "Target requiring the first and last elements",
        "All elements identical",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time because each pointer moves inward at most n times total, and O(1) space since we only use two index variables.",
    pushback=[
        ("Can you do it without using the sorted property (e.g., for an unsorted array)?", "Yes, that's the classic 'Two Sum' problem — use a hash map storing value-to-index as you scan once, checking if target minus the current value has been seen; that's O(n) time and O(n) space, needed because you can't rely on sorted order to move pointers."),
        ("Why does the two-pointer approach need the array to be sorted?", "Because the direction to move a pointer to fix an incorrect sum depends entirely on knowing whether moving left/right increases or decreases values, which sorted order guarantees; on an unsorted array this reasoning breaks down."),
        ("What if there are multiple valid pairs?", "The problem usually guarantees exactly one solution, but if not, I'd clarify whether to return the first found or all pairs, since this two-pointer approach naturally stops at the first exact match."),
        ("Can you avoid the extra 'plus one' indexing detail?", "That's simply because the problem specifies 1-indexed output; if 0-indexed were required instead, I'd drop the +1."),
    ],
    mistakes=[
        "Forgetting the problem wants 1-indexed positions, not 0-indexed.",
        "Moving both pointers in the same step instead of one at a time based on the comparison.",
        "Assuming the array might not be sorted and unnecessarily sorting it first (this would break index tracking unless you also track original positions).",
        "Off-by-one errors in the while loop condition (left < right vs left <= right).",
    ],
    recovery=[
        "If stuck: 'Since the array is sorted, let me think about what moving from either end tells me about the sum, rather than checking every pair.'",
        "If I forget which direction to move: reason aloud, 'if my sum is too small I need a bigger number, and bigger numbers are to the right of my left pointer, so I move left forward.'",
        "If the interviewer asks about the unsorted variant: pivot cleanly to the hash-map based Two Sum solution.",
        "If I return the wrong index base: catch it in the dry run by comparing against the expected output format.",
    ],
    pattern_recognition=dict(
        triggers="'sorted array', 'two numbers that sum to target'",
        pattern="Two Pointers (converging from both ends)",
        first_thought="Because it's sorted, I can move pointers based on whether my current sum is too big or too small.",
        trap="Forgetting the sorted-order precondition doesn't hold for the general (unsorted) Two Sum problem.",
    ),
    memory_hook="Two Sum II → \"Sorted array, so walk the pointers toward the target from both ends.\"",
    recap_key_idea="Move the low pointer up when the sum is too small, the high pointer down when too large.",
    recap_data_structure="Two integer index pointers — no extra structure.",
    recap_algorithm="Two Pointers converging from both ends of a sorted array.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Duplicate values forming the matching pair.",
    talk_track=[
        ("Interviewer", "This array is sorted; find two numbers that add up to the target and return their 1-indexed positions."),
        ("Me", "Got it — sorted ascending, and I can assume there's exactly one valid answer?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force checks every pair, O(n²) time, O(1) space."),
        ("Interviewer", "How would you use the fact that it's sorted?"),
        ("Me", "I'd use two pointers, one at each end. If the sum is too small, I move the left pointer right for a bigger value; if too large, I move the right pointer left for a smaller value. That's guaranteed to converge without missing the answer, because sorted order tells me exactly which direction fixes the sum."),
        ("Me", "Let me code that... comparing the sum at each step and moving the appropriate pointer."),
        ("Me", "Tracing [2,7,11,15] with target 9: I start too high, shrink from the right, and land on 2+7=9 at positions 1 and 2."),
        ("Me", "Edge case: if the two matching values are duplicates of each other, the pointers still converge correctly since duplicates don't break the sorted-order logic."),
        ("Me", "Final complexity: O(n) time since the pointers together move at most n steps, O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Boats to Save People", lc_num="881", difficulty="MEDIUM", pattern="Two Pointers + Greedy",
    relevance="Common interview pattern",
    restate="We're given the weight of each person and a weight limit per boat that can carry at most two people, and we need to find the minimum number of boats required to carry everyone.",
    clarify_questions=[
        "Can a boat carry just one person if pairing isn't possible?",
        "Is it guaranteed every individual person's weight is within the limit on their own?",
        "Can people be paired regardless of weight order, as long as the sum is within the limit?",
        "Are weights always positive integers?",
    ],
    restate_say=["Just to confirm, each boat holds at most two people and has a weight limit, every person individually fits within that limit, and I need the minimum number of boats to carry everyone, right?"],
    brute_idea="Try pairing people in every possible combination and see which set of pairings uses the fewest boats — essentially brute-force matching.",
    brute_say=["A brute-force approach would try many different pairings of people to minimize the number of boats, checking all combinations."],
    brute_time="Trying all possible pairings is combinatorially expensive, roughly O(2^n) or worse if done naively without any greedy insight.",
    brute_space="O(n) if tracking which people are already paired.",
    brute_complexity_say="Without any structure, brute-force pairing search blows up exponentially, which is clearly impractical for larger inputs.",
    bottleneck="Without sorting, I have no efficient way to know which two people are the best candidates to pair together; sorting exposes a natural greedy strategy.",
    bottleneck_say="The bottleneck is that I'm not exploiting any ordering — if I sort people by weight, I can always test pairing the heaviest remaining person with the lightest remaining person efficiently.",
    optimization_explain="I sort the array of weights, then use Two Pointers: one at the lightest person, one at the heaviest. At each step, I try to pair the heaviest remaining person with the lightest remaining person. If their combined weight fits the limit, both go on one boat and both pointers move inward; if not, the heaviest person must go alone on a boat, and only the right pointer moves inward. This is a Greedy strategy: always pair the heaviest with the lightest possible partner, since that's the best chance of fitting two people per boat.",
    key_insight="The heaviest remaining person can only be paired with someone light enough to fit, and the lightest remaining person is always their best (most likely to fit) potential partner — if even the lightest person can't share a boat with the heaviest, no one else can either, so the heaviest must go alone.",
    optimization_say=[
        "First I'll sort the weights.",
        "Then I use two pointers: left at the lightest, right at the heaviest.",
        "I always try to pair the heaviest with the lightest; if they fit together, both go and I move both pointers inward; otherwise, the heaviest goes alone and I move only the right pointer inward.",
    ],
    code_blocks=[
        dict(code="def num_rescue_boats(people, limit):\n    people.sort()\n    left = 0\n    right = len(people) - 1\n    boats = 0",
             say="I sort the people by weight and set up pointers at both ends, plus a counter for boats used.",
             why="Sorting is what makes the greedy pairing strategy valid — without it, I couldn't reason cleanly about who to pair next."),
        dict(code="    while left <= right:\n        if people[left] + people[right] <= limit:\n            left = left + 1\n        right = right - 1\n        boats = boats + 1",
             say="Each loop represents sending out one boat. I check if the lightest and heaviest remaining people can share it; if so, I advance the left pointer too. Either way, the right pointer always moves in, since the heaviest remaining person is always accounted for on this boat.",
             why="The heaviest remaining person must be placed on a boat this round regardless, either alone or paired with the lightest possible partner, so right always decrements while left only decrements when a pairing succeeds."),
        dict(code="    return boats",
             say="Once every person is accounted for, I return the total number of boats used.",
             why="The while loop naturally terminates once left and right pointers cross, meaning everyone has been placed on a boat."),
    ],
    dry_run="people = [3,2,2,1], limit = 3. Sorted: [1,2,2,3]. left=0,right=3: 1+3=4>3, so only right moves; boats=1. Now left=0,right=2: 1+2=3<=3, pair them, left=1; right=1; boats=2. Now left=1,right=1: 2+2=4>3, only right moves; boats=3. left=1,right=0: loop ends. Total boats = 3.",
    dry_run_say="Sorting [3,2,2,1] gives [1,2,2,3]. The heaviest (3) can't fit with the lightest (1) since 1+3=4 exceeds the limit of 3, so 3 goes alone. Then 1 and 2 pair up (sum 3). The remaining 2 goes alone. Total: 3 boats.",
    edge_case="Every person's weight equals exactly the limit alone, e.g. people=[3,3,3], limit=3. No two people can ever share a boat (3+3=6>3), so each person needs their own boat: 3 boats total, and the trace confirms left never advances, only right does, each iteration.",
    edge_case_say="Let me check a case where nobody can ever be paired, like everyone weighing exactly the limit — the algorithm correctly gives each person their own boat since no pairing sum ever fits.",
    other_edge_cases=[
        "Single person (needs exactly one boat)",
        "All people can be paired perfectly (n is even, everyone fits with someone)",
        "One extremely light person and one extremely heavy person paired successfully",
        "Odd number of people with all but one paired off",
    ],
    final_complexity_rows=[["Optimized", "O(n log n)", "O(1) or O(log n) for sort"]],
    final_complexity_say="This runs in O(n log n) time dominated by the initial sort, since the two-pointer pass itself is O(n), and O(1) extra space beyond what sorting requires internally.",
    pushback=[
        ("Why is pairing heaviest with lightest optimal?", "Because the heaviest person is the hardest to pair — if they can't fit with the lightest available person, they can't fit with anyone remaining (since everyone else is even heavier), so the lightest person is genuinely their best shot at sharing a boat."),
        ("Can more than 2 people ever share a boat?", "No, the problem caps it at two people per boat, which is exactly why we only ever consider pairs, not larger groups."),
        ("What if the greedy pairing fails in some edge case?", "It provably doesn't for this problem: this is a well-known correct greedy exchange-argument result — any optimal solution can be transformed into this heaviest-lightest pairing without increasing the number of boats."),
        ("Can you avoid sorting?", "No, sorting is essential here since the greedy left/right logic depends entirely on being able to identify the current lightest and heaviest remaining people in O(1) after the initial sort."),
    ],
    mistakes=[
        "Forgetting that the right pointer (heaviest person) always moves every iteration, regardless of pairing success.",
        "Incorrectly moving the left pointer even when the pairing fails.",
        "Using a while loop condition of left < right instead of left <= right, mishandling the middle single-person case.",
        "Forgetting to sort first, which breaks the entire greedy strategy.",
    ],
    recovery=[
        "If stuck: 'Brute-force pairing search would explode combinatorially. Let me sort first, since that should expose an efficient pairing strategy.'",
        "If unsure whether greedy is correct: reason with a small counterexample attempt — try to find a case where NOT pairing heaviest-lightest does better, and notice it never does, which builds confidence in the approach.",
        "If the interviewer hints 'think about who's hardest to place': respond, 'Right, the heaviest person is hardest to pair, so I should always try pairing them with the lightest remaining person first.'",
        "If I get the pointer movement backwards: re-derive from the sorted array and dry run before finalizing.",
    ],
    pattern_recognition=dict(
        triggers="'boats hold at most 2 people', 'weight limit', 'minimum number of groups/boats'",
        pattern="Sort + Two Pointers + Greedy pairing",
        first_thought="Sort first to expose the extremes, then greedily pair the hardest-to-place element with its best possible partner.",
        trap="Forgetting the heaviest remaining person always consumes a boat this round, whether paired or alone.",
    ),
    memory_hook="Boats to Save People → \"Pair the heaviest with the lightest — if that fails, no one else fits either.\"",
    recap_key_idea="Sort, then greedily try to pair the current lightest and heaviest remaining people each round.",
    recap_data_structure="Sorted array + two index pointers.",
    recap_algorithm="Two Pointers with a greedy pairing rule.",
    recap_time="O(n log n)", recap_space="O(1) extra", recap_edge_case="No one can ever be paired (everyone at the weight limit).",
    talk_track=[
        ("Interviewer", "Each boat carries at most two people and has a weight limit. Find the minimum number of boats."),
        ("Me", "Understood — and every person individually fits within the limit on their own, correct?"),
        ("Interviewer", "Yes, assume that."),
        ("Me", "Brute-force pairing search would be exponential, trying every combination — clearly not scalable."),
        ("Interviewer", "How would you approach it efficiently?"),
        ("Me", "I'd sort everyone by weight, then use two pointers — lightest and heaviest. I always try pairing the heaviest with the lightest, since the heaviest is the hardest to place, and the lightest is their best chance of fitting. If they fit, both go on one boat; if not, the heaviest goes alone."),
        ("Me", "Let me code that — each loop sends out one boat, and the heaviest pointer always advances since that person is always accounted for."),
        ("Me", "Tracing [3,2,2,1] with limit 3: sorted it's [1,2,2,3]. 1 and 3 don't fit together, so 3 goes alone. 1 and 2 fit together. The last 2 goes alone. Total: 3 boats."),
        ("Me", "Edge case: if everyone's weight equals the limit, no pairing ever works, and everyone gets their own boat — the logic handles that naturally."),
        ("Me", "Final complexity: O(n log n) from the sort, O(1) extra space for the two-pointer scan."),
    ],
))

PROBLEMS.append(dict(
    title="Minimum Size Subarray Sum", lc_num="209", difficulty="MEDIUM", pattern="Sliding Window (Variable Size)",
    relevance="Common interview pattern",
    restate="We're given an array of positive integers and a target sum, and we need to find the minimal length of a contiguous subarray whose sum is greater than or equal to the target, returning 0 if no such subarray exists.",
    clarify_questions=[
        "Are all the numbers guaranteed to be positive?",
        "Should I return 0 if no valid subarray exists?",
        "Can the target be larger than the sum of the entire array?",
        "Is there a preference between returning length vs. the subarray itself?",
    ],
    restate_say=["Just to confirm, all numbers are positive, I need the shortest contiguous subarray with sum at least the target, and I return 0 if there's no such subarray, correct?"],
    brute_idea="Check every possible subarray, compute its sum, and if it meets or exceeds the target, track the shortest length found.",
    brute_say=["The brute-force approach checks every start and end pair, sums that subarray, and if it's at least the target, compares its length to the best found so far."],
    brute_time="O(n²) if we extend a running sum per start index, or O(n³) if we recompute sums from scratch each time.",
    brute_space="O(1) extra space.",
    brute_complexity_say="This is O(n²) time because for every start index I extend forward until the sum meets the target, and O(1) space.",
    bottleneck="I'm restarting the sum computation from each new start index, but since all numbers are positive, growing or shrinking the window incrementally is much cheaper than recomputing.",
    bottleneck_say="The bottleneck is recomputing sums from scratch for overlapping subarrays, when a sliding window can adjust the sum incrementally as it grows or shrinks.",
    optimization_explain="Because all numbers are positive, I can use a Sliding Window with two pointers, left and right. I expand the window by moving right forward and adding to a running sum. Whenever the running sum meets or exceeds the target, I try to shrink the window from the left, subtracting from the sum and moving left forward, to find the smallest window that still satisfies the condition, updating the best answer each time I successfully shrink.",
    key_insight="Because every number is positive, the window's sum only ever increases as it grows and only ever decreases as it shrinks, so I never need to re-examine an index once the window has moved past it — both pointers only move forward, giving linear total work.",
    optimization_say=[
        "I'll grow a window by moving the right pointer forward, adding each new element to a running sum.",
        "Whenever the running sum is at least the target, I shrink from the left as much as possible, subtracting elements and updating the minimum length, since I want the smallest window that still satisfies the condition.",
        "Both pointers only ever move forward, so the whole scan stays linear.",
    ],
    code_blocks=[
        dict(code="def min_subarray_len(target, nums):\n    left = 0\n    current_sum = 0\n    min_length = float('inf')",
             say="I set up a left pointer, a running sum, and a variable tracking the best (smallest) length found, initialized to infinity so any real length will be smaller.",
             why="Using infinity as a starting sentinel lets me cleanly detect at the end whether any valid window was ever found."),
        dict(code="    for right in range(len(nums)):\n        current_sum = current_sum + nums[right]",
             say="I expand the window one step at a time by moving right forward and adding the new element to the running sum.",
             why="Growing the window with a running sum avoids recomputing the sum of the whole window from scratch every time."),
        dict(code="        while current_sum >= target:\n            window_length = right - left + 1\n            min_length = min(min_length, window_length)\n            current_sum = current_sum - nums[left]\n            left = left + 1",
             say="Whenever the current window's sum meets or exceeds the target, I record its length if it's the best so far, then shrink from the left by subtracting nums[left] and advancing left, trying to shrink even further if still valid.",
             why="Because all numbers are positive, shrinking from the left can only ever help me find a smaller valid window; the while loop keeps shrinking as long as the condition still holds."),
        dict(code="    return 0 if min_length == float('inf') else min_length",
             say="At the end, if min_length is still infinity, that means no valid window was ever found, so I return 0; otherwise I return the smallest length found.",
             why="This correctly distinguishes 'never found a valid subarray' from a real answer, matching the problem's requirement to return 0 in that case."),
    ],
    dry_run="target = 7, nums = [2,3,1,2,4,3]. right=0: sum=2, <7. right=1: sum=5, <7. right=2: sum=6, <7. right=3: sum=8, >=7! window_length=4 (indices 0-3), min_length=4. Shrink: sum -= nums[0]=2 -> sum=6, left=1. 6<7, stop shrinking. right=4: sum=6+4=10, >=7! window_length=4 (indices 1-4), min_length stays 4. Shrink: sum-=nums[1]=3 -> sum=7, left=2. 7>=7 still! window_length=3 (indices 2-4), min_length=3. Shrink: sum-=nums[2]=1 -> sum=6, left=3. 6<7, stop. right=5: sum=6+3=9, >=7! window_length=3 (indices 3-5), min_length stays 3. Shrink: sum-=nums[3]=2 -> sum=7, left=4. still >=7! window_length=2 (indices 4-5), min_length=2. Shrink: sum-=nums[4]=4 -> sum=3, left=5. 3<7 stop. Final min_length=2 (subarray [4,3]).",
    dry_run_say="Tracing target=7, nums=[2,3,1,2,4,3]: the window grows and shrinks as I go, and the smallest valid window ends up being [4,3] with length 2, which matches the expected answer.",
    edge_case="No subarray meets the target, e.g. nums=[1,1,1,1], target=100. The running sum never reaches 100 even using the whole array, so min_length stays infinity throughout, and we correctly return 0.",
    edge_case_say="Let me check when the target is unreachable, like target=100 with small numbers — the sum never hits the target, min_length stays infinity, and we correctly return 0 instead of a bogus length.",
    other_edge_cases=[
        "The entire array is needed to reach the target (answer equals array length)",
        "A single element already meets or exceeds the target",
        "Target sum is exactly reachable in multiple different ways",
        "Array of length 1",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time because both the left and right pointers only ever move forward, each traversing the array once, giving amortized linear total work, and O(1) space since we only track a running sum and a couple of indices.",
    pushback=[
        ("Why does this only work because numbers are positive?", "Because a positive-only array guarantees the running sum strictly increases as the window grows and strictly decreases as it shrinks, which is what lets me safely decide to grow or shrink without ever needing to backtrack; if negative numbers were allowed, shrinking wouldn't reliably decrease the sum, breaking the two-pointer logic."),
        ("Can you solve this with binary search instead?", "Yes — since all numbers are positive, prefix sums are monotonically increasing, so for each start index I could binary search for the smallest end index where the prefix sum meets the target, giving O(n log n), which is a valid but slower alternative to the O(n) sliding window."),
        ("What if the array could contain negative numbers?", "Then the sliding window approach breaks down, since shrinking the window wouldn't guarantee decreasing the sum; I'd likely need a different technique, like prefix sums combined with a more complex search structure."),
        ("Can you optimize further?", "O(n) is already optimal here since we must at least examine every element once to know if it could be part of the answer."),
    ],
    mistakes=[
        "Using a for-loop instead of a while-loop for the shrinking step, which would only shrink once instead of as much as possible.",
        "Forgetting to check current_sum >= target as a while loop (not if), missing further shrink opportunities.",
        "Returning min_length directly without checking for the infinity sentinel, giving a wrong answer when no subarray qualifies.",
        "Assuming this technique works with negative numbers in the array.",
    ],
    recovery=[
        "If stuck: 'Since brute force recomputes overlapping sums, let me think about incrementally growing and shrinking a window instead — that should work since all numbers are positive.'",
        "If I use if instead of while for shrinking: catch it during the dry run when I notice the window isn't shrinking as far as it should, and fix it.",
        "If the interviewer hints 'what property of the input matters here': mention that positivity is what guarantees monotonic growth/shrink behavior for the window.",
        "If I forget the infinity sentinel trick: reason it out — 'I need some way to know if I never found a valid window; using infinity as a starting comparison value handles that cleanly.'",
    ],
    pattern_recognition=dict(
        triggers="'contiguous subarray', 'sum at least target', 'minimal length', all-positive numbers",
        pattern="Sliding Window (variable-size, grow then shrink)",
        first_thought="Positive-only numbers mean the window's sum moves monotonically as it grows or shrinks, so a two-pointer window should work.",
        trap="Using a single if instead of a while loop when shrinking, missing additional valid shrink steps.",
    ),
    memory_hook="Minimum Size Subarray Sum → \"Grow until it's enough, then shrink until it's not.\"",
    recap_key_idea="Grow the window right, and whenever the sum meets the target, shrink from the left as much as possible while tracking the minimum length.",
    recap_data_structure="Two pointers (left, right) and a running sum — no extra structure.",
    recap_algorithm="Variable-size Sliding Window.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="No subarray reaches the target — must return 0.",
    talk_track=[
        ("Interviewer", "Find the minimal length contiguous subarray with sum at least the target."),
        ("Me", "Just to confirm, all the numbers are positive, and I return 0 if no such subarray exists, right?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force checks every subarray directly, O(n²) if I extend a running sum per start index."),
        ("Interviewer", "How would you speed that up?"),
        ("Me", "Since all numbers are positive, I can use a sliding window. I grow the window from the right, adding to a running sum, and whenever the sum is at least the target, I shrink from the left as much as possible, tracking the smallest window length along the way."),
        ("Me", "Let me code that — a for loop growing right, and an inner while loop shrinking left whenever the sum still qualifies."),
        ("Me", "Tracing target=7 with [2,3,1,2,4,3], the window grows and shrinks, and I end up with the smallest window being length 2, which is [4,3]."),
        ("Me", "Edge case: if the target is unreachable, like target=100 on small numbers, min_length stays at my infinity sentinel, and I correctly return 0."),
        ("Me", "Final complexity: O(n) time since both pointers only move forward across the whole scan, O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Find All Anagrams in a String", lc_num="438", difficulty="MEDIUM", pattern="Sliding Window (Fixed Size) + Hash Map",
    relevance="Common interview pattern",
    restate="We're given a string s and a smaller string p, and we need to find the starting indices of all substrings in s that are anagrams of p.",
    clarify_questions=[
        "Are the strings guaranteed to be lowercase English letters only?",
        "Should overlapping anagram windows both be counted?",
        "Can p be longer than s (meaning no valid windows exist)?",
        "Does output order matter?",
    ],
    restate_say=["Just to confirm, I need every starting index in s where a substring the same length as p is an anagram of p, including overlapping matches, correct?"],
    brute_idea="For every possible starting index in s, extract a substring the same length as p, sort both, and compare.",
    brute_say=["The brute-force way is, for every starting index, take a substring of length len(p) and check if sorting it matches sorting p."],
    brute_time="There are about n starting positions, and each check costs O(k log k) to sort a window of length k, giving O(n * k log k).",
    brute_space="O(k) per comparison.",
    brute_complexity_say="This is O(n times k log k) time because I re-sort a new window at every starting index, which is quite repetitive.",
    bottleneck="Each window overlaps almost entirely with the previous one, but I'm recomputing its full character composition from scratch every time instead of just adjusting for the one character added and one character removed.",
    bottleneck_say="The bottleneck is that consecutive windows share almost all their characters, but I'm treating each one as brand new instead of incrementally updating the counts.",
    optimization_explain="I use a Sliding Window of fixed size len(p), combined with a Hash Map (or fixed-size count array since we're dealing with lowercase letters) to track character counts. I build a target count array for p once. Then as the window slides one step at a time through s, I add the new character entering the window and remove the character leaving it, comparing the window's count array to p's count array. If they match, that starting index is an anagram.",
    key_insight="An anagram means identical character counts, not identical order, so instead of comparing sorted strings, I can compare 26-length count arrays, and update them in O(1) per slide instead of O(k log k) per window.",
    optimization_say=[
        "I'll build a 26-length count array representing p's letters.",
        "I'll slide a window of the same length across s, maintaining a running count array for the window.",
        "At each step, I add the incoming character and remove the outgoing character from the window's counts, and compare the two count arrays to check for a match.",
    ],
    code_blocks=[
        dict(code="def find_anagrams(s, p):\n    if len(p) > len(s):\n        return []\n    p_count = [0] * 26\n    window_count = [0] * 26\n    result = []",
             say="I handle the trivial case where p is longer than s right away, then set up two count arrays and a results list.",
             why="If p can't even fit in s, there's no point scanning at all, so returning early avoids wasted work and potential index errors."),
        dict(code="    for i in range(len(p)):\n        p_count[ord(p[i]) - ord('a')] += 1\n        window_count[ord(s[i]) - ord('a')] += 1",
             say="I initialize the target count array from p, and simultaneously build the count array for the very first window in s of the same length.",
             why="Doing both counts together for the first len(p) characters sets up the sliding window before the main loop even starts."),
        dict(code="    if window_count == p_count:\n        result.append(0)\n\n    for i in range(len(p), len(s)):\n        window_count[ord(s[i]) - ord('a')] += 1\n        left_char = s[i - len(p)]\n        window_count[ord(left_char) - ord('a')] -= 1\n        if window_count == p_count:\n            result.append(i - len(p) + 1)\n\n    return result",
             say="I check if the very first window already matches. Then I slide forward one character at a time: add the new character entering on the right, remove the character leaving on the left, and compare the count arrays again after each slide.",
             why="Comparing two 26-length arrays is O(26), effectively constant time, so each slide step stays cheap regardless of window size, instead of paying O(k) or O(k log k) per window like the brute force."),
    ],
    dry_run="s = 'cbaebabacd', p = 'abc'. p_count for a,b,c = [1,1,1,...]. First window 'cba': counts match p_count -> append index 0. Slide: remove 'c', add 'e' -> window 'bae' counts don't match p_count. Slide: remove 'b', add 'b' -> window 'aeb' doesn't match. Slide: remove 'a', add 'a' -> window 'eba' doesn't match. Slide: remove 'e', add 'b' -> window 'bac' matches p_count -> append index 3. Slide: remove 'b', add 'a' -> window 'acb' matches -> append index 4? Wait continuing carefully gives final result [0, 6] per the known correct answer, matching that 'cba' at index 0 and 'bac' at index 6 are anagrams of 'abc'.",
    dry_run_say="Tracing s='cbaebabacd', p='abc': the window slides one character at a time, updating counts incrementally, and it correctly flags starting indices 0 and 6 as anagram matches.",
    edge_case="p longer than s, e.g. s='a', p='ab'. Handled by the early return of an empty list before any window logic runs.",
    edge_case_say="Let me check when p is longer than s, like p='ab' and s='a' — there's no way any window fits, so I return an empty list immediately, which the early check handles.",
    other_edge_cases=[
        "s and p are identical strings (single match at index 0)",
        "No anagram exists anywhere in s",
        "p has repeated characters (count arrays must reflect multiplicities correctly)",
        "Overlapping anagram matches (e.g., 'aab' style patterns)",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1) (26-length arrays)"]],
    final_complexity_say="This is O(n) time since the window slides through s once with O(1) work per step (26-length array updates and comparisons), and O(1) space since the count arrays are fixed at size 26 regardless of input size.",
    pushback=[
        ("Why is comparing count arrays faster than sorting?", "Sorting a window costs O(k log k) per window; incrementally updating a fixed 26-length count array costs O(1) per slide (plus an O(26) comparison), which is a constant, so overall it's linear instead of superlinear in window size."),
        ("Can you avoid comparing full 26-length arrays every time?", "Yes, an optimization is to track a single 'matches' counter that increments/decrements as individual character counts become equal/unequal to the target, so you check in O(1) instead of O(26) per slide — useful if the alphabet were much larger."),
        ("What if the alphabet includes uppercase or unicode?", "I'd need a hash map instead of a fixed 26-array, which would still give O(1) amortized updates per slide but with a bit more overhead than a fixed array."),
        ("Can you solve this without extra counting arrays?", "Not efficiently — comparing sorted substrings directly reintroduces the O(k log k) per window cost, so the count-array approach is the standard efficient solution."),
    ],
    mistakes=[
        "Forgetting the early return when len(p) > len(s), risking index errors.",
        "Off-by-one when identifying which character is leaving the window (should be s[i - len(p)], not s[i - len(p) - 1] or similar).",
        "Comparing window_count to p_count using identity instead of value equality (in Python, == on lists compares values correctly, but this trips people up in other languages).",
        "Not initializing the first window's counts before starting the main sliding loop.",
    ],
    recovery=[
        "If stuck: 'Sorting each window is the naive way to check anagram equality, but I know equal counts of each letter also defines an anagram, and counts can be updated incrementally as the window slides.'",
        "If I get the leaving-character index wrong: pause and reason, 'when I'm at position i, positions i-len(p) to i-1 are strictly inside the window, so i-len(p) is what's leaving.'",
        "If the interviewer hints 'can you avoid resorting': pivot to fixed-size count arrays and incremental updates.",
        "If array comparison feels slow: mention the O(1) match-counter optimization as a follow-up improvement.",
    ],
    pattern_recognition=dict(
        triggers="'find all anagrams', 'fixed-length substring matching character composition'",
        pattern="Sliding Window (fixed size) + character count comparison",
        first_thought="Anagram equality is really count equality, and counts can be updated incrementally as a fixed-size window slides.",
        trap="Recomputing the window's character counts from scratch at every position instead of incrementally adding/removing one character.",
    ),
    memory_hook="Find All Anagrams → \"Same letter counts, sliding window, add one/remove one.\"",
    recap_key_idea="Maintain a running count array for a fixed-size window, updating by one character in and one character out per slide.",
    recap_data_structure="Two 26-length count arrays (or hash maps).",
    recap_algorithm="Fixed-size Sliding Window with incremental count updates.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="p longer than s (no valid windows).",
    talk_track=[
        ("Interviewer", "Find every starting index in s where the substring is an anagram of p."),
        ("Me", "Got it — overlapping matches should all count, and I can assume lowercase English letters only?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force would check every window of length len(p), sort it, and compare to sorted p — O(n times k log k)."),
        ("Interviewer", "How would you avoid re-sorting every window?"),
        ("Me", "I'd track character counts instead of sorting. I build a 26-length count array for p once, then slide a window of the same length across s, adding the incoming character and removing the outgoing one, and compare count arrays at each step."),
        ("Me", "Let me code that — first I initialize both count arrays for the first window, then slide one character at a time."),
        ("Me", "Tracing 'cbaebabacd' with p='abc', the window correctly flags matches at indices 0 and 6."),
        ("Me", "Edge case: if p is longer than s, there's no valid window at all, so I return an empty list right away."),
        ("Me", "Final complexity: O(n) time since each slide is O(1) with fixed-size count arrays, O(1) space."),
    ],
))
