PROBLEMS = []

PROBLEMS.append(dict(
    title="Reverse Bits", lc_num="190", difficulty="EASY", pattern="Bit Manipulation",
    relevance="Useful foundational problem",
    restate="We're given a 32-bit unsigned integer, and we need to reverse the order of its bits and return the resulting integer.",
    clarify_questions=[
        "Is the input always exactly 32 bits, zero-padded on the left if needed?",
        "Should the output also be treated as a 32-bit unsigned integer?",
        "Is there a preference for a bit-by-bit approach versus a built-in string reversal trick?",
        "Will this function be called repeatedly, which might favor a precomputation-based approach?",
    ],
    restate_say=["Just to confirm, the input is always a 32-bit unsigned integer, and I need to reverse the actual bit pattern (not just the numeric value) and return it as an integer, correct?"],
    brute_idea="Convert the integer to its 32-character binary string representation, reverse that string, and convert it back to an integer.",
    brute_say=["A simple approach is to convert the number to its 32-bit binary string, reverse that string directly, and parse it back into an integer."],
    brute_time="Converting to binary and back are both O(32), which is effectively O(1) for a fixed-width integer.",
    brute_space="O(32) for the string representation.",
    brute_complexity_say="Since we're always dealing with exactly 32 bits, this is O(1) time and space in an absolute sense, though conceptually it's O(k) for a k-bit integer.",
    bottleneck="There isn't a deeper algorithmic bottleneck to eliminate for a fixed 32-bit width; the interesting part is understanding both the straightforward string-based method and the more 'bit manipulation native' iterative method, since interviewers often want to see manipulation with shifts and masks directly.",
    bottleneck_say="This one doesn't really have an asymptotic bottleneck to fix, given the fixed 32-bit size; the goal is showing comfort with direct bit manipulation (shifts and masks) as an alternative to string conversion.",
    optimization_explain="I use direct Bit Manipulation with shifts. I initialize a result to 0, and for each of the 32 bit positions, I extract the least significant bit of the input (using n & 1), shift the result left by 1 to make room, and OR in that extracted bit. Then I shift the input right by 1 to expose the next bit. Repeating this 32 times naturally builds up the reversed bit pattern, since each bit extracted from the low end of the input gets placed into a progressively higher position of the result.",
    key_insight="Building the result by repeatedly shifting it left and OR-ing in the next bit from the input's low end naturally reverses bit order, since the FIRST bit extracted (originally the least significant) ends up shifted all the way to the most significant position by the end of the 32 iterations.",
    optimization_say=[
        "I'll process the number 32 bits at a time, since it's a fixed-width integer.",
        "At each step, I extract the current least significant bit of the input, shift my result left to make room, and OR in that extracted bit.",
        "I then shift the input right to expose the next bit, and repeat for all 32 positions.",
    ],
    code_blocks=[
        dict(code="def reverse_bits(n):\n    result = 0\n    for i in range(32):\n        bit = n & 1\n        result = (result << 1) | bit\n        n = n >> 1\n\n    return result",
             say="I start result at 0. For each of the 32 iterations, I extract the current lowest bit of n using a bitwise AND with 1, shift result left by one position to make room for this new bit, OR it into that new open slot, and then shift n right by one to expose the next bit for the following iteration.",
             why="Because each extracted bit gets shifted progressively further left in the result as more iterations happen, the very first bit extracted (originally n's least significant bit) ends up in the most significant position of the final result, and vice versa — exactly reversing the bit order."),
    ],
    dry_run="n = 0b00000010100101000001111010011100 (a specific 32-bit example, simplified conceptually). Let's use a smaller conceptual trace with 4 bits for clarity: n=0b1011 (conceptually, ignoring the full 32-bit requirement for illustration). i=0: bit=1011&1=1. result=(0<<1)|1=1. n=1011>>1=101. i=1: bit=101&1=1. result=(1<<1)|1=3 (0b11). n=101>>1=10. i=2: bit=10&1=0. result=(3<<1)|0=6 (0b110). n=10>>1=1. i=3: bit=1&1=1. result=(6<<1)|1=13 (0b1101). Final result=0b1101, which is indeed 0b1011 reversed. The same exact logic applies across all 32 iterations for the real problem.",
    dry_run_say="Using a simplified 4-bit example, n=0b1011: processing bit by bit, the result builds up to 0b1101, which is exactly 1011 reversed — the same mechanism scales directly to the full 32-bit case.",
    edge_case="An input of all zeros, n=0. Every iteration extracts bit=0, and result stays 0 throughout all 32 iterations, correctly returning 0, since the reverse of all zeros is still all zeros.",
    edge_case_say="Let me check an input of all zeros — every extracted bit is 0, so the result correctly stays 0 throughout, since reversing an all-zero bit pattern is still all zeros.",
    other_edge_cases=[
        "An input of all ones (should also return all ones, unchanged)",
        "An input with a single set bit at the very front (becomes a single set bit at the very back)",
        "An input with a single set bit at the very back (becomes a single set bit at the very front)",
        "A palindromic bit pattern (should return the exact same value)",
    ],
    final_complexity_rows=[["Optimized", "O(1)", "O(1)"]],
    final_complexity_say="Since we always process exactly 32 bits regardless of the input's value, this is O(1) time and space in absolute terms (or O(k) for a general k-bit integer if generalized beyond a fixed width).",
    pushback=[
        ("Why not just use the string-reversal approach?", "The string approach works and is simple to write, but this bit-shifting approach demonstrates direct comfort with bitwise operations, which many interviewers specifically want to see for a 'bit manipulation' tagged problem, and it also avoids the overhead of string conversion in performance-sensitive contexts."),
        ("What if this function were called many times on different inputs?", "The direct bit-shifting or string-reversal approaches are already O(1) per call given the fixed width, so there's limited room for further amortized optimization unless we specifically cache results for repeated identical inputs, which is unlikely to be useful in practice."),
        ("Can you do this with fewer than 32 iterations?", "Yes, there's a well-known 'divide and conquer' bit-reversal trick that swaps bits in groups of decreasing size (first swap 16-bit halves, then 8-bit chunks within those, then 4, 2, and finally 1), completing the reversal in only 5 steps using precomputed bit masks, which is a classic low-level optimization technique."),
        ("How would you handle a different bit width, like 16 or 64 bits?", "I'd simply change the loop bound from 32 to the appropriate bit width; the core logic (extract, shift result left, OR in, shift input right) generalizes directly to any fixed width."),
    ],
    mistakes=[
        "Off-by-one in the loop count, using something other than exactly 32 iterations for a 32-bit integer.",
        "Forgetting to shift the input right after extracting each bit, causing the same bit to be read repeatedly.",
        "Confusing the order of shifting result left versus OR-ing in the new bit (should shift first, then OR).",
        "Not handling potential sign issues in languages with signed integer types (less of a concern in Python, but worth mentioning for languages like Java).",
    ],
    recovery=[
        "If stuck: 'I know I need to process all 32 bits somehow. Let me think about extracting one bit at a time from one end and building up the result by placing it at the OTHER end.'",
        "If my dry run doesn't reverse correctly: check the order of operations — shift result left, THEN OR in the new bit, not the other way around.",
        "If the interviewer hints 'can you do it without converting to a string': pivot directly to the shift-and-mask bitwise approach.",
        "If asked about a faster method: mention the divide-and-conquer bit-swapping technique as a more advanced optimization.",
    ],
    pattern_recognition=dict(
        triggers="'reverse the bits of an integer', 'bit manipulation with fixed width'",
        pattern="Bit Manipulation (shift and mask, bit by bit)",
        first_thought="Extract bits from one end of the input one at a time, and build the result by shifting them into the opposite end.",
        trap="Getting the order of 'shift result left' vs 'OR in new bit' backwards, or forgetting to shift the input to expose the next bit.",
    ),
    memory_hook="Reverse Bits → \"Peel one bit off the front, tuck it onto the back of the result.\"",
    recap_key_idea="For 32 iterations, extract the lowest bit of n, shift result left and OR it in, then shift n right.",
    recap_data_structure="No extra data structure — just integer shifts and masks.",
    recap_algorithm="Bit Manipulation (iterative shift-and-mask).",
    recap_time="O(1) [O(k) general]", recap_space="O(1)", recap_edge_case="All-zero or all-one bit patterns.",
    talk_track=[
        ("Interviewer", "Reverse the bits of this 32-bit unsigned integer."),
        ("Me", "Got it — always exactly 32 bits, and I return the reversed bit pattern as an integer, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "One simple approach is converting to a 32-character binary string, reversing that string, and parsing it back — that works and is O(1) given the fixed width."),
        ("Me", "I can also do this with direct bit manipulation, which is often what's specifically being tested here: extract the lowest bit of the input, shift my result left to make room, OR that bit in, then shift the input right to expose the next bit, repeating 32 times."),
        ("Me", "Let me code that with a simple loop."),
        ("Me", "Tracing a small 4-bit example, 1011: after processing each bit, the result builds up to 1101, which is exactly the reverse — the same logic scales directly to the full 32-bit case."),
        ("Me", "Edge case: an all-zero input stays all zeros throughout, which is correctly unchanged after reversal."),
        ("Me", "Final complexity: O(1) since we always process exactly 32 bits regardless of the input value."),
        ("Interviewer", "Can you do it faster?"),
        ("Me", "There's a divide-and-conquer bit-swapping trick that reverses in just 5 steps by swapping progressively smaller chunks, using precomputed masks, if constant-factor speed really mattered."),
    ],
))

PROBLEMS.append(dict(
    title="Number of 1 Bits", lc_num="191", difficulty="EASY", pattern="Bit Manipulation",
    relevance="Useful foundational problem",
    restate="We're given an unsigned integer, and we need to count how many bits in its binary representation are set to 1 (this is often called the 'Hamming weight').",
    clarify_questions=[
        "Is the input always treated as a 32-bit unsigned integer, or could it be an arbitrary-size integer in Python?",
        "Is there a preference for using built-in functions versus manual bit manipulation?",
        "Will this be called many times, favoring a precomputed lookup approach?",
        "Should negative numbers be handled, or is the input guaranteed non-negative (unsigned)?",
    ],
    restate_say=["Just to confirm, the input is a non-negative (unsigned) integer, and I need to count how many of its bits are 1, correct? Should I assume a specific bit width like 32 bits?"],
    brute_idea="Check every one of the 32 bit positions individually: for each position, shift the number right by that many bits and check if the lowest bit is 1, incrementing a counter each time.",
    brute_say=["The direct approach checks all 32 possible bit positions one at a time, testing whether each one is set, and counts how many are."],
    brute_time="This always takes exactly 32 steps, so O(32), effectively O(1) for a fixed-width integer, or O(k) for a general k-bit integer.",
    brute_space="O(1) for the counter.",
    brute_complexity_say="This is O(1) time in an absolute sense since we always check exactly 32 positions, but there's a neater trick that can skip over runs of zero bits entirely.",
    bottleneck="I'm checking every single bit position even when many of them might be 0, when there's a bit trick that can jump directly from one set bit to the next, skipping any runs of zeros in between entirely.",
    bottleneck_say="The straightforward version checks all 32 positions regardless of how many are actually set; there's a classic trick (Brian Kernighan's algorithm) that only does as many steps as there are actual 1 bits, which can be meaningfully faster for numbers with few set bits.",
    optimization_explain="I use Brian Kernighan's Algorithm. The key trick is that n & (n - 1) always clears the LOWEST set bit of n (turns the rightmost 1 into a 0), without affecting any other bits. So I repeatedly apply n = n & (n - 1) and count how many times I do this until n becomes 0 — that count is exactly the number of 1 bits originally in n.",
    key_insight="Subtracting 1 from a number flips all the bits from the lowest set bit down to the end (turning that lowest 1 into a 0 and all the 0's below it into 1's), so ANDing the original number with (n - 1) exactly cancels out and clears just that lowest set bit, leaving every other bit unchanged — letting us count set bits in exactly as many steps as there are 1's, not always 32 steps.",
    optimization_say=[
        "I'll use the trick that n AND (n minus 1) always clears the lowest set bit of n, leaving everything else unchanged.",
        "I'll repeatedly apply that operation and count how many times it takes until n becomes 0.",
        "That count is exactly the number of 1 bits, and this only takes as many steps as there are actual set bits, not a fixed 32 steps.",
    ],
    code_blocks=[
        dict(code="def hamming_weight(n):\n    count = 0\n    while n != 0:\n        n = n & (n - 1)\n        count += 1\n\n    return count",
             say="I start a counter at 0. As long as n isn't already 0, I apply the n & (n-1) trick to clear its lowest set bit, and increment my counter once per clear. Once n becomes 0, every set bit has been cleared and counted.",
             why="Each iteration removes exactly one set bit (the lowest one), so the number of iterations needed to reduce n all the way to 0 is precisely the count of set bits it originally had — no wasted iterations on positions that are already 0."),
    ],
    dry_run="n = 11 (binary 1011). count=0. n=1011, n-1=1010. n&(n-1) = 1011 & 1010 = 1010. count=1. n=1010(binary, =10 decimal), n-1=1001. n&(n-1)=1010&1001=1000. count=2. n=1000(=8), n-1=0111. n&(n-1)=1000&0111=0000. count=3. n=0, loop ends. Final count=3, matching that binary 1011 has three 1 bits.",
    dry_run_say="Tracing n=11 (binary 1011): each application of the n & (n-1) trick clears exactly one set bit, taking exactly 3 iterations to reach 0, correctly matching that 1011 has three 1 bits.",
    edge_case="n = 0. The while loop condition 'n != 0' is immediately false, so the loop body never executes, and count remains 0, correctly reflecting that 0 has no set bits at all.",
    edge_case_say="Let me check n=0 — the loop condition is false right away, so we correctly return a count of 0, since there are no set bits in an all-zero number.",
    other_edge_cases=[
        "n with only a single set bit, like a power of 2 (should return 1)",
        "n being all 1 bits for a given width (e.g., 0xFFFFFFFF for 32 bits, should return 32)",
        "n = 1 (the smallest number with exactly one set bit)",
        "A number with alternating bit pattern, like 0b10101010",
    ],
    final_complexity_rows=[["Optimized", "O(k)", "O(1)"]],
    final_complexity_say="This is O(k) time, where k is the number of set bits (not the total bit width), since each iteration clears exactly one set bit, and O(1) space since only a counter is used; this can be meaningfully faster than a fixed 32-iteration approach when there are few set bits.",
    pushback=[
        ("Why does n & (n-1) clear exactly the lowest set bit?", "Subtracting 1 from n flips every bit starting from the lowest set bit (turning it into 0) down through all the trailing 0's below it (turning them into 1's); ANDing this modified value with the original n keeps every higher bit unchanged (since those didn't change), but the lowest set bit becomes 0 AND 1 = 0, and everything below it becomes 1 AND 0 = 0, so only that lowest set bit gets cleared."),
        ("Can you also just check all 32 bit positions directly?", "Yes, that's the straightforward alternative: for each of 32 positions, check (n >> i) & 1, which is always O(32) regardless of how many bits are actually set; Brian Kernighan's trick is an improvement specifically when the number of set bits is small relative to the total width."),
        ("Does Python have a built-in for this?", "Yes, in modern Python, bin(n).count('1') or the integer method n.bit_count() (available in Python 3.10+) directly gives this count; mentioning the built-in shows practical awareness, though implementing the bit trick demonstrates understanding of the underlying technique, which is often what's being tested."),
        ("Can you optimize this further?", "For very performance-critical code, a lookup-table approach (precomputing the bit count for every possible byte value, then combining 4 byte-lookups for a 32-bit integer) can get this down to O(1) with a small constant, trading memory for speed."),
    ],
    mistakes=[
        "Using the straightforward 32-iteration check-every-bit approach when the interviewer specifically wants to see the more clever Kernighan's trick.",
        "Forgetting the loop condition should be 'while n != 0', not a fixed range of 32 iterations, when using the bit-clearing trick.",
        "Misremembering the trick as n & (n+1) or some other variant instead of n & (n-1).",
        "Assuming this handles negative numbers directly without considering how negative numbers are represented in two's complement in a given language.",
    ],
    recovery=[
        "If stuck: 'Checking all 32 positions always works, but I recall there's a trick where n AND (n minus 1) clears the lowest set bit — let me think through why that's true and use it.'",
        "If unsure why the trick works: reason through a small binary example by hand, like n=1100, and verify that n-1=1011, and n&(n-1)=1000, clearing exactly the lowest set bit.",
        "If the interviewer hints 'can you do better than checking every bit': confirm and describe Brian Kernighan's algorithm.",
        "If asked about built-ins: mention bin(n).count('1') or n.bit_count() as a practical shortcut, while still being able to implement the manual approach.",
    ],
    pattern_recognition=dict(
        triggers="'count set bits', 'Hamming weight', 'number of 1 bits'",
        pattern="Bit Manipulation (Brian Kernighan's algorithm)",
        first_thought="n & (n-1) clears the lowest set bit — repeat until n is 0, counting iterations, rather than checking every fixed bit position.",
        trap="Defaulting to a fixed 32-iteration check-every-position approach when a more efficient bit trick is expected.",
    ),
    memory_hook="Number of 1 Bits → \"n AND (n-1) erases the lowest 1 — count how many erasures until zero.\"",
    recap_key_idea="Repeatedly apply n = n & (n-1), counting iterations until n becomes 0.",
    recap_data_structure="No extra data structure — just a counter.",
    recap_algorithm="Brian Kernighan's Algorithm.",
    recap_time="O(k) [k = number of set bits]", recap_space="O(1)", recap_edge_case="n = 0 (should return 0 immediately).",
    talk_track=[
        ("Interviewer", "Count the number of 1 bits in this integer's binary representation."),
        ("Me", "Got it — the input is non-negative, and I should count set bits regardless of a specific fixed width, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A direct approach checks all 32 bit positions individually, which is O(1) given a fixed width, but there's a neater trick that only takes as many steps as there are actual set bits."),
        ("Me", "The trick is that n AND (n minus 1) always clears the lowest set bit of n, leaving everything else unchanged. So I repeatedly apply that and count how many times it takes until n becomes 0."),
        ("Me", "Let me code that — a simple while loop."),
        ("Me", "Tracing n=11, binary 1011: each application clears one set bit, taking exactly 3 iterations to reach 0, matching that 1011 has three 1 bits."),
        ("Me", "Edge case: n=0 immediately satisfies the loop's exit condition, correctly returning a count of 0."),
        ("Me", "Final complexity: O(k) time, where k is the number of set bits, which can be meaningfully faster than checking all 32 positions when few bits are set, and O(1) space."),
    ],
))

PROBLEMS.append(dict(
    title="Pascal's Triangle", lc_num="118", difficulty="EASY", pattern="Dynamic Programming (Simple Row Building)",
    relevance="Useful foundational problem",
    restate="We're given an integer numRows, and we need to generate the first numRows rows of Pascal's Triangle, where each number is the sum of the two numbers directly above it in the previous row.",
    clarify_questions=[
        "Are the first and last elements of every row always 1?",
        "Is numRows guaranteed to be a positive integer?",
        "Should the output be a list of lists, one per row?",
        "Is there a size constraint that would make this impractical to build directly?",
    ],
    restate_say=["Just to confirm, every row starts and ends with 1, and each middle element is the sum of the two elements above it in the previous row, and I return a list of lists, one per row, correct?"],
    brute_idea="There isn't really a distinct 'brute force' here beyond the direct row-by-row construction, but one could imagine computing each entry using the binomial coefficient formula (n choose k) independently for every position, without building rows incrementally.",
    brute_say=["An alternative to building rows incrementally would be computing each entry directly using the binomial coefficient formula, n choose k, for every position independently."],
    brute_time="Computing each binomial coefficient directly (using factorials) costs O(row_index) per entry, and there are O(numRows²) entries total, giving O(numRows³) if done very naively with repeated factorial computations.",
    brute_space="O(numRows²) for storing the full triangle.",
    brute_complexity_say="Computing each entry independently via factorials is more expensive than necessary, potentially O(numRows cubed) if done naively, since it recomputes overlapping factorial calculations repeatedly.",
    bottleneck="I don't need to compute each entry from scratch using a formula; each row can be built directly and cheaply from the previous row, since Pascal's Triangle's defining property IS that relationship.",
    bottleneck_say="The bottleneck in the factorial-based approach is recomputing large factorials repeatedly, when each row can instead be built directly and cheaply from the row just before it.",
    optimization_explain="I build the triangle row by row using simple Dynamic Programming. Each row starts and ends with 1. Every middle element in a new row is the sum of the two elements directly above it (at the same index and the previous index) in the row before it. I build up one row at a time, using the previously completed row to construct each new one.",
    key_insight="Pascal's Triangle is defined recursively (each entry is the sum of the two above it), so building it row by row, reusing the previous row directly, is both the most natural and most efficient approach — no need for factorials or binomial coefficient formulas at all.",
    optimization_say=[
        "I'll build the triangle one row at a time, starting with the trivial first row [1].",
        "For each new row, I'll start and end with 1, and for every middle position, sum the two adjacent elements from the previous row.",
        "I'll repeat this until I've built all of the requested numRows rows.",
    ],
    code_blocks=[
        dict(code="def generate(num_rows):\n    triangle = [[1]]",
             say="I initialize the triangle with just its very first row, which is always simply [1].",
             why="Starting with this known, trivial base case gives me a previous row to build from when constructing the second row."),
        dict(code="    for row_num in range(1, num_rows):\n        previous_row = triangle[-1]\n        new_row = [1]",
             say="For each additional row I need to build, I grab the most recently completed row, and start the new row with a leading 1.",
             why="Every row in Pascal's Triangle always starts with 1, since there's nothing to its upper-left to sum with."),
        dict(code="        for i in range(1, len(previous_row)):\n            new_row.append(previous_row[i - 1] + previous_row[i])\n        new_row.append(1)\n        triangle.append(new_row)\n\n    return triangle",
             say="For each middle position, I sum the two adjacent values from the previous row. After filling in all the middle values, I append a trailing 1 to complete the row, then add this new row to the triangle.",
             why="Summing previous_row[i-1] and previous_row[i] directly implements the defining rule of Pascal's Triangle: each interior value is the sum of the two values diagonally above it."),
    ],
    dry_run="numRows=5. triangle=[[1]]. row_num=1: previous_row=[1]. new_row=[1]. Loop range(1,1) is empty (no middle elements). append 1 -> new_row=[1,1]. triangle=[[1],[1,1]]. row_num=2: previous_row=[1,1]. new_row=[1]. i=1: previous_row[0]+previous_row[1]=1+1=2, append -> [1,2]. append 1 -> [1,2,1]. triangle=[[1],[1,1],[1,2,1]]. row_num=3: previous_row=[1,2,1]. new_row=[1]. i=1: 1+2=3, append. i=2: 2+1=3, append. new_row=[1,3,3], append 1 -> [1,3,3,1]. row_num=4: previous_row=[1,3,3,1]. new_row=[1]. i=1:1+3=4. i=2:3+3=6. i=3:3+1=4. new_row=[1,4,6,4], append1 -> [1,4,6,4,1]. Final triangle: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]] — exactly the first 5 rows of Pascal's Triangle.",
    dry_run_say="Tracing numRows=5: building row by row from [1], each new row correctly sums adjacent pairs from the previous row, producing the exact expected first 5 rows of Pascal's Triangle.",
    edge_case="numRows = 1. The loop 'range(1, 1)' never executes, so the triangle stays as its initial value, [[1]], which is correctly just the single first row.",
    edge_case_say="Let me check numRows=1 — the loop to build additional rows never runs, so the triangle correctly stays as just the single row [[1]].",
    other_edge_cases=[
        "numRows = 2 (should produce [[1],[1,1]])",
        "A larger numRows verifying the symmetric structure of each row",
        "Confirming the outermost values in every row are always exactly 1",
        "numRows = 0 (edge case depending on constraints, likely returns an empty list if allowed)",
    ],
    final_complexity_rows=[["Optimized", "O(numRows²)", "O(numRows²)"]],
    final_complexity_say="This is O(numRows squared) time and space, since the total number of entries across all rows of Pascal's Triangle up to numRows is proportional to numRows squared, and each entry is computed in O(1) from the previous row.",
    pushback=[
        ("Why not compute each entry directly with the binomial coefficient formula?", "That would work too (entry at row r, position k is 'r choose k'), but computing factorials directly is more work per entry and doesn't reuse previously computed values the way building row by row does, making the incremental approach simpler and just as efficient overall."),
        ("Can you reduce space by not storing the whole triangle?", "If only the LAST row were needed (not all rows), I could maintain just a single rolling row and update it in place, working from right to left to avoid overwriting values I still need; but since the problem asks for ALL rows as output, storing the full triangle is necessary regardless."),
        ("Why does every row start and end with 1?", "Because the elements at the very edges of each row have nothing above and to one side of them in the triangle (conceptually, they're bordered by 'invisible zeros'), so summing an existing value with 0 just gives back that value, which is always 1 at the edges by the triangle's construction."),
        ("Can you optimize this further?", "No, O(numRows squared) is optimal since that's exactly the total number of values that must be output across all the rows."),
    ],
    mistakes=[
        "Off-by-one in the inner loop range, either missing the first or last middle element.",
        "Forgetting the leading or trailing 1 on a new row.",
        "Not properly referencing the PREVIOUS row when building sums, accidentally using values from the current, still-incomplete row.",
        "Mishandling the numRows=1 case if the initial triangle isn't seeded correctly with [[1]].",
    ],
    recovery=[
        "If stuck: 'Each row can be built directly from the one before it, following the sum-of-two-above rule — let me build the triangle row by row rather than computing entries independently.'",
        "If a row comes out with a wrong length or values: verify with a small dry run, comparing against the known correct triangle for small numRows.",
        "If the interviewer hints 'do you need factorials for this': confirm that building incrementally avoids that complexity entirely.",
        "If confused about indices: carefully trace the inner loop range with a concrete previous_row example to make sure boundaries are correct.",
    ],
    pattern_recognition=dict(
        triggers="'Pascal's Triangle', 'each value is the sum of the two above it'",
        pattern="Simple Dynamic Programming (build each row from the previous row)",
        first_thought="This is inherently defined recursively, row by row — build directly from the previous row rather than using a closed-form formula.",
        trap="Off-by-one errors in the inner loop bounds, or forgetting the leading/trailing 1 on each new row.",
    ),
    memory_hook="Pascal's Triangle → \"Each new row: start with 1, sum adjacent pairs above, end with 1.\"",
    recap_key_idea="Build each row from the previous one: start/end with 1, middle values are sums of adjacent pairs above.",
    recap_data_structure="A list of lists, growing one row at a time.",
    recap_algorithm="Simple Dynamic Programming (row-by-row construction).",
    recap_time="O(numRows²)", recap_space="O(numRows²)", recap_edge_case="numRows = 1 (just the single row [1]).",
    talk_track=[
        ("Interviewer", "Generate the first numRows rows of Pascal's Triangle."),
        ("Me", "Got it — every row starts and ends with 1, and middle values are sums of the two values above them in the previous row, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "I could compute each entry directly with the binomial coefficient formula, but that recomputes factorials unnecessarily; building each row directly from the previous one is simpler and just as efficient."),
        ("Me", "I'll start with the trivial first row [1], and for each additional row, start with 1, sum adjacent pairs from the previous row for the middle values, and end with 1."),
        ("Me", "Let me code that with a loop building one row at a time."),
        ("Me", "Tracing numRows=5: the rows build up correctly to [1], [1,1], [1,2,1], [1,3,3,1], [1,4,6,4,1], exactly matching Pascal's Triangle."),
        ("Me", "Edge case: numRows=1 just returns the single row [[1]], since the row-building loop never runs."),
        ("Me", "Final complexity: O(numRows squared) time and space, since that's exactly how many total values need to be output."),
    ],
))

PROBLEMS.append(dict(
    title="Longest Common Prefix", lc_num="14", difficulty="EASY", pattern="Horizontal/Vertical Scanning",
    relevance="Useful foundational problem",
    restate="We're given an array of strings, and we need to find the longest common prefix shared by all of them, returning an empty string if there's no common prefix at all.",
    clarify_questions=[
        "Can the array of strings be empty?",
        "Can any individual string in the array be empty?",
        "Should comparison be case-sensitive?",
        "Is there a size constraint that would favor one particular scanning strategy?",
    ],
    restate_say=["Just to confirm, I need the longest prefix shared by EVERY string in the array, returning an empty string if there's no common prefix, or if any string itself is empty, correct?"],
    brute_idea="Compare every pair of strings character by character to find their common prefix length, then take the minimum common prefix length across all pairs.",
    brute_say=["One approach is to compare every pair of strings to find their pairwise common prefix, then take the shortest one across all pairs as the overall answer."],
    brute_time="Comparing all pairs is O(n²) pairs, each taking O(m) to compare (m being average string length), giving O(n² * m).",
    brute_space="O(1) extra space beyond the input.",
    brute_complexity_say="This pairwise comparison approach is O(n squared times m), which is more comparisons than necessary, since we don't actually need every pairwise relationship, just a single shared answer across ALL strings at once.",
    bottleneck="I'm comparing pairs of strings redundantly, when I really just need to check, character position by character position, whether ALL strings agree at that position simultaneously.",
    bottleneck_say="The bottleneck is doing pairwise comparisons, when I can instead check all strings together at once, position by position, stopping the moment any disagreement is found.",
    optimization_explain="I use Vertical Scanning (character position by character position, across all strings simultaneously). I take the first string as a reference. For each character position (starting from 0), I check if that position exists in every other string and whether the character there matches the reference string's character at that position. The moment either check fails, the common prefix ends exactly there, and I return everything up to (but not including) that position.",
    key_insight="Instead of comparing whole strings to each other one pair at a time, I can compare a single character POSITION across every string at once, and stop immediately at the very first position where any string disagrees or runs out of characters — that position is exactly the length of the longest common prefix.",
    optimization_say=[
        "I'll use the first string in the array as a reference for what the prefix might look like.",
        "For each character position in that reference string, I'll check if every OTHER string has a matching character there.",
        "The moment any string disagrees or is too short, I stop and return everything matched so far.",
    ],
    code_blocks=[
        dict(code="def longest_common_prefix(strs):\n    if not strs:\n        return ''\n\n    for i in range(len(strs[0])):\n        char = strs[0][i]\n        for other in strs[1:]:\n            if i >= len(other) or other[i] != char:\n                return strs[0][:i]\n\n    return strs[0]",
             say="I handle the empty-array case first. Then, for each character position in the FIRST string, I check every OTHER string: if that string is too short to have a character at this position, or its character doesn't match, I immediately return everything matched so far (a slice of the first string up to position i). If I get through every position of the first string without any mismatch, the entire first string itself is the common prefix (meaning it's a prefix of, or equal to, every other string).",
             why="Checking position by position across ALL strings at once, and returning the instant any mismatch is found, avoids ever doing more comparisons than strictly necessary to find where agreement breaks down."),
    ],
    dry_run="strs = ['flower','flow','flight']. i=0: char='f'. Check 'flow'[0]='f' match. Check 'flight'[0]='f' match. i=1: char='l'. 'flow'[1]='l' match. 'flight'[1]='l' match. i=2: char='o'. 'flow'[2]='o' match. 'flight'[2]='i' — mismatch! Return strs[0][:2] = 'fl'. Final answer: 'fl', the correct longest common prefix.",
    dry_run_say="Tracing ['flower','flow','flight']: positions 0 and 1 ('f' and 'l') match across all three strings, but position 2 mismatches between 'flow' ('o') and 'flight' ('i'), so we correctly stop and return 'fl'.",
    edge_case="No common prefix at all, e.g. strs=['dog','racecar','car']. i=0: char='d'. Check 'racecar'[0]='r' — immediate mismatch. Return strs[0][:0] = '' (empty string), correctly indicating no common prefix exists.",
    edge_case_say="Let me check a case with no common prefix at all, like ['dog','racecar','car'] — the very first character position already mismatches, so we correctly return an empty string right away.",
    other_edge_cases=[
        "An array containing just a single string (the whole string is trivially the common prefix)",
        "An array where one of the strings is empty (result should be empty, since nothing can be common with an empty string except an empty prefix)",
        "All strings being identical (the whole string is the common prefix)",
        "An empty array of strings (should return an empty string, per the initial guard clause)",
    ],
    final_complexity_rows=[["Optimized", "O(n * m)", "O(1)"]],
    final_complexity_say="This is O(n times m) time in the worst case, where n is the number of strings and m is the length of the shortest string (or the common prefix length), since we check every string at every relevant position, and O(1) extra space beyond the output.",
    pushback=[
        ("Why use the first string as the reference instead of the shortest one?", "Using the first string works correctly regardless, since the moment we hit a string shorter than the current position, that comparison itself fails and we return early; using the shortest string as reference is a common further optimization to avoid unnecessary iterations, but isn't strictly required for correctness."),
        ("Can you solve this with a different scanning order, like Horizontal Scanning?", "Yes — horizontal scanning compares two strings' common prefix at a time (start with the first string as the running prefix, then repeatedly shrink it based on comparing against each subsequent string), which is also O(n*m) but processes strings sequentially rather than position by position across all simultaneously."),
        ("Can you solve this with a Divide and Conquer approach?", "Yes, split the array into two halves, recursively find the common prefix of each half, then find the common prefix of those two results; this is also O(n*m) in the worst case but can be more cache-friendly and parallelizable in some contexts."),
        ("Can you optimize this using a Trie?", "Yes, inserting all strings into a Trie and finding the longest path with only a single child at each node down to the first branching point (or end of a string) gives the common prefix; this is more useful if this operation needs to be repeated multiple times against an evolving set of strings."),
    ],
    mistakes=[
        "Forgetting the empty-array guard clause, causing an index error when accessing strs[0].",
        "Forgetting to check 'i >= len(other)' before indexing into other[i], causing an index error for shorter strings.",
        "Comparing only pairs of strings pairwise instead of checking all strings together at each position.",
        "Not handling the case where the first string itself IS the common prefix (i.e., the loop completes without ever returning early).",
    ],
    recovery=[
        "If stuck: 'Instead of comparing whole strings pairwise, let me check one character POSITION at a time, across all the strings simultaneously — stopping the moment any string disagrees.'",
        "If I get an index error: make sure I check the current string's length before indexing into it at the current position.",
        "If the interviewer hints 'can you avoid pairwise comparisons': confirm and describe vertical (position-by-position) scanning across all strings.",
        "If asked about Tries: describe the general idea (shared prefixes correspond to a single path with no branching) even if not implementing it directly.",
    ],
    pattern_recognition=dict(
        triggers="'longest common prefix among multiple strings'",
        pattern="Vertical Scanning (character position by character position across all strings)",
        first_thought="Compare a single character position across ALL strings simultaneously, stopping at the first disagreement, rather than pairwise string comparisons.",
        trap="Forgetting to bounds-check a string's length before indexing into it at the current position.",
    ),
    memory_hook="Longest Common Prefix → \"Check one position at a time across every string — stop at first disagreement.\"",
    recap_key_idea="For each position in the first string, verify every other string agrees there; stop and return at the first mismatch or short string.",
    recap_data_structure="No extra data structure — direct index comparisons.",
    recap_algorithm="Vertical Scanning.",
    recap_time="O(n * m)", recap_space="O(1)", recap_edge_case="No common prefix at all (return empty string immediately).",
    talk_track=[
        ("Interviewer", "Find the longest common prefix among these strings."),
        ("Me", "Got it — return an empty string if there's no common prefix, or if the array is empty, or if any string itself is empty, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A pairwise comparison approach would compare every pair of strings, which is more work than necessary, O(n squared times m)."),
        ("Me", "Instead, I'll check one character position at a time, but across ALL strings simultaneously, using the first string as a reference. The moment any string disagrees at a position, or is too short, I stop and return everything matched so far."),
        ("Me", "Let me code that with a loop over positions in the first string, and an inner check against every other string."),
        ("Me", "Tracing ['flower','flow','flight']: positions 0 and 1 match everywhere, but position 2 mismatches between 'flow' and 'flight', so I correctly return 'fl'."),
        ("Me", "Edge case: no common prefix at all, like ['dog','racecar','car'] — the very first position already mismatches, correctly returning an empty string."),
        ("Me", "Final complexity: O(n times m) time, where n is the number of strings and m is the common prefix length or shortest string length, and O(1) extra space."),
    ],
))

PROBLEMS.append(dict(
    title="Integer to Roman", lc_num="12", difficulty="MEDIUM", pattern="Greedy",
    relevance="Common interview pattern",
    restate="We're given an integer, and we need to convert it into its Roman numeral representation, following the standard subtractive notation rules (like IV for 4, IX for 9).",
    clarify_questions=[
        "Is the input guaranteed to be within the standard Roman numeral range, typically 1 to 3999?",
        "Should I handle the subtractive cases (IV, IX, XL, XC, CD, CM) explicitly, or derive them some other way?",
        "Is the input always a positive integer, with no need to handle 0 or negative numbers?",
        "Should the output use uppercase Roman numeral characters?",
    ],
    restate_say=["Just to confirm, the input is a positive integer within the standard range (typically up to 3999), and I need to include the standard subtractive notation like IV and IX, correct?"],
    brute_idea="Handle each digit place (thousands, hundreds, tens, ones) separately with a big set of if/elif conditions for every possible digit value (0-9) at each place, mapping directly to the right combination of Roman numeral symbols.",
    brute_say=["A very direct but repetitive approach would write out explicit if/elif branches for every possible digit (0 through 9) at each place value (ones, tens, hundreds, thousands), each producing the correct Roman numeral symbols."],
    brute_time="O(1) since there's a fixed, bounded number of digit places and values to check for any valid input.",
    brute_space="O(1) for the fixed set of hardcoded mappings.",
    brute_complexity_say="This hardcoded, exhaustive-branching approach is technically O(1) since the input range is bounded, but it's extremely repetitive and error-prone to write out every single case by hand.",
    bottleneck="Writing out every single digit-value combination by hand is repetitive and easy to get wrong; there's a more elegant pattern-based approach that captures the SAME logic using an ordered list of value-symbol pairs instead of dozens of hardcoded branches.",
    bottleneck_say="The real issue with the hardcoded branching approach isn't speed, it's that it's needlessly verbose and error-prone; a greedy approach with an ordered list of values captures the exact same logic far more concisely.",
    optimization_explain="I use a Greedy approach with a precomputed, ordered list of (value, symbol) pairs, listed from largest to smallest, including the special subtractive combinations (like (900, 'CM'), (400, 'CD'), (90, 'XC'), (40, 'XL'), (9, 'IX'), (4, 'IV')) alongside the standard ones. I repeatedly find the largest value in this list that's less than or equal to the remaining number, append its corresponding symbol to the result, and subtract that value from the remaining number, continuing until the remaining number reaches 0.",
    key_insight="By explicitly including the subtractive combinations (like 900 for 'CM') as their own entries in the ordered value list, the same simple greedy 'always take the biggest bite possible' logic that works for straightforward Roman numerals ALSO correctly handles all the special subtractive cases, without needing separate special-case logic.",
    optimization_say=[
        "I'll use an ordered list of value-symbol pairs, from largest to smallest, that explicitly includes the special subtractive combinations like 900 for 'CM' and 4 for 'IV'.",
        "I'll repeatedly find the largest value in that list that still fits within what's remaining, append its symbol, and subtract it from the remaining amount.",
        "I keep doing this until the remaining amount reaches 0, which builds up the correct Roman numeral string one greedy 'largest possible bite' at a time.",
    ],
    code_blocks=[
        dict(code="def int_to_roman(num):\n    value_symbols = [\n        (1000, 'M'), (900, 'CM'), (500, 'D'), (400, 'CD'),\n        (100, 'C'), (90, 'XC'), (50, 'L'), (40, 'XL'),\n        (10, 'X'), (9, 'IX'), (5, 'V'), (4, 'IV'), (1, 'I')\n    ]\n    result = []",
             say="I define the ordered list of value-symbol pairs, from largest to smallest, explicitly including all the subtractive combinations, and set up a list to build the result string.",
             why="Including entries like (900, 'CM') directly in this ordered list, rather than handling them as a special case afterward, is what lets the simple greedy loop below correctly produce proper Roman numerals without any extra logic."),
        dict(code="    for value, symbol in value_symbols:\n        while num >= value:\n            result.append(symbol)\n            num -= value\n\n    return ''.join(result)",
             say="For each value-symbol pair, in order from largest to smallest, I keep appending that symbol and subtracting its value from num as many times as it still fits. Once I've gone through the whole list, I join everything into the final string.",
             why="Because the list is sorted largest to smallest, greedily taking the biggest value that fits at each step always produces the correct, most compact standard Roman numeral representation."),
    ],
    dry_run="num = 1994. Check (1000,'M'): 1994>=1000, append 'M', num=994. 994<1000, move on. Check (900,'CM'): 994>=900, append 'CM', num=94. 94<900, move on. Check (500,'D') through (100,'C'): 94<100, skip. Check (90,'XC'): 94>=90, append 'XC', num=4. 4<90, move on. Check (50,'L') through (10,'X'): 4<10, skip. Check (9,'IX'): 4<9, skip. Check (5,'V'): 4<5, skip. Check (4,'IV'): 4>=4, append 'IV', num=0. Check (1,'I'): 0<1, skip. Final result: 'M'+'CM'+'XC'+'IV' = 'MCMXCIV', the correct Roman numeral for 1994.",
    dry_run_say="Tracing num=1994: the greedy approach correctly builds up 'M' (1000), then 'CM' (900), then 'XC' (90), then 'IV' (4), giving 'MCMXCIV', which is indeed the correct Roman numeral representation of 1994.",
    edge_case="A number entirely made of subtractive combinations, e.g. num=444. Check (400,'CD'): 444>=400, append 'CD', num=44. Check (90,'XC') down to (50,'L'): 44<90,<50, skip those. Check (40,'XL'): 44>=40, append 'XL', num=4. Check (10,'X'),(9,'IX'),(5,'V'): 4< all of those, skip. Check (4,'IV'): 4>=4, append 'IV', num=0. Final: 'CD'+'XL'+'IV' = 'CDXLIV', correctly using three separate subtractive combinations in a row.",
    edge_case_say="Let me check a number that uses several subtractive combinations in a row, like 444 — the greedy approach correctly produces 'CDXLIV', combining CD (400), XL (40), and IV (4).",
    other_edge_cases=[
        "The smallest valid input, num=1 (just 'I')",
        "The largest typical input, num=3999 ('MMMCMXCIX')",
        "A round number like 1000 ('M') or 500 ('D') with no subtractive parts needed",
        "A number requiring several repeats of the same symbol, like 3 ('III')",
    ],
    final_complexity_rows=[["Optimized", "O(1)", "O(1)"]],
    final_complexity_say="This is O(1) time and space since the number of value-symbol pairs is fixed (13 entries) and the input is bounded within the standard Roman numeral range, so the total work done is bounded by a small constant regardless of the specific input.",
    pushback=[
        ("Why include the subtractive combinations as explicit entries rather than detecting them separately?", "Because doing so lets the same simple greedy 'take the biggest value that fits' loop handle every case uniformly, without needing separate conditional logic to detect and construct subtractive patterns — it's a clean unification of what would otherwise be two different sets of rules."),
        ("Why does the greedy approach work here specifically?", "Because Roman numeral values were specifically designed such that greedily taking the largest applicable value at each step always produces the standard, correct, and most compact representation; this isn't true for arbitrary sets of denominations in general (like some coin systems), but it happens to hold for the specific set of Roman numeral values."),
        ("Can you solve this without the explicit subtractive list, deriving it programmatically instead?", "Yes, you could detect subtractive patterns by examining digit-by-digit values (checking if a digit's place value is 4 or 9 specifically) and handling those with separate logic, but this is more complex and error-prone than simply encoding the subtractive combinations directly into the ordered list."),
        ("Can you optimize this further?", "Since the input range and the number of value-symbol pairs are both small and fixed, this is already effectively O(1); there's no meaningful further optimization needed for this specific problem's constraints."),
    ],
    mistakes=[
        "Forgetting to include the subtractive combinations (900, 400, 90, 40, 9, 4) in the value-symbol list, producing incorrect (non-standard) representations like 'VIIII' instead of 'IX'.",
        "Ordering the value-symbol list incorrectly (not strictly descending), which would break the greedy logic.",
        "Using a while loop instead of correctly checking with >= at each step, potentially skipping valid repeated symbols.",
        "Assuming Roman numerals allow more than 3 repeated symbols in standard notation, missing the subtractive rule replacing 4+ repeats.",
    ],
    recovery=[
        "If stuck: 'Handling every digit place with hardcoded branches would work but is very repetitive. Let me think about a general list of value-symbol pairs and a consistent rule for using them.'",
        "If my output doesn't match standard Roman numerals: check whether I've included the subtractive combinations (900, 400, 90, 40, 9, 4) explicitly in my value list.",
        "If the interviewer hints 'can you avoid hardcoding every digit case': confirm and describe the greedy value-list approach.",
        "If unsure about ordering: emphasize that the list must be strictly descending by value for the greedy approach to work correctly.",
    ],
    pattern_recognition=dict(
        triggers="'convert integer to Roman numeral', 'convert to a different fixed symbolic representation with special combined cases'",
        pattern="Greedy (always take the largest applicable value)",
        first_thought="Can I list all possible symbol values, including special combined ones, in descending order, and greedily take the biggest one that fits repeatedly?",
        trap="Forgetting to explicitly include the subtractive combinations in the value list, producing non-standard output.",
    ),
    memory_hook="Integer to Roman → \"Ordered list of values (including CM, CD, XC...) — always take the biggest bite that fits.\"",
    recap_key_idea="Use an ordered (descending) list of value-symbol pairs, including subtractive combinations, and greedily subtract the largest fitting value repeatedly.",
    recap_data_structure="A fixed ordered list of (value, symbol) pairs.",
    recap_algorithm="Greedy largest-value-first construction.",
    recap_time="O(1)", recap_space="O(1)", recap_edge_case="A number requiring several subtractive combinations in a row (e.g., 444 -> CDXLIV).",
    talk_track=[
        ("Interviewer", "Convert this integer to its Roman numeral representation."),
        ("Me", "Got it — the input's within the standard range, and I need to correctly handle subtractive notation like IV and IX, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A very direct approach would hardcode every digit-place combination with if/elif branches, but that's repetitive and easy to get wrong."),
        ("Me", "Instead, I'll use a greedy approach: an ordered list of value-symbol pairs from largest to smallest, explicitly including the subtractive combinations like 900 for CM and 4 for IV. I repeatedly take the biggest value that still fits, append its symbol, and subtract it, until nothing remains."),
        ("Me", "Let me code that with the value list and a simple greedy loop."),
        ("Me", "Tracing num=1994: the greedy approach correctly builds 'M', then 'CM', then 'XC', then 'IV', giving MCMXCIV."),
        ("Me", "Edge case: a number using several subtractive combinations in a row, like 444, correctly produces CDXLIV, combining CD, XL, and IV."),
        ("Me", "Final complexity: O(1) time and space, since the value list and input range are both small and fixed."),
    ],
))

PROBLEMS.append(dict(
    title="Add Binary", lc_num="67", difficulty="EASY", pattern="Two Pointers + Carry Propagation",
    relevance="Useful foundational problem",
    restate="We're given two binary strings, and we need to add them together and return the sum, also as a binary string.",
    clarify_questions=[
        "Can the two input strings be of different lengths?",
        "Are the strings guaranteed to contain only '0' and '1' characters, with no sign or other characters?",
        "Should leading zeros in the result be avoided (except for the result '0' itself)?",
        "Is there a size constraint that would make converting to integers and back impractical (very long strings)?",
    ],
    restate_say=["Just to confirm, the two binary strings can be different lengths, contain only 0s and 1s, and I return their sum as a binary string with no unnecessary leading zeros, correct?"],
    brute_idea="Convert both binary strings to integers using Python's built-in int(s, 2), add them as regular integers, then convert the sum back to a binary string using bin() and stripping the '0b' prefix.",
    brute_say=["In Python, I could convert both binary strings to integers directly, add them normally, and convert the sum back to a binary string."],
    brute_time="Converting each string is O(n), addition is effectively O(n) for big integers, and converting back is O(n), so O(n) overall.",
    brute_space="O(n) for the intermediate integer and string representations.",
    brute_complexity_say="This is O(n) time and space in Python, and it's actually a perfectly valid solution here — but the more 'manual' digit-by-digit approach is often what's expected to demonstrate understanding of binary addition directly, and would be necessary in a language without arbitrary-precision integers or built-in base conversion.",
    bottleneck="Relying on built-in conversions sidesteps demonstrating the actual mechanics of binary addition, which is likely what the interviewer wants to see, especially since real-world equivalents of this problem (like adding numbers represented as arrays/lists) don't always have such convenient built-ins available.",
    bottleneck_say="Using built-in integer conversion works in Python, but it doesn't demonstrate the underlying mechanics of binary addition with carries, which is probably the specific skill being tested here.",
    optimization_explain="I simulate binary addition directly, digit by digit, from the rightmost (least significant) end of both strings using Two Pointers, just like manual addition on paper. I maintain a carry value starting at 0. At each step, I sum the current digits from both strings (defaulting to 0 if a string has been fully consumed) plus the carry, determine the result bit (sum modulo 2) and the new carry (sum divided by 2, integer division), and prepend that result bit to my growing answer. I continue until both pointers have gone past the start of their strings and there's no carry left.",
    key_insight="Binary addition works exactly like decimal addition on paper, just with a base of 2 instead of 10: I process one digit position at a time from the right, carry over anything that overflows past 1 (since binary only has two, digits 0 and 1), and stop once both strings and any leftover carry are fully accounted for.",
    optimization_say=[
        "I'll process both strings from right to left simultaneously, using two pointers.",
        "At each step, I sum the current digits from both strings (treating a missing digit as 0) plus any carry, and compute the resulting bit (sum mod 2) and new carry (sum divided by 2).",
        "I keep going until both pointers have exhausted their strings and there's no carry left over, building the result from right to left.",
    ],
    code_blocks=[
        dict(code="def add_binary(a, b):\n    result = []\n    i, j = len(a) - 1, len(b) - 1\n    carry = 0",
             say="I set up a list to build the result (since prepending to a string repeatedly is inefficient, I'll append and reverse at the end instead), two pointers starting at the last character of each string, and a carry starting at 0.",
             why="Using a list and appending, then reversing once at the end, is more efficient than repeatedly prepending to a string, which would be O(n) per prepend in many implementations."),
        dict(code="    while i >= 0 or j >= 0 or carry:\n        digit_a = int(a[i]) if i >= 0 else 0\n        digit_b = int(b[j]) if j >= 0 else 0\n        total = digit_a + digit_b + carry",
             say="I loop as long as either string still has digits left, or there's a carry to apply. I treat a missing digit (when a pointer has gone past its string's start) as 0, and sum both current digits plus the carry.",
             why="Continuing while 'carry' is truthy correctly handles cases like '1'+'1', which needs one more digit than either input string alone provides, similar to the leftover-carry case in Add Two Numbers."),
        dict(code="        carry = total // 2\n        result.append(str(total % 2))\n        i -= 1\n        j -= 1\n\n    return ''.join(reversed(result))",
             say="I compute the new carry (total divided by 2) and the current result bit (total mod 2), append that bit to my result list, and move both pointers one position to the left. At the end, I reverse the accumulated bits (since I built them from least to most significant) and join them into the final string.",
             why="Because I processed digits from right to left but need to return the result left to right (most significant digit first), reversing the accumulated list at the very end correctly restores proper reading order."),
    ],
    dry_run="a='11', b='1'. i=1,j=0,carry=0. Step1: digit_a=a[1]='1'->1, digit_b=b[0]='1'->1, total=1+1+0=2. carry=1, append str(0)='0'. i=0,j=-1. Step2: digit_a=a[0]='1'->1, digit_b=0 (j<0), total=1+0+1=2. carry=1, append '0'. i=-1,j=-2. Step3: digit_a=0,digit_b=0,carry=1, total=0+0+1=1. carry=0, append '1'. i=-2,j=-3. Loop condition: i<0,j<0,carry=0, stop. result=['0','0','1'], reversed='100'. Final answer: '100', which is indeed 3+1=4 in binary (11 is 3, 1 is 1, sum is 4 = 100 in binary).",
    dry_run_say="Tracing a='11' (which is 3) and b='1' (which is 1): processing right to left with carries, the result builds up to '100', which is 4 in binary — correctly matching 3 plus 1.",
    edge_case="Both inputs are '1', producing a result requiring an extra digit due to carry, e.g. a='1', b='1'. i=0,j=0,carry=0. Step1: digit_a=1,digit_b=1,total=2. carry=1,append '0'. i=-1,j=-1. Step2: both digits 0, carry=1, total=1. carry=0, append '1'. Loop ends. result=['0','1'], reversed='10'. Final answer '10', which is 2 in binary, correctly matching 1+1=2.",
    edge_case_say="Let me check a='1' plus b='1', which should need an extra digit due to the carry — the trace correctly produces '10', which is 2 in binary, matching 1 plus 1.",
    other_edge_cases=[
        "Strings of very different lengths",
        "One of the strings being just '0'",
        "Both strings being all 1's (maximal carry propagation)",
        "Strings representing a sum that's an exact power of 2",
    ],
    final_complexity_rows=[["Optimized", "O(max(n, m))", "O(max(n, m))"]],
    final_complexity_say="This is O(max(n, m)) time, where n and m are the lengths of the two input strings, since we process at most that many positions (plus possibly one more for a final carry), and O(max(n, m)) space for the resulting string.",
    pushback=[
        ("Why not just use Python's built-in int(s, 2) and bin()?", "That's a perfectly valid and much shorter solution in Python specifically, since Python has arbitrary-precision integers and built-in base conversion; however, demonstrating the manual digit-by-digit simulation shows understanding of the underlying mechanics, which is often exactly what's being tested, and is necessary in languages or contexts without such convenient built-ins (or for extremely large inputs where such conversions might be impractical)."),
        ("Why build the result with a list and reverse at the end, instead of prepending to a string?", "Because prepending to a string is generally an O(n) operation each time in many language implementations (creating a new string every time), while appending to a list is O(1) amortized; reversing once at the very end is much more efficient than reversing implicitly on every single prepend."),
        ("What if the strings could contain characters other than 0 and 1?", "I'd assume, per problem constraints, that inputs are always valid binary strings; if that weren't guaranteed, I'd add validation logic before processing."),
        ("Can you optimize this further?", "No, O(max(n,m)) is optimal since we must examine every digit of the longer string at least once to correctly compute the sum."),
    ],
    mistakes=[
        "Forgetting to continue the loop when both strings are exhausted but a carry remains (missing the final carry digit).",
        "Building the result by prepending to a string repeatedly instead of appending to a list and reversing at the end.",
        "Off-by-one in the pointer initialization (should start at len-1, the LAST character, not len).",
        "Not handling strings of different lengths correctly, causing an index error when one pointer goes out of bounds.",
    ],
    recovery=[
        "If stuck: 'This is just binary addition, structurally identical to how I'd add two numbers by hand in decimal, just working in base 2 with carries.'",
        "If a final carry gets dropped: check the while loop condition includes 'or carry', not just the two pointer conditions.",
        "If the interviewer is fine with using built-ins: mention int(s,2) and bin() as a quick Python-specific solution, but be ready to also explain the manual approach.",
        "If confused about append-then-reverse: reason aloud that since I'm processing right to left but need to output left to right, reversing once at the end restores correct order more efficiently than repeated prepending.",
    ],
    pattern_recognition=dict(
        triggers="'add two binary strings', 'simulate addition digit by digit in a given base'",
        pattern="Two Pointers with Carry Propagation (manual digit-by-digit addition)",
        first_thought="Simulate manual addition directly, processing from the least significant digit (rightmost) with a carry, just like paper arithmetic but in base 2.",
        trap="Forgetting to continue the loop for one final step if a carry remains after both strings are exhausted.",
    ),
    memory_hook="Add Binary → \"Paper addition in base 2 — sum digits plus carry, right to left.\"",
    recap_key_idea="Process both strings right to left with two pointers, summing digits plus carry, and finish with a check for a leftover carry.",
    recap_data_structure="A list for building the result, reversed at the end.",
    recap_algorithm="Two Pointers with Carry Propagation.",
    recap_time="O(max(n,m))", recap_space="O(max(n,m))", recap_edge_case="A leftover carry after both strings are exhausted (e.g., '1' + '1').",
    talk_track=[
        ("Interviewer", "Add these two binary strings and return the sum as a binary string."),
        ("Me", "Got it — the strings can be different lengths, contain only 0s and 1s, and I return the sum with no unnecessary leading zeros, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "In Python, I could convert both to integers, add them, and convert back to binary — that works, but I think demonstrating the manual digit-by-digit simulation is probably what's being tested here."),
        ("Me", "I'll process both strings from right to left with two pointers, summing corresponding digits plus a carry, just like paper addition but in base 2, treating a missing digit as 0 for the shorter string."),
        ("Me", "Let me code that, building the result in a list and reversing it at the end, since prepending to a string repeatedly would be less efficient."),
        ("Me", "Tracing a='11' (3) and b='1' (1): processing with carries gives '100', which is 4 — correct."),
        ("Me", "Edge case: a='1' plus b='1', which needs an extra digit due to carry propagation — correctly gives '10', which is 2."),
        ("Me", "Final complexity: O(max of the two lengths) time and space, since we process at most that many digit positions, plus possibly one more for a final carry."),
    ],
))
