PROBLEMS = []

PROBLEMS.append(dict(
    title="Maximum Depth of Binary Tree", lc_num="104", difficulty="EASY", pattern="DFS / Recursion (Tree Traversal)",
    relevance="Useful foundational problem",
    restate="We're given the root of a binary tree, and we need to find its maximum depth, meaning the number of nodes along the longest path from the root down to the farthest leaf.",
    clarify_questions=[
        "What should the depth of an empty tree (null root) be \u2014 0?",
        "Is depth counted in nodes or edges (a single-node tree has depth 1)?",
        "Is the tree guaranteed to be a valid binary tree (no cycles)?",
        "Should I use recursion, or is an iterative solution preferred?",
    ],
    restate_say=["Just to confirm, depth is measured in number of nodes along the longest root-to-leaf path, and an empty tree has depth 0, correct?"],
    brute_idea="There isn't really a 'brute force' distinct from the natural recursive solution here, but one could think of it as: explicitly enumerate every root-to-leaf path and take the longest one's length.",
    brute_say=["I could explicitly find every root-to-leaf path and take the maximum length among them, though that's effectively the same work as the natural recursive approach, just framed differently."],
    brute_time="O(n) since every node must be visited to know all paths.",
    brute_space="O(h) for the recursion/path stack, where h is the tree's height.",
    brute_complexity_say="Even this framing is O(n) time since we must visit every node, and O(h) space for tracking the current path or recursion depth.",
    bottleneck="There isn't really a bottleneck to eliminate here \u2014 visiting every node is unavoidable since depth depends on the whole tree structure; the key is recognizing that this is naturally a self-similar (recursive) problem.",
    bottleneck_say="There's no wasted work to cut out here; the interesting part is recognizing this as a classic recursive definition rather than something that needs a separate optimization step.",
    optimization_explain="I use straightforward DFS Recursion. The maximum depth of a tree rooted at any node is 1 (for the node itself) plus the larger of the maximum depths of its left and right subtrees. The base case is a null node, which has depth 0.",
    key_insight="A tree's depth is defined in terms of its subtrees' depths, which is the definition of a recursive structure: 'depth of the whole tree' = 1 + max(depth of left subtree, depth of right subtree), with null nodes contributing 0.",
    optimization_say=[
        "I'll solve this recursively: the base case is a null node, contributing depth 0.",
        "For any real node, I recursively find the max depth of its left subtree and its right subtree.",
        "The node's own depth is 1 plus whichever of those two is larger.",
    ],
    code_blocks=[
        dict(code="class TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef max_depth(root):\n    if root is None:\n        return 0",
             say="My base case: an empty subtree (null node) has depth 0.",
             why="This is what makes the recursion well-founded \u2014 every recursive call eventually reaches a null child and stops, since the tree is finite."),
        dict(code="    left_depth = max_depth(root.left)\n    right_depth = max_depth(root.right)\n    return 1 + max(left_depth, right_depth)",
             say="I recursively compute the depth of the left and right subtrees, then return 1 (for the current node) plus whichever subtree is deeper.",
             why="The '1 +' accounts for the current node itself being part of the path, and taking the max of the two subtree depths ensures I always follow the longest possible path down."),
    ],
    dry_run="Tree: 3 is root, left child 9 (leaf), right child 20 with children 15 and 7 (both leaves). max_depth(3): left=max_depth(9)=1+max(0,0)=1. right=max_depth(20): left=max_depth(15)=1, right=max_depth(7)=1, so max_depth(20)=1+max(1,1)=2. Back at root: max_depth(3)=1+max(1,2)=3. Final answer: 3.",
    dry_run_say="Tracing a small tree with root 3, left child 9, and right child 20 (which has two leaf children 15 and 7): the left side gives depth 1, the right side gives depth 2, so the whole tree's depth is 1 plus the max of those, which is 3.",
    edge_case="Empty tree, root = None. max_depth(None) immediately returns 0 via the base case, without any further recursion \u2014 correctly handling the smallest possible input.",
    edge_case_say="Let me check the empty tree case, where root is null \u2014 the base case immediately returns 0, which is exactly right.",
    other_edge_cases=[
        "A tree that's just a single node (depth 1)",
        "A completely unbalanced tree that's really just a linked list (depth equals number of nodes)",
        "A perfectly balanced tree",
        "A tree where one subtree is much deeper than the other",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(h)"]],
    final_complexity_say="This is O(n) time since we visit every node exactly once, and O(h) space for the recursion call stack, where h is the height of the tree (which is O(log n) for a balanced tree, or O(n) for a completely skewed one).",
    pushback=[
        ("Can you solve this iteratively instead of recursively?", "Yes \u2014 using a BFS level-order traversal with a queue, counting how many levels we process; each level fully dequeued represents one increment of depth, giving the same O(n) time but avoiding recursion stack usage in favor of an explicit queue."),
        ("What's the space complexity concern with recursion here?", "For a very deep, unbalanced tree (essentially a linked list), the recursion depth could be O(n), risking a stack overflow in some languages/environments, which is a good reason to mention the iterative BFS alternative as a more robust option."),
        ("Can you find the minimum depth instead?", "Similar recursive structure, but you need to be careful: if one subtree is null and the other isn't, minimum depth should follow the non-null subtree, not naively take min(0, other) which would incorrectly treat a missing subtree as if it were a valid short path."),
        ("Can you optimize this further?", "No, O(n) is optimal since we must visit every node at least once to know the true maximum depth of the whole tree."),
    ],
    mistakes=[
        "Forgetting the base case (null node returning 0), causing infinite recursion or a crash.",
        "Off-by-one: returning max(left_depth, right_depth) without adding 1 for the current node.",
        "Confusing 'depth in nodes' with 'depth in edges' (off by one from the expected convention).",
        "For the minimum-depth variant, incorrectly handling a node with only one child.",
    ],
    recovery=[
        "If stuck: 'This looks like it can be defined recursively \u2014 the depth of the tree depends on the depth of its subtrees, so let me write the recursive relationship directly.'",
        "If I forget the base case: remind myself that recursion always needs a stopping point, and a null node is the natural one here.",
        "If the interviewer hints 'can you do it without recursion': pivot to BFS with a queue, counting levels.",
        "If I'm unsure about off-by-one: verify with the smallest example, a single-node tree, which should give depth 1, not 0.",
    ],
    pattern_recognition=dict(
        triggers="'maximum depth', 'height of a binary tree'",
        pattern="DFS Recursion (post-order-like: process children first, then combine)",
        first_thought="Depth of a tree is naturally defined in terms of the depths of its subtrees \u2014 write the recursive relationship directly.",
        trap="Forgetting to add 1 for the current node, or mishandling the null base case.",
    ),
    memory_hook="Max Depth \u2192 \"1 plus whichever child subtree goes deeper.\"",
    recap_key_idea="Recursively compute 1 + max(depth of left subtree, depth of right subtree), with null returning 0.",
    recap_data_structure="Implicit recursion call stack \u2014 no extra data structure.",
    recap_algorithm="DFS Recursion.",
    recap_time="O(n)", recap_space="O(h)", recap_edge_case="Empty tree (root is null).",
    talk_track=[
        ("Interviewer", "Find the maximum depth of this binary tree."),
        ("Me", "Just to confirm, depth is counted in nodes along the longest root-to-leaf path, and an empty tree has depth 0, right?"),
        ("Interviewer", "Yes."),
        ("Me", "This is naturally recursive: the depth of the tree is 1 plus whichever of its two subtrees is deeper, with a null node contributing 0."),
        ("Me", "Let me code that directly \u2014 base case null returns 0, otherwise recurse on both children and combine."),
        ("Me", "Tracing a small tree with root 3, left child 9, and right child 20 having two leaf children: I get depth 3, which matches the expected longest path."),
        ("Me", "Edge case: an empty tree just returns 0 immediately from the base case."),
        ("Me", "Final complexity: O(n) time since every node is visited once, O(h) space for the recursion stack, where h is the tree's height."),
        ("Interviewer", "Can you do it without recursion?"),
        ("Me", "Yes, with a BFS queue, counting how many levels get fully processed \u2014 that avoids recursion stack depth issues on very unbalanced trees."),
    ],
))

PROBLEMS.append(dict(
    title="Same Tree", lc_num="100", difficulty="EASY", pattern="DFS / Recursion (Tree Traversal)",
    relevance="Useful foundational problem",
    restate="We're given the roots of two binary trees, and we need to determine whether they are structurally identical and have the same node values at every position.",
    clarify_questions=[
        "Does 'same' mean identical structure AND identical values at every node?",
        "Can either tree be empty?",
        "Should I compare node values with equality (==), assuming simple comparable types?",
        "Is there a size constraint that matters for a recursive vs iterative choice?",
    ],
    restate_say=["Just to confirm, two trees are the same only if they have identical structure and identical values at every corresponding node, and either tree could be empty, correct?"],
    brute_idea="Serialize both trees into some canonical string or list representation (e.g., pre-order with explicit null markers) and compare those representations directly.",
    brute_say=["One approach is to serialize both trees into a string or list, including markers for null children, and then just compare the two serializations directly."],
    brute_time="O(n) to serialize each tree, plus O(n) to compare the serializations, so O(n) overall.",
    brute_space="O(n) for the serialized representations.",
    brute_complexity_say="This is O(n) time and space, but it does extra work building intermediate representations that aren't strictly necessary.",
    bottleneck="Building full serialized representations of both trees is unnecessary overhead when I can compare the trees directly, node by node, stopping early the moment I find any mismatch.",
    bottleneck_say="The bottleneck is doing extra serialization work when I can compare the two tree structures directly and short-circuit as soon as any difference is found.",
    optimization_explain="I use direct DFS Recursion comparing both trees simultaneously. At each pair of corresponding nodes: if both are None, they're equal (and I stop this branch). If exactly one is None, they're not equal (structural mismatch). If both exist, I check their values match, and recursively check that their left subtrees match each other and their right subtrees match each other.",
    key_insight="Two trees are identical precisely when their roots match (both present/absent and same value) AND their left subtrees are identical to each other AND their right subtrees are identical to each other \u2014 which is directly expressible as a recursive base case plus combination.",
    optimization_say=[
        "I'll recursively walk both trees at the same time, comparing corresponding nodes as I go.",
        "If both current nodes are null, that branch matches. If only one is null, or the values differ, the trees don't match.",
        "Otherwise, I recursively check that both left subtrees match and both right subtrees match.",
    ],
    code_blocks=[
        dict(code="def is_same_tree(p, q):\n    if p is None and q is None:\n        return True\n    if p is None or q is None:\n        return False",
             say="First I handle the two null-related base cases: if both nodes are null, they trivially match; if only one is null, the structures differ, so they don't match.",
             why="These two checks together correctly distinguish 'both empty here' (fine) from 'one has a node the other doesn't' (a structural mismatch), which must be caught before comparing .val on a potentially null node."),
        dict(code="    if p.val != q.val:\n        return False\n\n    return is_same_tree(p.left, q.left) and is_same_tree(p.right, q.right)",
             say="If both nodes exist but their values differ, the trees don't match. Otherwise, I recursively check that both left subtrees match each other, and both right subtrees match each other, requiring both to be true.",
             why="Using 'and' ensures that if either subtree comparison fails, the overall result is correctly False, and Python's short-circuit evaluation means we skip the right-subtree check as soon as the left one fails, saving unnecessary work."),
    ],
    dry_run="p: 1 with left 2, right 3. q: 1 with left 2, right 3. is_same_tree(1,1): values match. Check left: is_same_tree(2,2): both null children, values match, True. Check right: is_same_tree(3,3): both null children, values match, True. Overall: True and True = True.",
    dry_run_say="Tracing two identical small trees, each with root 1 and children 2 and 3: every level's values match and every null-child comparison lines up, so the overall result correctly comes out true.",
    edge_case="One tree has an extra node the other doesn't, e.g. p: 1 with left 2, q: 1 with left 2 and right 3. is_same_tree(1,1): values match. Left: is_same_tree(2,2) True. Right: is_same_tree(None, 3): one is None and the other isn't, returns False immediately. Overall: True and False = False, correctly identifying the structural difference.",
    edge_case_say="Let me check a case where one tree has an extra node the other lacks \u2014 the null-vs-non-null check on that side correctly returns False, so the overall comparison is False, exactly as expected.",
    other_edge_cases=[
        "Both trees are empty (should be considered the same)",
        "Trees with identical structure but one differing value somewhere",
        "Single-node trees with equal or different values",
        "Deeply nested trees requiring many recursive comparisons",
    ],
    final_complexity_rows=[["Optimized", "O(min(n, m))", "O(min(h1, h2))"]],
    final_complexity_say="This is O(min(n, m)) time since the recursion can stop as soon as any mismatch is found, in the worst case visiting every node of the smaller tree, and O(min(h1, h2)) space for the recursion stack, bounded by the shallower comparison path before a mismatch or completion.",
    pushback=[
        ("Can you solve this iteratively?", "Yes, using two stacks (or one stack of paired nodes) and pushing/popping corresponding node pairs, doing the same null/value checks manually instead of relying on the call stack."),
        ("Why check both p is None and q is None separately from p is None or q is None?", "Because I need three distinct outcomes: both null (match, stop), exactly one null (mismatch, stop), or both non-null (continue comparing values and children) \u2014 the two checks together cleanly cover all three cases in the right order."),
        ("What if node values could be unordered/incomparable types?", "As long as equality (==) is well-defined for the value type, this approach works regardless of ordering; if values were more complex objects, I'd want to confirm equality is defined meaningfully for them."),
        ("Can you optimize further?", "No, O(n) in the worst case is necessary since confirming two identical trees requires visiting every node of at least one of them."),
    ],
    mistakes=[
        "Trying to access .val before checking for None, causing a crash on a null node.",
        "Using 'or' instead of 'and' when combining the left and right subtree comparisons.",
        "Forgetting the 'exactly one is null' case, only checking 'both null' and 'both non-null'.",
        "Comparing only root values without recursing into children at all.",
    ],
    recovery=[
        "If stuck: 'Two trees are the same if their roots match and both pairs of subtrees are also the same \u2014 that's directly recursive.'",
        "If I get a null-pointer-style error: check that I've handled the None cases before ever touching .val or .left/.right.",
        "If the interviewer hints 'think about what could be different between two nodes': enumerate the cases \u2014 different values, one has a child the other doesn't.",
        "If unsure about early stopping: mention that Python's 'and' short-circuits, so we naturally stop recursing further once a mismatch is found.",
    ],
    pattern_recognition=dict(
        triggers="'are these two trees identical', 'same structure and values'",
        pattern="DFS Recursion (simultaneous traversal of two trees)",
        first_thought="Two trees match if their roots match and both corresponding subtree pairs also match \u2014 a direct recursive definition.",
        trap="Accessing node attributes before properly checking for None on either side.",
    ),
    memory_hook="Same Tree \u2192 \"Match the roots, then recursively match both subtree pairs.\"",
    recap_key_idea="Compare both trees node by node simultaneously; null/null matches, one-null mismatches, otherwise compare values and recurse on both children.",
    recap_data_structure="Implicit recursion call stack.",
    recap_algorithm="Simultaneous DFS Recursion on two trees.",
    recap_time="O(min(n,m))", recap_space="O(min(h1,h2))", recap_edge_case="Trees differing only by one extra/missing node somewhere.",
    talk_track=[
        ("Interviewer", "Determine if these two binary trees are the same."),
        ("Me", "Got it \u2014 same means identical structure and identical values at every corresponding node, and either tree could be empty, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "I'll compare both trees recursively at the same time. If both current nodes are null, that part matches. If only one is null, or the values differ, they don't match. Otherwise, I recurse into both left and right children."),
        ("Me", "Let me code that with the base cases first, then the value check and recursive combination."),
        ("Me", "Tracing two identical small trees, 1 with children 2 and 3 on both sides: every comparison matches, so the result is true."),
        ("Me", "Edge case: if one tree has an extra node the other doesn't, the null-vs-non-null check catches that and correctly returns false."),
        ("Me", "Final complexity: O(min(n,m)) time since we can stop as soon as a mismatch is found, and O(min(h1,h2)) space for the recursion."),
    ],
))

PROBLEMS.append(dict(
    title="Validate Binary Search Tree", lc_num="98", difficulty="MEDIUM", pattern="DFS with Valid Range (or In-order Traversal)",
    relevance="Common interview pattern",
    restate="We're given the root of a binary tree, and we need to determine whether it's a valid Binary Search Tree, meaning every node's value is strictly greater than all values in its left subtree and strictly less than all values in its right subtree.",
    clarify_questions=[
        "Are duplicate values allowed anywhere in the tree?",
        "Should I compare only against immediate parent/children, or against ALL ancestors?",
        "Is an empty tree considered a valid BST?",
        "Are node values guaranteed to fit within normal integer ranges (relevant for boundary handling)?",
    ],
    restate_say=["Just to confirm, every node needs to be strictly greater than everything in its left subtree and strictly less than everything in its right subtree, not just compared to its immediate children, and duplicates aren't allowed, correct?"],
    brute_idea="For every node, check only against its immediate left and right children, ensuring left child is smaller and right child is bigger.",
    brute_say=["A tempting but incorrect shortcut is to just check that each node's immediate children are smaller (left) and bigger (right) than it, without considering further ancestors."],
    brute_time="O(n) if done this way, since we'd check each node once, but it produces WRONG answers.",
    brute_space="O(h) for recursion.",
    brute_complexity_say="This naive local check is O(n) time, but it's actually incorrect \u2014 it misses violations from a node further up the tree, like a right-subtree node that's smaller than a grandparent, which is a classic BST-validation bug.",
    bottleneck="The real issue isn't speed, it's correctness: checking only immediate parent-child relationships misses the requirement that a node must satisfy the BST property with respect to ALL of its ancestors, not just its direct parent.",
    bottleneck_say="The bug in the naive approach is that it only checks direct parent-child pairs, but the BST property is actually about the whole subtree relative to every ancestor, not just the immediate one.",
    optimization_explain="I use DFS with a Valid Range passed down through recursion. Each recursive call tracks a (low, high) bound that the current node's value must strictly fall within. When I recurse into the left child, I tighten the upper bound to the current node's value (since everything in the left subtree must be less than it); when I recurse into the right child, I tighten the lower bound to the current node's value. If a node ever violates its passed-down bounds, the whole tree is invalid.",
    key_insight="A node's value isn't just constrained by its immediate parent, but by every ancestor whose subtree it belongs to; passing down a shrinking (low, high) range as we recurse correctly accumulates all of those ancestor constraints without having to explicitly check every ancestor at every node.",
    optimization_say=[
        "I'll recursively validate each node against a valid range of (low, high) that gets passed down and tightened as I go deeper.",
        "Going left tightens the upper bound to the current node's value; going right tightens the lower bound.",
        "If any node falls outside its current allowed range, the tree isn't a valid BST.",
    ],
    code_blocks=[
        dict(code="def is_valid_bst(root):\n    def validate(node, low, high):\n        if node is None:\n            return True\n        if not (low < node.val < high):\n            return False",
             say="I write a helper that takes a node plus the current valid (low, high) range. A null node is trivially valid. Otherwise, I check that the current node's value strictly falls within the allowed range.",
             why="Using strict inequalities on both sides (low < val < high) directly encodes that BST values must be strictly greater/less, correctly rejecting duplicates."),
        dict(code="        return (validate(node.left, low, node.val) and\n                validate(node.right, node.val, high))\n\n    return validate(root, float('-inf'), float('inf'))",
             say="I recurse into the left child with an updated upper bound of the current node's value, and into the right child with an updated lower bound of the current node's value. I kick off the whole process starting with unbounded (-infinity, infinity).",
             why="Starting with infinite bounds means the root itself has no constraint, and every deeper node's constraints correctly accumulate from all of its ancestors as the range narrows on the way down."),
    ],
    dry_run="Tree: 5 with left 3, right 8; 3 has left 1, right 4 (wait, let's use a violating example): 5 with left 3 (which has right child 6). validate(5, -inf, inf): 5 is within range. Left: validate(3, -inf, 5). 3 is within range. Right child of 3 is 6: validate(6, 3, 5): is 3 < 6 < 5? No, 6 is not less than 5. Return False. This correctly identifies that 6, though greater than its immediate parent 3, violates the BST property relative to the ancestor 5's left-subtree constraint (everything under 5's left side must be < 5).",
    dry_run_say="Tracing a tree where node 5 has left child 3, and 3 has a right child 6: even though 6 is bigger than its direct parent 3 (which would look fine to a naive local check), it violates the ancestor constraint that everything in 5's left subtree must be less than 5, and the range-based check correctly catches this.",
    edge_case="A tree containing a duplicate value, e.g. root 2 with left child 2. validate(2, -inf, inf) is fine for the root. Left: validate(2, -inf, 2): is -inf < 2 < 2? No, since 2 is not strictly less than 2. Return False, correctly rejecting duplicates as invalid in a strict BST.",
    edge_case_say="Let me check a tree with a duplicate value, like a node equal to its parent \u2014 the strict inequality check correctly rejects it, since a valid BST here requires strictly less than / strictly greater than, not less-than-or-equal.",
    other_edge_cases=[
        "Empty tree (should be considered valid)",
        "Single-node tree (trivially valid)",
        "A valid BST that's deeply skewed to one side",
        "Extreme integer values near typical boundary limits, testing the infinite sentinel bounds",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(h)"]],
    final_complexity_say="This is O(n) time since every node is visited once in the worst case, and O(h) space for the recursion stack, where h is the tree's height.",
    pushback=[
        ("Can you solve this with in-order traversal instead?", "Yes \u2014 an in-order traversal of a valid BST always produces values in strictly increasing order, so I could do an in-order DFS and check that each value is strictly greater than the previous one visited, which is an equally valid O(n) time, O(h) space alternative."),
        ("Why doesn't checking only immediate parent-child pairs work?", "Because the BST property is about a node's relationship to its entire ancestor chain's subtrees, not just its direct parent \u2014 a node can satisfy its immediate parent's constraint while still violating a grandparent's constraint, as shown in the dry run."),
        ("What if the tree could contain duplicate values allowed on one side?", "That would change the inequality to be non-strict on whichever side allows duplicates (e.g., <=) \u2014 I'd clarify this convention with the interviewer since different BST definitions handle duplicates differently."),
        ("Can you optimize this further?", "No, O(n) is optimal since verifying the BST property in general requires examining every node at least once."),
    ],
    mistakes=[
        "Only comparing a node to its immediate children instead of tracking the full valid range from all ancestors.",
        "Using non-strict inequalities (<=, >=) when the problem requires strict BST ordering (no duplicates).",
        "Forgetting to update the correct bound (low vs high) when recursing left vs right.",
        "Using naive integer min/max values instead of proper infinities, which could fail if actual node values equal those chosen sentinels.",
    ],
    recovery=[
        "If stuck: 'Checking just parent-child pairs feels right but might miss ancestor constraints \u2014 let me think of a small counterexample to test that idea before committing to it.'",
        "If I catch myself checking only local parent-child relationships: verbally acknowledge the potential bug and switch to passing down a valid range instead.",
        "If the interviewer hints 'what about grandparents': confirm that's exactly the gap in the naive local-check approach, and describe the range-passing fix.",
        "If unsure about infinite bounds in a specific language without float('inf'): use a sufficiently large/small sentinel value appropriate to the language's constraints, or use None to represent 'no bound' explicitly.",
    ],
    pattern_recognition=dict(
        triggers="'validate binary search tree', 'is this a valid BST'",
        pattern="DFS with a passed-down valid (low, high) range",
        first_thought="A node's constraint comes from ALL its ancestors, not just its direct parent, so pass down a shrinking valid range as you recurse.",
        trap="Only checking immediate parent-child value relationships, missing violations from higher ancestors.",
    ),
    memory_hook="Validate BST \u2192 \"Every node lives inside a shrinking range passed down from its ancestors.\"",
    recap_key_idea="Recursively pass down a (low, high) valid range; left subtree tightens the high bound, right subtree tightens the low bound.",
    recap_data_structure="Implicit recursion call stack carrying (low, high) bounds.",
    recap_algorithm="DFS with Valid Range (alternative: in-order traversal check).",
    recap_time="O(n)", recap_space="O(h)", recap_edge_case="Duplicate values, or a violation from a non-immediate ancestor.",
    talk_track=[
        ("Interviewer", "Determine if this binary tree is a valid Binary Search Tree."),
        ("Me", "Just to confirm, every node needs to satisfy the BST property with respect to ALL of its ancestors, not just its direct parent, and duplicates aren't allowed, right?"),
        ("Interviewer", "Correct."),
        ("Me", "A tempting shortcut is checking only immediate parent-child relationships, but that misses violations from further up the tree \u2014 for example, a node could be fine relative to its parent but still be too large for a grandparent's left-subtree constraint."),
        ("Me", "Instead, I'll pass down a valid (low, high) range as I recurse. Going left tightens the upper bound to the current value; going right tightens the lower bound."),
        ("Me", "Let me code that with a helper function taking the node and its current valid range, starting from negative to positive infinity at the root."),
        ("Me", "Tracing a tree where 5 has left child 3, and 3 has a right child 6: even though 6 is bigger than 3, it violates 5's left-subtree constraint, and my range check correctly catches that."),
        ("Me", "Edge case: a duplicate value, like a node equal to its parent, correctly fails the strict inequality check."),
        ("Me", "Final complexity: O(n) time visiting every node once, O(h) space for the recursion stack."),
        ("Interviewer", "Any other way to solve it?"),
        ("Me", "Yes, an in-order traversal of a valid BST is always strictly increasing, so I could also check that property directly during an in-order DFS."),
    ],
))

PROBLEMS.append(dict(
    title="Kth Smallest Element in a BST", lc_num="230", difficulty="MEDIUM", pattern="In-order Traversal",
    relevance="Common interview pattern",
    restate="We're given the root of a Binary Search Tree and an integer k, and we need to find the kth smallest value stored in the tree.",
    clarify_questions=[
        "Is k guaranteed to be valid, i.e., between 1 and the total number of nodes?",
        "Are all values in the tree guaranteed to be unique?",
        "Will this function be called multiple times on the same tree with different k, which might favor a different strategy?",
        "Is there a preference for O(h) space versus O(n) space?",
    ],
    restate_say=["Just to confirm, k is guaranteed to be valid, all values are unique, and I need the kth smallest value overall, correct? Also, will this be called repeatedly on the same tree?"],
    brute_idea="Do a full in-order traversal, collecting every value into a list (which will be sorted since it's a BST), then return the (k-1)th index of that list.",
    brute_say=["The straightforward approach is to do a full in-order traversal, which visits BST nodes in sorted order, collect everything into a list, and index into it at position k-1."],
    brute_time="O(n) to traverse the entire tree.",
    brute_space="O(n) to store all the values in a list.",
    brute_complexity_say="This is O(n) time and O(n) space, since I'm storing every single value even though I might only need one of them, especially if k is small.",
    bottleneck="If k is small, I'm doing way more work and using way more memory than necessary by collecting every value in the tree, when I could stop the traversal as soon as I've found the kth one.",
    bottleneck_say="The bottleneck is continuing the traversal (and storing everything) even after I've already found the answer, when I could just stop early once I've counted k values.",
    optimization_explain="I use In-order Traversal (which visits BST nodes in ascending order: left, current, right) but stop early as soon as I've visited the kth node, instead of collecting everything. I keep a counter, and either use recursion with early-stopping logic, or an explicit stack-based iterative in-order traversal that I can break out of the moment the counter hits k.",
    key_insight="An in-order traversal of a BST naturally visits nodes in sorted (ascending) order, so the kth node visited during that traversal IS the kth smallest value \u2014 I just need to count visits and stop at k instead of always processing the whole tree.",
    optimization_say=[
        "I'll do an in-order traversal, since that visits BST values in ascending order automatically.",
        "I'll keep a counter of how many nodes I've visited so far.",
        "As soon as the counter reaches k, I have my answer and can stop the traversal early, using an iterative stack-based approach to make the early exit clean.",
    ],
    code_blocks=[
        dict(code="def kth_smallest(root, k):\n    stack = []\n    current = root\n    count = 0",
             say="I set up an explicit stack for the iterative in-order traversal, a pointer to walk down left children, and a counter for how many nodes I've visited.",
             why="Using an explicit stack (instead of recursion) makes it straightforward to break out of the traversal early the moment I find the answer, without extra bookkeeping to unwind recursive calls."),
        dict(code="    while stack or current:\n        while current:\n            stack.append(current)\n            current = current.left",
             say="This inner loop walks as far left as possible, pushing each node onto the stack along the way, which is the standard first step of iterative in-order traversal.",
             why="In a BST, going as far left as possible from any point always leads to the next smallest unvisited value, which is exactly what in-order traversal needs to process first."),
        dict(code="        current = stack.pop()\n        count += 1\n        if count == k:\n            return current.val\n        current = current.right\n\n    return -1",
             say="I pop the next node to process, increment my counter, and if I've just reached the kth node, I return its value immediately. Otherwise, I move to its right subtree and continue the traversal.",
             why="Returning as soon as count == k avoids any unnecessary work processing the remaining nodes, which is the whole point of the optimization over collecting everything upfront."),
    ],
    dry_run="BST: 3 with left 1 (right child 2), right 4. k=1. current=3, push 3, go left to 1, push 1, go left (none, 1 has no left), stop inner loop. Pop 1, count=1. count==k(1), return 1.val=1. Final answer: 1, the smallest value in the tree.",
    dry_run_say="Tracing a small BST with root 3, left child 1 (which has a right child 2), and right child 4, looking for k=1: the traversal walks left first, finds 1 as the smallest value, and since count immediately hits k=1, I return 1 right away without visiting anything else.",
    edge_case="k equals the total number of nodes (asking for the largest value). The traversal must visit every single node before the counter finally reaches k on the very last (rightmost, deepest) node visited, correctly returning the maximum value in the tree.",
    edge_case_say="Let me check when k equals the total number of nodes, meaning I'm asking for the largest value \u2014 the traversal has to visit everything, and the counter only hits k on the final node processed, correctly returning the maximum value.",
    other_edge_cases=[
        "A single-node tree with k=1",
        "A completely left-skewed or right-skewed tree",
        "k=1 (smallest value) on a large tree",
        "A balanced tree with k in the middle",
    ],
    final_complexity_rows=[["Optimized", "O(h + k)", "O(h)"]],
    final_complexity_say="This is O(h + k) time, since we walk down to the leftmost node (O(h)) and then process at most k nodes before stopping, and O(h) space for the explicit stack, which only ever holds nodes along the current path, not the whole tree.",
    pushback=[
        ("Why is this better than collecting all values into a list?", "Because if k is much smaller than n, this approach stops as soon as it's found the answer, using only O(h+k) time and O(h) space, instead of always doing O(n) time and O(n) space regardless of how small k is."),
        ("What if this function is called many times on the same tree with different k values?", "If repeated queries are expected, it might be worth augmenting each node with the size of its subtree (precomputed once in O(n)), which then allows each individual query to run in O(h) time by using subtree sizes to decide whether to go left, return the current node, or go right \u2014 much faster for many repeated queries."),
        ("Can you solve this with recursion instead of an explicit stack?", "Yes, recursion works too, but early-stopping is a bit more awkward to express cleanly (often requiring a mutable counter passed by reference or a class attribute), which is why I prefer the explicit stack version for clean early exit."),
        ("What if the tree could be modified (inserts/deletes) between queries?", "If updates happen frequently, maintaining subtree sizes at each node (updated on every insert/delete) would let each kth-smallest query run in O(h) time consistently, which is a natural follow-up if the interviewer asks about a dynamic version."),
    ],
    mistakes=[
        "Doing a full in-order traversal and collecting everything into a list even when only a small k is needed.",
        "Off-by-one in the counter comparison (using k instead of k, but incrementing at the wrong point relative to the check).",
        "Forgetting this only works correctly because it's specifically a BST (in-order gives sorted order); this technique wouldn't directly apply to a generic binary tree.",
        "Using recursion without a clean way to stop early, leading to unnecessary continued traversal after finding the answer.",
    ],
    recovery=[
        "If stuck: 'Collecting everything into a list works, but if k is small, that's wasteful \u2014 let me think about whether I can stop the traversal as soon as I've found the kth value.'",
        "If I forget in-order gives sorted order for a BST specifically: remind myself that's the defining property being used here, not something true for a random binary tree.",
        "If the interviewer hints 'what if this were called many times': mention the subtree-size augmentation as a natural follow-up optimization.",
        "If my early-stop logic doesn't trigger correctly: recheck whether the counter increment happens before or after the equality check, and align it with a small dry run.",
    ],
    pattern_recognition=dict(
        triggers="'kth smallest/largest in a BST', 'sorted order from a tree'",
        pattern="In-order Traversal (with early stopping)",
        first_thought="In-order traversal of a BST visits values in sorted order \u2014 can I stop as soon as I've counted k of them, instead of collecting everything?",
        trap="Always doing a full traversal and collecting all values, even when k is small and early stopping would save significant work.",
    ),
    memory_hook="Kth Smallest in BST \u2192 \"In-order traversal is sorted order \u2014 just stop counting at k.\"",
    recap_key_idea="Use iterative in-order traversal with an explicit stack, counting nodes visited and stopping as soon as the count reaches k.",
    recap_data_structure="An explicit stack for iterative traversal.",
    recap_algorithm="In-order Traversal with early exit.",
    recap_time="O(h + k)", recap_space="O(h)", recap_edge_case="k equal to the total number of nodes (largest value).",
    talk_track=[
        ("Interviewer", "Find the kth smallest value in this BST."),
        ("Me", "Got it \u2014 k is guaranteed valid, and all values are unique, correct? Also, will this be called repeatedly on the same tree?"),
        ("Interviewer", "Just a single call for now."),
        ("Me", "The straightforward approach is a full in-order traversal, since that visits BST nodes in sorted order, collecting everything into a list and indexing at k-1 \u2014 that's O(n) time and space."),
        ("Me", "Since I don't need the whole sorted list, just the kth value, I can do an iterative in-order traversal with an explicit stack and stop as soon as I've counted k nodes."),
        ("Me", "Let me code that... walking left as far as possible, then popping, counting, and checking against k before moving right."),
        ("Me", "Tracing a small BST with root 3, left child 1, right child 4, looking for k=1: the traversal quickly finds 1 as the smallest and returns immediately."),
        ("Me", "Edge case: if k equals the total node count, I'd need to traverse the entire tree before finding the answer on the very last node, which the logic handles correctly."),
        ("Me", "Final complexity: O(h+k) time and O(h) space, much better than O(n) time and space when k is small."),
        ("Interviewer", "What if this were called many times?"),
        ("Me", "I'd consider augmenting each node with its subtree size, which would let each query run in O(h) time by directly navigating toward the kth element instead of a linear scan."),
    ],
))

PROBLEMS.append(dict(
    title="Construct Binary Tree from Preorder and Inorder Traversal", lc_num="105", difficulty="MEDIUM", pattern="Recursion + Hash Map",
    relevance="Common interview pattern",
    restate="We're given two integer arrays representing the preorder and inorder traversal of the same binary tree, and we need to reconstruct and return the original binary tree.",
    clarify_questions=[
        "Are all node values guaranteed to be unique?",
        "Are both arrays guaranteed to be valid traversals of the same tree (same length, consistent)?",
        "Is there a size constraint that would make repeated linear scans too slow?",
        "Can the tree be empty (empty input arrays)?",
    ],
    restate_say=["Just to confirm, all values are unique, both arrays represent valid traversals of the same tree, and I need to actually rebuild the tree structure, not just verify something about it, correct?"],
    brute_idea="Use the first element of preorder as the root, then linearly search for that value in inorder to split it into left and right parts, and recursively build both subtrees the same way.",
    brute_say=["The natural approach is: the first element of preorder is always the root. I search for that value in inorder to split it into left-subtree values and right-subtree values, then recurse on both halves using the corresponding pieces of preorder."],
    brute_time="Each recursive call does an O(n) linear search in inorder to find the root's position, and there are O(n) calls total, giving O(n\u00b2) in the worst case.",
    brute_space="O(n) for the recursion stack and the resulting tree.",
    brute_complexity_say="This is O(n\u00b2) time in the worst case because of the repeated linear search to locate each subtree's root within inorder, which adds up across all the recursive calls.",
    bottleneck="I'm repeatedly scanning the inorder array from scratch to find each root's position, when I could precompute all those positions once upfront and look them up instantly.",
    bottleneck_say="The bottleneck is redoing a linear search for the root's position in inorder at every single recursive call, when a single upfront hash map lookup could replace all of those searches.",
    optimization_explain="I precompute a Hash Map from value to its index in the inorder array, giving O(1) lookups instead of O(n) searches. I also track a running index into preorder (since preorder is always processed left to right: root, then left subtree, then right subtree). At each recursive call, I take the next value from preorder as the root, look up its position in inorder using the hash map to know how many elements belong to the left subtree, then recursively build the left subtree (which consumes exactly that many following preorder elements) and then the right subtree.",
    key_insight="The very first unused element of preorder is always the current subtree's root, and its position in inorder tells you exactly how many elements to its left belong to the left subtree and how many to its right belong to the right subtree \u2014 which is exactly the information needed to split both arrays consistently.",
    optimization_say=[
        "I'll precompute a hash map of value to index in inorder, so I can find any value's split point instantly.",
        "I'll track a pointer into preorder that always points at the next unused root value.",
        "For each recursive call, I take that next preorder value as the root, use the inorder index to know the left subtree's size, and recurse first into the left side (consuming exactly that many preorder elements) and then the right side.",
    ],
    code_blocks=[
        dict(code="def build_tree(preorder, inorder):\n    inorder_index = {val: i for i, val in enumerate(inorder)}\n    self_preorder_index = 0",
             say="I build a hash map from value to its index in inorder for O(1) lookups, and set up a counter tracking which preorder element is next to be used as a root.",
             why="Precomputing this map once, in O(n), replaces what would otherwise be O(n) searches repeated at every recursive call."),
        dict(code="    def build(left, right):\n        nonlocal self_preorder_index\n        if left > right:\n            return None",
             say="I define a recursive helper describing 'build the subtree covering inorder[left..right]'. If that range is empty (left > right), there's nothing to build, so I return None.",
             why="Using an inorder index range (left, right) to describe 'which part of the tree am I building' is what lets me correctly know when to stop recursing."),
        dict(code="        root_val = preorder[self_preorder_index]\n        self_preorder_index += 1\n        root = TreeNode(root_val)\n        mid = inorder_index[root_val]\n        root.left = build(left, mid - 1)\n        root.right = build(mid + 1, right)\n        return root\n\n    return build(0, len(inorder) - 1)",
             say="I take the next unused preorder value as this subtree's root, advance my pointer, then look up where that value sits in inorder to find the split point, and recursively build the left part (before the split) and the right part (after the split), attaching both as children before returning the root.",
             why="Because preorder always lists root, then everything in the left subtree, then everything in the right subtree, building the left side FIRST (immediately after taking the root) correctly consumes exactly the preorder elements that belong to the left subtree before we ever touch the right subtree's elements."),
    ],
    dry_run="preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]. inorder_index={9:0,3:1,15:2,20:3,7:4}. build(0,4): root_val=preorder[0]=3, index advances to 1. mid=inorder_index[3]=1. root.left=build(0,0): root_val=preorder[1]=9, index->2. mid=inorder_index[9]=0. left=build(0,-1)=None. right=build(1,0)=None. Return node 9 as leaf. Back: root.right=build(2,4): root_val=preorder[2]=20, index->3. mid=inorder_index[20]=3. left=build(2,2): root_val=preorder[3]=15, index->4, mid=2, build(2,1)=None,build(3,2)=None, returns leaf 15. right=build(4,4): root_val=preorder[4]=7, index->5, leaf 7. So node 20 has left=15, right=7. Final tree: root 3, left=9 (leaf), right=20 (left=15, right=7) \u2014 matching the expected tree structure.",
    dry_run_say="Tracing preorder=[3,9,20,15,7] and inorder=[9,3,15,20,7]: the algorithm correctly reconstructs root 3 with left child 9, and right child 20 which itself has children 15 and 7, matching the known correct tree for these traversals.",
    edge_case="Empty input arrays, representing an empty tree. build(0, -1) is called initially (since len(inorder)-1 = -1), and left > right (0 > -1) is immediately true, so None is returned right away \u2014 correctly representing an empty tree.",
    edge_case_say="Let me check the empty tree case, with empty preorder and inorder arrays \u2014 the initial call has left=0 and right=-1, so left > right is true immediately, and we correctly return null.",
    other_edge_cases=[
        "Single-node tree (both arrays have exactly one element)",
        "A tree that's completely left-skewed (right children are all null)",
        "A tree that's completely right-skewed (left children are all null)",
        "A tree where the root's value appears at the very start or very end of inorder",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(n)"]],
    final_complexity_say="This is O(n) time since building the hash map is O(n) and each recursive call now does O(1) work (aside from the recursive calls themselves), visiting each node exactly once, and O(n) space for the hash map and the recursion stack.",
    pushback=[
        ("Why do you need to build the left subtree before the right subtree in the recursive calls?", "Because preorder always lists all of the left subtree's values immediately after the root, before any right subtree values, so I must consume exactly the correct number of preorder elements for the left subtree first, in order, before the running preorder pointer is correctly positioned to start reading the right subtree's values."),
        ("Could you do this with postorder and inorder instead?", "Yes, a very similar technique works: the LAST element of postorder is the root (since postorder processes left, right, root), and you'd recursively build the RIGHT subtree first (working backward from the end of postorder) before the left, but the core hash-map-for-split-point idea is the same."),
        ("What if there were duplicate values in the tree?", "This approach specifically relies on unique values to correctly and unambiguously look up a value's split point in inorder; with duplicates, the reconstruction would become ambiguous or require additional information to disambiguate."),
        ("Can you optimize this further?", "No, O(n) is optimal, since we must construct n nodes and read n elements from at least one of the input arrays to reconstruct the tree."),
    ],
    mistakes=[
        "Building the right subtree before the left subtree, which desynchronizes the preorder pointer from where it should be.",
        "Using a linear search inside the recursion instead of precomputing the hash map upfront, causing the slower O(n\u00b2) approach.",
        "Off-by-one errors in the (left, right) range passed to each recursive call.",
        "Forgetting to advance the preorder pointer (or doing so at the wrong point) before or after creating the current node.",
    ],
    recovery=[
        "If stuck: 'The first element of preorder is always the current subtree's root. If I can find that value's position in inorder, I know exactly how the rest of this subtree splits into left and right.'",
        "If the tree comes out shaped wrong: check whether I'm building left before right in the recursive calls, since order matters given how the preorder pointer advances.",
        "If the interviewer hints 'can you avoid repeated searching': pivot straight to precomputing a hash map of value-to-inorder-index.",
        "If confused about the range bounds: reason through it with a tiny 2-3 node example by hand before trusting the general recursive formula.",
    ],
    pattern_recognition=dict(
        triggers="'construct/reconstruct a binary tree from traversals'",
        pattern="Recursion + Hash Map (for O(1) split-point lookup)",
        first_thought="The first (or last) element of one traversal identifies the root; the other traversal tells you how to split into left/right subtrees around that root.",
        trap="Building right subtree before left, desynchronizing the running preorder index from where it should be.",
    ),
    memory_hook="Construct Binary Tree \u2192 \"Preorder's first value is root; inorder's position of that value splits left from right.\"",
    recap_key_idea="Precompute value-to-inorder-index map; recursively take the next preorder value as root, split inorder at its index, build left then right.",
    recap_data_structure="Hash map (value -> inorder index) + recursion stack.",
    recap_algorithm="Recursion guided by preorder pointer and inorder split index.",
    recap_time="O(n)", recap_space="O(n)", recap_edge_case="Empty input arrays (empty tree).",
    talk_track=[
        ("Interviewer", "Reconstruct the binary tree from its preorder and inorder traversals."),
        ("Me", "Got it \u2014 all values are unique, and both arrays are valid traversals of the same tree, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "The first element of preorder is always the current subtree's root. If I find that value's position in inorder, everything to its left in inorder is the left subtree, and everything to its right is the right subtree."),
        ("Me", "Doing that search naively each time is O(n) per call, giving O(n\u00b2) overall. I can avoid that by precomputing a hash map from value to its index in inorder up front."),
        ("Me", "Let me code that \u2014 I'll track a running pointer into preorder, and recursively build the left subtree before the right subtree, since that's the order preorder lists them in."),
        ("Me", "Tracing preorder=[3,9,20,15,7], inorder=[9,3,15,20,7]: this correctly reconstructs root 3 with left child 9, and right child 20 having children 15 and 7."),
        ("Me", "Edge case: empty input arrays correctly produce a null tree, since the initial range is immediately invalid."),
        ("Me", "Final complexity: O(n) time and space, since the hash map turns every split-point lookup into O(1)."),
    ],
))

PROBLEMS.append(dict(
    title="Serialize and Deserialize Binary Tree", lc_num="297", difficulty="HARD", pattern="DFS Preorder Traversal (with null markers)",
    relevance="Design-heavy problem",
    restate="We need to design a way to serialize a binary tree into a string, and deserialize that string back into the original tree structure, so the two operations are exact inverses of each other.",
    clarify_questions=[
        "Is there a preferred format for the serialized string, or is any format acceptable as long as it round-trips correctly?",
        "Can node values include characters that might conflict with a chosen delimiter (like commas)?",
        "Does the tree need to preserve exact structure, including which side null children are on?",
        "Is there a size constraint that would rule out recursion (stack depth)?",
    ],
    restate_say=["Just to confirm, I get to choose the serialization format myself, as long as serialize followed by deserialize reproduces the exact original tree structure, correct?"],
    brute_idea="One naive idea is to just serialize the values from a level-order (BFS) traversal without recording nulls, but that loses structural information about which children are missing where.",
    brute_say=["A tempting first idea is to just list out node values in some traversal order, but without explicitly recording where nulls are, we lose information about the exact tree shape."],
    brute_time="Any single traversal without null markers is O(n) to produce, but it's fundamentally lossy.",
    brute_space="O(n) for the string.",
    brute_complexity_say="Without recording null markers, this approach is fast, O(n), but incorrect — it can't disambiguate different tree shapes that happen to produce the same sequence of non-null values.",
    bottleneck="The real issue isn't speed, it's that omitting null markers destroys structural information needed to correctly reconstruct the tree; I need a serialization that explicitly records where subtrees are absent.",
    bottleneck_say="The core problem with a naive traversal-only serialization is ambiguity — I need explicit markers for missing children so deserialization can unambiguously rebuild the exact same shape.",
    optimization_explain="I use Preorder DFS Traversal, explicitly writing a special marker (like '#' or 'null') whenever I encounter a null child, and joining everything with a delimiter (like a comma). For deserialization, I process the same tokens in the same preorder sequence: read a value, and if it's the null marker, that subtree is None; otherwise create a node and recursively build its left child (consuming the next tokens) and then its right child.",
    key_insight="Preorder traversal (root, then left, then right) combined with explicit null markers makes the serialized sequence unambiguous: deserialization can rebuild the tree by processing tokens strictly in order, since each null marker correctly terminates a branch instead of leaving structural ambiguity.",
    optimization_say=[
        "For serialization, I'll do a preorder DFS, writing the current node's value, then recursively serializing left, then right — and explicitly writing a marker for any null child instead of skipping it.",
        "For deserialization, I'll process the same tokens in the same order: build a node from the current token, then recursively build its left child from the next tokens, then its right child.",
        "The null markers are what make this fully reversible, since they tell deserialization exactly when a branch ends.",
    ],
    code_blocks=[
        dict(code="def serialize(root):\n    result = []\n    def dfs(node):\n        if node is None:\n            result.append('#')\n            return\n        result.append(str(node.val))\n        dfs(node.left)\n        dfs(node.right)\n    dfs(root)\n    return ','.join(result)",
             say="I do a preorder DFS, appending the current node's value (or '#' for a null) to a list, then recursing left, then right, and finally join everything with commas into one string.",
             why="Writing '#' for every null child, rather than skipping it, is exactly what preserves enough structural information for deserialization to unambiguously reconstruct the tree."),
        dict(code="def deserialize(data):\n    values = iter(data.split(','))\n    def build():\n        val = next(values)\n        if val == '#':\n            return None\n        node = TreeNode(int(val))\n        node.left = build()\n        node.right = build()\n        return node\n    return build()",
             say="I split the string back into tokens and use an iterator so I can consume tokens one at a time. For each call, I read the next token: if it's the null marker, this subtree is None; otherwise I build a node and recursively build its left child, then its right child, from the following tokens.",
             why="Using an iterator (rather than an index I manage manually) makes it natural to always 'consume the next token', which mirrors exactly how serialize wrote them out in preorder, guaranteeing the reconstruction matches the original tree precisely."),
    ],
    dry_run="Tree: 1 with left 2 (leaf), right 3 which has left 4 and right 5 (both leaves). Serialize: dfs(1): append '1'. dfs(2): append '2', dfs(None)->append '#', dfs(None)->append '#'. dfs(3): append '3'. dfs(4): append '4', append '#', append '#'. dfs(5): append '5', append '#', append '#'. Result: '1,2,#,#,3,4,#,#,5,#,#'. Deserialize: build() reads '1', creates node 1. Its left: build() reads '2', creates node 2, left reads '#'->None, right reads '#'->None. Back to node 1's right: build() reads '3', creates node 3. Its left: build() reads '4', both children '#'->None. Its right: build() reads '5', both children '#'->None. Final tree matches the original exactly.",
    dry_run_say="Tracing a small tree with root 1, left leaf 2, and right child 3 (which has leaves 4 and 5): serializing gives '1,2,#,#,3,4,#,#,5,#,#', and deserializing that string token by token perfectly reconstructs the original structure.",
    edge_case="An empty tree, root=None. Serialize: dfs(None) immediately appends '#' and returns, giving the string '#'. Deserialize('#'): build() reads '#', returns None immediately — correctly representing an empty tree round-tripping correctly.",
    edge_case_say="Let me check the empty tree case — serializing gives just '#', and deserializing that single token correctly returns null, so an empty tree round-trips correctly.",
    other_edge_cases=[
        "A single-node tree with no children",
        "A tree that's completely left-skewed",
        "A tree that's completely right-skewed",
        "Negative node values or values with multiple digits (delimiter must correctly separate them)",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(n)"]],
    final_complexity_say="Both serialize and deserialize run in O(n) time, since each visits every real node and every null marker exactly once, and O(n) space for the resulting string/token list and the recursion stack.",
    pushback=[
        ("Why choose preorder over another traversal order?", "Preorder naturally processes the root before its children, which makes it easy to reconstruct top-down: read a value, that's the root, then recursively read its left subtree's tokens, then its right subtree's tokens, all directly from a single forward-moving iterator, without needing to look ahead or backtrack."),
        ("Could you do this with level-order (BFS) instead?", "Yes, that's also a common alternative, similar to how many online BST/tree visualizers represent trees; it requires null markers as placeholders per level too, and reconstruction uses a queue instead of recursion, but it's equally valid."),
        ("What if node values could contain commas?", "I'd choose a different delimiter, or use a length-prefixed encoding (each value preceded by its character count) to avoid ambiguity, which is a good practical detail to bring up if values are strings rather than plain integers."),
        ("Can you avoid recursion for very deep trees?", "Yes, I could implement both serialize and deserialize iteratively using an explicit stack, mirroring the same preorder logic, to avoid Python's recursion depth limit on very unbalanced trees."),
    ],
    mistakes=[
        "Forgetting to explicitly serialize null children, which destroys structural information needed for correct deserialization.",
        "Using a delimiter that could appear inside node values themselves, corrupting the split during deserialization.",
        "Managing a manual index into the token list instead of using an iterator, risking off-by-one bugs.",
        "Mismatching the order of operations between serialize and deserialize (e.g., serializing preorder but trying to deserialize as if it were inorder).",
    ],
    recovery=[
        "If stuck: 'A traversal alone loses information about missing children, so I need to explicitly mark nulls in the serialized output to make reconstruction unambiguous.'",
        "If deserialization produces a wrong shape: verify that both serialize and deserialize consistently use the same traversal order (preorder in both).",
        "If the interviewer hints 'what if values contain your delimiter': acknowledge it and propose either a different delimiter or a length-prefixed format.",
        "If recursion depth is a concern: offer the iterative stack-based alternative as a follow-up.",
    ],
    pattern_recognition=dict(
        triggers="'serialize and deserialize a tree', 'convert a tree to a string and back'",
        pattern="DFS Preorder Traversal with explicit null markers",
        first_thought="A traversal alone is ambiguous without recording where children are missing; explicit null markers plus a consistent traversal order (preorder is easiest) make it reversible.",
        trap="Omitting null markers, which makes different tree shapes indistinguishable from the same serialized sequence.",
    ),
    memory_hook="Serialize/Deserialize → \"Preorder plus explicit nulls — nothing is ambiguous.\"",
    recap_key_idea="Preorder DFS writes value or null marker for every node/child; deserialize reads tokens in the same order to rebuild recursively.",
    recap_data_structure="A list/string of tokens; an iterator during deserialization.",
    recap_algorithm="DFS Preorder Traversal (symmetric encode/decode).",
    recap_time="O(n)", recap_space="O(n)", recap_edge_case="Empty tree (root is null).",
    talk_track=[
        ("Interviewer", "Design an algorithm to serialize and deserialize a binary tree."),
        ("Me", "Got it — I can choose my own format, as long as serialize followed by deserialize exactly reproduces the original tree, right?"),
        ("Interviewer", "Yes."),
        ("Me", "A naive idea would be listing out just the node values in some traversal order, but that loses information about where children are missing, so different trees could serialize identically — that's ambiguous and wrong."),
        ("Me", "Instead, I'll do a preorder DFS and explicitly write a marker, like '#', for every null child, then join everything with commas."),
        ("Me", "For deserialization, I'll process the same tokens in the same preorder order using an iterator: read a value, if it's the marker return null, otherwise build a node and recursively build its left child then its right child from the following tokens."),
        ("Me", "Let me trace a small tree with root 1, left leaf 2, and right child 3 having leaves 4 and 5 — serializing gives '1,2,#,#,3,4,#,#,5,#,#', and deserializing that reconstructs the exact same tree."),
        ("Me", "Edge case: an empty tree just serializes to '#' and deserializes back to null."),
        ("Me", "Final complexity: O(n) time and space for both operations, since every node and null marker is processed exactly once."),
    ],
))

PROBLEMS.append(dict(
    title="Balanced Binary Tree", lc_num="110", difficulty="EASY", pattern="DFS / Recursion (Bottom-Up)",
    relevance="Useful foundational problem",
    restate="We're given the root of a binary tree, and we need to determine whether it's height-balanced, meaning for every node, the heights of its left and right subtrees differ by no more than 1.",
    clarify_questions=[
        "Does balance need to hold at every single node, not just at the root?",
        "Is an empty tree considered balanced?",
        "Is a single-node tree considered balanced?",
        "Is there a preference for avoiding redundant height recomputation?",
    ],
    restate_say=["Just to confirm, balance means at EVERY node, not just the root, the left and right subtree heights differ by at most 1, and an empty tree counts as balanced, correct?"],
    brute_idea="For every node, separately compute the height of its left subtree and right subtree (each a full recursive height computation), check if they differ by more than 1, and recurse to check the same condition for all other nodes.",
    brute_say=["The direct approach is, for every node, compute its left and right subtree heights independently, check the difference, and then recursively check the same condition throughout the whole tree."],
    brute_time="Computing height at each node costs O(n) in the worst case, and doing this for every one of the n nodes gives O(n²) total.",
    brute_space="O(h) for the recursion stack.",
    brute_complexity_say="This is O(n²) time in the worst case because we're recomputing the height of overlapping subtrees repeatedly at every single node.",
    bottleneck="I'm recomputing the height of the same subtrees over and over as I check balance at each ancestor, when a single traversal could compute height and check balance for every node simultaneously.",
    bottleneck_say="The bottleneck is redundant height recomputation — the height of a subtree doesn't change depending on which ancestor is asking, so I should compute each subtree's height exactly once.",
    optimization_explain="I use a Bottom-Up DFS Recursion that computes height AND checks balance in a single pass. My helper function returns the height of a subtree if it's balanced, or a sentinel value (like -1) if it (or any part of it) is already unbalanced. At each node, I recursively get the left and right heights; if either is the sentinel -1, or if they differ by more than 1, I immediately propagate -1 upward. Otherwise, I return 1 + max(left height, right height) as this subtree's real height.",
    key_insight="By combining 'compute height' and 'check balance' into a single recursive pass, and using a sentinel value to short-circuit and propagate 'already unbalanced' up through all ancestors, I avoid ever recomputing the same subtree's height more than once.",
    optimization_say=[
        "I'll write a helper that returns a subtree's real height if it's balanced, or -1 as a sentinel meaning 'unbalanced somewhere below'.",
        "At each node, I get the left and right heights from that same helper; if either came back -1, or if they differ by more than 1, I immediately return -1 to signal unbalanced.",
        "Otherwise, the current subtree is balanced, so I return its real height, 1 plus the max of the two child heights.",
    ],
    code_blocks=[
        dict(code="def is_balanced(root):\n    def check_height(node):\n        if node is None:\n            return 0",
             say="I define a helper that returns either a real height or the sentinel -1. The base case, a null node, has height 0 and is trivially balanced.",
             why="Combining height computation and balance checking into one function, using a special sentinel for 'unbalanced', is what lets me do both jobs in a single pass without recomputation."),
        dict(code="        left_height = check_height(node.left)\n        if left_height == -1:\n            return -1\n        right_height = check_height(node.right)\n        if right_height == -1:\n            return -1",
             say="I recursively check the left subtree first; if it already came back as unbalanced (-1), I immediately propagate that upward without even checking the right subtree. Otherwise, I check the right subtree the same way.",
             why="Short-circuiting as soon as I detect an unbalanced subtree avoids unnecessary further computation, and ensures a single -1 anywhere below correctly poisons every ancestor's result."),
        dict(code="        if abs(left_height - right_height) > 1:\n            return -1\n\n        return 1 + max(left_height, right_height)\n\n    return check_height(root) != -1",
             say="If both subtree heights are valid but differ by more than 1, this node itself is unbalanced, so I return -1. Otherwise, I return the real height, 1 plus the taller of the two subtrees. At the top level, the tree is balanced if and only if the overall result isn't -1.",
             why="This single traversal correctly determines both the height of every subtree and whether balance holds everywhere, since any violation anywhere immediately propagates the -1 sentinel all the way up to the final answer."),
    ],
    dry_run="Tree: 3 with left 9 (leaf), right 20 (left 15, right 7, both leaves). check_height(3): left=check_height(9)=1+max(0,0)=1 (balanced). right=check_height(20): left=check_height(15)=1, right=check_height(7)=1, diff=0, return 1+max(1,1)=2. Back at 3: left_height=1, right_height=2, diff=1, not >1, return 1+max(1,2)=3. Final: check_height(root)=3, not -1, so is_balanced returns True.",
    dry_run_say="Tracing a small tree with root 3, left leaf 9, and right child 20 having two leaf children: every subtree's height difference stays within 1, so the whole tree is correctly identified as balanced, with final height 3.",
    edge_case="A tree that's unbalanced deep down, e.g. a long left-skewed chain hanging off of an otherwise small tree. Even though the imbalance occurs far from the root, the -1 sentinel correctly propagates all the way up through every ancestor, causing the final result to be False, without needing separate checks at each level.",
    edge_case_say="Let me check a tree where the imbalance is buried deep, several levels down — the -1 sentinel correctly bubbles all the way up through every ancestor's check, so the top-level result is still correctly False.",
    other_edge_cases=[
        "Empty tree (should be considered balanced)",
        "Single-node tree (trivially balanced)",
        "A perfectly balanced complete tree",
        "A tree unbalanced right at the root level",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(h)"]],
    final_complexity_say="This is O(n) time since each node's height is computed exactly once in a single bottom-up pass, and O(h) space for the recursion stack, a major improvement over the O(n²) naive approach.",
    pushback=[
        ("Why is the sentinel value -1 chosen specifically?", "Because a real height can never be negative, -1 is a safe, unambiguous signal meaning 'unbalanced', which can be checked with a simple equality test at every level without confusing it with any legitimate height value."),
        ("Can you solve this top-down instead?", "Yes, that's the O(n²) brute-force version, checking balance independently at each node by recomputing subtree heights from scratch; it's simpler to write but significantly less efficient."),
        ("Does this approach short-circuit as soon as it finds an imbalance?", "Partially — it stops recursing into unnecessary subtrees once -1 is detected at a given point (skipping the right subtree check if the left already failed), but doesn't necessarily avoid visiting nodes elsewhere in the tree if the traversal reaches them independently before the failure is found."),
        ("Can you optimize further?", "No, O(n) is optimal since verifying balance requires knowing the height of every subtree, which means visiting every node at least once."),
    ],
    mistakes=[
        "Computing height and checking balance in two separate recursive passes, reintroducing the O(n²) inefficiency.",
        "Using 0 or None as the 'unbalanced' sentinel instead of a value like -1 that can never be a legitimate height.",
        "Forgetting to short-circuit and check the left result before computing the right subtree's height.",
        "Off-by-one in the imbalance check (using >= 1 instead of > 1, which would incorrectly flag valid balanced trees).",
    ],
    recovery=[
        "If stuck: 'The naive approach recomputes height at every node, which is wasteful. Let me think about a single traversal that computes height and checks balance for every node at the same time.'",
        "If I use two separate passes: recognize the inefficiency out loud and combine them using a sentinel value approach.",
        "If the interviewer hints 'can you avoid recomputing height so many times': confirm and pivot to the bottom-up single-pass version.",
        "If unsure why -1 works as a sentinel: reason aloud that real heights are always non-negative, so -1 can never be confused with a legitimate value.",
    ],
    pattern_recognition=dict(
        triggers="'height-balanced binary tree', 'subtree heights differ by at most 1'",
        pattern="Bottom-Up DFS Recursion with a sentinel value to combine two checks in one pass",
        first_thought="Can I compute height and check balance simultaneously in one traversal, instead of recomputing height separately at every node?",
        trap="Splitting height computation and balance checking into two separate passes, reintroducing quadratic time.",
    ),
    memory_hook="Balanced Binary Tree → \"Compute height and check balance together; -1 means 'already broken, stop caring'.\"",
    recap_key_idea="A single bottom-up recursive pass returns real height, or -1 if any subtree below is already unbalanced.",
    recap_data_structure="Implicit recursion call stack.",
    recap_algorithm="Bottom-up DFS Recursion with sentinel propagation.",
    recap_time="O(n)", recap_space="O(h)", recap_edge_case="Imbalance occurring deep in the tree, far from the root.",
    talk_track=[
        ("Interviewer", "Determine if this binary tree is height-balanced."),
        ("Me", "Just to confirm, balance needs to hold at EVERY node, not just the root, and an empty tree counts as balanced, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A direct approach would compute left and right subtree heights independently at every node and check the difference, but that recomputes overlapping heights repeatedly, giving O(n squared)."),
        ("Me", "Instead, I'll do a single bottom-up pass that computes height and checks balance at the same time. My helper returns the real height if a subtree is balanced, or a sentinel of -1 if it's already unbalanced somewhere below."),
        ("Me", "At each node, if either child's result is -1, or if the two heights differ by more than 1, I immediately propagate -1 upward. Otherwise, I return 1 plus the taller child's height."),
        ("Me", "Let me code that... short-circuiting the right subtree check if the left already failed."),
        ("Me", "Tracing a small tree with root 3, left leaf 9, right child 20 with two leaves: every level stays within a height difference of 1, so it's correctly identified as balanced."),
        ("Me", "Edge case: if the imbalance is buried deep in the tree, the -1 sentinel correctly bubbles all the way up to the top-level result."),
        ("Me", "Final complexity: O(n) time since every node's height is computed exactly once, O(h) space for the recursion."),
    ],
))

PROBLEMS.append(dict(
    title="Subtree of Another Tree", lc_num="572", difficulty="EASY", pattern="DFS / Recursion (Tree Matching)",
    relevance="Useful foundational problem",
    restate="We're given the roots of two binary trees, root and subRoot, and we need to determine whether subRoot exactly matches some subtree of root (a node and all of its descendants), including matching structure and values.",
    clarify_questions=[
        "Does the whole subtree starting at the matching node need to match exactly, including all descendants?",
        "Can subRoot be an empty tree, and if so, is that trivially a subtree of anything?",
        "Are node values guaranteed unique, or could there be repeated values across the tree?",
        "Should matching be based on both structure and values, like the Same Tree problem?",
    ],
    restate_say=["Just to confirm, I need to find some node in root such that the ENTIRE subtree rooted there exactly matches subRoot in both structure and values, correct?"],
    brute_idea="For every single node in root, check if the subtree rooted at that node is identical to subRoot, reusing a 'same tree' style comparison, and return true if any such node is found.",
    brute_say=["I can reuse the same-tree comparison logic: for every node in root, check whether the subtree rooted there is exactly identical to subRoot."],
    brute_time="Visiting every node in root is O(n), and for each one, doing a same-tree comparison against subRoot costs up to O(m), giving O(n * m) overall.",
    brute_space="O(h1 + h2) for the combined recursion depth of both traversals.",
    brute_complexity_say="This is O(n times m) time, where n and m are the sizes of root and subRoot, since in the worst case we might attempt a full comparison at every single node of root.",
    bottleneck="There isn't really a faster asymptotic algorithm needed here for typical interview purposes — the natural approach genuinely does require checking multiple candidate starting points, though we can make each individual check as efficient as possible and stop early on any mismatch.",
    bottleneck_say="This one doesn't have a deeper optimization to unlock the way some other problems do; the natural O(n*m) approach combining tree traversal with same-tree comparisons is generally accepted as the expected solution, though there is a string-serialization alternative worth mentioning.",
    optimization_explain="I combine two pieces of recursive logic: a helper is_same_tree(a, b) that checks if two trees are exactly identical (structure and values), reused from the classic Same Tree problem; and a main traversal that, for every node in root, calls is_same_tree(that node, subRoot), returning true as soon as any match is found, or recursing into the node's children if not.",
    key_insight="'Is subRoot a subtree of root' can be broken into 'does the CURRENT node's subtree exactly match subRoot' OR 'is subRoot a subtree of root's left child' OR 'is subRoot a subtree of root's right child' — a clean recursive OR across all possible starting points.",
    optimization_say=[
        "I'll reuse the Same Tree comparison logic as a helper to check if two trees are exactly identical.",
        "Then, starting from root, I check if the current node's subtree exactly matches subRoot using that helper.",
        "If it doesn't match, I recursively check the same thing starting from root's left child, or root's right child, returning true if any of those checks succeed.",
    ],
    code_blocks=[
        dict(code="def is_same_tree(a, b):\n    if a is None and b is None:\n        return True\n    if a is None or b is None:\n        return False\n    if a.val != b.val:\n        return False\n    return is_same_tree(a.left, b.left) and is_same_tree(a.right, b.right)",
             say="This is the exact same-tree helper from before: both null matches, one null is a mismatch, otherwise compare values and recurse into both children.",
             why="Reusing well-understood logic (rather than reinventing tree comparison here) keeps the solution clean and easy to reason about."),
        dict(code="def is_subtree(root, sub_root):\n    if root is None:\n        return False\n    if is_same_tree(root, sub_root):\n        return True\n    return is_subtree(root.left, sub_root) or is_subtree(root.right, sub_root)",
             say="If root is null, there's nothing left to check, so no match is possible here. Otherwise, I first check if the CURRENT node's subtree exactly matches subRoot; if so, I'm done. If not, I recursively check root's left and right children as new candidate starting points.",
             why="Trying an exact match at every single node (not just the root of the whole tree) is what correctly finds subRoot anywhere within root, not just at the very top."),
    ],
    dry_run="root: 3 with left 4 (which has left 1, right 2), right 5. subRoot: 4 with left 1, right 2. is_subtree(3, subRoot): is_same_tree(3, 4)? values 3 vs 4 differ, False. Recurse: is_subtree(4, subRoot) or is_subtree(5, subRoot). is_subtree(4, subRoot): is_same_tree(4,4)? values match, then compare left(1,1) match, right(2,2) match -> True. So is_subtree(4, subRoot) returns True, and the overall result is True.",
    dry_run_say="Tracing root=3 (left child 4 with children 1 and 2, right child 5) and subRoot=4 (with children 1 and 2): the root itself doesn't match, but its left child does exactly match subRoot, so the overall answer is true.",
    edge_case="subRoot has a node with the same value as some node in root but different descendant structure, e.g. root has a node 4 with an extra unexpected child that subRoot's node 4 doesn't have. is_same_tree correctly returns False in that case, since it checks the ENTIRE subtree structure, not just the value at the starting node, so we correctly don't count that as a match and continue searching elsewhere.",
    edge_case_say="Let me check a case where a node has the right value but a different subtree shape than subRoot expects — the same-tree check correctly rejects that as a match since it verifies the full structure, not just the top value, so we correctly keep searching rather than falsely matching.",
    other_edge_cases=[
        "subRoot is a single leaf node matching a leaf somewhere in root",
        "root and subRoot are identical trees (match at the very root)",
        "subRoot doesn't appear anywhere in root (should return false)",
        "root is much larger than subRoot with several nodes sharing subRoot's root value",
    ],
    final_complexity_rows=[["Optimized", "O(n * m)", "O(h1 + h2)"]],
    final_complexity_say="This is O(n times m) time in the worst case, where n and m are the number of nodes in root and subRoot respectively, since we might attempt a full same-tree comparison at many candidate nodes, and O(h1 + h2) space for the combined recursion depth of both traversals.",
    pushback=[
        ("Can you do better than O(n * m)?", "Yes — an alternative is to serialize both trees into strings (using preorder traversal with explicit null markers, similar to the Serialize/Deserialize problem), and then simply check if subRoot's serialization is a substring of root's serialization, using an efficient string-matching algorithm like KMP, achieving O(n + m) time overall."),
        ("Why does the string-serialization trick work correctly here?", "Because with proper null markers and unique delimiters, the serialized preorder string uniquely represents a tree's structure and values, so 'is subRoot a subtree of root' becomes exactly 'is subRoot's string a contiguous substring of root's string', which efficient string matching algorithms can answer quickly."),
        ("What if node values could repeat frequently across the tree?", "The same-tree comparison still works correctly regardless of repeated values, since it checks the FULL structure, not just a single value; repeated values would just mean more candidate starting points get attempted (and rejected) during the search, affecting only performance, not correctness."),
        ("Can you avoid redundant same-tree comparisons?", "Not easily with this direct recursive approach, which is why the string-serialization plus substring-search alternative is worth mentioning if better asymptotic complexity is specifically requested."),
    ],
    mistakes=[
        "Only comparing the value at the root of a candidate subtree without checking the full structure recursively.",
        "Forgetting to recurse into BOTH root.left and root.right when the current node doesn't match.",
        "Confusing 'is subRoot equal to root' with 'is subRoot a subtree somewhere within root' (missing that it can start at any node).",
        "Not handling the null root case (should return False if root is null but subRoot search hasn't found a match yet).",
    ],
    recovery=[
        "If stuck: 'I already know how to check if two trees are exactly identical — let me reuse that, but try it starting from every node in root, not just the root itself.'",
        "If I only check the top-level root: recognize the mistake by testing a case where the match is deeper in the tree, and add the recursive search into left/right children.",
        "If the interviewer asks for a faster approach: mention the serialize-and-substring-search alternative using string matching.",
        "If confused about which helper does what: keep the two functions conceptually separate — 'is_same_tree' checks exact equality, 'is_subtree' searches for any matching starting point.",
    ],
    pattern_recognition=dict(
        triggers="'is this tree a subtree of another tree', 'find a matching subtree anywhere'",
        pattern="DFS Recursion combining exact-match checking with a search across candidate starting points",
        first_thought="Reuse a 'same tree' equality check, but try it as a candidate match starting from every node, not just the root.",
        trap="Only checking the top-level root for a match instead of recursively trying every node in the larger tree as a candidate.",
    ),
    memory_hook="Subtree of Another Tree → \"Try an exact match at every node — reuse Same Tree as the check.\"",
    recap_key_idea="At every node in root, check if its subtree exactly equals subRoot (reusing Same Tree logic); recurse into children if not.",
    recap_data_structure="Implicit recursion call stack (two nested recursive checks).",
    recap_algorithm="DFS Recursion with a nested exact-match helper.",
    recap_time="O(n * m)", recap_space="O(h1 + h2)", recap_edge_case="A node with matching value but different subtree structure.",
    talk_track=[
        ("Interviewer", "Determine if subRoot is a subtree of root."),
        ("Me", "Got it — that means some node in root, with its ENTIRE subtree, must exactly match subRoot in both structure and values, right?"),
        ("Interviewer", "Yes."),
        ("Me", "I already know how to check if two trees are exactly identical — that's the Same Tree problem. I'll reuse that as a helper."),
        ("Me", "Then, for the main search, I'll check if the current node in root exactly matches subRoot using that helper; if not, I recursively check root's left and right children as new candidate starting points."),
        ("Me", "Let me code both pieces — the same-tree helper first, then the search that tries it at every node."),
        ("Me", "Tracing root=3 (left child 4 with children 1, 2, right child 5) and subRoot=4 (with children 1, 2): the root doesn't match, but the left child does exactly, so the answer is true."),
        ("Me", "Edge case: a node with the right value but a different subtree shape correctly fails the same-tree check, so we keep searching instead of falsely matching."),
        ("Me", "Final complexity: O(n times m) time in the worst case, O(h1 plus h2) space for the recursion."),
        ("Interviewer", "Can you do better than that?"),
        ("Me", "Yes, by serializing both trees into strings with explicit null markers and checking if subRoot's string is a substring of root's string using an efficient string-matching algorithm, getting down to O(n+m)."),
    ],
))
