PROBLEMS = []

PROBLEMS.append(dict(
    title="Evaluate Reverse Polish Notation", lc_num="150", difficulty="MEDIUM", pattern="Stack",
    relevance="Common interview pattern",
    restate="We're given a list of tokens representing an arithmetic expression in Reverse Polish (postfix) notation, and we need to evaluate it and return the result.",
    clarify_questions=[
        "Should integer division truncate toward zero?",
        "Can the operands be negative numbers?",
        "Is the input guaranteed to always be a valid RPN expression?",
        "Should the result be returned as an integer even if intermediate division isn't exact?",
    ],
    restate_say=["Just to confirm, tokens come in postfix order, operators apply to the two most recent operands, and I can assume the expression is always valid, correct? Also, does division truncate toward zero?"],
    brute_idea="There isn't really a simpler 'brute force' here beyond the direct stack simulation \u2014 but a naive alternative would be to convert the expression back to infix and use a general expression parser/evaluator.",
    brute_say=["I could try converting this back into infix notation and using a general-purpose expression evaluator, but that's much more complex than necessary given postfix notation is designed to be evaluated directly."],
    brute_time="A general infix parser with operator precedence handling would take similar O(n) time but with significantly more code and edge cases to manage.",
    brute_space="O(n) for any intermediate representation.",
    brute_complexity_say="Converting back to infix would still be roughly O(n) time but adds a lot of unnecessary complexity, like handling operator precedence and parentheses that don't even exist in this format.",
    bottleneck="Postfix notation is specifically designed so operators always apply to the two most recently seen operands \u2014 trying to reconstruct precedence rules is solving a problem that doesn't need to exist here.",
    bottleneck_say="The real issue with overcomplicating this is ignoring that postfix notation already tells us exactly which two operands to combine and when \u2014 we just need a structure that remembers the most recent operands.",
    optimization_explain="I use a Stack. I scan the tokens left to right. Whenever I see a number, I push it onto the stack. Whenever I see an operator, I pop the top two numbers off the stack (in the right order), apply the operator, and push the result back. By the end, the stack holds exactly one value: the final result.",
    key_insight="A stack naturally remembers 'the most recent operands' in the correct order, which is exactly what postfix notation needs: each operator always combines the two values most recently pushed.",
    optimization_say=[
        "I'll use a stack to hold numbers as I scan the tokens.",
        "When I see a number, I push it; when I see an operator, I pop the top two values, apply the operator, and push the result back.",
        "At the end, the single remaining value on the stack is the answer.",
    ],
    code_blocks=[
        dict(code="def eval_rpn(tokens):\n    stack = []\n    operators = {'+', '-', '*', '/'}",
             say="I set up an empty stack and a set of the valid operator symbols for quick checking.",
             why="A Python list works perfectly as a stack here since I only ever push/pop from the end, both O(1) operations."),
        dict(code="    for token in tokens:\n        if token not in operators:\n            stack.append(int(token))\n        else:\n            b = stack.pop()\n            a = stack.pop()",
             say="If the token is a number, I push it onto the stack. If it's an operator, I pop the top two values \u2014 the second-popped one, a, came first in the expression, and b came second.",
             why="Order matters for non-commutative operators like subtraction and division: since b was pushed last, it's the right-hand operand, and a is the left-hand operand."),
        dict(code="            if token == '+':\n                stack.append(a + b)\n            elif token == '-':\n                stack.append(a - b)\n            elif token == '*':\n                stack.append(a * b)\n            else:\n                stack.append(int(a / b))\n\n    return stack.pop()",
             say="I apply the operator to a and b in the correct order and push the result back onto the stack. At the very end, I pop and return the final answer.",
             why="Using int(a / b) instead of a // b ensures truncation toward zero for negative results, matching how most languages define integer division for this problem, rather than Python's floor division which rounds toward negative infinity."),
    ],
    dry_run="tokens = ['2','1','+','3','*']. Push 2 -> [2]. Push 1 -> [2,1]. '+': pop b=1, a=2, push 2+1=3 -> [3]. Push 3 -> [3,3]. '*': pop b=3, a=3, push 3*3=9 -> [9]. Final pop: 9.",
    dry_run_say="Tracing ['2','1','+','3','*']: I push 2 and 1, then '+' combines them into 3, then I push another 3, and '*' combines those into 9, which is the final answer.",
    edge_case="Division producing a negative fractional result, e.g. tokens=['10','3','-','5','/'] evaluating (10-3)/5 = 7/5 = 1.4, which should truncate toward zero to 1 using int(a/b), not Python's // which would also give 1 here, but consider a negative case like -7/2 = -3.5 which should truncate to -3, not floor to -4.",
    edge_case_say="Let me check a division case that could go wrong with truncation, like -7 divided by 2, which should truncate toward zero to -3, not floor down to -4 the way Python's // operator would \u2014 using int(a/b) instead of a//b gets this right.",
    other_edge_cases=[
        "Single-number expression with no operators at all",
        "Division resulting in an exact integer",
        "Deeply nested expression using many operators in sequence",
        "Negative numbers as individual operand tokens",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(n)"]],
    final_complexity_say="This is O(n) time since we process each token exactly once, and O(n) space in the worst case for the stack, such as when the expression is a long sequence of numbers before any operators appear.",
    pushback=[
        ("Why use int(a/b) instead of a // b for division?", "Because Python's // operator floors toward negative infinity, but this problem (like most languages' default integer division) expects truncation toward zero, so int(a/b) is the correct way to get that behavior in Python."),
        ("Can you do this without an explicit stack, e.g. recursively?", "Not cleanly for postfix notation processed left to right; recursion is more natural for prefix notation processed right to left, but a stack directly mirrors how postfix is meant to be evaluated in a single left-to-right pass."),
        ("What if division by zero occurs?", "The problem typically guarantees a valid expression that never divides by zero; if that assumption didn't hold, I'd add an explicit check and raise or handle an error case."),
        ("Can you optimize this further?", "O(n) time and space is already optimal, since we must read every token at least once, and in the worst case (all numbers, one final operator) the stack must hold up to n/2 or more values at once."),
    ],
    mistakes=[
        "Popping operands in the wrong order for non-commutative operators like subtraction and division (a should be popped second, b first).",
        "Using a // b instead of int(a / b), which gives wrong results for negative divisions.",
        "Forgetting to convert string tokens to integers before doing arithmetic.",
        "Not handling multi-digit or negative number tokens correctly when parsing.",
    ],
    recovery=[
        "If stuck: 'Postfix notation means operators always act on the two most recently seen numbers, and a stack is exactly the structure that remembers 'most recent' in order.'",
        "If I get operand order backwards: verify with a subtraction example by hand, since addition/multiplication would hide the bug but subtraction/division would immediately expose it.",
        "If the interviewer hints 'watch out for negative division': switch to int(a/b) and explain why // is wrong here.",
        "If I forget which token types are operators: just check membership in a small operators set, as coded.",
    ],
    pattern_recognition=dict(
        triggers="'Reverse Polish Notation', 'postfix expression evaluation'",
        pattern="Stack (Last-In-First-Out processing of the most recent operands)",
        first_thought="Operators always combine the two most recently seen values \u2014 a stack captures 'most recent' naturally.",
        trap="Getting the order of operands backwards for non-commutative operators.",
    ),
    memory_hook="Evaluate RPN \u2192 \"Numbers pile up, operators pop the top two and push the result back.\"",
    recap_key_idea="Push numbers; on an operator, pop the top two, apply it in the correct order, and push the result.",
    recap_data_structure="A single stack (Python list).",
    recap_algorithm="Single left-to-right scan with stack push/pop.",
    recap_time="O(n)", recap_space="O(n)", recap_edge_case="Negative number division needing truncation toward zero.",
    talk_track=[
        ("Interviewer", "Evaluate this expression given in Reverse Polish Notation."),
        ("Me", "Got it \u2014 operators always apply to the two most recent operands, and I can assume the expression is always valid, right? Does division truncate toward zero?"),
        ("Interviewer", "Yes to both."),
        ("Me", "Since postfix is designed to be evaluated left to right using a stack, I'll push numbers as I see them, and whenever I hit an operator, pop the top two values, apply the operator, and push the result back."),
        ("Me", "Let me code that \u2014 I need to be careful about operand order for subtraction and division, since the second-popped value came first in the expression."),
        ("Me", "Tracing ['2','1','+','3','*']: 2 and 1 combine to 3, then 3 and 3 combine to 9, which is the final answer."),
        ("Me", "One thing I want to double check \u2014 negative division. -7 divided by 2 should truncate to -3, not floor to -4, so I'll use int(a/b) instead of Python's // operator."),
        ("Me", "Final complexity: O(n) time for one pass through the tokens, O(n) space for the stack in the worst case."),
    ],
))

PROBLEMS.append(dict(
    title="Next Greater Element I", lc_num="496", difficulty="EASY", pattern="Monotonic Stack",
    relevance="Common interview pattern",
    restate="We're given two arrays, nums1 (a subset of nums2), and for each element in nums1 we need to find its next greater element to the right in nums2, or -1 if none exists.",
    clarify_questions=[
        "Are all elements in nums1 guaranteed to exist in nums2?",
        "Are there duplicate values in nums2?",
        "What should I return if there's no greater element to the right?",
        "Are the arrays guaranteed non-empty?",
    ],
    restate_say=["Just to confirm, every value in nums1 appears somewhere in nums2, and for each I need the first larger value that appears later in nums2, or -1 if there isn't one, correct?"],
    brute_idea="For each element in nums1, find its position in nums2, then scan rightward until a larger value is found.",
    brute_say=["The brute-force approach is, for every element in nums1, locate it in nums2 and then scan forward until I find something bigger."],
    brute_time="Finding each element and scanning forward is O(n) per query in the worst case, giving O(n*m) for m queries.",
    brute_space="O(1) extra space beyond the output.",
    brute_complexity_say="This is O(n times m) time in the worst case, since for every queried value I might scan almost the entire second array, and O(1) extra space.",
    bottleneck="I keep re-scanning parts of nums2 for different queries, when the 'next greater element' for every position in nums2 could be precomputed once and reused for all queries.",
    bottleneck_say="The bottleneck is redoing the rightward scan for every query separately, when I could precompute the next greater element for every value in nums2 a single time.",
    optimization_explain="I use a Monotonic Stack. I scan nums2 left to right, maintaining a stack of numbers for which I haven't yet found a next greater element. For each new number, while the stack's top is smaller than the current number, I pop it and record the current number as its 'next greater element' in a hash map. I push the current number onto the stack. After processing all of nums2, I look up each nums1 value in the hash map.",
    key_insight="A monotonic (decreasing) stack lets me resolve 'next greater element' for many values at once: as soon as a bigger number appears, it immediately answers the question for every smaller number still waiting on the stack, in one pass.",
    optimization_say=[
        "I'll do one pass over nums2 with a stack that only ever holds a decreasing sequence of numbers.",
        "Whenever the current number is bigger than the stack's top, that top value has found its next greater element, so I pop it and record the answer in a hash map, repeating until the stack top is bigger or the stack is empty.",
        "Then I just look up each nums1 value in that hash map, defaulting to -1 if it was never resolved.",
    ],
    code_blocks=[
        dict(code="def next_greater_element(nums1, nums2):\n    next_greater = {}\n    stack = []",
             say="I set up a hash map to store the answer for each value in nums2, and an empty stack.",
             why="The hash map will let me answer each nums1 query in O(1) after the single pass over nums2 is done."),
        dict(code="    for num in nums2:\n        while stack and stack[-1] < num:\n            smaller = stack.pop()\n            next_greater[smaller] = num\n        stack.append(num)",
             say="For each number in nums2, I pop off any stack values smaller than it, recording the current number as their next greater element, then push the current number onto the stack.",
             why="Anything still on the stack when a bigger number shows up has just found its answer; anything left on the stack at the end simply never finds a next greater element."),
        dict(code="    return [next_greater.get(num, -1) for num in nums1]",
             say="Finally, for every value in nums1, I look up its answer in the hash map, defaulting to -1 if it was never resolved.",
             why="Some values never get popped because nothing bigger ever appears after them, so those correctly default to -1."),
    ],
    dry_run="nums2 = [2,1,2,4,3], nums1=[2,4]. Process 2: stack empty, push -> [2]. Process 1: 1<2 no pop, push -> [2,1]. Process 2: top=1<2, pop, next_greater[1]=2; top=2, not <2, stop; push 2 -> [2,2]. Process 4: top=2<4 pop, next_greater[2]=4 (first 2); top=2<4 pop, next_greater[2]=4 (second 2, same key overwritten, fine since both were 2); push 4 -> [4]. Process 3: top=4, not<3, push -> [4,3]. Map: {1:2, 2:4}. Query nums1=[2,4]: 2->4, 4-> not in map -> -1. Result: [4,-1].",
    dry_run_say="Tracing nums2=[2,1,2,4,3]: as bigger numbers appear, they resolve smaller ones on the stack, building up next_greater = {1:2, 2:4}. Then for nums1=[2,4], 2 maps to 4, and 4 was never resolved (nothing bigger comes after it), so it's -1. Final: [4,-1].",
    edge_case="A value in nums2 that's already the largest and appears last, e.g. the final element in a strictly increasing nums2 like [1,2,3,4] \u2014 4 never gets popped and remains without an entry in the map, correctly defaulting to -1 when queried.",
    edge_case_say="Let me check the case where a number is the largest and occurs at the very end, like the last element of a strictly increasing array \u2014 it never gets popped off the stack, so it correctly defaults to -1.",
    other_edge_cases=[
        "nums2 is strictly decreasing (every element defaults to -1)",
        "nums1 and nums2 are identical arrays",
        "nums2 has only one element",
        "Duplicate values appearing in nums2",
    ],
    final_complexity_rows=[["Optimized", "O(n + m)", "O(n)"]],
    final_complexity_say="This is O(n + m) time, where n is the length of nums2 (each element is pushed and popped at most once) and m is the length of nums1 for the lookups, and O(n) space for the hash map and stack.",
    pushback=[
        ("Why is the stack guaranteed O(n) total, not worse?", "Because every element is pushed exactly once and popped at most once across the entire scan, so even though there's a while loop inside the for loop, the total number of pop operations across all iterations can't exceed n, giving amortized O(n) overall."),
        ("What if nums2 could contain duplicates?", "The map would just store the most recent 'next greater' resolution for a given value; since the problem guarantees nums1 values are unique in nums2, or at least resolvable, this doesn't cause issues in practice."),
        ("Can you solve it without a hash map, directly with indices?", "Yes, if nums1 were about positions instead of values, I could store next-greater results in an array indexed by position in nums2 directly, but since we're keying by value here, a hash map is the natural fit."),
        ("Can you optimize further?", "O(n + m) is optimal since we must at least look at every element of nums2 once and every query in nums1 once."),
    ],
    mistakes=[
        "Popping conditionally with 'while' but forgetting to check 'stack' is non-empty first, causing an index error.",
        "Recomputing next greater elements per-query instead of precomputing once for all of nums2.",
        "Forgetting the default of -1 when a nums1 value's next greater element was never found.",
        "Confusing 'next greater to the right' with 'next greater anywhere', missing the directional requirement.",
    ],
    recovery=[
        "If stuck: 'Since I'm answering multiple queries against the same array, let me precompute answers for every value in nums2 once, rather than searching per query.'",
        "If I forget the stack's monotonic property: reason aloud, 'the stack should only ever hold values that haven't found something bigger yet, so it must be decreasing from bottom to top.'",
        "If the interviewer hints 'you don't need to search each query separately': confirm and switch to the single-pass precompute-then-lookup approach.",
        "If unsure about amortized complexity: explain that each element is pushed once and popped at most once, so total stack operations are bounded by n.",
    ],
    pattern_recognition=dict(
        triggers="'next greater element', 'next warmer day', 'next larger value to the right'",
        pattern="Monotonic Stack",
        first_thought="Can I resolve many 'next greater' questions in one pass by keeping a stack of unresolved candidates?",
        trap="Re-scanning the array separately for each query instead of precomputing everything in one monotonic-stack pass.",
    ),
    memory_hook="Next Greater Element \u2192 \"Stack holds the unresolved; a bigger number resolves everyone smaller beneath it.\"",
    recap_key_idea="Maintain a decreasing stack; when a bigger number arrives, it resolves all smaller values still waiting.",
    recap_data_structure="Stack + hash map (value \u2192 next greater value).",
    recap_algorithm="Monotonic Stack, single pass over nums2.",
    recap_time="O(n + m)", recap_space="O(n)", recap_edge_case="Largest value occurring at the very end (always resolves to -1).",
    talk_track=[
        ("Interviewer", "For each value in nums1, find its next greater element in nums2, or -1."),
        ("Me", "Got it \u2014 every nums1 value appears in nums2, and I want the first larger value appearing after it in nums2, right?"),
        ("Interviewer", "Correct."),
        ("Me", "Brute force: for each nums1 value, find it in nums2 and scan forward for something bigger \u2014 O(n times m) in the worst case."),
        ("Interviewer", "Can you avoid redoing that scan for every query?"),
        ("Me", "Yes \u2014 I'll do one pass over nums2 using a monotonic decreasing stack. Whenever I see a number bigger than the stack's top, that resolves the top's 'next greater element', so I pop it and record the answer in a hash map."),
        ("Me", "Let me code that... after the single pass, I just look up each nums1 query in the map, defaulting to -1."),
        ("Me", "Tracing nums2=[2,1,2,4,3]: the map ends up as {1:2, 2:4}. For nums1=[2,4], I get [4,-1], since 4 never finds anything bigger after it."),
        ("Me", "Edge case: if the largest value is at the very end of nums2, it's never popped, and correctly stays -1."),
        ("Me", "Final complexity: O(n+m) time since the stack does amortized O(1) work per element, O(n) space for the map and stack."),
    ],
))

PROBLEMS.append(dict(
    title="Decode String", lc_num="394", difficulty="MEDIUM", pattern="Stack",
    relevance="Common interview pattern",
    restate="We're given an encoded string with a pattern like k[encoded_string], meaning the encoded_string inside the brackets should be repeated k times, and encodings can be nested, and we need to return the fully decoded string.",
    clarify_questions=[
        "Can the encodings be nested, like 2[3[a]b]?",
        "Are the numbers guaranteed to be positive integers, possibly multi-digit?",
        "Is the input guaranteed to be well-formed (brackets always balanced)?",
        "Are there plain (non-bracketed) characters mixed in with encoded parts?",
    ],
    restate_say=["Just to confirm, encodings can nest arbitrarily deep, numbers can be multiple digits, and the input is always well-formed with balanced brackets, correct?"],
    brute_idea="Try to handle this with string replacement or regular expressions, repeatedly expanding the innermost bracket pattern until none remain.",
    brute_say=["One approach is to repeatedly find the innermost k[...] pattern with something like a regular expression, expand it, and repeat until no brackets remain."],
    brute_time="Each expansion pass can cost O(n) to scan and rebuild the string, and we may need O(n) passes in the worst case of deep nesting, giving O(n\u00b2) or worse.",
    brute_space="O(n) for the string being rebuilt at each step.",
    brute_complexity_say="This repeated-expansion approach can be O(n\u00b2) or worse in the worst case, since deeply nested brackets require many passes, each rebuilding a growing string.",
    bottleneck="I'm rebuilding and rescanning the whole string at every level of nesting, when a single pass tracking open contexts as I go would let me handle nesting directly without repeated scans.",
    bottleneck_say="The bottleneck is treating nesting as a series of separate passes, when I could handle it directly in one scan if I had a way to remember 'what I was building before I went one level deeper'.",
    optimization_explain="I use a Stack to remember state when I enter a new bracket level. As I scan left to right: digits accumulate into a current number, letters accumulate into a current string, and when I see '[', I push the current string and current number onto the stack and reset both to start fresh for the nested section. When I see ']', I pop the previous string and repeat count, and combine them: current_string = previous_string + (repeat_count * current_string).",
    key_insight="Each '[' opens a new 'building context' and each ']' closes it by merging back into the context that was paused \u2014 that's exactly what a stack is for: remembering paused work so it can be resumed later.",
    optimization_say=[
        "I'll scan the string once, building up a current number and current string as I go.",
        "When I hit '[', I push the current string and number onto a stack and reset them, since I'm about to start building a nested piece.",
        "When I hit ']', I pop the previous string and number, and combine them: previous string plus the nested string repeated that many times.",
    ],
    code_blocks=[
        dict(code="def decode_string(s):\n    stack = []\n    current_string = ''\n    current_number = 0",
             say="I set up a stack, and two variables tracking what I'm currently building: the string so far and any number being read digit by digit.",
             why="current_number needs to accumulate across multiple digit characters (since numbers can be multi-digit, like '213'), so I build it up rather than reading one digit at a time."),
        dict(code="    for char in s:\n        if char.isdigit():\n            current_number = current_number * 10 + int(char)\n        elif char == '[':\n            stack.append((current_string, current_number))\n            current_string = ''\n            current_number = 0",
             say="If I see a digit, I fold it into current_number using the standard multi-digit accumulation trick. If I see '[', I push the current string and number as a pair, then reset both to start fresh for the nested content.",
             why="Multiplying by 10 and adding the new digit correctly builds multi-digit numbers like '2' then '1' then '3' becoming 213, not just 2, 1, 3 separately."),
        dict(code="        elif char == ']':\n            previous_string, repeat_count = stack.pop()\n            current_string = previous_string + current_string * repeat_count\n        else:\n            current_string = current_string + char\n\n    return current_string",
             say="If I see ']', I pop the paused string and repeat count, and rebuild current_string as the previous string followed by the nested string repeated that many times. Any regular letter just gets appended to current_string directly.",
             why="This is where nesting resolves itself naturally: whatever was paused before the bracket gets combined with the fully-built nested content, one level at a time, correctly handling arbitrarily deep nesting."),
    ],
    dry_run="s = '3[a2[c]]'. char '3': current_number=3. char '[': push ('',3), reset current_string='', current_number=0. char 'a': current_string='a'. char '2': current_number=2. char '[': push ('a',2), reset current_string='', current_number=0. char 'c': current_string='c'. char ']': pop ('a',2), current_string='a' + 'c'*2 = 'acc'. char ']': pop ('',3), current_string='' + 'acc'*3 = 'accaccacc'. Final result: 'accaccacc'.",
    dry_run_say="Tracing '3[a2[c]]': I build up to pushing ('',3) then ('a',2), then when the inner bracket closes I get 'acc', and when the outer bracket closes I get 'accaccacc', which is the correct decoding.",
    edge_case="No brackets at all, just plain letters, e.g. s='abc'. The loop just appends each character to current_string directly, and since the stack is never touched, the final result is simply 'abc'.",
    edge_case_say="Let me check a string with no brackets at all, like 'abc' \u2014 every character just appends directly to current_string, the stack stays empty, and I correctly return 'abc' unchanged.",
    other_edge_cases=[
        "Multiple sibling bracket groups at the same level, like '2[a]3[b]'",
        "Multi-digit repeat counts, like '213[a]'",
        "Deeply nested brackets several levels deep",
        "A bracket group containing multiple different letters, like '3[abc]'",
    ],
    final_complexity_rows=[["Optimized", "O(n * maxK)", "O(n)"]],
    final_complexity_say="Time is roughly O(n times maxK) where maxK is the largest repeat multiplier, since string concatenation with repetition can multiply the output size, and space is O(n) for the stack and the output string in the worst case of deep nesting or large repeat counts.",
    pushback=[
        ("Can you avoid quadratic string concatenation costs?", "In languages where string concatenation is expensive, I could build results using a list of characters or a more efficient buffer and join at the end; in Python, repeated concatenation of small pieces is generally acceptable but could be optimized similarly if profiling showed it mattered."),
        ("Can you solve this recursively instead of with an explicit stack?", "Yes, recursion works naturally here too, since each nested bracket is essentially its own subproblem \u2014 the recursive call stack implicitly plays the same role as my explicit stack, just expressed differently."),
        ("What if the repeat count could be zero?", "A count of 0 would mean the nested content is dropped entirely (repeated zero times), which my formula previous_string + current_string * 0 handles correctly since Python string multiplication by 0 yields an empty string."),
        ("What's the worst-case output size?", "It can be exponential in the input length if brackets are deeply nested with large multipliers (e.g., 2[2[2[2[...]]]]), so I'd flag that as a potential real-world constraint to discuss with the interviewer if inputs could be adversarial."),
    ],
    mistakes=[
        "Reading only single digits instead of accumulating multi-digit numbers correctly.",
        "Forgetting to reset current_string and current_number after pushing them onto the stack when entering a new bracket.",
        "Getting the concatenation order wrong when popping (should be previous_string + current_string * count, not the reverse).",
        "Not handling plain (non-bracketed) characters that appear alongside encoded sections.",
    ],
    recovery=[
        "If stuck: 'Nesting means I need to remember what I was building before I went one level deeper, which is exactly what a stack is designed for.'",
        "If I get concatenation order backwards: verify with a simple trace like '3[a]b' by hand, which would immediately reveal an ordering bug.",
        "If the interviewer hints 'think about pausing and resuming work': confirm that's exactly the push/pop pattern I'm using.",
        "If I forget how to build multi-digit numbers: use the standard trick, current_number = current_number * 10 + digit, and explain it as you write it.",
    ],
    pattern_recognition=dict(
        triggers="'nested encoding', 'k[string]', 'decode string with repeats'",
        pattern="Stack (to pause/resume nested build contexts)",
        first_thought="Every time I go one level deeper (open bracket), I need to remember what I was building before, and resume it later (close bracket) \u2014 a stack does exactly that.",
        trap="Forgetting to reset the current string/number after pushing when entering a new nested level.",
    ),
    memory_hook="Decode String \u2192 \"Bracket opens: pause and push. Bracket closes: pop and combine.\"",
    recap_key_idea="Push (string-so-far, repeat-count) on '[', pop and combine on ']'.",
    recap_data_structure="A stack of (string, number) pairs.",
    recap_algorithm="Single-pass scan with push/pop for nested contexts.",
    recap_time="O(n * maxK)", recap_space="O(n)", recap_edge_case="Deeply nested brackets with multi-digit repeat counts.",
    talk_track=[
        ("Interviewer", "Decode this string where k[substring] means substring repeated k times, and it can nest."),
        ("Me", "Got it \u2014 nesting can go arbitrarily deep, numbers can be multi-digit, and the input is always well-formed, right?"),
        ("Interviewer", "Yes."),
        ("Me", "One naive approach is repeatedly expanding the innermost bracket with something like regex until none remain, but that could take many passes and rebuild the string repeatedly \u2014 not great for deep nesting."),
        ("Interviewer", "How would you do it in one pass?"),
        ("Me", "I'd use a stack. As I scan, I build up a current string and current number. When I hit '[', I push both onto the stack and reset them, since I'm about to build a nested piece. When I hit ']', I pop the paused string and count, and combine them: previous string plus the nested string repeated that many times."),
        ("Me", "Let me code that up, being careful to accumulate multi-digit numbers correctly."),
        ("Me", "Tracing '3[a2[c]]': the inner bracket resolves to 'acc', and the outer bracket resolves to 'accaccacc', which is correct."),
        ("Me", "Edge case: a string with no brackets at all just passes straight through unchanged, since the stack never gets used."),
        ("Me", "Final complexity is roughly O(n times maxK) time since large repeat counts multiply the output, and O(n) space for the stack and result."),
    ],
))

PROBLEMS.append(dict(
    title="Simplify Path", lc_num="71", difficulty="MEDIUM", pattern="Stack",
    relevance="Common interview pattern",
    restate="We're given an absolute Unix-style file path, and we need to simplify it into its canonical form, resolving '.' (current directory), '..' (parent directory), and collapsing multiple slashes.",
    clarify_questions=[
        "What should happen if '..' appears at the root, with no parent to go up to?",
        "Should trailing slashes be removed from the final answer?",
        "Can there be multiple consecutive slashes, and should they collapse to one?",
        "Is the path guaranteed to start with a single leading slash?",
    ],
    restate_say=["Just to confirm, I need to resolve '.' and '..' components, collapse repeated slashes, and if '..' tries to go above the root, it should just stay at the root, correct?"],
    brute_idea="Directly manipulate the string character by character, trying to track directory boundaries and handle '..' by searching backward for the previous slash to remove.",
    brute_say=["A naive approach is direct string manipulation \u2014 scanning through and trying to delete characters or find the previous slash whenever I hit '..', directly on the string."],
    brute_time="Removing characters or searching backward within a string repeatedly can cost O(n) per operation, giving O(n\u00b2) in the worst case for many '..' components.",
    brute_space="O(n) for the string being modified.",
    brute_complexity_say="Direct string surgery is error-prone and can hit O(n\u00b2) time if I'm repeatedly searching backward or shifting characters around within the string.",
    bottleneck="Treating the path as a flat string makes 'go up one directory' awkward and error-prone, when really the path is naturally a sequence of directory names that behaves like a stack \u2014 push to go deeper, pop to go up.",
    bottleneck_say="The bottleneck is fighting with raw string indices to simulate 'going up a directory', when directory names naturally behave like a stack of pushes and pops.",
    optimization_explain="I split the path by '/' to get a list of components. I use a Stack: for each component, if it's empty or '.', I ignore it; if it's '..', I pop the stack (if non-empty, to go up a directory); otherwise it's a real directory name, so I push it. At the end, I join the stack's contents with '/' and prepend a single leading slash.",
    key_insight="Splitting by '/' turns the whole problem into a sequence of simple stack operations: real names push, '..' pops, and '.' or empty segments (from repeated slashes) are simply skipped.",
    optimization_say=[
        "I'll split the path on '/' to get a list of pieces, some of which might be empty due to repeated slashes.",
        "I'll use a stack: skip empty pieces and '.', pop on '..' if there's something to pop, and push any real directory name.",
        "At the end I join everything in the stack with '/' and add a single leading slash.",
    ],
    code_blocks=[
        dict(code="def simplify_path(path):\n    parts = path.split('/')\n    stack = []",
             say="I split the input on '/' into individual pieces, and set up an empty stack.",
             why="Splitting handles the tokenization for me; pieces between consecutive slashes become empty strings, and '.', '..', and real names all show up as distinct list elements."),
        dict(code="    for part in parts:\n        if part == '' or part == '.':\n            continue\n        elif part == '..':\n            if stack:\n                stack.pop()\n        else:\n            stack.append(part)",
             say="For each piece, I skip empty strings and single dots. For double dots, I pop the stack if it's not empty, going up one directory. Otherwise, it's a real directory name, so I push it.",
             why="Checking 'if stack' before popping on '..' prevents trying to go above the root, which should just be a no-op rather than an error."),
        dict(code="    return '/' + '/'.join(stack)",
             say="Finally, I join everything left in the stack with '/' and add a single leading slash to form the canonical absolute path.",
             why="The problem always wants an absolute path starting with exactly one slash, and joining with '/' naturally produces single slashes between directory names, with no trailing slash."),
    ],
    dry_run="path = '/a/./b/../../c/'. Split by '/': ['', 'a', '.', 'b', '..', '..', 'c', '']. Process '': skip. 'a': push -> ['a']. '.': skip. 'b': push -> ['a','b']. '..': pop -> ['a']. '..': pop -> []. 'c': push -> ['c']. '': skip. Final stack: ['c']. Result: '/' + 'c' = '/c'.",
    dry_run_say="Tracing '/a/./b/../../c/': after splitting and processing each piece, 'a' and 'b' get pushed, then both get popped by the two '..' pieces, and finally 'c' gets pushed, giving the canonical path '/c'.",
    edge_case="Trying to go up past the root, e.g. path='/../'. Split gives ['', '..', '']. The '..' tries to pop an empty stack, which the 'if stack' check prevents, so nothing happens. Final stack is empty, and the result is '/' + '' = '/', correctly staying at the root instead of erroring.",
    edge_case_say="Let me check what happens if the path tries to go above the root, like '/../' \u2014 popping an empty stack is guarded against, so we correctly stay at the root and return just '/'.",
    other_edge_cases=[
        "Path with multiple consecutive slashes, like '/a//b'",
        "Path that's already in canonical form",
        "Path consisting only of '.' components",
        "Very deeply nested path with many real directory names",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(n)"]],
    final_complexity_say="This is O(n) time since splitting and processing the path both scan it a constant number of times, and O(n) space for the stack and the split list of components.",
    pushback=[
        ("Why not manipulate the string directly instead of splitting?", "Splitting converts the problem into clean, discrete tokens, which makes the stack logic straightforward and avoids fragile index arithmetic that direct string manipulation would require, especially around variable numbers of slashes."),
        ("What if the input had trailing slashes?", "Splitting on '/' naturally produces a trailing empty string in that case, which the 'skip empty' rule already discards, so trailing slashes are handled without any special-casing."),
        ("Can you avoid using Python's split entirely?", "Yes, I could manually scan character by character and build tokens between slashes myself, which would still be O(n) time and space, just with more manual bookkeeping \u2014 split() is simply cleaner to write and reason about."),
        ("What about relative paths (not starting with '/')?", "This problem specifies an absolute Unix-style path, so I'm assuming a leading slash; if relative paths needed support, I'd clarify how '..' should behave when the stack is empty (whether to keep '..' as a literal token instead of discarding it)."),
    ],
    mistakes=[
        "Forgetting to guard the pop with 'if stack', causing an error when '..' appears at the root.",
        "Not skipping empty strings that arise from consecutive slashes, resulting in bogus stack entries.",
        "Confusing '.' (current directory, ignore) with '..' (parent directory, pop).",
        "Adding a trailing slash to the final joined result when the problem expects none (except for the root itself).",
    ],
    recovery=[
        "If stuck: 'Let me not think about this as raw string surgery \u2014 if I split on slashes, each piece is either something to push, something to pop, or something to ignore, which sounds like a stack.'",
        "If I get an index error from popping an empty stack: add the 'if stack' guard and explain why '..' at the root should be a no-op, not an error.",
        "If the interviewer hints 'think about how a shell resolves cd ..': confirm that's literally the stack pop behavior being modeled.",
        "If I'm unsure about repeated slashes: trace a small example with '//' in it to confirm empty strings are correctly skipped.",
    ],
    pattern_recognition=dict(
        triggers="'Unix path', 'simplify path', 'canonical path', './ and ../'",
        pattern="Stack (directory push/pop simulation)",
        first_thought="Split into path components, then treat directory traversal as stack pushes ('name') and pops ('..').",
        trap="Forgetting to guard against popping an empty stack when '..' appears at the root.",
    ),
    memory_hook="Simplify Path \u2192 \"Split by slash; real names push, '..' pops, '.' does nothing.\"",
    recap_key_idea="Split the path into components and use a stack to push directory names and pop on '..'.",
    recap_data_structure="A stack (list) of directory names.",
    recap_algorithm="Single pass over split components with push/pop/skip rules.",
    recap_time="O(n)", recap_space="O(n)", recap_edge_case="'..' appearing at the root (must not error or go negative).",
    talk_track=[
        ("Interviewer", "Simplify this absolute Unix-style file path into its canonical form."),
        ("Me", "Got it \u2014 I need to resolve '.', '..', and collapse repeated slashes, and if '..' would go above the root, it just stays at the root, right?"),
        ("Interviewer", "Yes."),
        ("Me", "A naive approach would be manipulating the raw string directly, searching backward for slashes whenever I hit '..', but that gets fragile and can be O(n\u00b2)."),
        ("Interviewer", "How would you simplify it?"),
        ("Me", "I'd split the path on '/' into components, then use a stack: skip empty pieces and single dots, pop on double-dot if there's something to pop, and push any real directory name."),
        ("Me", "Let me code that, then join the stack with '/' and prepend a leading slash at the end."),
        ("Me", "Tracing '/a/./b/../../c/': 'a' and 'b' get pushed then both popped by the two '..'s, and 'c' gets pushed, giving '/c'."),
        ("Me", "Edge case: if the path tries to go above the root, like '/../', I guard the pop so it just stays at the root and returns '/'."),
        ("Me", "Final complexity: O(n) time and space for the split and stack operations."),
    ],
))
