\
PROBLEMS = []

PROBLEMS.append(dict(
    title="Maximum Subarray", lc_num="53", difficulty="MEDIUM", pattern="Dynamic Programming (Kadane's Algorithm)",
    relevance="Common interview pattern",
    restate="We're given an array of integers, possibly including negative numbers, and we need to find the contiguous subarray with the largest sum, then return that sum.",
    clarify_questions=[
        "Can the array be empty, or is it guaranteed to have at least one element?",
        "Are negative numbers allowed, and could the whole array be negative?",
        "Do we need to return the subarray itself, or just the sum?",
        "Is there a size constraint on the array that would rule out an O(n²) approach?",
    ],
    restate_say=["So just to confirm — I'm given an array that can contain negative numbers, and I need to find the maximum possible sum of any contiguous run of elements, correct? And if everything is negative, I should still return the largest single element rather than an empty subarray?"],
    brute_idea="Try every possible subarray: for each starting index, extend the ending index one step at a time, keep a running sum, and track the best sum seen across all of them.",
    brute_say=["The brute-force way is to check every pair of start and end indices, compute the sum of that subarray, and keep track of the maximum sum found so far."],
    brute_time="For every start index we scan forward to every end index, so we're doing roughly n choices of start times n choices of end, giving O(n²) work just to enumerate sums (and O(n³) if we recompute each sum from scratch instead of extending a running total).",
    brute_space="We only need a couple of variables to track the current sum and the best sum, so it's O(1) extra space.",
    brute_complexity_say="This is O(n²) time because for every starting index I'm re-scanning forward through the rest of the array, and O(1) space since I'm not storing anything beyond a couple of running totals.",
    bottleneck="We're recomputing sums for overlapping subarrays over and over. If I already know the best sum ending at index i, I don't need to start over from scratch at index i+1 — I can reuse that information.",
    bottleneck_say="The bottleneck is that we keep re-summing overlapping ranges of the array instead of reusing the sum we already computed for a slightly shorter subarray.",
    optimization_explain="This is Kadane's Algorithm, a one-pass Dynamic Programming approach. At each index, I ask one question: is it better to extend the previous subarray by adding the current number, or is the previous subarray dragging me down so much that I should just start fresh at the current number? I keep a running 'best sum ending here' value, and separately track the overall best sum seen so far.",
    key_insight="If the running sum ever goes negative, it can only hurt any future subarray, so the optimal choice is to drop it and restart the running sum at the current element. This is the same idea as 'sunk cost' — a negative prefix is never worth carrying forward.",
    optimization_say=[
        "I can avoid recomputation by keeping a running sum as I scan left to right.",
        "At each element, I decide whether to extend the current subarray or start a new one here, whichever gives a bigger sum.",
        "I'll also keep a separate variable for the best sum I've seen across the whole scan, since the best subarray might have ended earlier."
    ],
    code_blocks=[
        dict(code="def max_subarray(nums):\n    current_sum = nums[0]\n    best_sum = nums[0]",
             say="I'm initializing both my running sum and my best answer to the first element, not to zero.",
             why="Starting at zero would be wrong if every number in the array is negative — we'd incorrectly allow an empty subarray with sum 0. Starting from nums[0] guarantees we always pick at least one real element."),
        dict(code="    for i in range(1, len(nums)):\n        current = nums[i]\n        if current_sum < 0:\n            current_sum = current\n        else:\n            current_sum = current_sum + current",
             say="For each new number, I check whether my running sum has gone negative. If it has, it's not helping me, so I restart the subarray at the current number. Otherwise, I extend the subarray by adding the current number.",
             why="A negative running sum can only reduce any future total, so keeping it around is strictly worse than dropping it and starting over at the current index."),
        dict(code="        if current_sum > best_sum:\n            best_sum = current_sum\n\n    return best_sum",
             say="After updating the running sum, I compare it against the best sum I've recorded so far, and update if this is a new maximum. At the end I return the best sum found.",
             why="The best subarray might not end at the very last index, so I have to check after every single step, not just once at the end."),
    ],
    dry_run="nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]. Start: current_sum = best_sum = -2. i=1 (val 1): current_sum was -2 (negative) so restart -> current_sum = 1; best_sum = 1. i=2 (val -3): current_sum = 1 + (-3) = -2; best_sum stays 1. i=3 (val 4): current_sum was -2 (negative) so restart -> current_sum = 4; best_sum = 4. i=4 (val -1): current_sum = 4 - 1 = 3; best_sum stays 4. i=5 (val 2): current_sum = 3 + 2 = 5; best_sum = 5. i=6 (val 1): current_sum = 5 + 1 = 6; best_sum = 6. i=7 (val -5): current_sum = 6 - 5 = 1; best_sum stays 6. i=8 (val 4): current_sum = 1 + 4 = 5; best_sum stays 6. Final answer: 6, from subarray [4, -1, 2, 1].",
    dry_run_say="Let me walk through [-2, 1, -3, 4, -1, 2, 1, -5, 4]. I'll track current_sum and best_sum at each step... and I land on 6, which matches the subarray [4, -1, 2, 1].",
    edge_case="All-negative array, e.g. nums = [-3, -1, -2]. current_sum and best_sum start at -3. At -1: current_sum was -3 (negative), restart to -1; best_sum becomes -1. At -2: current_sum was -1 (negative), restart to -2; best_sum stays -1. Final answer -1, the least negative single element, which is correct since we must pick at least one element.",
    edge_case_say="Let me test the case where every number is negative, like [-3, -1, -2], to make sure I don't accidentally return 0 for an 'empty' subarray. Walking through it, I get -1, which is the best single element — exactly what's expected.",
    other_edge_cases=[
        "Single-element array (answer is just that element)",
        "Array where the maximum subarray is the entire array",
        "Array with a single very large positive number surrounded by negatives",
        "Array containing zeros mixed with negatives and positives",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="The final solution runs in O(n) time because I make exactly one pass through the array, and it uses O(1) extra space because I only keep two running variables.",
    pushback=[
        ("Can you do it without extra space?", "We're already at O(1) extra space — the running sum and best sum are the only variables we use, so there's nothing further to strip out."),
        ("Can you also return the actual subarray, not just the sum?", "Yes — I'd track a start and end index. Whenever I restart current_sum at index i, I set a temporary start pointer to i. Whenever best_sum updates, I record the current start and the current index i as the end."),
        ("Can you solve it with Divide and Conquer instead?", "Yes, that's the classic alternative: split the array in half, recursively find the best subarray fully in the left half and fully in the right half, then find the best subarray that crosses the midpoint, and take the max of the three. That's O(n log n), which is worse than Kadane's O(n), so I'd mention it but prefer the linear approach."),
        ("What if all numbers are positive?", "Then the best subarray is always the entire array, and Kadane's algorithm naturally arrives at that since current_sum never needs to reset."),
    ],
    mistakes=[
        "Initializing current_sum or best_sum to 0 instead of nums[0] — breaks on all-negative arrays. Catch it by testing an all-negative example.",
        "Resetting current_sum to 0 instead of to the current element when it goes negative.",
        "Forgetting to update best_sum on every iteration, not just when a reset happens.",
        "Confusing 'largest subarray sum' with 'largest subarray length' — they're different problems.",
    ],
    recovery=[
        "If I don't see the optimized solution: 'I have a brute-force O(n²) solution scanning every subarray. Let me think about what I'm recomputing — each new subarray sum overlaps almost entirely with the previous one, so I should be able to update it incrementally instead of rescanning.'",
        "If I make a coding mistake: point it out myself — 'Wait, I initialized this to 0, but that breaks if all numbers are negative, let me fix that to nums[0].'",
        "If the interviewer hints 'what if you track a running best as you go': respond 'Right, so instead of storing all subarray sums, I keep one running sum and reset it when it turns negative — that's Kadane's algorithm.'",
        "If I forget the exact name 'Kadane's algorithm', that's fine — just describe the running-sum idea in plain language; the interviewer cares about the reasoning, not the name.",
    ],
    pattern_recognition=dict(
        triggers="'contiguous subarray', 'maximum sum', 'largest sum subarray'",
        pattern="Dynamic Programming / Kadane's Algorithm (one-pass running optimum)",
        first_thought="Can I express the answer at index i in terms of the answer at index i-1? If yes, I likely don't need to rescan from scratch.",
        trap="Forgetting that a subarray must be non-empty and contiguous, and initializing sums to 0 instead of the first element.",
    ),
    memory_hook="Maximum Subarray → \"A negative running sum is dead weight — drop it and start fresh.\"",
    recap_key_idea="At each index, either extend the running subarray or restart it here, whichever gives more.",
    recap_data_structure="Two scalar variables (current_sum, best_sum) — no extra data structure needed.",
    recap_algorithm="Kadane's Algorithm: single left-to-right pass, reset running sum when negative.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="All-negative array — must not default to 0.",
    talk_track=[
        ("Interviewer", "Given an integer array, find the contiguous subarray with the largest sum."),
        ("Me", "So just to confirm, the array can include negative numbers, and I need to return the maximum sum of any contiguous run, right? Should I return the subarray or just the sum?"),
        ("Interviewer", "Just the sum is fine."),
        ("Me", "Okay. The brute-force way would be to check every possible start and end pair and sum each subarray, keeping the best one."),
        ("Interviewer", "What's the complexity of that?"),
        ("Me", "That's O(n²) since for each start index I scan forward through the rest of the array, and O(1) space."),
        ("Interviewer", "Can you optimize it?"),
        ("Me", "Yes — the brute force keeps re-summing overlapping ranges. Instead, I can scan once and keep a running sum: at each step, if that running sum has gone negative, it can only hurt me going forward, so I drop it and restart at the current element. I'll track the best sum separately as I go."),
        ("Me", "Let me code that up. I'm initializing both current_sum and best_sum to the first element, not zero, because the array could be all negative."),
        ("Me", "Now let me trace through [-2, 1, -3, 4, -1, 2, 1, -5, 4] to double check... and I land on 6, matching subarray [4, -1, 2, 1]."),
        ("Me", "Let me also check an all-negative input like [-3, -1, -2] to make sure I don't wrongly return 0 — and yes, I correctly get -1."),
        ("Me", "So the final solution runs in O(n) time with one pass, and O(1) extra space."),
    ],
))

PROBLEMS.append(dict(
    title="Maximum Product Subarray", lc_num="152", difficulty="MEDIUM", pattern="Dynamic Programming (Tracking Max & Min)",
    relevance="Advanced pattern (good follow-up to Maximum Subarray)",
    restate="We're given an array of integers and need to find the contiguous subarray with the largest product, then return that product.",
    clarify_questions=[
        "Can the array contain zero, and if so, does that reset the running product?",
        "Can the array contain negative numbers?",
        "Is the array guaranteed to be non-empty?",
        "Do we need the subarray itself, or just the maximum product value?",
    ],
    restate_say=["Just to confirm, I need the contiguous subarray with the largest product, and the array can contain zeros and negative numbers, which is what makes this trickier than the sum version, right?"],
    brute_idea="Check every subarray, compute its product, and keep the maximum. This mirrors the brute force for Maximum Subarray but with multiplication instead of addition.",
    brute_say=["The brute-force approach checks every start and end pair, multiplies out that subarray, and tracks the best product seen."],
    brute_time="We have roughly n choices for the start and n for the end, and multiplying out each subarray from scratch costs another O(n), giving O(n³) naively, or O(n²) if we extend a running product instead of recomputing.",
    brute_space="O(1) extra space beyond the running product and best answer.",
    brute_complexity_say="This is O(n²) time if I extend a running product per start index, and O(1) space since I only track a couple of numbers.",
    bottleneck="Unlike sums, a negative number can flip a very negative running product into the largest positive product, so I can't just track a single running best like in Kadane's — the bottleneck is that a single 'best so far' isn't enough information.",
    bottleneck_say="The issue is that multiplying by a negative number can turn my worst running product into my best one, so tracking only a maximum isn't enough information to carry forward.",
    optimization_explain="This is still a one-pass Dynamic Programming scan, but I track TWO running values at each index: the maximum product ending here, and the minimum (most negative) product ending here. When I hit a negative number, the max and min swap roles, because multiplying the smallest (most negative) number by another negative can produce the largest positive number.",
    key_insight="Because two negatives make a positive, the 'best product ending here' might come from continuing the most negative running product, not the most positive one. Tracking both max and min ending at each index covers this.",
    optimization_say=[
        "I'll keep two running values at each index: the max product ending here and the min product ending here.",
        "At each new number, I compute candidates using the current number alone, the current number times the previous max, and the current number times the previous min, then take the new max and min from those three candidates.",
        "I update the global best whenever the running max exceeds it.",
    ],
    code_blocks=[
        dict(code="def max_product(nums):\n    result = nums[0]\n    current_max = nums[0]\n    current_min = nums[0]",
             say="I initialize the result, current_max, and current_min all to the first element.",
             why="Just like Maximum Subarray, starting at the first real element (not 0 or infinity) handles arrays that are all negative or contain just one element."),
        dict(code="    for i in range(1, len(nums)):\n        num = nums[i]\n        if num < 0:\n            current_max, current_min = current_min, current_max",
             say="If the current number is negative, I swap current_max and current_min before combining them with num, since multiplying by a negative flips which one becomes bigger.",
             why="This swap is the key trick: without it, multiplying a negative num by the previous current_max could wrongly become the new current_min instead of a candidate for current_max."),
        dict(code="        current_max = max(num, current_max * num)\n        current_min = min(num, current_min * num)\n        result = max(result, current_max)\n\n    return result",
             say="I update current_max and current_min by either starting fresh at num or extending the previous run, then update my overall result if current_max is a new best.",
             why="Starting fresh at num handles the case where the running product has become worse than just restarting, exactly like the reset logic in Kadane's algorithm."),
    ],
    dry_run="nums = [2, 3, -2, 4]. Start: result=cur_max=cur_min=2. i=1 (3): not negative. cur_max=max(3, 2*3)=6, cur_min=min(3, 2*3)=3. result=max(2,6)=6. i=2 (-2): negative, so swap cur_max/cur_min -> cur_max=3, cur_min=6. Then cur_max=max(-2, 3*-2)=max(-2,-6)=-2, cur_min=min(-2, 6*-2)=min(-2,-12)=-12. result stays 6. i=3 (4): not negative. cur_max=max(4, -2*4)=max(4,-8)=4, cur_min=min(4,-12*4)=min(4,-48)=-48. result=max(6,4)=6. Final answer: 6.",
    dry_run_say="Walking through [2, 3, -2, 4]: the running max builds up to 6 with [2,3], then the -2 tanks things, and 4 alone can't beat 6, so the final answer stays 6.",
    edge_case="Array containing a zero, e.g. [-2, 0, -1]. At num=0: not negative, cur_max=max(0, -2*0)=0, cur_min=min(0,-2*0)=0, result=max(-2,0)=0. At num=-1: negative, swap cur_max/cur_min (both 0, no change), cur_max=max(-1, 0*-1)=max(-1,0)=0, cur_min=min(-1,0*-1)=-1. result stays max(0,0)=0. Final answer 0, correct because zero acts as a hard reset point.",
    edge_case_say="Let me test an array with a zero in it, like [-2, 0, -1], since zero should act like a wall that resets the running product — and the trace confirms it correctly resets to 0 and the final answer is 0.",
    other_edge_cases=[
        "Single-element array, including a single negative number",
        "Array with an even count of negative numbers (best product is the whole array)",
        "Array with an odd count of negative numbers separated by zeros",
        "All-zero array",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This runs in O(n) time since it's a single pass, and O(1) space because I only track a constant number of running values.",
    pushback=[
        ("Why do you need to track both max and min?", "Because multiplying two negative numbers gives a positive result, the best product ending at some index might come from continuing the smallest (most negative) running product rather than the largest, so I need both to correctly compute the next step."),
        ("Can you avoid the swap logic?", "Yes, an alternative is to compute both candidate products (num*current_max and num*current_min) without swapping, and just take max()/min() over all three candidates (num, num*current_max, num*current_min) directly — the swap is just a small optimization/clarity trick, not strictly required."),
        ("What if there are multiple zeros?", "Zeros break the array into independent segments, since any subarray crossing a zero has product zero. My reset logic (max(num, current_max*num)) naturally restarts at each zero, so segments are handled correctly without special-casing."),
        ("Can you solve this differently?", "Yes, one alternative is to split the array on zeros into segments, and for each segment count leading/trailing negatives to figure out the best product by trimming from one end if there's an odd number of negatives. It's more complex to reason about, so I'd prefer the DP approach."),
    ],
    mistakes=[
        "Forgetting to swap current_max and current_min when the number is negative.",
        "Initializing result/current_max/current_min to 1 or 0 instead of nums[0].",
        "Only tracking a running max like in Maximum Subarray, forgetting that products need the min too.",
        "Not handling zero correctly (it should act as a natural reset, not a special case).",
    ],
    recovery=[
        "If stuck: 'This is like Maximum Subarray, but products flip sign with negative numbers, so a single running max might not be enough — let me think about what a negative number does to the smallest running product.'",
        "If I forget the swap trick mid-code: just write it as three candidates — max(num, num*current_max, num*current_min) — and reason out loud that this covers the same cases.",
        "If the interviewer hints 'what about very negative numbers': say 'Right, a very negative running product times another negative could become my new maximum, so I need to track the minimum too.'",
        "If I realize my first attempt (single running max) is wrong: 'Let me reconsider — I think I need to also track the minimum product ending here, since two negatives multiply into a positive.'",
    ],
    pattern_recognition=dict(
        triggers="'maximum product subarray', 'contiguous subarray product'",
        pattern="Dynamic Programming with dual running state (max AND min)",
        first_thought="Sums only need a running max; products need both a running max and running min because sign can flip.",
        trap="Tracking only current_max and missing that current_min can become the new current_max after a negative number.",
    ),
    memory_hook="Maximum Product → \"Two negatives make a positive — track the min too, not just the max.\"",
    recap_key_idea="Track both running max and running min ending at each index; negative numbers swap their roles.",
    recap_data_structure="Three scalars: result, current_max, current_min.",
    recap_algorithm="One-pass DP with max/min swap on negative numbers.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Array containing zero(s), which should reset the running product.",
    talk_track=[
        ("Interviewer", "Find the contiguous subarray with the largest product."),
        ("Me", "Got it — and the array can include negatives and zeros? That's the tricky part compared to the sum version."),
        ("Interviewer", "Yes, assume both are possible."),
        ("Me", "Brute force would check every subarray's product directly, which is O(n²) if I extend a running product per start index."),
        ("Interviewer", "Can you do better?"),
        ("Me", "Yes. Similar to Kadane's for sums, but here a negative number can flip my worst running product into my best, since two negatives multiply into a positive. So I'll track both a running max and a running min ending at each index."),
        ("Me", "When I hit a negative number, I'll swap max and min before combining with the current number, since that's exactly when the flip happens."),
        ("Me", "Let me trace [2, 3, -2, 4] to be sure... the max builds to 6, dips at -2, and 4 alone doesn't beat it, so I get 6."),
        ("Me", "Let me also check a zero case, like [-2, 0, -1], to make sure zero correctly resets things — yes, it does, landing on 0."),
        ("Me", "Final complexity is O(n) time, one pass, and O(1) space, just three running variables."),
    ],
))

PROBLEMS.append(dict(
    title="Group Anagrams", lc_num="49", difficulty="MEDIUM", pattern="Hash Map",
    relevance="Common interview pattern",
    restate="We're given a list of strings, and we need to group together all the strings that are anagrams of each other, returning the groups in any order.",
    clarify_questions=[
        "Can the list contain empty strings?",
        "Are all strings guaranteed to be lowercase letters, or could there be other characters/case differences?",
        "Does the order of groups or the order of strings within a group matter?",
        "How large can the strings and the list get — does that rule out per-pair comparisons?",
    ],
    restate_say=["So I need to bucket the strings such that any two strings in the same bucket are anagrams of each other, and return those buckets. Order doesn't matter, correct?"],
    brute_idea="For each string, compare it against every other string by sorting both and checking if the sorted versions match, building up groups as I go.",
    brute_say=["The brute-force way is to compare every pair of strings — sort each one and check if they're equal — and merge them into the same group if they match."],
    brute_time="Comparing every pair is O(n²), and sorting each string of length k costs O(k log k), so overall it's O(n² * k log k).",
    brute_space="We need O(n * k) space to store the groups themselves.",
    brute_complexity_say="This is roughly O(n² k log k) time because I'm comparing every pair of strings and sorting them each time I compare, which is quite wasteful.",
    bottleneck="I'm re-sorting and re-comparing strings against every other string, when really I just need one consistent 'signature' per string so identical signatures automatically land in the same group.",
    bottleneck_say="The bottleneck is redundant pairwise comparisons — I don't need to compare strings directly if I can compute a canonical signature that's identical for all anagrams.",
    optimization_explain="I use a Hash Map where the key is a canonical signature for a string (its sorted characters) and the value is the list of original strings that share that signature. Since anagrams contain exactly the same characters, sorting any anagram of a word always produces the same string, so all anagrams collapse to the same key automatically.",
    key_insight="Two strings are anagrams if and only if their sorted character sequences are identical, so sorting gives a canonical key you can hash on, turning grouping into a single pass with O(1) average lookups.",
    optimization_say=[
        "For each string, I'll sort its characters to get a canonical key.",
        "I'll use a hash map from that sorted key to a list of original strings.",
        "Anagrams will always produce the same sorted key, so they'll land in the same bucket automatically, without ever comparing strings to each other directly.",
    ],
    code_blocks=[
        dict(code="def group_anagrams(strs):\n    groups = {}",
             say="I'm creating a dictionary that will map a sorted-character key to the list of original words sharing that key.",
             why="A hash map lets me look up 'does this signature already exist' in O(1) average time instead of scanning existing groups."),
        dict(code="    for word in strs:\n        key = ''.join(sorted(word))\n        if key not in groups:\n            groups[key] = []\n        groups[key].append(word)",
             say="For each word, I sort its letters to build the key, create a new list the first time I see that key, and append the original word to it.",
             why="Sorting normalizes any anagram of the same letters into one identical string, which is exactly the property that lets the hash map group them for free."),
        dict(code="    return list(groups.values())",
             say="Finally, I return just the grouped lists of original words, not the keys.",
             why="The problem only asks for the groups themselves; the sorted keys were only a means to group them."),
    ],
    dry_run="strs = ['eat','tea','tan','ate','nat','bat']. 'eat'->key 'aet', new group ['eat']. 'tea'->key 'aet', append -> ['eat','tea']. 'tan'->key 'ant', new group ['tan']. 'ate'->key 'aet', append -> ['eat','tea','ate']. 'nat'->key 'ant', append -> ['tan','nat']. 'bat'->key 'abt', new group ['bat']. Final: [['eat','tea','ate'], ['tan','nat'], ['bat']].",
    dry_run_say="Walking through the example list, 'eat', 'tea', and 'ate' all sort to 'aet' so they land in one group, 'tan' and 'nat' sort to 'ant', and 'bat' is on its own — matching the expected grouping.",
    edge_case="Empty string in the list, e.g. strs = ['']. Its sorted key is also '' (empty string), so it forms its own single-element group [''] — handled correctly with no special casing.",
    edge_case_say="Let me check an edge case with an empty string in the input — it sorts to itself, an empty key, and just becomes its own group, so no special-casing is needed.",
    other_edge_cases=[
        "A list with only one string",
        "All strings being anagrams of each other (one big group)",
        "No strings being anagrams of each other (every string its own group)",
        "Duplicate identical strings (they belong in the same group)",
    ],
    final_complexity_rows=[["Optimized", "O(n * k log k)", "O(n * k)"]],
    final_complexity_say="The final solution is O(n times k log k) time, where n is the number of strings and k is the max string length, because I sort each string once, and O(n times k) space to store all the strings in the hash map.",
    pushback=[
        ("Can you avoid sorting each string?", "Yes — since we likely only have lowercase letters, I can build a 26-length count array for each word as the key instead of sorting, which drops the per-word cost from O(k log k) to O(k)."),
        ("Why does sorting work as a key?", "Because an anagram is just a rearrangement of the same multiset of characters, and sorting is a canonical form — any rearrangement of the same characters always sorts to the identical string."),
        ("What if the strings contain unicode or mixed case?", "I'd clarify whether case should be treated as significant; if not, I'd lowercase first before sorting/counting so 'Eat' and 'tea' still group together."),
        ("Can you optimize further?", "The count-array approach is already linear per string, so the overall O(n*k) time (down from O(n*k log k)) is close to optimal since we must at least read every character of every string once."),
    ],
    mistakes=[
        "Forgetting to initialize a new list before appending to a hash map key the first time it's seen.",
        "Using the original (unsorted) word as the key instead of the sorted version.",
        "Assuming string order within a group matters when the problem allows any order.",
        "Not considering case sensitivity or non-letter characters if the constraints allow them.",
    ],
    recovery=[
        "If stuck: 'I know I need some canonical form that's identical for all anagrams of a word — sorting the characters gives me exactly that.'",
        "If I forget Python's sorted() returns a list: remember to join it back into a string with ''.join(sorted(word)) since dict keys need to be hashable strings, not lists.",
        "If the interviewer hints 'can you avoid sorting': pivot to the character-count array trick and explain the O(k) vs O(k log k) tradeoff.",
        "If I mislabel a group: re-trace by hand which sorted key each word maps to before continuing.",
    ],
    pattern_recognition=dict(
        triggers="'group anagrams', 'group strings that are permutations of each other'",
        pattern="Hash Map with a canonical signature as the key",
        first_thought="What single deterministic value can represent all variations of the same 'thing' so I can bucket them in one pass?",
        trap="Comparing strings pairwise instead of computing one signature per string.",
    ),
    memory_hook="Group Anagrams → \"Sort the letters, and identical anagrams sort to identical keys.\"",
    recap_key_idea="Sorted characters (or a 26-count signature) act as a canonical key that's identical for all anagrams.",
    recap_data_structure="Hash map from signature to list of original strings.",
    recap_algorithm="Single pass: compute signature, append to bucket.",
    recap_time="O(n k log k) [or O(n k) with counting]", recap_space="O(n k)", recap_edge_case="Empty string as one of the inputs.",
    talk_track=[
        ("Interviewer", "Group these strings by anagram."),
        ("Me", "So any two strings with the same letters in the same counts go in the same group, and order doesn't matter, right?"),
        ("Interviewer", "Correct."),
        ("Me", "Brute force would be comparing every pair of strings by sorting and checking equality — that's roughly O(n² k log k), too slow if the list is big."),
        ("Interviewer", "How would you speed it up?"),
        ("Me", "I'd use a hash map. If I sort each string's letters, every anagram of the same word produces the identical sorted string, so I can use that as a key and just append to the matching bucket in one pass."),
        ("Me", "Let me code that... for each word I compute the sorted key, initialize a list if it's new, and append the original word."),
        ("Me", "Tracing through ['eat','tea','tan','ate','nat','bat'], eat/tea/ate all map to key 'aet', tan/nat map to 'ant', and bat is alone — matches what's expected."),
        ("Me", "One thing to check — an empty string just becomes its own group with an empty key, no special case needed."),
        ("Me", "Final complexity is O(n k log k) time for sorting each string once, and O(n k) space for storing everything."),
        ("Interviewer", "Can you avoid the log k factor?"),
        ("Me", "Yes, I could use a 26-element character count tuple as the key instead of sorting, bringing it down to O(n k)."),
    ],
))

PROBLEMS.append(dict(
    title="Product of Array Except Self", lc_num="238", difficulty="MEDIUM", pattern="Prefix / Suffix Products",
    relevance="Common interview pattern",
    restate="We're given an array of numbers, and for every index we need to return the product of all the other elements, without using division, ideally in O(n) time.",
    clarify_questions=[
        "Am I allowed to use division? (Usually the problem explicitly forbids it.)",
        "Can the array contain zero, or multiple zeros?",
        "Can the array contain negative numbers?",
        "Does the output array count against the O(1) extra space constraint, if one exists?",
    ],
    restate_say=["Just to confirm, for each index I return the product of every other element, division isn't allowed, and I should assume the array could contain zeros, correct?"],
    brute_idea="For every index, loop through the rest of the array and multiply all the other elements together directly.",
    brute_say=["The brute-force approach is, for each index, to loop over the whole array again and multiply everything except that index."],
    brute_time="For each of the n indices we do an O(n) inner loop, giving O(n²) total.",
    brute_space="O(1) extra space beyond the output array.",
    brute_complexity_say="This is O(n²) time because for every element I'm re-scanning the entire array to compute its product, and O(1) extra space not counting the output.",
    bottleneck="I'm recomputing overlapping products from scratch for every index, when the product to the left of index i and to the right of index i can each be built incrementally and reused.",
    bottleneck_say="The bottleneck is repeatedly multiplying the same ranges of the array for each index instead of reusing previously computed prefix and suffix products.",
    optimization_explain="I use Prefix and Suffix products. First I build an array where each position holds the product of everything to its left. Then I sweep from the right, multiplying in the product of everything to that position's right. The answer at each index is just prefix[i] * suffix[i], computed without ever dividing.",
    key_insight="The product of everything except index i is exactly (product of everything before i) times (product of everything after i) — two smaller, incrementally-buildable pieces instead of one big recomputation.",
    optimization_say=[
        "I'll do two passes over the array.",
        "First pass, left to right, builds a running prefix product and stores it in the result array.",
        "Second pass, right to left, multiplies in a running suffix product on top of what's already stored, giving the final answer with no division needed.",
    ],
    code_blocks=[
        dict(code="def product_except_self(nums):\n    n = len(nums)\n    result = [1] * n",
             say="I initialize a result array of all 1s, the same length as the input.",
             why="1 is the multiplicative identity, so it's the correct starting value before any real products have been multiplied in."),
        dict(code="    prefix = 1\n    for i in range(n):\n        result[i] = prefix\n        prefix = prefix * nums[i]",
             say="I walk left to right keeping a running prefix product. Before including nums[i] itself, I store the prefix so far into result[i], then update the running prefix to include nums[i].",
             why="Storing before multiplying in nums[i] ensures result[i] holds the product of everything strictly to the left of i, not including i itself."),
        dict(code="    suffix = 1\n    for i in range(n - 1, -1, -1):\n        result[i] = result[i] * suffix\n        suffix = suffix * nums[i]\n\n    return result",
             say="Now I walk right to left keeping a running suffix product, multiplying it into the existing result[i], then updating the suffix to include nums[i].",
             why="This combines the left-side product already stored with the right-side product being built, giving the full 'everything except index i' product with no division."),
    ],
    dry_run="nums = [1,2,3,4]. Prefix pass: prefix=1; result[0]=1, prefix=1*1=1; result[1]=1, prefix=1*2=2; result[2]=2, prefix=2*3=6; result[3]=6, prefix=6*4=24. result=[1,1,2,6]. Suffix pass: suffix=1; i=3: result[3]=6*1=6, suffix=1*4=4; i=2: result[2]=2*4=8, suffix=4*3=12; i=1: result[1]=1*12=12, suffix=12*2=24; i=0: result[0]=1*24=24, suffix=24*1=24. Final result=[24,12,8,6].",
    dry_run_say="Tracing [1,2,3,4]: after the prefix pass I have [1,1,2,6], and after folding in the suffix pass right to left I get [24,12,8,6], which matches 2*3*4, 1*3*4, 1*2*4, 1*2*3.",
    edge_case="Array containing a single zero, e.g. [1,2,0,4]. Prefix pass gives result=[1,1,2,0] (prefix becomes 0 once it passes index 2). Suffix pass multiplies in everything to the right of the zero for index 2 specifically, while every other index's answer becomes 0 because the zero is included in either their prefix or suffix. Final result=[0,0,8,0], correctly giving a nonzero answer only at the zero's own position.",
    edge_case_say="Let me test an array with one zero in it, like [1,2,0,4], since that's the trickiest case — every position except the zero's own index should become 0, and the zero's own position should get the product of everything else. Tracing it through confirms result=[0,0,8,0].",
    other_edge_cases=[
        "Array with two or more zeros (every output becomes 0)",
        "Array with negative numbers (sign should be handled naturally by regular multiplication)",
        "Very small array of length 2",
        "Array where all elements are 1",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1) extra (excl. output)"]],
    final_complexity_say="This is O(n) time because I make exactly two linear passes over the array, and O(1) extra space besides the output array, since prefix and suffix are just single running variables.",
    pushback=[
        ("Can you do it without extra space at all?", "The output array itself is required by the problem, but I'm not using any other array — the prefix and suffix are scalars, so I'm already at O(1) additional space beyond the mandated output."),
        ("Why can't you just use division?", "Some interviewers forbid division specifically because it breaks when any element is zero (or there are multiple zeros), and the problem statement usually disallows it explicitly for that reason."),
        ("What if there are multiple zeros?", "Then every position's answer is 0, because any product excluding one zero still includes at least one other zero. My prefix/suffix approach handles this automatically without special-casing, since multiplying by 0 naturally zeroes things out."),
        ("Can you optimize further?", "We must produce n outputs, so O(n) time is optimal; there's no faster complexity class possible here."),
    ],
    mistakes=[
        "Storing prefix product AFTER multiplying in nums[i] instead of before, which would incorrectly include nums[i] itself.",
        "Using two full extra arrays for prefix and suffix instead of folding the suffix pass directly into the result array.",
        "Trying to use division as a shortcut, which breaks on zeros and is often explicitly disallowed.",
        "Off-by-one errors in the range() bounds for the suffix (backward) loop.",
    ],
    recovery=[
        "If stuck: 'Since I can't use division, let me think of the answer at each index as two independent pieces — everything to the left, and everything to the right — and see if I can build those incrementally.'",
        "If I mix up when to store vs. update: pause and clarify out loud, 'result[i] should be the product BEFORE including nums[i], so I store first, then multiply.'",
        "If the interviewer hints 'think about two directions': respond 'Right, one pass for prefix products left to right, another for suffix products right to left.'",
        "If I forget syntax for the reversed range: just say 'let me loop from n-1 down to 0' and write range(n-1, -1, -1), reasoning through the bounds out loud.",
    ],
    pattern_recognition=dict(
        triggers="'product except self', 'without using division'",
        pattern="Prefix / Suffix Products (two-pass accumulation)",
        first_thought="Can I split the answer for index i into an independent left-piece and right-piece that I can compute incrementally?",
        trap="Forgetting the order of store-then-multiply in the prefix pass, or trying to sneak division back in.",
    ),
    memory_hook="Product Except Self → \"Everything to my left, times everything to my right.\"",
    recap_key_idea="Split the answer into a prefix product (left side) and suffix product (right side), computed in two passes.",
    recap_data_structure="The result/output array doubles as prefix storage; two scalar running products.",
    recap_algorithm="Left-to-right prefix pass, then right-to-left suffix pass folded into the same array.",
    recap_time="O(n)", recap_space="O(1) extra", recap_edge_case="Array containing one or more zeros.",
    talk_track=[
        ("Interviewer", "Return an array where each element is the product of all other elements, without division."),
        ("Me", "Got it — and I should assume zeros and negative numbers could appear, and division truly isn't allowed?"),
        ("Interviewer", "Correct, no division."),
        ("Me", "Brute force: for each index, loop through the rest of the array and multiply. That's O(n²) time, O(1) extra space."),
        ("Interviewer", "How do you get it faster?"),
        ("Me", "The answer at index i is just the product of everything to its left times everything to its right. I can build the left products in one left-to-right pass, then fold in the right products in one right-to-left pass — no division, no recomputation."),
        ("Me", "Let me code the prefix pass first... I store the running prefix into result[i] before multiplying nums[i] in, so it never includes itself."),
        ("Me", "Now the suffix pass, right to left, multiplies in a running suffix product on top of what's already stored."),
        ("Me", "Tracing [1,2,3,4] gives [24,12,8,6], which checks out against the expected products."),
        ("Me", "Let me also check a case with a zero, like [1,2,0,4] — everywhere except the zero's own index should become 0, and it does: [0,0,8,0]."),
        ("Me", "Final complexity: O(n) time for two linear passes, O(1) extra space beyond the output array."),
    ],
))

PROBLEMS.append(dict(
    title="Top K Frequent Elements", lc_num="347", difficulty="MEDIUM", pattern="Hash Map + Heap (or Bucket Sort)",
    relevance="Common interview pattern",
    restate="We're given an array of numbers and an integer k, and we need to return the k most frequently occurring elements.",
    clarify_questions=[
        "What should happen if there's a tie in frequency at the cutoff?",
        "Does the output order matter?",
        "Can k equal the number of distinct elements, or is it always strictly smaller?",
        "How large can the array be \u2014 does that rule out a full sort?",
    ],
    restate_say=["Just to confirm, I need to return the k elements with the highest frequency counts, and the order of the output doesn't matter, correct?"],
    brute_idea="Count the frequency of every element with a hash map, then sort all the distinct elements by frequency descending, and take the first k.",
    brute_say=["The straightforward approach is to count frequencies with a hash map, then sort the distinct elements by their counts and take the top k."],
    brute_time="Counting is O(n), but sorting the distinct elements by frequency is O(d log d) where d is the number of distinct elements, which can be O(n log n) in the worst case.",
    brute_space="O(n) for the frequency map.",
    brute_complexity_say="This is O(n log n) time in the worst case because of the sort, and O(n) space for the frequency map.",
    bottleneck="A full sort gives me way more information than I need \u2014 I only need the top k, not a total ordering of every distinct value.",
    bottleneck_say="The bottleneck is that sorting fully orders everything, when I really only need the top k frequencies, which is less information.",
    optimization_explain="I use a Min-Heap of size k (a Heap / Priority Queue pattern). I push (frequency, value) pairs onto the heap, and whenever the heap grows past size k, I pop the smallest, so the heap only ever holds the k largest frequencies seen so far. Alternatively, Bucket Sort works in true O(n): create buckets indexed by frequency (1 to n), place each value in the bucket matching its count, then read off values from the highest-frequency bucket down until we have k.",
    key_insight="You never need a full ordering to find the top k \u2014 a size-k min-heap only 'remembers' the k best candidates at any point, discarding anything that falls out of the top k as it goes.",
    optimization_say=[
        "First I count frequencies with a hash map, just like the brute force.",
        "Then, instead of sorting everything, I use a min-heap capped at size k, pushing each (count, value) pair and popping the smallest whenever the heap exceeds size k.",
        "At the end, whatever remains in the heap are exactly the k most frequent elements.",
    ],
    code_blocks=[
        dict(code="import heapq\nfrom collections import Counter\n\ndef top_k_frequent(nums, k):\n    counts = Counter(nums)\n    heap = []",
             say="I count frequencies with Counter, then set up an empty list to use as a min-heap.",
             why="Python's heapq module operates on plain lists and always maintains the smallest element at index 0, which is exactly the min-heap behavior I need."),
        dict(code="    for value, count in counts.items():\n        heapq.heappush(heap, (count, value))\n        if len(heap) > k:\n            heapq.heappop(heap)",
             say="For every distinct value, I push its (count, value) pair onto the heap. If that makes the heap bigger than k, I pop the smallest count off, keeping the heap capped at size k.",
             why="Because heapq compares tuples by their first element first, the pair with the smallest count always bubbles to the top and gets removed, guaranteeing only the k largest counts survive."),
        dict(code="    return [value for count, value in heap]",
             say="Finally I pull out just the values from the remaining heap entries and return them.",
             why="The heap only stores what we need internally as (count, value) for comparison purposes; the answer only needs the values."),
    ],
    dry_run="nums = [1,1,1,2,2,3], k=2. counts = {1:3, 2:2, 3:1}. Push (3,1) -> heap=[(3,1)]. Push (2,2) -> heap=[(2,2),(3,1)] (heap property keeps 2 on top). size=2, no pop. Push (1,3) -> heap size 3, push then pop smallest (1,3) -> heap back to [(2,2),(3,1)]. Final heap holds (2,2) and (3,1); output values = [2,1] (order may vary), matching expected top-2 frequent elements {1,2}.",
    dry_run_say="With [1,1,1,2,2,3] and k=2, after counting I get 1:3, 2:2, 3:1. Pushing all three onto the heap and popping the smallest whenever it exceeds size 2 leaves exactly {1,2} \u2014 the two most frequent values.",
    edge_case="k equals the number of distinct elements. Then the heap never needs to pop anything, and all distinct values are returned \u2014 correct, since 'top k out of exactly k' is just everything.",
    edge_case_say="Let me check when k equals the number of distinct elements \u2014 the heap just accumulates everything without ever popping, so we correctly return all of them.",
    other_edge_cases=[
        "All elements identical (only one distinct value, k=1)",
        "All elements with the same frequency (any valid k of them is acceptable)",
        "k = 1 (just the single most frequent element)",
        "Very large array with many low-frequency singletons",
    ],
    final_complexity_rows=[["Heap approach", "O(n log k)", "O(n)"], ["Bucket sort", "O(n)", "O(n)"]],
    final_complexity_say="The heap approach runs in O(n log k) time since each of the n elements does an O(log k) heap push/pop, using O(n) space for the counts and O(k) for the heap; the bucket sort alternative achieves true O(n) time and space if we need to beat log k.",
    pushback=[
        ("Can you do this in true O(n)?", "Yes \u2014 Bucket Sort. Create an array of buckets indexed 1 to n (max possible frequency), place each distinct value into the bucket matching its count, then scan from the highest-index bucket down, collecting values until we have k. Since frequency can't exceed n, this avoids any log factor."),
        ("Why use a min-heap and not a max-heap?", "A min-heap of size k lets me cheaply discard the smallest of my 'current best k' whenever a better candidate comes along, using only O(k) space; a max-heap of all n elements would need O(n) space and I'd pop k times at the end anyway, which is less efficient when k is much smaller than n."),
        ("What if there are ties in frequency at the boundary?", "The problem typically guarantees a unique answer for a given k, but if not, I'd clarify with the interviewer whether any valid set of k is acceptable or if there's a tiebreaker rule."),
        ("Can you solve it with sorting instead?", "Yes, that's the O(n log n) brute-force-plus approach; it's simpler to write but strictly slower than either the heap or bucket sort when k is small."),
    ],
    mistakes=[
        "Using a max-heap of all elements instead of a min-heap capped at size k, wasting time and space.",
        "Forgetting that heapq is a min-heap by default in Python, and needing (count, value) tuples ordered so count compares first.",
        "Off-by-one when comparing heap size to k (using >= instead of > when deciding to pop).",
        "Forgetting to extract just the values (not the counts) in the final return.",
    ],
    recovery=[
        "If stuck: 'I know full sorting works but gives more info than I need. Let me think about a structure that only tracks the top k as I go \u2014 that's a bounded-size heap.'",
        "If I confuse min-heap vs max-heap: reason out loud, 'I want to throw away the smallest of my current best k whenever something better shows up, so I need quick access to the minimum \u2014 that's a min-heap.'",
        "If the interviewer hints 'can you avoid the log factor': bring up bucket sort by frequency.",
        "If I forget heapq syntax: describe the operation in words first ('push, then pop if too big') and translate to heapq.heappush/heappop as I go.",
    ],
    pattern_recognition=dict(
        triggers="'top k frequent', 'k most common', 'kth largest/smallest'",
        pattern="Hash Map for counting + Heap (bounded to size k) or Bucket Sort",
        first_thought="I don't need a full ordering, just the top k \u2014 a size-k heap is cheaper than a full sort.",
        trap="Sorting everything when only a partial (top-k) answer is needed.",
    ),
    memory_hook="Top K Frequent \u2192 \"Count first, then keep only a heap of size k.\"",
    recap_key_idea="Count frequencies, then maintain only the top k using a bounded min-heap (or bucket sort by frequency).",
    recap_data_structure="Hash map (counts) + min-heap of size k.",
    recap_algorithm="Push (count, value), pop smallest when heap exceeds size k.",
    recap_time="O(n log k)", recap_space="O(n)", recap_edge_case="k equal to total number of distinct elements.",
    talk_track=[
        ("Interviewer", "Return the k most frequent elements in this array."),
        ("Me", "Just to confirm, output order doesn't matter, and I can assume there's a well-defined top k?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force: count frequencies with a hash map, then sort distinct values by count and take the top k. That's O(n log n) because of the sort."),
        ("Interviewer", "Can you avoid the full sort?"),
        ("Me", "Yes \u2014 I don't need a total ordering, just the top k, so I can use a min-heap capped at size k. I push each (count, value) pair, and pop the smallest whenever the heap grows past k, so only the k largest survive."),
        ("Me", "Let me code that with Python's heapq and Counter for the frequency map."),
        ("Me", "Tracing [1,1,1,2,2,3] with k=2: counts are 1:3, 2:2, 3:1, and after pushing and trimming, the heap ends up holding exactly {1,2}, matching what's expected."),
        ("Me", "Edge case: if k equals the number of distinct values, the heap never pops anything, and we just return everything \u2014 correct."),
        ("Me", "Final complexity is O(n log k) time and O(n) space for the counts."),
        ("Interviewer", "Can you get pure O(n)?"),
        ("Me", "Yes, with bucket sort by frequency \u2014 bucket index equals count, then read buckets from the top down until we've collected k values."),
    ],
))

PROBLEMS.append(dict(
    title="Find the Duplicate Number", lc_num="287", difficulty="MEDIUM", pattern="Fast & Slow Pointers (Cycle Detection)",
    relevance="Advanced pattern",
    restate="We're given an array of n+1 integers where each value is between 1 and n, and exactly one number is duplicated (possibly more than once); we need to find that duplicate, without modifying the array and using O(1) extra space.",
    clarify_questions=[
        "Am I allowed to modify the input array, or sort it?",
        "Is there a space constraint that rules out a hash set?",
        "Is there guaranteed to be exactly one duplicated value, though it may appear more than twice?",
        "Are all values guaranteed to be within the 1..n range?",
    ],
    restate_say=["So there's exactly one number that repeats, values are between 1 and n in an array of size n+1, and I shouldn't modify the input or use extra space beyond O(1) \u2014 is that right?"],
    brute_idea="Use a hash set: walk through the array, and the first value I've already seen before is the duplicate.",
    brute_say=["The simplest approach is a hash set \u2014 walk through the array and return the first value that's already in the set."],
    brute_time="O(n), one pass through the array.",
    brute_space="O(n) for the hash set, which is what we're trying to avoid.",
    brute_complexity_say="This is O(n) time but also O(n) space for the hash set, which violates the O(1) space constraint the interviewer usually wants here.",
    bottleneck="The hash set is only needed to remember 'have I seen this value before', but the numbers themselves (being in range 1..n) can be treated as pointers into the array, letting us detect the duplicate without any extra memory.",
    bottleneck_say="The bottleneck is that a hash set uses O(n) memory just to remember which values I've visited, when the array's own values can act like pointers if I think of it as a linked structure.",
    optimization_explain="Since every value points to a valid array index (values 1..n, indices 0..n), I can treat the array as a Linked List where index i 'points to' index nums[i]. Because there's a duplicate value, at least two indices point to the same place, which means this implicit linked list has a cycle. Finding a cycle with O(1) space is exactly Floyd's Tortoise and Hare algorithm: a slow pointer moves one step at a time, a fast pointer moves two steps, and where they meet is inside the cycle. Then I reset one pointer to the start and move both one step at a time; where they meet again is the cycle's entrance, which is exactly the duplicate number.",
    key_insight="A duplicate value in the 1..n range creates two 'pointers' into the same index, which is precisely the structure of a cycle in a linked list, so cycle-detection math (which normally finds where a loop begins) directly finds the duplicate number.",
    optimization_say=[
        "I'll treat the array as a linked list where value at index i tells me which index to go to next.",
        "Because of the duplicate, this implicit list has a cycle, so I use Floyd's slow/fast pointers to detect it.",
        "Once slow and fast meet, I reset one pointer to the start and advance both one step at a time \u2014 they meet again exactly at the cycle's entry point, which is the duplicate value.",
    ],
    code_blocks=[
        dict(code="def find_duplicate(nums):\n    slow = nums[0]\n    fast = nums[0]",
             say="I start both slow and fast pointers at the same starting position, nums[0].",
             why="Both pointers must start from the same place for the meeting-point math of Floyd's algorithm to correctly identify the cycle entrance later."),
        dict(code="    while True:\n        slow = nums[slow]\n        fast = nums[nums[fast]]\n        if slow == fast:\n            break",
             say="Slow moves one step (one hop through the array), fast moves two steps. I keep going until they land on the same value, which means they're both inside the cycle.",
             why="Because fast moves twice as fast as slow, if there's a cycle they're guaranteed to eventually meet somewhere inside it \u2014 this is the classic tortoise-and-hare guarantee."),
        dict(code="    slow2 = nums[0]\n    while slow2 != slow:\n        slow2 = nums[slow2]\n        slow = nums[slow]\n\n    return slow",
             say="Now I start a new pointer from the beginning and move both it and the original slow pointer one step at a time until they meet \u2014 that meeting point is the duplicate number.",
             why="This is the mathematical property of cycle detection: the distance from the start to the cycle entrance equals the distance from the meeting point to the cycle entrance, so moving both at the same speed makes them converge exactly there."),
    ],
    dry_run="nums = [1,3,4,2,2]. slow=fast=1. Step: slow=nums[1]=3, fast=nums[nums[1]]=nums[3]=2. Not equal. Step: slow=nums[3]=2, fast=nums[nums[2]]=nums[4]=2. Equal! slow=fast=2. Phase 2: slow2 starts at nums[0]=1. slow2=1, slow=2, not equal. Move: slow2=nums[1]=3, slow=nums[2]=4. Not equal. Move: slow2=nums[3]=2, slow=nums[4]=2. Equal! Return 2, the duplicate.",
    dry_run_say="Tracing [1,3,4,2,2]: the two pointers meet inside the cycle at value 2 after a couple of steps, then the second phase \u2014 resetting one pointer and moving both together \u2014 also converges at 2, which is indeed the duplicate.",
    edge_case="The duplicate appears more than twice, e.g. [2,2,2,2,2] is invalid (breaks the 'array of n+1 with values 1..n' shape for n=4 requiring 5 elements) \u2014 more realistically [1,2,2,2] with n=3: this still forms a valid cycle since indices 2 and 3 both point to index 2, and the algorithm still converges correctly on 2.",
    edge_case_say="Let me check a case where the duplicate shows up three or more times, since the problem allows that \u2014 the cycle structure still holds because multiple indices funnel into the same duplicated value, so the two-phase pointer approach still finds it correctly.",
    other_edge_cases=[
        "Duplicate value equal to n (the largest allowed value)",
        "Duplicate value equal to 1 (the smallest allowed value)",
        "Smallest possible array, n=1 so array is [1,1]",
        "Duplicate appearing at the very start vs. very end of the array",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This runs in O(n) time since both phases move through the array a bounded number of times proportional to n, and O(1) extra space since only two or three pointer variables are used, with no modification to the input.",
    pushback=[
        ("Can you do it without the cycle-detection trick?", "Yes, alternatives include sorting the array (O(n log n) time, but modifies the array) or Binary Search on the value range 1..n, counting how many elements are \u2264 mid to decide which half the duplicate is in (O(n log n) time, O(1) space, doesn't modify the array)."),
        ("Why does treating the array as a linked list work?", "Because every value is a valid index (1..n) into an array of size n+1, we can always 'jump' from index i to index nums[i]; the duplicate means two different indices jump to the same place, which is exactly what creates a cycle in that implicit graph."),
        ("What if there were multiple duplicates of different values?", "The problem guarantees exactly one number is duplicated (though it may repeat multiple times), so the array only has one entry point into the cycle; if the constraints changed to allow multiple distinct duplicates, this specific technique wouldn't directly generalize."),
        ("Can you find it with sorting?", "Yes, sort and scan for two adjacent equal values, but that's O(n log n) and typically modifies the array, which may violate constraints, so the pointer or binary-search approaches are usually preferred."),
    ],
    mistakes=[
        "Forgetting that both slow and fast pointers must start at the exact same index/value before phase one begins.",
        "Mixing up when to reset the pointer for phase two (must reset to nums[0], continuing to use array values, not the raw index 0).",
        "Off-by-one confusion about whether indices or values are being compared.",
        "Assuming a hash set is acceptable when the interviewer has explicitly asked for O(1) space.",
    ],
    recovery=[
        "If stuck: 'A hash set solves it in O(n) time but O(n) space. Since I need O(1) space, let me think about how the values relate to indices \u2014 maybe I can use the array structure itself instead of extra memory.'",
        "If I forget the exact Floyd's algorithm formula: reason from first principles \u2014 'I know two pointers moving at different speeds will meet inside a cycle; then resetting one to the start and moving both at equal speed finds the entrance,' and write the code from that logic.",
        "If the interviewer hints 'think of it as a linked list': respond, 'Right, values point to indices, so a duplicate creates a shared destination, i.e., a cycle.'",
        "If I second-guess the two-phase logic: verify it with a small dry run before committing to the final code.",
    ],
    pattern_recognition=dict(
        triggers="'array with values 1 to n', 'find the duplicate', 'without modifying the array', 'O(1) space'",
        pattern="Fast & Slow Pointers / Floyd's Cycle Detection reused on an implicit linked list",
        first_thought="Can this array be reinterpreted as a linked list (index -> value -> next index) where a duplicate naturally forms a cycle?",
        trap="Reaching for a hash set by default without noticing the O(1) space constraint that signals cycle detection is expected.",
    ),
    memory_hook="Find the Duplicate \u2192 \"Values point to indices \u2014 a duplicate makes a loop, so hunt it like a cycle.\"",
    recap_key_idea="Treat array values as 'next pointers' into the array; the duplicate creates a cycle, found via Floyd's algorithm.",
    recap_data_structure="Just two or three integer pointer variables \u2014 no extra structure.",
    recap_algorithm="Floyd's Tortoise and Hare, phase one detects the cycle, phase two finds its entrance.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Duplicate value repeating more than twice.",
    talk_track=[
        ("Interviewer", "Find the duplicate number in this array of n+1 integers, values from 1 to n, without modifying the array."),
        ("Me", "Understood \u2014 and I assume there's a space constraint too, like O(1) extra space, since otherwise a hash set would trivially solve it?"),
        ("Interviewer", "Yes, O(1) space."),
        ("Me", "Okay, brute force with a hash set is O(n) time but O(n) space, which won't satisfy that constraint."),
        ("Interviewer", "How would you get O(1) space?"),
        ("Me", "Since every value is a valid index into the array, I can treat it like a linked list where index i points to index nums[i]. A duplicate means two indices point to the same place, which creates a cycle \u2014 and I can find that with Floyd's tortoise-and-hare algorithm in O(1) space."),
        ("Me", "First phase: slow moves one step, fast moves two, until they meet inside the cycle."),
        ("Me", "Second phase: reset one pointer to the start, move both one step at a time \u2014 they'll meet exactly at the cycle's entrance, which is the duplicate."),
        ("Me", "Let me trace [1,3,4,2,2] to confirm... both phases converge on 2, which is correct."),
        ("Me", "Final complexity: O(n) time, O(1) space, and the array is never modified."),
    ],
))

PROBLEMS.append(dict(
    title="Single Number", lc_num="136", difficulty="EASY", pattern="Bit Manipulation (XOR)",
    relevance="Useful foundational problem",
    restate="We're given a non-empty array where every element appears exactly twice except for one element that appears only once, and we need to find that single element, ideally in O(n) time and O(1) space.",
    clarify_questions=[
        "Can I assume every other element appears exactly twice, not more?",
        "Is there always exactly one element that appears once?",
        "Are negative numbers possible?",
        "Is there a constraint against using extra memory, like a hash map?",
    ],
    restate_say=["Just to confirm, every value except one appears exactly twice, and I need to find that one exception, correct? Is there a space constraint I should keep in mind?"],
    brute_idea="Use a hash map to count occurrences of each value, then scan the map for the value with count 1.",
    brute_say=["The straightforward way is to count occurrences with a hash map, then look for the entry with a count of exactly one."],
    brute_time="O(n) to build the counts and O(n) to scan them, so O(n) overall.",
    brute_space="O(n) for the hash map.",
    brute_complexity_say="This is O(n) time, but it also uses O(n) space for the hash map, which is what we'd like to avoid.",
    bottleneck="I'm storing every value just to check if it appears twice, but there's a mathematical operation that cancels out pairs automatically without needing to remember anything.",
    bottleneck_say="The bottleneck is that I don't actually need to remember counts \u2014 I just need something that makes pairs cancel out, and a hash map is overkill for that.",
    optimization_explain="I use Bit Manipulation via XOR. XOR has two useful properties: a number XORed with itself is 0, and XOR is commutative/associative, so order doesn't matter. If I XOR every element in the array together, every pair of identical numbers cancels out to 0, and whatever's left over is exactly the single unique number.",
    key_insight="x XOR x = 0 and x XOR 0 = x, so XOR-ing the whole array causes every duplicate pair to vanish, leaving only the number that had no partner.",
    optimization_say=[
        "I'll XOR every number in the array together into one running result.",
        "Any number that appears twice will XOR with itself and cancel to zero.",
        "Whatever remains after processing the whole array must be the single number that never had a pair.",
    ],
    code_blocks=[
        dict(code="def single_number(nums):\n    result = 0\n    for num in nums:\n        result = result ^ num\n    return result",
             say="I start a running XOR at 0, then XOR in every number in the array one at a time, and return the final result.",
             why="Starting at 0 is safe because x XOR 0 = x, so it doesn't affect the very first number XORed in, and by the end all pairs have cancelled, leaving only the singleton."),
    ],
    dry_run="nums = [4,1,2,1,2]. result=0. XOR 4 -> 4. XOR 1 -> 4^1=5. XOR 2 -> 5^2=7. XOR 1 -> 7^1=6. XOR 2 -> 6^2=4. Final result = 4, the single number (1 and 2 each appeared twice and cancelled out).",
    dry_run_say="Walking through [4,1,2,1,2]: as I XOR everything in, the two 1's cancel each other and the two 2's cancel each other, leaving 4 as the final answer.",
    edge_case="Array of length 1, e.g. [7]. result starts at 0, XOR 7 -> 7. Returned correctly since there's nothing else to cancel it out.",
    edge_case_say="Let me check the smallest possible input, a single-element array like [7] \u2014 XOR-ing it against the initial 0 just gives back 7, which is correct.",
    other_edge_cases=[
        "Negative numbers in the array (XOR works the same on two's-complement representations)",
        "The single number being 0 itself",
        "Large arrays with many pairs (verifies performance, not correctness)",
        "The unique number being the first or last element",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time for a single pass through the array, and O(1) space since I only keep one running integer.",
    pushback=[
        ("Why does XOR work here specifically?", "Because XOR is its own inverse (x^x=0) and identity-preserving (x^0=x), and it's both commutative and associative, so the order I XOR numbers in doesn't matter \u2014 every duplicate pair always cancels regardless of where it appears in the array."),
        ("What if every other number appeared three times instead of twice?", "Then plain XOR wouldn't work since three copies wouldn't cancel to zero; that variant (LeetCode 137) needs a bit-counting trick tracking bits mod 3, which is a different technique."),
        ("Can you solve it without bit manipulation?", "Yes, the hash map approach works but costs O(n) space; there's also a math trick using 2*(sum of distinct values) - (sum of all values), but that requires extra space to track which values are distinct or risks overflow, so XOR is cleaner."),
        ("Can you optimize further?", "We must look at every element at least once to be sure we've found the singleton, so O(n) time is already optimal; O(1) space is also optimal since we need at least one variable to store the answer."),
    ],
    mistakes=[
        "Trying to use a running sum or product instead of XOR, which doesn't cleanly cancel duplicates.",
        "Forgetting that XOR is commutative and associative, and worrying unnecessarily about array order.",
        "Assuming this technique generalizes to duplicates appearing three or more times without modification.",
        "Initializing the running result to something other than 0.",
    ],
    recovery=[
        "If stuck: 'I want an operation where identical values cancel out without me having to remember what I've seen \u2014 XOR does exactly that.'",
        "If I forget XOR properties mid-interview: just state them out loud \u2014 'x XOR x is 0, x XOR 0 is x' \u2014 and reason forward from there.",
        "If the interviewer hints 'can you avoid extra memory': pivot straight to bit manipulation / XOR.",
        "If I'm unsure this generalizes to triples: acknowledge it directly \u2014 'this specific trick relies on pairs; if duplicates were triples, I'd need a different approach.'",
    ],
    pattern_recognition=dict(
        triggers="'every element appears twice except one', 'find the single element', O(1) space",
        pattern="Bit Manipulation \u2014 XOR to cancel pairs",
        first_thought="Is there an operation that's its own inverse, so pairs vanish and only a lone value survives?",
        trap="Reaching for a hash map by default and missing the O(1)-space signal that XOR is expected.",
    ),
    memory_hook="Single Number \u2192 \"XOR cancels pairs \u2014 whatever survives is the one without a partner.\"",
    recap_key_idea="XOR the entire array together; duplicate pairs cancel to zero, leaving the singleton.",
    recap_data_structure="A single integer accumulator \u2014 no extra structure.",
    recap_algorithm="One-pass running XOR.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Single-element array.",
    talk_track=[
        ("Interviewer", "Every number in this array appears twice except one \u2014 find that one."),
        ("Me", "Got it, and I assume O(1) extra space is preferred here rather than a hash map?"),
        ("Interviewer", "Yes, ideally."),
        ("Me", "A hash map counting occurrences would work in O(n) time but O(n) space."),
        ("Interviewer", "Can you do it in O(1) space?"),
        ("Me", "Yes \u2014 XOR has a nice property: a number XORed with itself is 0, and XOR order doesn't matter. If I XOR every element together, every duplicate pair cancels out, and only the single unmatched number survives."),
        ("Me", "Let me code that \u2014 a running result starting at 0, XOR-ing in every number as I go."),
        ("Me", "Tracing [4,1,2,1,2]: the two 1's cancel, the two 2's cancel, and I'm left with 4, which is correct."),
        ("Me", "Edge case: a single-element array just returns that element, since 0 XOR x is x."),
        ("Me", "Final complexity: O(n) time, one pass, and O(1) space, just one integer variable."),
    ],
))

PROBLEMS.append(dict(
    title="Move Zeroes", lc_num="283", difficulty="EASY", pattern="Two Pointers (In-Place Partition)",
    relevance="Useful foundational problem",
    restate="We're given an array of integers, and we need to move all the zeroes to the end while keeping the relative order of the non-zero elements, doing it in-place without making a copy of the array.",
    clarify_questions=[
        "Do the non-zero elements need to keep their original relative order?",
        "Should I do this in-place, or is returning a new array acceptable?",
        "Can the array be empty or contain no zeroes at all?",
        "Are negative numbers or duplicates possible?",
    ],
    restate_say=["Just to confirm, I need to shift every zero to the end of the array, in-place, while keeping the non-zero elements in their original relative order, right?"],
    brute_idea="Build a new list of all non-zero elements in order, then a list of zeroes, concatenate them, and copy back into the original array.",
    brute_say=["The simplest approach is to collect all non-zero elements into a new list, then append the right number of zeroes, and copy that back over the original array."],
    brute_time="O(n) to build the new list and O(n) to copy it back, so O(n) overall.",
    brute_space="O(n) for the temporary list, which violates a strict in-place requirement.",
    brute_complexity_say="This is O(n) time, but O(n) extra space for the temporary array, which usually isn't what the interviewer wants for an 'in-place' requirement.",
    bottleneck="I don't need a separate array at all \u2014 I can shuffle non-zero elements toward the front directly within the same array using two pointers.",
    bottleneck_say="The bottleneck is using extra space for a copy, when I can rearrange elements within the original array directly.",
    optimization_explain="I use Two Pointers: one pointer (insert_pos) marks where the next non-zero element should go, and another pointer (i) scans through the array. Whenever nums[i] is non-zero, I swap it into position insert_pos and advance insert_pos. By the end, all non-zero elements have been shifted to the front in order, and everything from insert_pos onward is naturally zero.",
    key_insight="Swapping (rather than just overwriting) preserves the zeroes we've already passed, so by the time the scan finishes, every element after insert_pos is guaranteed to be a zero we swapped out of the way.",
    optimization_say=[
        "I'll keep a slow pointer that marks the next position for a non-zero value.",
        "I'll scan the array with a fast pointer, and every time I find a non-zero value, I swap it into the slow pointer's position and advance the slow pointer.",
        "Using a swap instead of just overwriting means the zero that was displaced ends up further to the right, exactly where it belongs.",
    ],
    code_blocks=[
        dict(code="def move_zeroes(nums):\n    insert_pos = 0",
             say="I set up insert_pos at 0 \u2014 this tracks where the next non-zero value should be placed.",
             why="Everything before insert_pos will always be the non-zero elements processed so far, in their original order."),
        dict(code="    for i in range(len(nums)):\n        if nums[i] != 0:\n            nums[insert_pos], nums[i] = nums[i], nums[insert_pos]\n            insert_pos = insert_pos + 1",
             say="I scan through with i. Whenever I find a non-zero element, I swap it with whatever is at insert_pos, then move insert_pos forward.",
             why="Swapping (not just assigning) ensures that if nums[insert_pos] was a zero, it gets pushed to where nums[i] used to be, which is always at or after the current scan position, keeping all zeroes correctly shifted right."),
    ],
    dry_run="nums = [0,1,0,3,12]. insert_pos=0. i=0 (val 0): skip. i=1 (val 1): swap nums[0] and nums[1] -> [1,0,0,3,12], insert_pos=1. i=2 (val 0): skip. i=3 (val 3): swap nums[1] and nums[3] -> [1,3,0,0,12], insert_pos=2. i=4 (val 12): swap nums[2] and nums[4] -> [1,3,12,0,0], insert_pos=3. Final array: [1,3,12,0,0].",
    dry_run_say="Tracing [0,1,0,3,12]: every time I hit a non-zero value I swap it into the next open slot, and by the end I get [1,3,12,0,0] \u2014 all non-zero values in original order, zeroes pushed to the end.",
    edge_case="Array with no zeroes at all, e.g. [1,2,3]. Every element is non-zero, so insert_pos advances every step and each element gets swapped with itself (a no-op), leaving the array unchanged \u2014 correct.",
    edge_case_say="Let me check an array with no zeroes, like [1,2,3] \u2014 every swap ends up being with itself since insert_pos and i stay in lockstep, so the array is correctly left unchanged.",
    other_edge_cases=[
        "Array that is all zeroes",
        "Array with a single element (zero or non-zero)",
        "Zeroes only at the very front already",
        "Zeroes only at the very end already",
    ],
    final_complexity_rows=[["Optimized", "O(n)", "O(1)"]],
    final_complexity_say="This is O(n) time since it's a single pass through the array, and O(1) extra space because everything is rearranged in-place using swaps.",
    pushback=[
        ("Can you avoid using swap and just overwrite?", "I could track how many zeroes I've passed and overwrite nums[i] directly with 0 after copying non-zero values forward in a first pass, then fill the remaining tail with zeroes in a second pass \u2014 that's also O(n) time, O(1) space, just done in two passes instead of one with swaps."),
        ("Does this preserve relative order of non-zero elements?", "Yes \u2014 since I scan strictly left to right and only ever move a non-zero element to the next available front slot, their relative order among themselves never changes."),
        ("What if the array is very large, does this still work in-place?", "Yes, the algorithm doesn't depend on array size beyond the O(n) pass \u2014 it never allocates a second array, so it scales the same way regardless of size."),
        ("Can you do it with fewer total swaps?", "The two-pass version (copy non-zero forward, then fill zeroes) does fewer swaps when there are many zeroes, since it doesn't swap zero-with-zero segments repeatedly, but both are O(n) overall."),
    ],
    mistakes=[
        "Overwriting nums[insert_pos] with nums[i] without swapping, which can lose track of the zero that was there.",
        "Forgetting to advance insert_pos only when a non-zero is found, not on every iteration.",
        "Assuming this needs sorting, which is unnecessary and slower.",
        "Not preserving relative order (e.g., sorting zeroes and non-zeroes separately without regard to original sequence).",
    ],
    recovery=[
        "If stuck: 'I want to avoid extra space, so let me think about doing this within the same array using two pointers \u2014 one to scan, one to mark where non-zero values should land.'",
        "If I use overwrite instead of swap and get a wrong trace: notice the discrepancy during dry run and switch to a swap, explaining why it fixes the issue.",
        "If the interviewer hints 'think about the two-pointer technique': confirm and describe the insert_pos/scan-pointer approach.",
        "If I get confused about pointer order: slow down and re-walk a small example by hand before continuing to code.",
    ],
    pattern_recognition=dict(
        triggers="'move all zeroes to the end', 'in-place', 'preserve relative order'",
        pattern="Two Pointers \u2014 in-place partitioning",
        first_thought="Can I use one pointer to track where 'good' elements should go, and another to scan, all within the same array?",
        trap="Overwriting instead of swapping, which can silently drop or duplicate a zero.",
    ),
    memory_hook="Move Zeroes \u2192 \"Slow pointer marks the next non-zero slot; swap it in as you scan.\"",
    recap_key_idea="Use a slow pointer for the next non-zero slot; swap non-zero values into it as a fast pointer scans.",
    recap_data_structure="No extra structure \u2014 in-place swaps within the original array.",
    recap_algorithm="Two Pointers: insert_pos and scan index i.",
    recap_time="O(n)", recap_space="O(1)", recap_edge_case="Array with no zeroes, or all zeroes.",
    talk_track=[
        ("Interviewer", "Move all zeroes in this array to the end, in-place, keeping the other elements' order."),
        ("Me", "Understood \u2014 in-place means I shouldn't allocate a new array, and non-zero elements should keep their relative order, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "Brute force would build a new array of non-zeroes followed by zeroes, then copy it back \u2014 that's O(n) time but O(n) extra space."),
        ("Interviewer", "Can you avoid the extra space?"),
        ("Me", "Yes, with two pointers. I'll keep an insert_pos marking where the next non-zero value should go, and scan the array with another pointer. Whenever I find a non-zero value, I swap it into insert_pos and advance insert_pos."),
        ("Me", "Swapping instead of just overwriting matters, because it pushes the zero that was sitting there further right, instead of losing track of it."),
        ("Me", "Let me trace [0,1,0,3,12]... after the swaps I get [1,3,12,0,0], which is correct."),
        ("Me", "Edge case: an array with no zeroes at all just ends up swapping elements with themselves and stays unchanged, which is fine."),
        ("Me", "Final complexity: O(n) time for one pass, O(1) space since everything happens in-place."),
    ],
))
