PROBLEMS = []

PROBLEMS.append(dict(
    title="Min Stack", lc_num="155", difficulty="MEDIUM", pattern="Stack (Auxiliary Min-Tracking)",
    relevance="Design-heavy problem",
    restate="We need to design a stack that supports the usual push, pop, and top operations, plus a getMin operation that retrieves the minimum element currently in the stack, all in O(1) time.",
    clarify_questions=[
        "Do push, pop, top, AND getMin all need to run in O(1) time, not just amortized?",
        "Can the stack contain duplicate values, including duplicates of the current minimum?",
        "Is it guaranteed that pop and top are never called on an empty stack?",
        "Is there a constraint on how much extra space I can use?",
    ],
    restate_say=["Just to confirm, ALL four operations — push, pop, top, and getMin — need to run in O(1) time, and duplicate values (including duplicate minimums) are possible, correct?"],
    brute_idea="Use a plain stack, and whenever getMin is called, scan through the entire stack to find the minimum value.",
    brute_say=["The simplest approach is a regular stack, and whenever getMin is called, scan through all the current elements to find the smallest one."],
    brute_time="Push, pop, and top are all O(1), but getMin costs O(n) since it scans the whole stack.",
    brute_space="O(n) for the stack itself.",
    brute_complexity_say="This gives O(1) for push, pop, and top, but O(n) for getMin, which violates the requirement that ALL operations run in O(1) time.",
    bottleneck="I'm recomputing the minimum from scratch every time getMin is called, when I could instead maintain the minimum incrementally as elements are pushed and popped, so it's always instantly available.",
    bottleneck_say="The bottleneck is treating getMin as a fresh computation every time, instead of maintaining a running 'current minimum' that updates automatically as the stack changes.",
    optimization_explain="I maintain a second, Auxiliary Stack that tracks the minimum value at each point in the main stack's history. Whenever I push a value onto the main stack, I also push onto the min-stack: either the new value (if it's less than or equal to the min-stack's current top) or the min-stack's current top again (if the new value isn't a new minimum). This way, the min-stack's top always reflects the minimum of everything currently in the main stack. When I pop from the main stack, I also pop from the min-stack, keeping both stacks perfectly synchronized.",
    key_insight="By pushing a 'running minimum as of this point' onto a parallel stack every time I push a real value, popping from both stacks together automatically 'un-does' the minimum tracking too, since whatever minimum was true before that push is exactly what's revealed again on the min-stack after popping.",
    optimization_say=[
        "I'll maintain a second stack alongside the main one, specifically for tracking minimums.",
        "Every time I push a value, I also push the smaller of that value and the current minimum onto the min-stack, so its top is always the overall minimum so far.",
        "Every time I pop, I pop from both stacks together, which automatically restores the correct previous minimum.",
    ],
    code_blocks=[
        dict(code="class MinStack:\n    def __init__(self):\n        self.stack = []\n        self.min_stack = []",
             say="I initialize two empty lists: the main stack for regular values, and the min-stack for tracking running minimums.",
             why="Keeping these as two separate, perfectly synchronized stacks (always the same length) is what lets every operation, including getMin, run in O(1) time."),
        dict(code="    def push(self, val):\n        self.stack.append(val)\n        if not self.min_stack or val <= self.min_stack[-1]:\n            self.min_stack.append(val)\n        else:\n            self.min_stack.append(self.min_stack[-1])",
             say="I push the value onto the main stack as usual. For the min-stack, if it's empty or the new value is less than or equal to its current top, I push the new value; otherwise, I push a duplicate of the current top.",
             why="Using <= (not just <) correctly handles duplicate minimum values, ensuring that popping one copy of the minimum still leaves the min-stack correctly reporting that value as the minimum if another copy remains below it."),
        dict(code="    def pop(self):\n        self.stack.pop()\n        self.min_stack.pop()\n\n    def top(self):\n        return self.stack[-1]\n\n    def get_min(self):\n        return self.min_stack[-1]",
             say="Popping removes from both stacks together, keeping them synchronized. top() just returns the main stack's top as usual, and get_min() simply returns the min-stack's top, which is always correct by construction.",
             why="Because both stacks are always pushed to and popped from together, the min-stack's top always accurately reflects the minimum of exactly what's currently in the main stack, with no scanning ever required."),
    ],
    dry_run="Operations: push(-2), push(0), push(-3), getMin(), pop(), top(), getMin(). push(-2): stack=[-2], min_stack empty so push -2 -> min_stack=[-2]. push(0): stack=[-2,0]. 0<=-2? No. push min_stack[-1]=-2 again -> min_stack=[-2,-2]. push(-3): stack=[-2,0,-3]. -3<=-2? Yes. push -3 -> min_stack=[-2,-2,-3]. getMin(): return min_stack[-1]=-3. Correct, min of [-2,0,-3] is -3. pop(): stack=[-2,0], min_stack=[-2,-2]. top(): return stack[-1]=0. getMin(): return min_stack[-1]=-2. Correct, min of [-2,0] is -2.",
    dry_run_say="Tracing push(-2), push(0), push(-3), getMin() (gives -3), pop(), top() (gives 0), getMin() (gives -2): every operation returns the correct value, and the min-stack automatically 'remembers' the right minimum at each point as we pop back through history.",
    edge_case="Pushing duplicate minimum values, e.g. push(1), push(1), pop(), getMin(). push(1): stack=[1], min_stack=[1] (empty check, push 1). push(1): 1<=1? Yes, push 1 again -> min_stack=[1,1]. pop(): stack=[1], min_stack=[1]. getMin(): return 1, still correctly the minimum even though we just removed one of the two 1's.",
    edge_case_say="Let me check pushing the same minimum value twice, then popping once — using <= (not strict <) when deciding what to push onto the min-stack ensures that after popping one copy, getMin still correctly returns the remaining 1.",
    other_edge_cases=[
        "Popping until the stack is completely empty",
        "Pushing values in strictly increasing order (min-stack always just duplicates the very first value)",
        "Pushing values in strictly decreasing order (min-stack mirrors the main stack exactly)",
        "A stack containing only a single element",
    ],
    final_complexity_rows=[["All operations", "O(1)", "O(n)"]],
    final_complexity_say="Every operation — push, pop, top, and getMin — runs in O(1) time, since each just accesses or modifies the end of one or both stacks, and the overall space is O(n) for maintaining the two parallel stacks.",
    pushback=[
        ("Why use <= instead of < when deciding what to push onto the min-stack?", "Because using strict < would fail to correctly track a duplicate minimum: if I pushed a value equal to the current minimum but didn't also duplicate it onto the min-stack, popping the main stack later could leave the min-stack out of sync, no longer correctly reflecting that the same minimum value still exists deeper in the stack."),
        ("Can you do this with less extra space, like O(1) instead of O(n) for the min-stack?", "Yes, an alternative encodes the minimum differently: instead of a parallel stack, store just a single running minimum variable, and when pushing a new minimum, push an ENCODED value onto the main stack itself (like 2*val - old_min) that lets you recover the previous minimum during a pop; this trades some arithmetic complexity for avoiding a full second stack, though it requires careful handling of potential overflow in some languages."),
        ("Does this handle negative numbers correctly?", "Yes, the min-stack approach works identically regardless of whether values are positive, negative, or zero, since it's just comparing values directly with <=, with no assumption about sign."),
        ("Can you optimize this further?", "No, O(1) per operation is already optimal, since these are meant to be constant-time stack primitives by design; the only real tradeoff available is the space optimization mentioned above."),
    ],
    mistakes=[
        "Using strict < instead of <= when pushing onto the min-stack, breaking correctness with duplicate minimum values.",
        "Forgetting to pop from BOTH stacks together, causing them to fall out of sync.",
        "Trying to maintain just a single 'current minimum' variable without a full auxiliary stack, which can't correctly restore a PREVIOUS minimum after a pop.",
        "Not initializing the min-stack correctly on the very first push (missing the 'is min_stack empty' check).",
    ],
    recovery=[
        "If stuck: 'Scanning for the minimum every time is O(n), but I need O(1). Let me think about maintaining the minimum incrementally instead, updated alongside every push and pop.'",
        "If getMin() gives a wrong answer after a pop: verify that both stacks are always pushed and popped together, keeping them the same length at all times.",
        "If the interviewer hints 'can you use less space': mention the single running-minimum-with-encoding trick as a space-optimized alternative.",
        "If confused about <= vs <: trace through a duplicate-minimum example by hand, which will clearly reveal why <= is required for correctness.",
    ],
    pattern_recognition=dict(
        triggers="'design a stack that also supports getMin/getMax in O(1)'",
        pattern="Stack with an Auxiliary Tracking Stack",
        first_thought="Maintain a second, perfectly synchronized stack that tracks the running minimum, so it's always immediately available without scanning.",
        trap="Using strict < instead of <= when pushing onto the min-stack, which breaks correctness for duplicate minimum values.",
    ),
    memory_hook="Min Stack → \"A second stack, always tracking the minimum-so-far, pushed and popped in lockstep.\"",
    recap_key_idea="Maintain a parallel min-stack; each push also pushes the running minimum; pop from both together.",
    recap_data_structure="Two stacks (lists): the main stack and the min-stack.",
    recap_algorithm="Auxiliary stack synchronized push/pop.",
    recap_time="O(1) all operations", recap_space="O(n)", recap_edge_case="Duplicate minimum values pushed and later popped.",
    talk_track=[
        ("Interviewer", "Design a stack that also supports retrieving the minimum element in O(1) time."),
        ("Me", "Got it — push, pop, top, AND getMin all need to be O(1), and duplicate values including duplicate minimums are possible, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "A regular stack handles push, pop, and top in O(1) easily, but getMin would need to scan the whole stack, O(n), unless I track it incrementally."),
        ("Me", "I'll maintain a second, auxiliary min-stack alongside the main one. Every push also pushes the current running minimum onto this second stack, and every pop removes from both stacks together, so they stay perfectly synchronized."),
        ("Me", "Let me code that — using <= rather than strict < when deciding what to push onto the min-stack, which matters for correctly handling duplicate minimums."),
        ("Me", "Tracing push(-2), push(0), push(-3), getMin(), pop(), top(), getMin(): every operation returns the correct value, and the min-stack automatically restores the right minimum as we pop."),
        ("Me", "Edge case: pushing the same minimum value twice, then popping once — the <= comparison ensures getMin still correctly returns that value afterward."),
        ("Me", "Final complexity: O(1) for every single operation, O(n) space for the two parallel stacks."),
        ("Interviewer", "Can you reduce the space usage?"),
        ("Me", "Yes, there's a trick using a single running-minimum variable and encoding values pushed onto the main stack itself, avoiding a full second stack, though it adds some arithmetic complexity."),
    ],
))

PROBLEMS.append(dict(
    title="Insert Delete GetRandom O(1)", lc_num="380", difficulty="MEDIUM", pattern="Hash Map + Array",
    relevance="Design-heavy problem",
    restate="We need to design a data structure that supports inserting a value, removing a value, and getting a truly random element from the current set of values, all in average O(1) time.",
    clarify_questions=[
        "Should insert and remove return whether the operation actually changed anything (e.g., false if inserting a duplicate or removing something not present)?",
        "Does every element (including duplicates, if allowed) need equal probability of being chosen by getRandom, or are all values guaranteed unique?",
        "Is there a constraint on extra space usage?",
        "Should getRandom use a uniform distribution across all current elements?",
    ],
    restate_say=["Just to confirm, all values are unique (it's a set, not a multiset), insert/remove should indicate whether something actually changed, and getRandom needs uniform probability across current elements, correct?"],
    brute_idea="Use just a Python list: insert appends (checking for duplicates first), remove searches for and removes the value by scanning, and getRandom picks a random index directly.",
    brute_say=["Using just a plain list, insert can check for duplicates and append, getRandom can pick a random index directly in O(1), but remove has to search through the list to find the value's position first."],
    brute_time="Insert is O(n) to check for duplicates, remove is O(n) to find the value, and getRandom is O(1).",
    brute_space="O(n) for the list.",
    brute_complexity_say="Insert and remove both risk being O(n) with a plain list, since checking for duplicates or finding a value's exact position requires scanning, which violates the O(1) requirement for those operations.",
    bottleneck="A list alone doesn't give O(1) lookup for 'does this value exist' or 'where is this value', but an array alone is what gives O(1) random access needed for getRandom — I need to combine both structures to get the best of each.",
    bottleneck_say="The bottleneck is that a hash map alone can't give O(1) random access (needed for getRandom), and an array alone can't give O(1) lookup/removal by value — I need both structures working together.",
    optimization_explain="I combine a Hash Map and an Array (list). The array stores all the actual values, giving O(1) random access for getRandom (just pick a random valid index). The hash map stores value-to-index-in-the-array, giving O(1) lookup to check existence or find a value's position. The tricky part is removal: to remove a value in O(1), instead of shifting all elements after it (which would be O(n)), I swap it with the LAST element in the array, update the hash map for that swapped element's new position, then simply pop the last element off (which is now the value I wanted to remove) — all O(1) operations.",
    key_insight="Removing from the middle of an array is normally O(n) because of the need to shift everything after it, but if you don't care about preserving order, swapping the target with the very last element first turns 'remove from the middle' into 'remove from the end', which is O(1) — the hash map is what lets you instantly find where the target is without searching.",
    optimization_say=[
        "I'll keep both an array of values (for O(1) random access) and a hash map from value to its index in that array (for O(1) lookup).",
        "Insert appends to the array and records its index in the map, if it's not already present.",
        "Remove is the clever part: I swap the target value with the array's last element, update the map for the swapped element, then pop the last element off, turning an O(n) middle-removal into an O(1) operation.",
    ],
    code_blocks=[
        dict(code="import random\n\nclass RandomizedSet:\n    def __init__(self):\n        self.values = []\n        self.value_to_index = {}",
             say="I initialize an empty list to store values, and an empty hash map from value to its current index in that list.",
             why="These two structures together are what let every operation run in O(1): the array for random access, the map for instant lookups."),
        dict(code="    def insert(self, val):\n        if val in self.value_to_index:\n            return False\n        self.value_to_index[val] = len(self.values)\n        self.values.append(val)\n        return True",
             say="If the value already exists, insertion fails (returns False) since we maintain a set of unique values. Otherwise, I record its new index (the current length of the list, before appending) and add it to the end of the list.",
             why="Recording the index BEFORE appending correctly captures 'where this new value will land', since appending to a list of current length L places the new item at index L."),
        dict(code="    def remove(self, val):\n        if val not in self.value_to_index:\n            return False\n        index_to_remove = self.value_to_index[val]\n        last_value = self.values[-1]\n        self.values[index_to_remove] = last_value\n        self.value_to_index[last_value] = index_to_remove\n        self.values.pop()\n        del self.value_to_index[val]\n        return True",
             say="If the value doesn't exist, removal fails. Otherwise, I find its index using the map, then move the array's LAST value into that position (overwriting the target), update the map so the moved value points to its new index, and finally pop the true last slot off the array (which now correctly represents the removed target's old duplicate) and delete the removed value's own map entry.",
             why="This swap-with-last trick is exactly what avoids an O(n) shift: instead of removing from the middle (expensive), we move the problem to the end (cheap), since popping the last element of a list is O(1)."),
        dict(code="    def get_random(self):\n        return random.choice(self.values)",
             say="I return a uniformly random element directly from the array.",
             why="Since the array holds every current value exactly once with no gaps, random.choice gives a perfectly uniform O(1) random selection."),
    ],
    dry_run="insert(1): values=[1], map={1:0}. insert(2): values=[1,2], map={1:0,2:1}. insert(3): values=[1,2,3], map={1:0,2:1,3:2}. remove(2): index_to_remove=map[2]=1. last_value=values[-1]=3. values[1]=3 -> values=[1,3,3] temporarily. map[3]=1 (updated). values.pop() -> values=[1,3]. del map[2]. Final: values=[1,3], map={1:0,3:1}. Correctly removed 2, and 3 (which was swapped into 2's old slot) now correctly maps to index 1.",
    dry_run_say="Tracing insert(1), insert(2), insert(3), then remove(2): the value 3 gets swapped into 2's old position, the map is updated to reflect that, and the last slot is popped off, leaving values=[1,3] with a correctly updated map — all in O(1) steps, no shifting required.",
    edge_case="Removing the very last element in the array, e.g. after the above state (values=[1,3]), remove(3). index_to_remove=map[3]=1. last_value=values[-1]=3 (same as the value being removed, since it IS the last element). values[1]=3 (no actual change, since it's swapping the last element with itself). map[3]=1 (unchanged). values.pop() -> values=[1]. del map[3]. Correctly ends with values=[1], map={1:0}, with no corruption despite the target and the 'last value' being the same element.",
    edge_case_say="Let me check removing an element that's ALREADY the last one in the array — the swap-with-last logic ends up swapping it with itself, which is harmless, and the pop correctly removes it, leaving the structure in a valid state.",
    other_edge_cases=[
        "Removing a value that doesn't exist (should return False, no change)",
        "Inserting a duplicate value (should return False, no change)",
        "getRandom called when only one element exists",
        "Repeated insert/remove cycles verifying the map and array stay correctly synchronized",
    ],
    final_complexity_rows=[["All operations", "O(1) average", "O(n)"]],
    final_complexity_say="Insert, remove, and getRandom all run in average O(1) time, since each involves only a constant number of hash map and array operations, and the overall space is O(n) for storing all the current values in both structures.",
    pushback=[
        ("Why swap with the LAST element specifically, rather than any other element?", "Because popping from the END of a Python list is O(1), while removing from the middle would require shifting all subsequent elements, which is O(n); by moving the 'gap' created by removal to the very end first, we can close it with a cheap pop instead of an expensive shift."),
        ("What if the value being removed is already the last element?", "As shown in the edge case, the algorithm still works correctly, though the swap becomes a harmless no-op (swapping an element with itself) before the final pop removes it."),
        ("Does getRandom truly give a uniform distribution?", "Yes, since the array contains every current value exactly once with no gaps or duplicates, and random.choice selects uniformly among all current array positions, every element has an equal 1/n chance of being selected."),
        ("Can you extend this to a multiset that allows duplicate values?", "Yes, that's a related follow-up (Insert Delete GetRandom O(1) - Duplicates allowed), which requires the hash map to store a SET of indices per value instead of a single index, adding some complexity to correctly handle removal when duplicates exist."),
    ],
    mistakes=[
        "Trying to remove from the array by searching for the value's position instead of using the hash map, reintroducing O(n) removal.",
        "Shifting elements after removal instead of using the swap-with-last-then-pop trick, which is O(n) instead of O(1).",
        "Forgetting to update the hash map entry for the swapped (formerly-last) value after moving it.",
        "Forgetting to delete the removed value's own entry from the hash map, leaving stale data.",
    ],
    recovery=[
        "If stuck: 'An array gives me O(1) random access but O(n) removal by value; a hash map gives me O(1) lookup but no random access. Let me combine both, and think about how to make removal O(1) too.'",
        "If removal seems inherently O(n): reason aloud, 'popping from the END of an array is O(1) — can I turn removing from the middle into removing from the end somehow?' which leads to the swap trick.",
        "If the interviewer hints 'think about swapping': confirm and describe swapping the target with the last element before popping.",
        "If confused about updating the map after a swap: trace through a small example by hand to see exactly which map entries need updating.",
    ],
    pattern_recognition=dict(
        triggers="'O(1) insert, delete, AND random access all together'",
        pattern="Hash Map + Array combined (Hash Map for lookup, Array for random access)",
        first_thought="No single structure gives O(1) for both lookup/removal AND random access — combine a hash map (value to index) with an array (values), and use a swap-with-last trick to make removal O(1) too.",
        trap="Forgetting to update the hash map for the swapped element's new index after a removal, corrupting future lookups.",
    ),
    memory_hook="Insert Delete GetRandom → \"Array for random access, hash map for lookup, swap-with-last to remove.\"",
    recap_key_idea="Combine an array (random access) with a hash map (value-to-index lookup); remove by swapping with the last element then popping.",
    recap_data_structure="An array (list) plus a hash map (value → index).",
    recap_algorithm="Swap-with-last removal technique.",
    recap_time="O(1) average, all operations", recap_space="O(n)", recap_edge_case="Removing a value that is already the array's last element.",
    talk_track=[
        ("Interviewer", "Design a structure supporting insert, remove, and getRandom, all in average O(1) time."),
        ("Me", "Got it — all values are unique, insert/remove should indicate whether something actually changed, and getRandom needs to be uniformly random, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "An array alone gives O(1) getRandom, but removal by value would require an O(n) search. A hash map alone gives O(1) lookup, but no O(1) random access. I'll combine both."),
        ("Me", "The array stores the values; the hash map stores value-to-index. Insert appends to the array and records its index. GetRandom just picks a random array index directly."),
        ("Me", "Removal is the interesting part: instead of shifting elements after removing from the middle, which would be O(n), I swap the target with the array's LAST element, update the map for that swapped element, and pop the last slot off — all O(1)."),
        ("Me", "Let me code that up."),
        ("Me", "Tracing insert(1), insert(2), insert(3), then remove(2): 3 gets swapped into 2's old slot, the map updates accordingly, and the last slot pops off cleanly, leaving [1,3] correctly."),
        ("Me", "Edge case: removing a value that's already the last element in the array — the swap becomes a harmless no-op with itself, and the pop still correctly removes it."),
        ("Me", "Final complexity: O(1) average time for every operation, O(n) space for the array and hash map together."),
    ],
))
