PROBLEMS = []

PROBLEMS.append(dict(
    title="Generate Parentheses", lc_num="22", difficulty="MEDIUM", pattern="Backtracking",
    relevance="Common interview pattern",
    restate="We're given an integer n, and we need to generate all combinations of n pairs of parentheses that are well-formed (validly balanced).",
    clarify_questions=[
        "Does 'well-formed' mean every open parenthesis has a matching close, and they're never mismatched in order?",
        "Is n guaranteed to be a small positive integer, given the output size grows quickly (Catalan numbers)?",
        "Does the order of the returned combinations matter?",
        "Should duplicates ever occur, or is each valid combination distinct by construction?",
    ],
    restate_say=["Just to confirm, I need every distinct valid combination of n open and n close parentheses, and the order of the output doesn't matter, correct?"],
    brute_idea="Generate all possible strings of length 2n using '(' and ')' in every combination, then filter out the ones that aren't validly balanced.",
    brute_say=["A brute-force way is to generate every possible string of length 2n made of parentheses, then check each one for validity and keep only the valid ones."],
    brute_time="There are 2^(2n) total strings of length 2n, and validating each takes O(n), giving O(2^(2n) * n).",
    brute_space="O(n) per validity check, plus storing all generated strings.",
    brute_complexity_say="This is O(2 to the 2n times n) time, since we're generating every possible arrangement, most of which aren't even valid, and then filtering afterward.",
    bottleneck="I'm generating a huge number of strings that are invalid from very early on (e.g., starting with a close parenthesis), when I could avoid ever building those invalid prefixes in the first place.",
    bottleneck_say="The bottleneck is generating strings that are already broken from an early point and only checking validity at the very end, instead of pruning invalid choices as soon as they become impossible to fix.",
    optimization_explain="I use Backtracking. I build the string one character at a time, and at each step, I only add a character if it keeps the string 'on track' to possibly become valid: I can add an open parenthesis as long as I haven't used all n of them yet, and I can add a close parenthesis only if doing so wouldn't exceed the number of opens used so far (i.e., there are more opens than closes currently placed). When the string reaches length 2n, it's guaranteed to be a valid combination, so I add it to the results.",
    key_insight="A partial string can only ever become valid if, at every point, the number of close parentheses placed never exceeds the number of opens placed so far, and we never use more than n opens total \u2014 checking these two conditions at each step prunes away every invalid path immediately, rather than discovering the mistake only at the very end.",
    optimization_say=[
        "I'll build the string character by character using backtracking, tracking how many opens and closes I've used so far.",
        "I can add an open parenthesis if I haven't used all n yet, and a close parenthesis only if it wouldn't create more closes than opens at that point.",
        "Whenever the string reaches length 2n, it's guaranteed valid, so I record it as one of the answers.",
    ],
    code_blocks=[
        dict(code="def generate_parenthesis(n):\n    result = []\n\n    def backtrack(current, open_count, close_count):\n        if len(current) == 2 * n:\n            result.append(current)\n            return",
             say="I set up a results list and a recursive helper tracking the string built so far, plus how many opens and closes have been used. The base case: once the string reaches the full length 2n, it's a complete valid combination, so I record it.",
             why="Because I only ever add characters that keep the string 'on track' to be valid, reaching length 2n guarantees the result is automatically well-formed, with no separate validation step needed."),
        dict(code="        if open_count < n:\n            backtrack(current + '(', open_count + 1, close_count)",
             say="If I haven't used all n open parentheses yet, I try adding one, recursing with the updated counts.",
             why="Limiting opens to at most n directly enforces that we never use more open parentheses than allowed."),
        dict(code="        if close_count < open_count:\n            backtrack(current + ')', open_count, close_count + 1)",
             say="I only try adding a close parenthesis if doing so wouldn't create more closes than opens so far.",
             why="This is exactly the condition that guarantees validity at every prefix: a close parenthesis can only ever be placed if there's a corresponding unmatched open parenthesis already placed before it."),
        dict(code="    backtrack('', 0, 0)\n    return result",
             say="I kick off the recursion with an empty string and zero opens/closes used, then return the accumulated results.",
             why="Starting from the empty string and exploring both valid choices at each step (open, close, or both when applicable) systematically builds every valid combination without ever constructing an invalid one."),
    ],
    dry_run="n=2. backtrack('',0,0): open_count(0)<2, try '(' -> backtrack('(',1,0). Inside: open_count(1)<2, try '((' -> backtrack('((',2,0). Inside: open_count(2) not <2, skip open. close_count(0)<open_count(2), try '(()' -> backtrack('(()',2,1). Inside: open not<2 skip. close(1)<2, try '(())' -> backtrack('(())',2,2). length=4=2n, add '(())' to result. Back up: backtrack('(',1,0) also tries close: close_count(0)<open_count(1), try '()' -> backtrack('()',1,1). Inside: open(1)<2, try '()(' -> backtrack('()(',2,1). length not yet 4, close(1)<2, try '()()'->backtrack('()()',2,2), length=4, add '()()'. Also from '()',1,1: close(1) not< open(1), skip close there. Final result after full exploration: ['(())', '()()'] \u2014 matches the expected 2 valid combinations for n=2.",
    dry_run_say="Tracing n=2: the backtracking explores adding opens and closes while respecting the validity rules at every step, correctly producing exactly the two valid combinations, '(())' and '()()'.",
    edge_case="n=0. backtrack('',0,0) immediately checks len(current)==0==2*0, true, so it appends the empty string '' to result right away. Final result: [''], which is the (arguably trivial but technically correct) single valid combination when zero pairs are requested.",
    edge_case_say="Let me check n=0 \u2014 the base case triggers immediately since the target length is also 0, so we get a single result: the empty string, which is technically valid for zero pairs.",
    other_edge_cases=[
        "n=1 (should produce just '()')",
        "Larger n verifying the count matches the nth Catalan number",
        "Ensuring no duplicate strings are ever generated",
        "Ensuring no invalid combination like ')(' is ever produced",
    ],
    final_complexity_rows=[["Optimized", "O(4^n / sqrt(n))", "O(4^n / sqrt(n))"]],
    final_complexity_say="This is bounded by the nth Catalan number, which grows roughly as O(4^n / n^1.5), since that's exactly how many valid combinations exist and each takes O(n) to build, and the space is similarly proportional to the total output size (the Catalan number) times the string length.",
    pushback=[
        ("Why is backtracking better than generate-then-filter here?", "Because backtracking prunes invalid branches immediately \u2014 the moment a choice would make the string unfixable (too many closes, or too many opens), we simply don't explore that branch at all, whereas generate-then-filter wastes time constructing and then discarding a huge number of invalid full-length strings."),
        ("What is the exact count of valid combinations for a given n?", "It's the nth Catalan number, C(n) = (2n choose n) / (n+1), which is a well-known combinatorial quantity that also shows up in many other problems involving balanced structures."),
        ("Can you solve this iteratively instead of recursively?", "Yes, using an explicit stack to simulate the recursive backtracking, storing (current_string, open_count, close_count) tuples, achieving the same result without relying on the call stack."),
        ("Can you optimize this further?", "Not meaningfully \u2014 since we must actually output every valid combination, the time complexity is inherently tied to how many valid combinations exist (the Catalan number), so this approach is already asymptotically optimal for the output size."),
    ],
    mistakes=[
        "Forgetting the constraint on when a close parenthesis can be added (close_count < open_count), which would allow invalid combinations like ')('.",
        "Forgetting the constraint limiting opens to at most n, potentially generating overly long strings.",
        "String concatenation inefficiency in some languages (using a list/StringBuilder and backtracking by removing the last character might be preferred over creating new strings each call, though in Python this is a minor concern).",
        "Not handling n=0 correctly if the base case check isn't exactly right.",
    ],
    recovery=[
        "If stuck: 'Generating everything and filtering afterward wastes a lot of work on strings that are already broken early on. Let me think about what makes a PARTIAL string still fixable, and only build those.'",
        "If I generate an invalid combination: check the two conditions \u2014 open_count < n for adding '(' and close_count < open_count for adding ')' \u2014 and verify both are being enforced.",
        "If the interviewer hints 'can you avoid wasted work': confirm and describe pruning invalid branches early via backtracking.",
        "If asked about the exact output count: mention the Catalan number formula, even if just to acknowledge the connection without deriving it from scratch.",
    ],
    pattern_recognition=dict(
        triggers="'generate all valid combinations', 'well-formed parentheses'",
        pattern="Backtracking (constrained choice at each step)",
        first_thought="Only build partial strings that could still possibly become valid \u2014 prune invalid choices immediately instead of filtering complete strings afterward.",
        trap="Forgetting the close-count-less-than-open-count constraint, which is what actually enforces validity at every prefix.",
    ),
    memory_hook="Generate Parentheses \u2192 \"Only add ')' if there's an unmatched '(' waiting for it.\"",
    recap_key_idea="Backtrack, only adding '(' if under the limit n, and ')' only if fewer closes than opens so far.",
    recap_data_structure="A results list; implicit recursion call stack.",
    recap_algorithm="Backtracking with two pruning constraints.",
    recap_time="O(4^n / sqrt(n))", recap_space="O(4^n / sqrt(n))", recap_edge_case="n = 0 (single empty-string result).",
    talk_track=[
        ("Interviewer", "Generate all valid combinations of n pairs of parentheses."),
        ("Me", "Got it \u2014 I need every distinct well-formed combination, and order doesn't matter, right?"),
        ("Interviewer", "Correct."),
        ("Me", "Brute force would generate every string of length 2n and filter for validity afterward, which wastes a lot of time on strings that are broken from the very first few characters."),
        ("Me", "Instead, I'll use backtracking: build the string one character at a time, only adding '(' if I haven't used all n yet, and only adding ')' if doing so wouldn't create more closes than opens so far."),
        ("Me", "Once the string reaches length 2n, it's guaranteed to be valid, so I add it directly to my results, no separate validation needed."),
        ("Me", "Let me code that recursive structure."),
        ("Me", "Tracing n=2: the backtracking explores valid choices at each step and correctly produces exactly '(())' and '()()', the two valid combinations."),
        ("Me", "Edge case: n=0 immediately produces just the empty string as the single trivial result."),
        ("Me", "Final complexity is tied to the nth Catalan number, since that's exactly how many valid combinations exist, and we must output all of them."),
    ],
))

PROBLEMS.append(dict(
    title="Combination Sum", lc_num="39", difficulty="MEDIUM", pattern="Backtracking",
    relevance="Common interview pattern",
    restate="We're given a list of distinct positive integers and a target, and we need to find all unique combinations where the chosen numbers sum to the target, allowing the same number to be reused an unlimited number of times.",
    clarify_questions=[
        "Can the same number be used multiple times within one combination?",
        "Are all the candidate numbers guaranteed distinct and positive?",
        "Should combinations that use the same numbers in a different order be considered duplicates?",
        "Is the target guaranteed to be a positive integer?",
    ],
    restate_say=["Just to confirm, the same number can be reused multiple times within a combination, and combinations that use the same multiset of numbers in different orders count as the same (shouldn't be duplicated), correct?"],
    brute_idea="Try every possible combination of numbers (with repetition) using nested loops or recursion without pruning, checking whether each complete selection sums to the target.",
    brute_say=["A very naive approach would try building every possible sequence of chosen numbers and checking at the end whether it sums to the target, without any early pruning."],
    brute_time="Without pruning, this can be enormously wasteful, potentially unbounded, since numbers can repeat, so a bound must be set some other way; even with a reasonable bound, it can be exponential.",
    brute_space="O(target/min_candidate) for the depth of recursion in the worst case.",
    brute_complexity_say="Without pruning, this approach can spiral into massive redundant exploration, since we might keep adding numbers well past the target before ever checking if we've overshot.",
    bottleneck="I'm continuing to explore branches even after the running sum has already exceeded the target, and exploring numbers in an order that lets the same combination be discovered multiple times in different arrangements, leading to duplicate work and duplicate answers.",
    bottleneck_say="The bottleneck is not stopping early once the running sum exceeds the target, and not enforcing an order on which candidates can be picked next, which causes both wasted exploration and duplicate combinations.",
    optimization_explain="I use Backtracking with two key prunes. First, I stop exploring a branch immediately if the running sum exceeds the target (no point continuing). Second, to avoid generating the same combination in different orders, I only allow picking candidates from the current index ONWARD (never going back to an earlier candidate), which means each combination is only ever discovered once, in a single canonical (sorted) order.",
    key_insight="By only ever choosing the current candidate again or moving forward to later candidates (never backward), each valid combination is generated in exactly one canonical order, completely avoiding the need to de-duplicate results afterward; combined with stopping as soon as the running sum exceeds the target, this prunes the search dramatically.",
    optimization_say=[
        "I'll use backtracking, tracking a running sum and the current path of chosen numbers.",
        "At each step, I only consider candidates from the current index onward, which naturally prevents generating the same combination in a different order.",
        "I stop exploring a branch immediately if the running sum would exceed the target, and record a valid combination whenever the running sum exactly equals it.",
    ],
    code_blocks=[
        dict(code="def combination_sum(candidates, target):\n    result = []\n\n    def backtrack(start, path, remaining):\n        if remaining == 0:\n            result.append(list(path))\n            return\n        if remaining < 0:\n            return",
             say="I define a recursive helper tracking the starting index for candidates, the current path of chosen numbers, and how much of the target is still remaining. If remaining hits exactly 0, I've found a valid combination, so I record a COPY of the current path. If remaining goes negative, this branch has overshot the target, so I stop exploring it.",
             why="Copying the path (list(path)) is important because the same path list object gets mutated throughout the backtracking, so without copying, all recorded results would end up referencing the same (eventually emptied) list."),
        dict(code="        for i in range(start, len(candidates)):\n            path.append(candidates[i])\n            backtrack(i, path, remaining - candidates[i])\n            path.pop()\n\n    backtrack(0, [], target)\n    return result",
             say="I loop through candidates starting from 'start' (never going backward), trying each one: add it to the path, recurse with the SAME index i (allowing it to be reused), subtracting its value from the remaining target, and then remove it from the path afterward to try the next candidate.",
             why="Passing 'i' (not 'i+1') as the next starting index is what allows the same number to be reused multiple times, while still preventing combinations from being generated in a different order, since we never go back to try an earlier candidate after moving forward."),
    ],
    dry_run="candidates=[2,3,6,7], target=7. backtrack(0,[],7): i=0 (2): path=[2], backtrack(0,[2],5). i=0(2): path=[2,2], backtrack(0,[2,2],3). i=0(2): path=[2,2,2], backtrack(0,...,1). i=0(2): remaining becomes -1, return (overshoot). i=1(3): remaining -1? Let's recompute: at path=[2,2,2], remaining=1; try i=0(2): 1-2=-1, overshoot, return. i=1(3): 1-3=-2, overshoot, return. i=2(6): overshoot. i=3(7): overshoot. Pop back to [2,2], remaining=3. i=1(3): path=[2,2,3], remaining=0! Record [2,2,3]. Pop. i=2(6): 3-6 overshoot. i=3(7): overshoot. Pop back further... eventually also finds [7] directly: backtrack(0,[],7) after exhausting the '2' branch tries i=3 at the top level (7): path=[7], remaining=0, record [7]. Final result: [[2,2,3],[7]].",
    dry_run_say="Tracing candidates=[2,3,6,7] with target=7: the backtracking explores reusing 2 repeatedly, eventually finding [2,2,3], and separately finds [7] directly, giving the correct final answer of [[2,2,3],[7]].",
    edge_case="No combination sums to the target at all, e.g. candidates=[5], target=3. backtrack(0,[],3): i=0(5): remaining=3-5=-2, overshoot, return immediately. No valid combination is ever recorded. Final result: [] (empty list), correctly indicating no solution exists.",
    edge_case_say="Let me check a case where no combination can reach the target, like candidates=[5] with target=3 \u2014 every attempt immediately overshoots, so we correctly end up with an empty result list.",
    other_edge_cases=[
        "Target exactly equal to one of the candidates (a single-element combination)",
        "Candidates that individually already exceed the target (immediately pruned)",
        "A target of 0 (only the empty combination would sum to it, though typically targets are positive)",
        "Candidates list containing just one very small number requiring many repetitions",
    ],
    final_complexity_rows=[["Optimized", "O(N^(T/min) )", "O(T/min)"]],
    final_complexity_say="The time complexity is difficult to express simply since it depends on the branching factor and depth, roughly bounded by the number of candidates raised to the power of (target divided by the smallest candidate), and space is O(target/min_candidate) for the maximum recursion depth (the path length in the worst case).",
    pushback=[
        ("Why pass 'i' instead of 'i+1' as the next start index?", "Passing 'i' allows the same candidate to be chosen again in the next recursive call, which is required since numbers can be reused an unlimited number of times; if repetition weren't allowed, I'd pass i+1 instead, as in the related 'Combination Sum II' variant."),
        ("How do you avoid duplicate combinations in a different order?", "By always choosing candidates in non-decreasing index order (never going back to an earlier index), each valid multiset of numbers is only ever discovered in one canonical order, so there's no need for any post-processing deduplication."),
        ("Can you optimize by sorting the candidates first?", "Yes \u2014 sorting lets me break out of the loop early as soon as a candidate alone (added to the current running sum) would exceed the target, since all later candidates would be even larger, which is a nice additional pruning on top of the core backtracking."),
        ("What if candidates could include duplicates in the input list?", "I'd want to deduplicate the candidates list first (or handle it explicitly), since this specific algorithm assumes distinct candidate values as given in the problem constraints."),
    ],
    mistakes=[
        "Passing i+1 instead of i as the next starting index, which would incorrectly disallow reusing the same number.",
        "Forgetting to copy the path list when appending to results, causing all recorded combinations to reference the same mutated list.",
        "Not pruning when remaining goes negative, wasting time exploring clearly-overshot branches.",
        "Allowing candidates to be chosen from any earlier index, which would generate duplicate combinations in different orders.",
    ],
    recovery=[
        "If stuck: 'I need a way to explore combinations without generating the same set of numbers in multiple different orders. If I only ever move forward through the candidate list, that naturally avoids duplicates.'",
        "If duplicates appear in my results: check whether I'm passing the correct next-start index (should be non-decreasing, never allowing a backward jump).",
        "If the interviewer hints 'can you prune more aggressively': mention sorting the candidates first to break out of the loop early once a candidate alone would overshoot.",
        "If path.pop() is missing: recognize the bug when a dry run shows stale values persisting from a previous branch that should have been un-chosen.",
    ],
    pattern_recognition=dict(
        triggers="'find all combinations that sum to a target', 'numbers can be reused'",
        pattern="Backtracking with a forward-only index constraint",
        first_thought="To avoid duplicate combinations in different orders, only ever pick candidates at the current index or later, never going backward.",
        trap="Forgetting to pass 'i' (allowing reuse) vs. 'i+1' (disallowing reuse), or forgetting to copy the path before appending to results.",
    ),
    memory_hook="Combination Sum \u2192 \"Only move forward through candidates; reuse allowed by staying at the same index.\"",
    recap_key_idea="Backtrack forward-only through candidates, allowing reuse of the current candidate, pruning when remaining goes negative.",
    recap_data_structure="A results list and a path list; implicit recursion call stack.",
    recap_algorithm="Backtracking with a forward-only index and early pruning.",
    recap_time="Exponential (bounded by branching and depth)", recap_space="O(target/min_candidate)", recap_edge_case="No combination reaches the target at all.",
    talk_track=[
        ("Interviewer", "Find all unique combinations of these numbers that sum to the target, reusing numbers freely."),
        ("Me", "Got it \u2014 the same number can be used multiple times, and combinations using the same numbers in a different order should only count once, right?"),
        ("Interviewer", "Yes."),
        ("Me", "A naive approach would explore every possible sequence without pruning, which risks huge redundant work and duplicate results in different orders."),
        ("Me", "I'll use backtracking: track a running remaining target, and only ever consider candidates from the current index forward, which naturally prevents generating the same combination in different orders. I'll also stop immediately if the remaining target goes negative."),
        ("Me", "When the remaining target hits exactly 0, I record a copy of the current path as a valid combination."),
        ("Me", "Let me code that, being careful to pass the SAME index forward (not index+1) so numbers can be reused."),
        ("Me", "Tracing candidates=[2,3,6,7] with target=7: the search finds [2,2,3] and [7] as the two valid combinations."),
        ("Me", "Edge case: if no combination can reach the target, like candidates=[5] with target=3, every attempt immediately overshoots, giving an empty result."),
        ("Me", "The complexity is exponential in the worst case, but the pruning on overshooting the target and the forward-only ordering keep the actual search space manageable."),
    ],
))

PROBLEMS.append(dict(
    title="Letter Combinations of a Phone Number", lc_num="17", difficulty="MEDIUM", pattern="Backtracking",
    relevance="Common interview pattern",
    restate="We're given a string of digits from 2 to 9, each mapping to a set of letters like on a phone keypad, and we need to return all possible letter combinations that the digit string could represent.",
    clarify_questions=[
        "Should an empty input string return an empty list, or a list containing just the empty string?",
        "Is the digit-to-letters mapping the standard phone keypad mapping (2=abc, 3=def, etc.)?",
        "Does the order of the returned combinations matter?",
        "Can digits 0 or 1 appear, which typically have no letters mapped to them?",
    ],
    restate_say=["Just to confirm, I use the standard phone keypad mapping, digits are 2 through 9 only, and an empty input should return an empty list, correct?"],
    brute_idea="Use nested loops, one for each digit's possible letters, to build every combination directly \u2014 but this requires knowing the input length in advance, which doesn't generalize to a variable-length string.",
    brute_say=["For a fixed number of digits, I could write nested loops, one per digit, to enumerate every combination directly, but that doesn't generalize since the input string can be any length."],
    brute_time="If it could be done, this would still be O(4^n) in the worst case (some digits map to 4 letters), since that's how many total combinations exist.",
    brute_space="O(n) for tracking a single combination during construction.",
    brute_complexity_say="Even a hypothetical fixed-nested-loop approach would still be O(4 to the n) time in the worst case, since that's fundamentally how many combinations exist; the real issue is that nested loops don't generalize to arbitrary input lengths.",
    bottleneck="Nested loops require knowing the exact number of digits in advance, which doesn't work for a general variable-length input; I need a technique that naturally handles any input length by building up combinations one digit at a time.",
    bottleneck_say="The bottleneck is that a fixed set of nested loops can't handle inputs of varying length; I need an approach that generalizes by processing one digit at a time regardless of how many digits there are.",
    optimization_explain="I use Backtracking, which naturally generalizes to any input length. I maintain a current partial combination as I recursively process each digit's position. For each digit, I try every letter it maps to: add that letter to the current combination, recurse to handle the next digit, and then remove the letter (backtrack) to try the next possible letter for that same digit. When the current combination's length equals the number of digits, it's complete, and I add it to the results.",
    key_insight="Backtracking naturally generalizes to any number of digits because it processes one digit at a time regardless of how many total digits there are, whereas nested loops would need to be manually written out for a specific fixed count, which doesn't scale.",
    optimization_say=[
        "I'll map each digit to its corresponding letters using a fixed lookup table.",
        "I'll recursively build up a combination one digit at a time: try each possible letter for the current digit, recurse into the next digit, then backtrack to try the next letter.",
        "Once the combination's length matches the number of input digits, it's complete, and I record it.",
    ],
    code_blocks=[
        dict(code="def letter_combinations(digits):\n    if not digits:\n        return []\n\n    phone = {\n        '2': 'abc', '3': 'def', '4': 'ghi', '5': 'jkl',\n        '6': 'mno', '7': 'pqrs', '8': 'tuv', '9': 'wxyz'\n    }\n    result = []",
             say="I handle the empty input case right away, returning an empty list. Then I set up the standard digit-to-letters phone keypad mapping and a results list.",
             why="Explicitly checking for an empty string avoids accidentally producing a list containing just the empty string, matching the expected convention for this problem."),
        dict(code="    def backtrack(index, current):\n        if index == len(digits):\n            result.append(current)\n            return\n\n        possible_letters = phone[digits[index]]\n        for letter in possible_letters:\n            backtrack(index + 1, current + letter)\n\n    backtrack(0, '')\n    return result",
             say="My recursive helper tracks which digit index I'm currently processing and the combination built so far. Once index reaches the end of the digits, the combination is complete, so I record it. Otherwise, I look up the current digit's possible letters and try each one, recursing to handle the next digit.",
             why="Because index moves forward by exactly one with each recursive call, and the base case triggers precisely when we've assigned a letter for every digit, this naturally produces every possible combination of letters, one full assignment per recursive path."),
    ],
    dry_run="digits = '23'. backtrack(0, ''): digit[0]='2', letters='abc'. Try 'a': backtrack(1,'a'). digit[1]='3', letters='def'. Try 'd': backtrack(2,'ad'), index==2==len, record 'ad'. Try 'e': backtrack(2,'ae'), record 'ae'. Try 'f': backtrack(2,'af'), record 'af'. Back to backtrack(0,''), try 'b': backtrack(1,'b') similarly produces 'bd','be','bf'. Try 'c': backtrack(1,'c') produces 'cd','ce','cf'. Final result: ['ad','ae','af','bd','be','bf','cd','ce','cf'] \u2014 all 9 combinations for digits '23'.",
    dry_run_say="Tracing digits='23': the backtracking pairs every letter for '2' (a,b,c) with every letter for '3' (d,e,f), producing all 9 combinations: ad, ae, af, bd, be, bf, cd, ce, cf.",
    edge_case="Empty input string. The very first check 'if not digits: return []' triggers immediately, correctly returning an empty list rather than a list containing an empty string.",
    edge_case_say="Let me check the empty string input \u2014 the initial guard clause catches it and correctly returns an empty list right away, rather than accidentally including an empty combination.",
    other_edge_cases=[
        "A single digit (returns just that digit's individual letters as single-character combinations)",
        "A digit mapping to 4 letters, like '7' or '9' (verifies all 4 branches are explored)",
        "The maximum expected input length for the given constraints",
        "Multiple identical digits in a row, like '22' (still produces distinct letter combinations correctly)",
    ],
    final_complexity_rows=[["Optimized", "O(4^n * n)", "O(n)"]],
    final_complexity_say="This is O(4^n times n) time in the worst case, since there are up to 4^n total combinations (for digits like 7 and 9 that map to 4 letters), and building each combination string takes O(n), and O(n) space for the recursion depth (not counting the output storage itself).",
    pushback=[
        ("Why can't nested loops solve this directly?", "Because the number of digits (and therefore the number of nested loops needed) varies per input, and you can't write a variable number of nested loops in most languages without some other mechanism, which is exactly what recursion/backtracking provides naturally."),
        ("Can you solve this iteratively instead of recursively?", "Yes, an iterative approach can build up the result list progressively: start with [''], and for each digit, expand every existing partial combination by appending each of that digit's possible letters, replacing the result list with these expanded combinations after each digit is processed."),
        ("What's the true size of the output?", "It's the product of the number of letters mapped to each digit (3 or 4 depending on the digit), which in the worst case (all digits being 7 or 9) is 4^n, matching the stated time complexity."),
        ("Can you optimize this further?", "No, since we must actually produce every valid combination as output, the time complexity is inherently tied to the total number of combinations that exist."),
    ],
    mistakes=[
        "Forgetting the empty-string edge case, which could otherwise produce a list containing a spurious empty combination.",
        "Using a wrong or incomplete digit-to-letters mapping (some digits like 7 and 9 have 4 letters instead of 3).",
        "Not advancing the index correctly in the recursive call, causing infinite recursion or missing digits.",
        "Trying to hardcode a fixed number of nested loops instead of a general recursive approach that handles any input length.",
    ],
    recovery=[
        "If stuck: 'Nested loops would work for a fixed number of digits, but I need something that generalizes to any length \u2014 that's exactly what recursion is good for, processing one digit at a time.'",
        "If I get the wrong number of combinations: double-check the phone mapping, especially for digits 7 and 9 which have 4 letters instead of the usual 3.",
        "If the interviewer hints 'think about a general approach, not hardcoded loops': confirm and describe the recursive backtracking solution.",
        "If asked for an iterative version: describe progressively expanding a list of partial combinations, one digit at a time.",
    ],
    pattern_recognition=dict(
        triggers="'phone keypad letter combinations', 'all combinations across multiple independent choices'",
        pattern="Backtracking (one choice dimension per recursive level)",
        first_thought="Each digit contributes an independent set of choices; recursion naturally handles a variable number of these choice dimensions where nested loops couldn't.",
        trap="Forgetting the empty-input edge case, or using an incorrect digit-to-letter mapping.",
    ),
    memory_hook="Letter Combinations \u2192 \"One recursive level per digit \u2014 try every letter, then move to the next digit.\"",
    recap_key_idea="Recursively try every possible letter for the current digit, advancing to the next digit index, until all digits are assigned.",
    recap_data_structure="A results list; implicit recursion call stack.",
    recap_algorithm="Backtracking, one recursive level per input digit.",
    recap_time="O(4^n * n)", recap_space="O(n)", recap_edge_case="Empty input string (should return an empty list).",
    talk_track=[
        ("Interviewer", "Given a string of digits, return all possible letter combinations using the phone keypad mapping."),
        ("Me", "Got it \u2014 standard keypad mapping, and an empty input should return an empty list rather than a list with an empty string, correct?"),
        ("Interviewer", "Yes."),
        ("Me", "For a fixed number of digits I could write nested loops, one per digit, but that doesn't generalize to arbitrary input lengths, so I'll use recursion instead."),
        ("Me", "I'll build up a combination one digit at a time: for the current digit, try every possible letter, recurse into the next digit, and once the combination's length matches the number of digits, record it."),
        ("Me", "Let me code that with the standard digit-to-letters mapping."),
        ("Me", "Tracing digits='23': it pairs every letter of 2 (a,b,c) with every letter of 3 (d,e,f), producing all 9 combinations, ad through cf."),
        ("Me", "Edge case: an empty input string correctly returns an empty list immediately via a guard clause."),
        ("Me", "Final complexity: O(4^n times n) time in the worst case, since some digits map to 4 letters, and O(n) space for the recursion depth."),
    ],
))

PROBLEMS.append(dict(
    title="Valid Sudoku", lc_num="36", difficulty="MEDIUM", pattern="Hash Set (Constraint Checking)",
    relevance="Common interview pattern",
    restate="We're given a 9x9 Sudoku board partially filled with digits 1-9 and empty cells marked '.', and we need to determine if the current board configuration is valid, meaning no row, column, or 3x3 sub-box contains a repeated digit.",
    clarify_questions=[
        "Do I need to check that the board is SOLVABLE, or just that the CURRENT configuration doesn't violate any rules?",
        "Are empty cells always represented by the character '.'?",
        "Is the board always exactly 9x9?",
        "Should I validate that only digits 1-9 (and '.') appear, or can I assume the input is already well-formed in that sense?",
    ],
    restate_say=["Just to confirm, I only need to check that the CURRENT filled-in numbers don't violate any row/column/box rule, not whether the puzzle is ultimately solvable, correct?"],
    brute_idea="For each row, column, and 3x3 box separately, scan through and check for duplicate non-empty digits using a temporary set for each one.",
    brute_say=["A straightforward approach checks each row, then each column, then each 3x3 box separately, using a temporary set each time to detect duplicates."],
    brute_time="Checking all rows is O(81), all columns is another O(81), and all boxes another O(81), so overall it's O(81) times a constant factor of 3, which simplifies to O(1) since the board size is fixed at 9x9, but conceptually O(n\u00b2) for a general n x n board.",
    brute_space="O(9) per temporary set, reused across checks.",
    brute_complexity_say="Since the board size is fixed at 9x9, this is technically O(1) time and space in an absolute sense, but conceptually it's O(n\u00b2) for an n x n board, since we make three separate full passes over the board.",
    bottleneck="Making three completely separate passes (one for rows, one for columns, one for boxes) means visiting every cell three times total, when I could check all three constraints for each cell in a SINGLE pass instead.",
    bottleneck_say="The bottleneck, such as it is, is visiting the board three separate times instead of combining all three checks into one single pass over every cell.",
    optimization_explain="I use three sets of Hash Sets (one per row, one per column, one per 3x3 box), and do a single pass over every cell in the board. For each filled cell, I compute which row-set, column-set, and box-set it belongs to (the box index is computed as (row // 3) * 3 + (col // 3)), and check if the digit is already in any of those three corresponding sets. If it is, the board is invalid; otherwise, I add the digit to all three sets and continue.",
    key_insight="Every cell belongs to exactly one row, one column, and one box, and a hash set gives O(1) average time to check 'have I seen this digit in this row/column/box before' \u2014 doing all three checks together for each cell as I scan once is strictly more efficient than three separate full scans.",
    optimization_say=[
        "I'll create 9 sets for rows, 9 for columns, and 9 for boxes.",
        "I'll do a single pass through every cell; for each filled cell, I check whether its digit is already in the corresponding row, column, or box set.",
        "If it is, the board is invalid immediately; otherwise, I add the digit to all three relevant sets and move on.",
    ],
    code_blocks=[
        dict(code="def is_valid_sudoku(board):\n    rows = [set() for _ in range(9)]\n    cols = [set() for _ in range(9)]\n    boxes = [set() for _ in range(9)]",
             say="I create a list of 9 empty sets each for rows, columns, and boxes.",
             why="Using a list of sets, one per row/column/box index, lets me check and update the right set in O(1) using simple index lookups as I scan the board."),
        dict(code="    for r in range(9):\n        for c in range(9):\n            val = board[r][c]\n            if val == '.':\n                continue\n            box_index = (r // 3) * 3 + (c // 3)",
             say="I loop through every cell. If it's empty, I skip it. Otherwise, I compute which of the 9 boxes this cell belongs to using integer division on the row and column.",
             why="Dividing row and column by 3 (integer division) groups cells into their correct 3x3 box, and the formula (r//3)*3 + (c//3) maps that 3x3 grid position into a single flat index from 0 to 8."),
        dict(code="            if val in rows[r] or val in cols[c] or val in boxes[box_index]:\n                return False\n\n            rows[r].add(val)\n            cols[c].add(val)\n            boxes[box_index].add(val)\n\n    return True",
             say="I check if this digit already exists in its row's set, column's set, or box's set; if so, the board is invalid. Otherwise, I add the digit to all three relevant sets and continue to the next cell.",
             why="Checking and updating all three constraints together, for every cell, in a single pass, is what lets this whole validation run in just one scan over the board instead of three separate scans."),
    ],
    dry_run="A tiny conceptual trace: suppose row 0 has '5' at column 0 and later another '5' at column 4 in the same row. Processing (0,0): val='5', rows[0] empty, cols[0] empty, boxes[0] empty, no conflict, add '5' to rows[0], cols[0], boxes[0]. Later processing (0,4): val='5', check rows[0]: '5' is already in rows[0]! Return False immediately \u2014 correctly catching the duplicate in the same row.",
    dry_run_say="Tracing a small case where the digit 5 appears twice in row 0: the first occurrence adds 5 to that row's set, and the second occurrence immediately finds it already there, correctly flagging the board as invalid.",
    edge_case="A duplicate digit within the same 3x3 box but in different rows and columns, e.g. '3' at (0,0) and '3' at (2,2), both within the top-left box. Both map to box_index = (0//3)*3+(0//3)=0 and (2//3)*3+(2//3)=0 respectively \u2014 same box! The second occurrence finds '3' already in boxes[0], correctly returning False even though they're in different rows and columns.",
    edge_case_say="Let me check a duplicate that's only a box violation, not a row or column violation \u2014 like '3' appearing at both (0,0) and (2,2), which are in different rows and columns but the same 3x3 box. The box index calculation correctly maps both to the same box, catching the violation.",
    other_edge_cases=[
        "A completely empty board (should be trivially valid)",
        "A completely and correctly filled valid Sudoku solution",
        "Only a single digit filled in anywhere (trivially valid)",
        "A duplicate that spans exactly a row-column-box intersection in a tricky way",
    ],
    final_complexity_rows=[["Optimized", "O(1) (fixed 81 cells)", "O(1) (fixed 243 slots)"]],
    final_complexity_say="Since the board is a fixed 9x9 size, this is technically O(1) time and space in absolute terms (81 cells, at most 243 total set entries), but thinking of it generally as an n x n board, it's O(n\u00b2) time and space, achieved in a single pass rather than three separate passes.",
    pushback=[
        ("Why compute the box index as (r//3)*3 + (c//3)?", "Because dividing the row and column by 3 groups them into one of 3 'super-rows' and 3 'super-columns' of boxes; multiplying the super-row by 3 and adding the super-column flattens that 3x3 arrangement of boxes into a single index from 0 to 8, uniquely identifying each 3x3 box."),
        ("Could you use a single combined set with tagged entries instead of three separate structures?", "Yes, a common trick is to insert strings like f'row{r}-{val}', f'col{c}-{val}', f'box{box_index}-{val}' all into one big set, checking membership before adding; this achieves the same result with a single set instead of three separate lists of sets, just with slightly more string overhead per entry."),
        ("What if the board could contain invalid characters or wrong dimensions?", "I'd assume, based on problem constraints, that the board is always a well-formed 9x9 grid with only digits 1-9 or '.', but if that weren't guaranteed, I'd add validation for those cases first."),
        ("Can you optimize this further?", "Since we must examine every filled cell at least once to detect any violation, and the board size is fixed, this single-pass approach is already essentially optimal."),
    ],
    mistakes=[
        "Doing three separate full passes over the board (once each for rows, columns, boxes) instead of combining all three checks into one pass.",
        "Getting the box index formula wrong, such as forgetting to multiply by 3 or dividing incorrectly.",
        "Forgetting to skip empty cells ('.'), which would otherwise be treated as a value to check/add.",
        "Checking validity as if a full board solution were required, when only the current partial configuration needs to be conflict-free.",
    ],
    recovery=[
        "If stuck: 'Checking rows, columns, and boxes separately means visiting every cell three times. Let me see if I can check all three constraints for each cell in one single pass instead.'",
        "If the box index seems wrong: work out a small example by hand, mapping cell (row, col) pairs to expected box numbers 0-8, and verify the formula against that.",
        "If the interviewer hints 'can you do this in one pass': confirm and describe combining all three hash-set checks together per cell.",
        "If confused about what's being validated: clarify explicitly that this checks CURRENT validity, not whether the puzzle is solvable to completion.",
    ],
    pattern_recognition=dict(
        triggers="'validate a Sudoku board', 'no duplicates in row/column/box'",
        pattern="Hash Set (multiple constraint tracking in a single pass)",
        first_thought="Each cell belongs to exactly one row, column, and box \u2014 check all three constraints together per cell using hash sets, rather than three separate full passes.",
        trap="Getting the box-index formula wrong, or doing three separate scans instead of one combined scan.",
    ),
    memory_hook="Valid Sudoku \u2192 \"One pass, three sets per cell: row, column, and box.\"",
    recap_key_idea="For each filled cell, check and update its row, column, and box hash sets together in a single pass.",
    recap_data_structure="Three lists of 9 hash sets each (rows, columns, boxes).",
    recap_algorithm="Single-pass constraint checking with hash sets.",
    recap_time="O(1) [O(n\u00b2) general]", recap_space="O(1) [O(n\u00b2) general]", recap_edge_case="A duplicate that violates only the box constraint, not row or column.",
    talk_track=[
        ("Interviewer", "Determine if this partially filled Sudoku board is currently valid."),
        ("Me", "Just to confirm, I only need to check the current configuration for conflicts, not whether the puzzle is solvable to completion, right?"),
        ("Interviewer", "Correct."),
        ("Me", "A straightforward approach checks all rows, then all columns, then all boxes separately, each with a temporary set \u2014 that's three full passes over the board."),
        ("Me", "I can combine that into a single pass: I'll keep 9 sets each for rows, columns, and boxes, and for every filled cell, check and update all three relevant sets together."),
        ("Me", "The box index for a cell comes from dividing its row and column by 3 and combining them into a single 0-8 index."),
        ("Me", "Let me code that \u2014 looping through every cell once, skipping empties, and checking membership in the row, column, and box sets before adding."),
        ("Me", "Tracing a small case with a duplicate 5 in the same row: the second occurrence is immediately caught since 5 is already in that row's set."),
        ("Me", "Edge case: a duplicate that only violates the box constraint, like the same digit at two different cells within the same 3x3 box but different rows and columns \u2014 the box index correctly identifies and catches that."),
        ("Me", "Since the board is a fixed 9x9, this is effectively O(1) time and space, achieved in one single pass instead of three."),
    ],
))
